### ISSUE TITLE
samtools 1.5 fastq bug - lost half of the reads

### ISSUE THREAD

**Issue by xunchen85** [samtools/samtools#1005]
Under Linux, samtools fastq output different results between version 1.5 and 1.6. Specifically, samtools 1.5 will miss almost half of the paired-end reads in the BAM file.

**Comment by daviesrob** [comment]
Is your input file collated by name (I.e. name sorted or processed by `samtools collate`)?  Commit 6c87075a5 fixed a bug where reads could be dropped if not name collated.  This is the only change between 1.5 and 1.6 that touched fastq.  You would normally want to name collate the reads before converting to fastq so that paired reads end up together in the output files.

I would also recommend upgrading to the latest version if you can, as many other bugs have been fixed since versions 1.5 and 1.6 came out.

**Comment by xunchen85** [comment]
Thanks for your reply. The input file is directly from "samtools view".

I have further tested my previously installed version 1.3. It seems like the issue only existed in version 1.5. 

I have upgraded to the latest version.
