### ISSUE TITLE
samtools treats many errors as EOF, silently hiding problems

### ISSUE THREAD

**Issue by beaumontlab** [samtools/samtools#101]
In the development of Antonie, I generated BAM files that were subtly malformed. This is of course my own bug, and of course samtools should not compensate for my bugs. However, samtools silently accepted my BAM files, and appeared to process them quite well!

Further investigation found that 'samread()' returns negative values for both errors and EOFS, and that many loops within samtools treat all negative values equally. In other words, they turn an error into a normal EOF, which generates no error or warning message.

Any loop like this is problematic: 
    while (samread(sam,bam_line) >= 0) {... }

As an example, http://ds9a.nl/tmp/blah.bam has an invalid sequence id in there, but 'samtools stats blah.bam' processes it without apparent error, but also without producing any statistics beyond the problematic read.

While I of course appreciate the samtools software, I would suggest screaming bloody murder on any kind of unexpected error, lest our users end up with invalid results because part of their data was silently skipped!

Thanks for your attention.

**Comment by jkbonfield** [comment]
Checking this I see that the bugs reported here have mostly been fixed, including an equivalent fix to Peter's patch, but grepping for ```sam_read1``` calls I still see failure to check in other cases; fastq, fixmate, phase, targetcut, bedcov and maybe more.  It looks like there is a lack of iterator checking in many places too.

So leaving this open still (sorry), but it's unlikely we'll go through all these prior to 1.4.

**Comment by dkj** [comment]
More fixes unlikely before 1.4

**Comment by jmarshall** [comment]
Unfortunately even back in 2013 it proved impractical to alter the codes returned by `sam_read1()` as discussed in https://github.com/samtools/samtools/issues/101#issuecomment-29732655, so error checking code to this day must check `ret < -1` to detect errors.

At the time of writing, all direct invocations of `sam_read1()` in the samtools code (the legacy `samread()` API is no longer used, so irrelevant to samtools) have been correctly checked, producing a diagnostic and `EXIT_FAILURE`, for a long time. However there remained some checking infelicities when the call is via iterator or pileup wrappers, as @jkbonfield's most recent comment mentions, all of which are fixed by PR #1379.
