### ISSUE TITLE
Missing input argument and SGE interaction

### ISSUE THREAD

**Issue by nigiord** [samtools/samtools#1010]
On latest release (1.9) on a Sun Grid Engine cluster (SGE 8.1.9).

When I run the following command 
`samtools view -o test.bam` 
The exit status is 1 and I get the following error message:
```
samtools view: No input provided or missing option argument.

Usage: […]
```

So far so good. But when I submit the exact same command to the SGE cluster through `qsub`, the exit status is 0, stderr and stdout are blank (even when manually redirected with `&>`), and more importantly samtools creates a `test.bam` file that is not empty but does not return any value either when passed through `samtools view -h test.bam`.

Same problem occurs with `samtools sort -o test.bam` except the `test.bam` file now contains:
```
$ samtools view -h test.bam
@HD	VN:1.6	SO:coordinate
```
This file can also be indexed without error.

Cheers,
Nils

**Comment by daviesrob** [comment]
`samtools` will only print the message and exit non-zero if the input is a terminal.  This is so you don't run into the problem of typing `samtools view -o test.bam` and then wondering for ages why nothing happened because it's waiting for you to type something in and then press control-d.

In your SGE case, it's likely that the input has been redirected to `/dev/null` so `samtools view` will read an empty file.  As an empty file is actually a valid SAM file, it gives you back a BAM file with no reads in it.  See the discussion in https://github.com/samtools/htslib/issues/261#issuecomment-135058322.  Unfortunately no-one has got around to implementing the solution of rejecting empty SAM files yet (and disallowing them in the specification).

**Comment by nigiord** [comment]
That makes sense, thank you. I can indeed reproduce the behavior outside of qsub with `samtools view -o test.bam /dev/null` and running the following script through qsub returns yes:
```bash
if [ "$(stat -Lc %t:%T /dev/stdin)" = "$(stat -Lc %t:%T /dev/null)" ]
    then echo yes
else
    echo no
fi
```
Not sure why `/dev/null` is used by qsub when the input argument is missing though. I also think disallowing empty SAM file by default would be a good idea.

**Comment by jmarshall** [comment]
I expect qsub (like nohup) always redirects stdin from /dev/null unless otherwise specified. If it didn't, which terminal would you like your job to try to read from? :smile:

It's still on my list to rework PR samtools/htslib#721. Because of reasons, this would involve fixing samtools/htslib#261 and so disallowing empty SAM files.
