### ISSUE TITLE
Recommendation for a Workstation

### ISSUE THREAD

**Issue by pintie** [samtools/samtools#1043]
Hello,

i have to build a new Workstation for a coworker.
Do you have any suggestions what to pick ?

- Is there a CPU limitation of Cores ? Or could i just use dual Xeon Gold 6140 with 36 cores / 72 Threads ?
- Is there any GPU support ? like CUDA on Quadro cards ?
- RAM limitation ? or does it support like 192 GB ?

Thanks !

**Comment by pintie** [comment]
thanks for closing... 
any idea where else i can ask for support ?
i can't find anything about Hardware for samtools

**Comment by valeriuo** [comment]
You didn't mention samtools or what you need the workstation for, so I assumed the issue was misplaced.

Samtools can run on a variety of platforms (Windows, Linux, macOS) and you can do a lot of work on even a decent laptop. Platform limitations come into play when you are processing large amounts of data. For example, sorting a 25 GB BAM file can lead to a memory usage of 50 GB and a running time longer than 10 minutes

**Comment by jkbonfield** [comment]
For non-bug issues it's probably best to use the email lists.  See http://www.htslib.org/support/

Memory usage for sort doesn't need to be that big as it'll chunk into multiple sorted smaller files and then merge, although the memory limit is confusing as it's per thread so that catches people out.  I'm not really sure there's anything in samtools that requires more resources than your average modern desktop offers, but more resources makes it more efficient.

**Comment by pintie** [comment]
Ok thanks.

at the moment he is using linux with 32GB RAM on a 4 core (8Thread) Workstation. 
and it takes 5 Days ! for one run. 

maybe he is using it wrong.
the files are  75-100GB. 

i guess it is a VM ware Problem. 

thanks.
