### ISSUE TITLE
unable to fetch regions from http/https url with local .bai file

### ISSUE THREAD

**Issue by avilella** [samtools/samtools#1045]
I wonder if someone can tell me what step am I missing here to be able to fetch reads from an http/https url bam:

```
30940 /media/sf_Downloads  1005  2019-04-26 12:42:12 sudo apt-get install -y autoconf automake make gcc perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev libncurses5-dev
30900 /home/avilella/samtools-1.9  1014  2019-04-26 12:42:22 make clean
30900 /home/avilella/samtools-1.9  1015  2019-04-26 12:42:22 make
30900 /home/avilella  1020  2019-04-26 12:45:58 scp avilella@10.0.2.46:~/CEGX_Run712/CEGX_Run712-12345678/CEG99_712_94PC-232457229/*.bai .

avilella@albertLX1u16:~$ export HTS_ALLOW_UNENCRYPTED_AUTHORIZATION_HEADER=1 && ~/samtools-1.9/samtools view http://dl.dnanex.us/F/D/k8yj9Kfx7zVyZvq06k0yPJb4kYxQbvpxPb45qxZV/CEG99-712-94PC_S190_L00.bml.GRCh38.karyo.deduplicated.bam | head

connect: Connection timed out
[E::hts_open_format] Failed to open file http://dl.dnanex.us/F/D/k8yj9Kfx7zVyZvq06k0yPJb4kYxQbvpxPb45qxZV/CEG99-712-94PC_S190_L00.bml.GRCh38.karyo.deduplicated.bam
samtools view: failed to open "http://dl.dnanex.us/F/D/k8yj9Kfx7zVyZvq06k0yPJb4kYxQbvpxPb45qxZV/CEG99-712-94PC_S190_L00.bml.GRCh38.karyo.deduplicated.bam" for reading: Bad file descriptor

avilella@albertLX1u16:~$ 
avilella@albertLX1u16:~$ uname -sr
Linux 4.13.0-36-generic
avilella@albertLX1u16:~$ uname -m
x86_64
avilella@albertLX1u16:~$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by daviesrob** [comment]
Run `./configure` before running `make` (if you're working on a git checkout, you will also need to run `autoconf  && autoheader` to get the configure script.)

The `htsfile` program that **htslib** builds is useful for diagnosing this sort of problem.  Try:

```
htsfile -vvvvvv -c 'http://dl.dnanex.us/F/D/k8yj9Kfx7zVyZvq06k0yPJb4kYxQbvpxPb45qxZV/CEG99-712-94PC_S190_L00.bml.GRCh38.karyo.deduplicated.bam' | head
```

**Comment by avilella** [comment]
Thanks, I got it to work with the ./configure && make and then with this:

```
ln -s CEG99-712-94PC_S190_L00.bml.GRCh38.karyo.deduplicated.bai
CEG99-712-94PC_S190_L00.bml.GRCh38.karyo.deduplicated.bam.csi
~/samtools-1.9/samtools view
https://dl.dnanex.us/F/D/p4V8P06Y1zZ8947fgzvPxG8P4ypxyYvVPk86FB88/CEG99-712-94PC_S190_L00.bml.GRCh38.karyo.deduplicated.bam
chr7:101739583 | head
```
If the index file of file.bam is simply called file.bai or file.bam.bai,
then it does not work and instead attempts to create a .bam.csi file before
giving the result. But the symlinking above solved the problem.

**Comment by daviesrob** [comment]
When it looks for an index (for, say `https://example.com/foo.bam`) , samtools will try the following, in the given order:

```
https://example.com/foo.bam.csi
https://example.com/foo.csi
https://example.com/foo.bam.bai
https://example.com/foo.bai
```
In each case, it will check for the index file in the current directory and try to download it if it isn't there.

It turns out that this plays very badly with the way DNAnexus are presenting files via https.  The ting that determines which file you get is actually the set of random letters before the last slash.  You can actually change the last part of the URL to anything (as long as it's there) and still get the bam file.  This means samtools will attempt to download the .csi index and get a copy of the bam file instead.

We should probably change it so that it checks for all of the possible local files before attempting to download anything.  It should also peek at the data it's downloading to check that it really is an index, so it doesn't waste lots of time and bandwidth getting something that it doesn't want.

Meanwhile, when using the `develop` version of samtools, you can use the new `-X` option to say where the index is as a work-around:

```
./samtools view -X https://example.com/foo.bam myindex.bai chr7:101739583
```
