### ISSUE TITLE
samtools fastq -i does not produce Casava format

### ISSUE THREAD

**Issue by dinvlad** [samtools/samtools#1047]
#### Are you using the latest version of [samtools]
`samtools 1.9`

#### Please describe your environment.
- OS: `Linux 4.14.94+`
- machine architecture: `x86_64`
- compiler: `gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516`

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
According to [Samtools doc](http://www.htslib.org/doc/samtools.html), `samtools fastq -1 f1.fastq -2 f2.fastq -i in.bam` (note the `-i`) should
> add Illumina Casava 1.8 format entry to header (eg 1:N:0:ATCACG)

However, all reads in the resulting FASTQ files _don't_ contain `1:N:0:<BARCODE>` tag. This is despite the fact that `samtools view -H` is in the form
```
@HD     VN:1.6  SO:queryname
@RG     ID:A00XX.1      SM:Sample1   LB:Sample1   PL:illumina     PU:A00XXX:NNN:HH1VVYYZZ.1.GGCCTTAA-ATCGATCG     CN:BI
```
All reads in the resulting FASTQs look like
```
@A00XXX:NNN:HH1VVYYZZ:1:1101:10000:10000
...
```
while they should look like
```
@A00XXX:NNN:HH1VVYYZZ:1:1101:10000:10000 1:N:0:GGCCTTAAATCGATCG 
...
```

**Comment by daviesrob** [comment]
To get the `-i` option to work, you need to supply both the `--index-format` and `--i1` options (and maybe also `--i2` if you used dual indexing).  So something like this should work (`-n` is also used here to get rid of the `/1` and `/2` on the read names):

```
samtools fastq -1 name_R1.fastq.gz -2 name_R2.fastq.gz --i1 name_I1.fastq.gz --index-format "i*" -n -i name.bam
```

Arguably having to supply `--i1` shouldn't be strictly necessary with `-i`, but `fastq` will currently insist on having it.  If you don't actually want the barcode fastq file, you can always work around this by using `--i1 /dev/null`.

**Comment by dinvlad** [comment]
Thanks - it doesn't appear to work for us. The barcodes are only contained in the `PU` field of `@RG` header in the input BAM, like `PU:A00XXX:NNN:HH1VVYYZZ.1.GGCCTTAA-ATCGATCG` (`GGCCTTAA-ATCGATCG` being the dual-index barcode here). I'm not sure which `--index-format` we should use then.

**Comment by daviesrob** [comment]
I'm afraid that's not going to work.  `samtools fastq -i` gets barcode sequences from the `BC:Z:` tag on the alignment records.  They `--barcode-tag` can be used to change `BC` to something else, but it still has to be on the alignments.  `BC:Z:` records the sequence as read by the machine, rather than the one you expected to see, which is presumably what you have in the header.

While testing this, it looks like `samtools fastq -i` may have bugs when there's more than one barcode - it seems to always add the second one.  I'll see if we can get that fixed.  Meanwhile, for this your best solution might be to dump the fastq without the extra annotations and then add them separately, which you can do fairly easily with something like this:

```
perl -ple 'if (($. % 4) == 1) { s/$/ 1:N:0:GGCCTTAA/; }' 1.fq > casava1.fq
perl -ple 'if (($. % 4) == 1) { s/$/ 2:N:0:ATCGATCG/; }' 2.fq > casava2.fq
```

**Comment by dinvlad** [comment]
Thanks for the info @daviesrob - we’ve been using `sed` to “patch” our FASTQs similarly to how you suggested. I’ll look forward to any fixes, but feel free to close this issue.

**Comment by jenniferliddle** [comment]
PR #1059 addresses these problems.
