### ISSUE TITLE
Silent crash/error on samtools index

### ISSUE THREAD

**Issue by kdmurray91** [samtools/samtools#1057]
Hello,

I'm having a persistent issue indexing a very large BAM file. This file contains reads from ~1000 samples across ~5000 run/library combinations, to a total size of around 4.5TB and ~60 billion reads. I actually have two such bams, with the same read data aligned to two different reference assemblies. One reference is 11 chromosomes and a chloroplast sequence, the other is around 4000 contigs. The chromosome-scale assembly works perfectly fine, however indexing the merged contig-level assembly bam fails silently after ~8 hours (exit 1, no STDERR, no output .bai).

Obviously I can't send either input or log files, so debugging this will be hard. Are there any know issues of this sort? What steps could I take to reproduce or debug the issue? I'm currently running samtools attached to GDB interactively, so it should be possible to get a backtrace at least.

Cheers,
Kevin

#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

Yes, samtools 1.9 from bioconda

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

Centos 6, using samtools from bioconda

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

`samtools merge -o merged.bam ${ABOUT_6000_BAMS} && samtools index merged.bam`

**Comment by jkbonfield** [comment]
What's the maximum length of any chromosome?
What data technologies are being used?  As far as I'm aware we don't have issues with long reads, but do they exist?  I assume all the pre-merged bams index OK?

Failing silently is a bit rubbish, which makes it hard to debug. There's no clear breakpoint to set if it's bubbling the stack all the way back to main and an exit(1).  :-(  However the fact it exits non-zero means it is catching an error somewhere so we can look through the code and try to figure out what condition could fail without producing a message.  If we find such a case, we can test it with either inserting a log message there or putting a breakpoint.  I'll explore...

Also while we're doing that and given it's been some time since the last release, the first (clutching at straws here) test is whether the "develop" branch of samtools and htslib have the same problem.

**Comment by jkbonfield** [comment]
At first glances, I see the main `bam_index` function either returns 0 or calls `print_error / print_error_errno` before returning 1, so the lack of any error message means the internal `sam_index_build3` function has either called exit(1) explicitly (maybe you can set a breakpoint on that) or has simply crashed, although I'd expect some form of error.  I can't see any obvious exit calls and generally we try to avoid them in the library.

I guess one interesting question to note is how far it's got through the file.  Eg htslib/sam.c has the following code in sam_index_build3:

```
    case bam:
        idx = bam_index(fp->fp.bgzf, min_shift);
        if (idx) {
            ret = hts_idx_save_as(idx, fn, fnidx, (min_shift > 0)? HTS_FMT_CSI : HTS_FMT_BAI);
            if (ret < 0) ret = -4;
            hts_idx_destroy(idx);
        }
        else ret = -1;
        break;
```

Does it get to the `if (idx)` line?  Ie has it built the index in memory, but fails to write it to disk?  Also do you know how much memory it is using when it fails?  Has it ran out?  It may be the index is larger for the 4000 contigs variant, but I really don't know.  Maybe "dmesg" gives some hints if it's a memory limit thing?

Note one way you can tell how far samtools has got through the index is to find the PID of the process and then look in /proc/PID/fdinfo/3 (probably 3, but see where the symlink in /proc/PID/fd/3 points to).  That'll tell you the current position within your input file and gives you can idea of how much longer it's going to take too (eg if it's only 20% through the file then that's going to be an 40 hour job!).

**Comment by jkbonfield** [comment]
Sorry, one more thing.  Are you *sure* there is no stderr message?  If you run commands under nohup or under some batch processing tools your stderr may get swallowed or secreted away into a file somewhere.

**Comment by kdmurray91** [comment]
Thanks James.

RE read lengths, maximum would be 150bp, as this is a mix of hiseq 2x100 and novoseq 2x150 data. (& some small amount of misc other illumina platforms, but definitely no 3rd-gen long reads).

RE stderr, I was using snakemake via our cluster. the log file contained no output, but who knows what could have eaten between snakemake and PBS... I'm also not 100% sure that it exits 1, as now I think of it, not producing the output file snakemake expects is treated and reported the same as non-zero exit status.

RE chromosome lengths, i think the max is ~40Mbp, the genome's only around 650Mbp. The longest contig of the more fragmented genome is around 20Mbp from memory, and N50 is around 2Mbp. They're two closely related species (*Eucalyptus grandis* is the chromosome-level one, and we have an assembly of *E. melliodora*. Both are public on NCBI if that would be of use...).

RE indexes on individual bams, I haven't tried that, and would be difficult since they've been deleted after the merge finished to save space.

It's now running in gdb, and after ~6 hours it's done around 1TB of the 4.5TB. From memory, it reliably took around 8 hours to die, so I'll check before I go to sleep tonight (I'm UTC+10), as it should have crashed by then.

**Comment by kdmurray91** [comment]
OK, so having run overnight in gdb, I can confirm the error **isn't** silent (sorry for the confusion on this):
```
[E::bgzf_read] Read block operation failed with error 33 after 0 of 4 bytes
samtools index: failed to create index for "TMP_bwa~emel-scott~all_samples_forindexdebug_conda-samtools.bam"
```
I get the same error with samtools 1.9 installed from source, and from conda.

I can also confirm that the peak RAM usage was around 2gb, but that this didn't seem to cause the issues as I ran it on a 16gb ram node...

`samtools quickcheck` says:
```
verbosity set to 3
checking TMP_bwa~emel-scott~all_samples_forindexdebug_conda-samtools.bam
opened TMP_bwa~emel-scott~all_samples_forindexdebug_conda-samtools.bam
TMP_bwa~emel-scott~all_samples_forindexdebug_conda-samtools.bam is sequence data
TMP_bwa~emel-scott~all_samples_forindexdebug_conda-samtools.bam has 115 targets in header.
TMP_bwa~emel-scott~all_samples_forindexdebug_conda-samtools.bam has good EOF block.
```
Which I assume means the file is not truncated?


Cheers,
Kevin

**Comment by daviesrob** [comment]
`error 33` comes from the combination `BGZF_ERR_ZLIB|BGZF_ERR_CRC` so sadly it looks like your monstrous bam file has a corrupt block somewhere inside it.  Unfortunately the message doesn't say where the corruption is (we need to fix that...) but if you can stand the wait you could try setting a breakpoint in gdb on the `hts_log_error()` [line](https://github.com/samtools/htslib/blob/1832d3a/bgzf.c#L989) in `bgzf_read` that prints the error message and then inspect `*fp` to see where it got to.

If it is a file corruption, it's unlikely that you will be able to recover the lost block (although [it might be possible to correct very small errors](https://stackoverflow.com/questions/3788570/is-it-possible-to-do-rudimentary-error-correction-with-crc)).  If you can find the location and extent of the bad data then you might be able to splice it out with `dd`.   You could also try splicing out the bad part to inspect it more conveniently.

If the problem is at around the 2Gb point, it may be due to 32bit issues (e.g. undersized _FILE_OFFSET_BITS) although I somewhat doubt that is the problem if you're using a 64-bit machine.

**Comment by daviesrob** [comment]
Oh, you could also try commenting out the [part that checks the CRC](https://github.com/samtools/htslib/blob/1832d3a/bgzf.c#L588) to see if you get lucky and it manages to read through the corruption.

**Comment by kdmurray91** [comment]
Thanks for the tips Rob. I'll take a poke around as you suggest, but in any case this looks like data corruption rather than a bug, so I'll close this issue.

**Comment by jkbonfield** [comment]
One way of double checking that is simply "zcat file.bam > /dev/null".  BGZF is just a series of concatenated gzip streams so zcat is quite happy to uncompress, and importantly, validate the CRC.

Locally we've found quite a few cases where we get CRC errors on our BAMs.  Shovel enough data around and sooner or later you'll end up with a disk corruption.  It's also possible to get BAMs where a bit error can flip a base or a quality value but still uncompress correctly (bar an incorrect CRC).  Most BAM readers do no validate the CRC, so this gives the appearance that some tools work while others do not.
