### ISSUE TITLE
Sort order in header is unknown when using -t

### ISSUE THREAD

**Issue by gusevfe** [samtools/samtools#1074]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
```
> samtools --version
samtools 1.9
Using htslib 1.9
```

 #### Please describe your environment.
- Linux 3.10.0-957.1.3.el7.x86_64
- x86_64
- GCC 6.4.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
When sorting a file and `-t` is NOT specified, the sort order in the header of output file (SO tag in HD) is set to `coordinate`. If you specify `-t`, then the order is set to `unknown`, no matter which value you set `-t` to (even when using default value 0). 

```
> samtools sort toy.sam | samtools view -H | grep SO
@HD     VN:1.6  SO:coordinate
> samtools sort -t 0 toy.sam | samtools view -H | grep SO
@HD     VN:1.6  SO:unknown
> samtools sort -t 1 toy.sam | samtools view -H | grep SO
@HD     VN:1.6  SO:unknown
> samtools sort -t 4 toy.sam | samtools view -H | grep SO
@HD     VN:1.6  SO:unknown
```
It seems like the SO tag should be set to `coordinate` in all cases.

**Comment by daviesrob** [comment]
The `-t` option does not take a number.  Instead it should be given a two-letter [auxiliary tag](http://samtools.github.io/hts-specs/SAMtags.pdf) name, for example `RG`.

If the option is used in this way, the output will be sorted first by the value of the tag in each alignment record (so for `-t RG` it would sort first by read group) and then by position.  As this is neither a "coordinate" nor a "queryname" sort, the `SO:` value in the header is set to "unknown".

The sort order tag in the header isn't really able to describe files sorted this way.  Pull request samtools/hts-specs#361 will add a sub-sort tag that is much more expressive, but it's not been merged yet and samtools will require an update in order to support it properly.

**Comment by gusevfe** [comment]
Right... I mixed it up with `-@`.
