### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by piriboy** [samtools/samtools#1079]
#### Is your feature request related to a problem? Please specify.
I got an error when compile.
OS : Mac Mojave 
./configure worked; however, when I tried to "make", I keep getting an error message as below.

Donghoons-MacBook-Pro-2015:samtools hoon$ make
gcc -g -O2 -I. -I/Library/SAMTools/htslib-1.9/ -I./lz4  -c -o bam_plcmd.o bam_plcmd.c
bam_plcmd.c:888:60: error: expected ')'
                                    fprintf(pileup_fp, "%" PRId64 "", tag_i);
                                                           ^
bam_plcmd.c:888:44: note: to match this '('
                                    fprintf(pileup_fp, "%" PRId64 "", tag_i);
                                           ^
1 error generated.
make: *** [bam_plcmd.o] Error 1

I installed HTSlib-1.9 under /Library/SAMTools/htslib-1.9 and I configured as above.
I would appreciate any help for this problem.
Thanks
Hoon

**Comment by daviesrob** [comment]
It looks like it's missing a definition for `PRId64`.  Could you try adding:

```
#include <inttypes.h>
```

To `bam_plcmd.c`?  You should put it with the other `#include` lines, for example after `#include <getopt.h>`.

**Comment by jmarshall** [comment]
The `PRId64` in _bam_plcmd.c_ was introduced recently in samtools **develop**, and happens to work against HTSlib **develop** because on **develop** _htslib/faidx.h_ includes `<inttypes.h>` (really it should just include `<stdint.h>`).

So _bam_plcmd.c_ does need to get that `#include <inttypes.h>` itself; but once you've fixed that you'll get lots more errors as **develop** samtools uses new API functions that aren't in HTSlib **1.9**. So (at the moment) you'll need to compile **develop** samtools against **develop** HTSlib too anyway.

**Comment by daviesrob** [comment]
Ah, thanks.  I was wondering how it was managing to work.
