### ISSUE TITLE
Name lossy CRAM compression doesn't work with secondary and supplementary alignments

### ISSUE THREAD

**Issue by FrankFeng** [samtools/samtools#1088]
#### Are you using the latest version of [samtools]

I am using the stable 1.9 version:
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.

 #### Please describe your environment.

OS: Linux 3.10.0-693.11.6.el7.x86_64
machine architecture: x86_64
compiler: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

Hello,

I am using Samtools to remove read names from a BAM file, converting BAM to CRAM, and want to get the maximum space saving by discarding all read names. I first sorted the input BAM by read name, converted the name-sorted BAM to CRAM, and sorted the CARM by coordinate to get the final output. My data were paired-end reads, and the command of Samtools (V1.9) was:

```bash
samtools sort -n -l 0 -O bam -T bam_out $in_bam | \
    samtools view -O cram,reference=$ref,lossy_names=1,seqs_per_slice=200000,level=0 | \
    samtools sort -l 9 -O cram -T cram_out > lossy_name.cram
```

In the resulting CARM file, for those reads with secondary or supplementary alignments, the names were not removed. Neither the secondary/supplementary or their corresponding primary alignments were removed for the names. As some of my BAM files contained a large fraction of secondary or supplementary alignments, too many reads (e.g. 40% of the total) were still with their original names.

Did I do this in the wrong way? Is this what you expected or a bug? Thanks!

Regards,

Frank

**Comment by jkbonfield** [comment]
In order to permit random access, if reads span slices the read names are stored verbatim.  Thus for CRAM to discard the read names it needs to be certain that all the occurances of that name occur within the same slice.  This can be done efficiently when name sorted, as your data is, but I unfortunately I didn't optimise for that case as it's not the scenario we see often.

CRAM uses the `expected_template_count` function to return the expected number of alignment records for the template.   It does this by looking at the "TC" auxiliary tag.  If that isn't present and it sees evidence of supplementary or secondary alignments ("SA" tag) it just gives up and returns an unknown number of segments which in turn disables the read-name removal.

The correct fix here is to ensure all aligners outputting anything other than 2 alignments for a read-pair also output the TC tag.  This has been SAM best practices since 2010 (https://github.com/samtools/hts-specs/commit/3dd87ec1) but unfortunately is advice ignored by all aligners that I know of, including those from the author of that bit of best practices!  I also queried this in 2014 (https://sourceforge.net/p/samtools/mailman/message/33054794/), but it's pretty much status quo.

In your case however you could work around this issue by pre-processing the file with a small script to count lines with the same name and add TC aux tag to each one.

**Comment by jkbonfield** [comment]
One final comment, note that our implementation is dumb!  What lossy_names does is avoid writing out read names when they're not needed.  When reading them back, the code generates new names for you.  However if you read such a file and then write it back out again Samtools now *stores* those reads names instead.  Stupid I know...

As a consequence of this, you need to also use lossy_names=1 on subsequent commands too.  What we need is a way of storing CRAM parameters in the header block so we can give hints to the default actions for subsequent tools.

**Comment by FrankFeng** [comment]
Thanks @jkbonfield 

I found another tool which accepts name-sorted alignments and remove all read names, regarless of secondary or supplementary alignmets. That is what I really need.

For the compression of germline human DNAseq data, I am using crumble. Loing it! Thank you!

**Comment by jkbonfield** [comment]
Thanks for the comments of support.

I'm closing this issue now as I think you've got a solution.
