### ISSUE TITLE
How to upgrade Samtools from 1.9 to 1.10?

### ISSUE THREAD

**Issue by PlatonB** [samtools/samtools#1152]
Previously, I compiled from the sources Samtools 1.9. Now I've executed the standard three commands with the new version.
`./configure`
`sudo make`
`sudo make install`

But the version stayed the same.
`samtools --version`
> samtools 1.9
> Using htslib 1.9
> Copyright (C) 2018 Genome Research Ltd.

Is it possible to completely uninstall the previous version in order to install the new one without any problems?

**Comment by mp15** [comment]
When you first installed using `./configure` did you by any chance set `--prefix=/usr` or did you set PATH to include `/usr/local/bin` instead.

**Comment by PlatonB** [comment]
No, I didn't use any additional parameters.

**Comment by jkbonfield** [comment]
You can use `which samtools` to see where it is coming from.  If it was a system package installed as part of your operating system it will be /usr/bin/.  As @mp15 points out the default install from source is /usr/local/bin.

if your existing binaries are in /usr/bin then it's probably best to not just overwrite them by setting prefix on configure.  You should find out if your operating system is using a package manage (apt, dpkg, yum, etc) and uninstall them using the official tool, otherwise you may get in a pickle when trying to update the OS.

Alternatively just make sure /usr/local/bin is in your path before /usr/bin.

**Comment by PlatonB** [comment]
@jkbonfield I tried `which samtools`. It turned out that Samtools 1.9 was invisibly installed by Conda as a dependency of another program. After uninstalling conda's version of Samtools, V1.10 has appeared. Thanks for the help!

**Comment by jmarshall** [comment]
Finally for future readers: if you've installed a new _/usr/local/bin/samtools_ that's in your PATH in front of a previously-installed _/usr/bin/samtools_, and it's still the old one that's being executed…

If you're using bash or other shells that remember command paths, you may need to quit and restart your terminal (or just type `hash -r` or similar) to get the shell to notice the new _samtools_ location.
