### ISSUE TITLE
Error: [W::sam_parse1] urecognized mate reference name; treated as unmapped

### ISSUE THREAD

**Issue by teepean** [samtools/samtools#1158]
The last version where the issue does not occur is Version: 1.2 (using htslib 1.2.1)

OS: Windows 10, Linux, WSL
Compiler:  gcc 9.2.0 - 9.2.1 etc. Does not seems to have any effect on the issue

Relevant command:

samtools view -bT test.fa test.sam > test.bam

I am trying to convert sam to bam using above command but get an error:

`[W::sam_parse1] urecognized mate reference name; treated as unmapped`

The last version I have tested that works is samtools 1.2. I have attached a test case.

[testparse.zip](https://github.com/samtools/samtools/files/4012785/testparse.zip)

**Comment by jmarshall** [comment]
Your _test.fa_ file contains a single FASTA sequence named `chrM`.

Your _test.sam_ file has no headers and 70521 alignment records all with an RNAME of `chrM`, of which 70112 have an RNEXT field indicating `chrM` and the remainder (409 records, corresponding to the number of warnings you're getting) with an RNEXT of `1`…`22`, `X`, or `hs37d5`.

For SAM files that contain `@SQ` headers, all the values that appear in records' RNAME and RNEXT fields must have appeared in one of the `@SQ` headers. It's under-documented, but when you provide headers via `samtools view` `-t`/`-T`all the RNAME/RNEXT values that appear must similarly be present in the `-t`/`-T` file.

When samtools encounters a previously unseen RNAME or RNEXT value in an alignment record, it's too late to add it to the `sam_hdr_t` data structure. So it pretends that the RNAME/RNEXT value was `*` (unmapped) rather than whatever contig it actually was and emits the warning you've seen accordingly.

There is room for improvement in the warning: it could give an indication of the line number in question and/or print out the problematic contig name (carefully, as this is potentially adversarial input); and there is a buglet nearby (`s/tid/mtid/`) nearby (and a typo in the message).

Your recommended approach would be to add appropriate `@SQ` headers to your SAM file. If you continue using `view -T` instead, you need to add the other chromosomes and contigs that exist in your SAM file to your FASTA file.

Samtools 1.2 was also changing 409 lines of your data to `*`, but it was doing it silently instead of warning you.

**Comment by teepean** [comment]
The process is from BAM Analysis Kit which really needs rethinking from my part to be compatible with samtools. The error message does not occur always but I did not realise it did not work correctly earlier.

`https://github.com/teepean/BAM-Analysis-Kit/blob/master/console_bam.bat`

The SAM file is created this way:

`bin\cygwin\bin\bash.exe -c "bin/bow/samtools.exe view -@ %BAMKIT_THREADS% inchr.bam | /bin/sed 's/\t/\tchr/2' > tmp.sam"
bin\cygwin\bin\bash.exe -c "/bin/cat tmp.sam | /bin/sed 's/\tchrchr/\tchr/' > inchr.sam"

if "%%A" == "M" (
  bin\cygwin\bin\bash.exe -c "/bin/cat inchr.sam | /bin/sed 's/\tchrMT/\tchrM/' > inchr_tmp.sam"
  DEL /Q /F inchr.sam
  copy inchr_tmp.sam inchr.sam > NUL
  DEL /Q /F inchr_tmp.sam
)`

**Comment by jkbonfield** [comment]
It can sometimes be useful (ie quick and dirty to implement) for tools to just emit alignments and ignore fiddly things like headers, but obviously the output data is malformed.

For such cases, it's possibly best just to do something like this (not Windows, but you get the idea):

```
(cat header; some_command_producing_SAM) | samtools view -o out.bam -
```

As for your specific case though, it's simply because `samtools view` by default doesn't output the header lines when printing up as SAM.  This IMO is a mistake, but it's sadly a design decision which we cannot back out of without breaking lots of pipelines.  You should add a `-h` option in there to get it to print up the headers.

**Comment by teepean** [comment]
I took a look at the code and it is actually reheadering it after the lines I quotes earlier.

bin\cygwin\bin\bash.exe -c "bin/bow/samtools.exe view -@ %BAMKIT_THREADS% inchr.bam | /bin/sed 's/\t/\tchr/2' > tmp.sam"
bin\cygwin\bin\bash.exe -c "/bin/cat tmp.sam | /bin/sed 's/\tchrchr/\tchr/' > inchr.sam"

if "%%A" == "M" (
  bin\cygwin\bin\bash.exe -c "/bin/cat inchr.sam | /bin/sed 's/\tchrMT/\tchrM/' > inchr_tmp.sam"
  DEL /Q /F inchr.sam
  copy inchr_tmp.sam inchr.sam > NUL
  DEL /Q /F inchr_tmp.sam
)

bin\cygwin\bin\bash.exe -c "/bin/samtoolsold.exe view -bT ref.fa inchr.sam > reads.bam"
bin\cygwin\bin\bash.exe -c "bin/bow/samtools.exe view -@ %BAMKIT_THREADS% -H inchr.bam|/bin/grep -v SN > header01"
bin\cygwin\bin\bash.exe -c "bin/bow/samtools.exe view -@ %BAMKIT_THREADS% -H reads.bam > header02"
copy header01+header02 header /Y /B > NUL
bin\cygwin\bin\bash.exe -c "bin/bow/samtools.exe reheader header reads.bam > bam_wh_tmp.bam"``

**Comment by teepean** [comment]
> and the remainder (409 records, corresponding to the number of warnings you're getting) with an RNEXT of 1…22, X, or hs37d5.

So these lines should be filtered out from the resulting file anyway?

**Comment by jmarshall** [comment]
> So these lines should be filtered out from the resulting file anyway?

They represent the two ends of the template being individually well-mapped but to different chromosomes, indicating a breakpoint within the unsequenced insert between the two reads or some other perhaps artefactual anomaly.

Whether this means the lines are of interest for your analysis depends on the nature of your analysis. I would think that typically they would be interesting and not to be filtered out.

**Comment by jmarshall** [comment]
To reiterate the interesting part of this from an HTSlib maintenance point of view:

> There is room for improvement in the warning: it could give an indication of the line number in question and/or print out the problematic contig name (carefully, as this is potentially adversarial input); and there is a buglet (`s/tid/mtid/`) nearby (and a typo in the message).

**Comment by teepean** [comment]
> > So these lines should be filtered out from the resulting file anyway?
> 
> They represent the two ends of the template being individually well-mapped but to different chromosomes, indicating a breakpoint within the unsequenced insert between the two reads or some other perhaps artefactual anomaly.

The program calls splits the BAM and calls variants separately for each chromosome so the data would not be used regardless of it's usability. 

Thank you very much for your replies. I think I will just output the warnings to null.

Here's Linux version of the program I am trying to improve. If you have any ideas how to split the chromosomes more efficiently, please let me know. Thanks!

[console_bam.zip](https://github.com/samtools/samtools/files/4019240/console_bam.zip)


https://raw.githubusercontent.com/teepean/BAM-Analysis-Kit-Linux/master/console_bam.sh
