### ISSUE TITLE
samtools index: failed to create index: 

### ISSUE THREAD

**Issue by zrhhl** [samtools/samtools#1182]
#### Are you using the latest version of [samtools]
Yes.
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
Linux 2.6.32-696.el6.x86_64

- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
x86_64

- compiler (run `gcc --version` or `clang --version`)
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
Copyright (C) 2010 Free Software Foundation, Inc.

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

1)
I have run "samtools index -c -@ 20 ./output.sort.bam ./output.bam.csi",
the error information was "
[E::hts_idx_push] NO_COOR reads not in a single block at the end 19 -1
samtools index: failed to create index for "./output.bam": No such file or directory
"
2)
Before run index,I have also run "samtools sort -m 50G ./output.bam -o ./output.sort.bam" and it was completed,but the error still appear.

3)
It's worth noting that the bam file is about 75G and the length of chromosome is about 1GB~2GB,I'm not sure if the error is because of the file big size.

Thanks a lot,
Laura

**Comment by valeriuo** [comment]
> I have run "samtools index -c -@ 20 ./output.sort.bam ./output.bam.csi",
the error information was "
[E::hts_idx_push] NO_COOR reads not in a single block at the end 19 -1
samtools index: failed to create index for "./output.bam": No such file or directory

The strange fact is that samtools appears to have been given **output.bam** as argument, and not **output.sort.bam**. Also, when sorting you can probably get the job done with less than 50 GB of RAM, even if the file is large. Do you have that much available?

Can you also try the commands with the latest versions of [htslib](https://github.com/samtools/htslib/releases/tag/1.10.2) and [samtools](https://github.com/samtools/samtools/releases/tag/1.10)?

**Comment by zrhhl** [comment]
Thanks,valeriuo!

I tried " samtools index -c -@ 20 output.sort.bam output.sort.bam.csi  ",but the error above-mentioned still existed. Also I'm not sure weather I get your meaning. Besides,you mean the RAM and CPU are related to the error?

I have checked the latest version  of samtools is "samtools-1.10" and I'm stalling it.

Thanks !

**Comment by zrhhl** [comment]
Additional information：
The latest version of samtools I have tried:
" samtools-1.10/bin/samtools index -c -@ 20 output.sort.bam output.sort.bam.csi "

And the error info :
【
[E::hts_idx_push] NO_COOR reads not in a single block at the end 15 -1
[E::sam_index] Read 'CL100125759L2C004R008_259430/2' with ref_name='chr7_2', ref_length=1276855688, flags=16, pos=1073741926 cannot be indexed
samtools index: failed to create index for "output.sort.bam"
】

Thanks a lot,
Laura

**Comment by jkbonfield** [comment]
This error message dates back to 2014: cc207d82c83fc051c0d549d9f2e3d75448963e1c

It's presumably triggered for the reason it is citing - that your BAM file has unmapped data followed by mapped reads.  The most obvious conclusion is that it's not position sorted, but it could also be due to some other glitch in whatever made the BAM (samtools sort apparently).

How fast is it producing this error message?  If it's quick, presumably read CL100125759L2C004R008_259430/2 is close to the start (the "/2" in there worries me a bit - should it be the second half of a read pair? if so it's wrongly processed and named).

In which case looking for this read and surrounding ones may be informative. Eg:

```
samtools view output.sort.bam | grep -B1 -A1 CL100125759L2C004R008_259430/2
```
would show this read and the one before/after it.  By the sounds of it, the indexer is claiming the previous one is unmapped and unplaced (ie chr is "*").

**Comment by zrhhl** [comment]
Thank you,jkbonfield.

Yes,as you say,the error message produced quickly.

Here is the information around the line above mentioned:

CL100125759L2C011R078_191064/2  0       chr7_2  1073741765      255     100M8S  *       0       0
CL100125759L2C004R008_259430/2  16      chr7_2  1073741926      255     8S100M  *       0       0
CL100125759L2C014R092_193949/2  16      chr7_2  1073741927      255     8S100M  *       0       0

I also extracted the "chr7_2.bam“  from "output.sort.bam"  with all info mapped "chr7_2"  to run “samtools sort chr7_2_all.bam -o chr7_2_all.sort.bam”
and "samtools index -c chr7_2_all.sort.bam chr7_2.sort.bam.csi"，It finished without error.

But when I just run "samtools index -c chr7_2_all.bam chr7_2_all.bam.csi", it reported error"
[E::hts_idx_push] Unsorted positions on sequence #16: 1276853533 followed by 1073741826
samtools index: failed to create index for "chr7_2_all.bam": No such file or directory
"
But the original whole bam file have been sorted.I wonder what has caused this phenomenon?Maybe the file is too big to sort normally?

Thanks a lot,
Laura

**Comment by jkbonfield** [comment]
It shouldn't be too big to sort, but I was trying to rule out a sort bug when I asked for the results of that grep command.

It just doesn't make sense though:

>  [E::hts_idx_push] Unsorted positions on sequence #16: 1276853533 followed by 1073741826

According to your grep, the sorted file goes from 1073741765 to 1073741926, which straddles 1073741826.  Also all 3 of those reads in the grep are mapped and sorted, so I don't see why you'd get a NO_COOR error message reported for CL100125759L2C004R008_259430/2.

You won't be able to index the unsorted data, which is why `samtools index -c chr7_2_all.bam chr7_2_all.bam.csi` errors (unlike the index of chr7_2_all.sort.bam).  However this still doesn't explain your original error.

I'm wondering if we can minimise it down to a smaller subset by trial and error. Eg to index the first 10,000 records you could do this.

```
(samtools view -H in.bam;samtools view in.bam | head -10000) | samtools view -b -o out.bam
samtools index out.bam
```

If it's failing at the start, it's likely you can by trial and error figure out which head count is required to produce the error.  Then you can throw away the starting reads to narrow it down further. Eg for records 8000 to 10000 we could do:

```
(samtools view -H in.bam;samtools view in.bam | head -10000 | tail -2000) | samtools view -b -o out.bam
samtools index out.bam
```

This is all a bit tedious, but without seeing your data I cannot diagnose the reason for the error you are getting so trying to isolate it to a couple of reads yourself is probably the easiest way forward.

PS.  I still suspect your reads are misnamed, although this shouldn't affect sort or index.  It's clearly short read data.  What aligner are you using?  Do you have a CL100125759L2C004R008_259430/1 too?  If so they should likely both be called CL100125759L2C004R008_259430 and labelled as READ1 and READ2 in the flags in order to form a pair.

**Comment by jkbonfield** [comment]
My mistake on a rogue linkage to this issue in a PR.  Wrong tab! It was meant to be another - fixing.

**Comment by zrhhl** [comment]
Thanks！

Yes ,I agree with you.I divided the "output.sort.bam" into two parts at a line, which is the demarcation point of two different reference sequence name. The part one run without error,and part two reported the error "
[E::hts_idx_push] Chromosome blocks not continuous
samtools index: failed to create index for "chr_unplaced.sort.bam": No such file or directory
" 
And then I checked the part2.bam, there existed the reads map to the different reference sequence but with same position,so when the pos is same,the order will depend on the alphabetical order of its reference sequence name.I wonder maybe this situation cause the initial error.

And I am not sure how to deal with this situation,I try to use different parameters with  "samtools sort " function,but it seams that there is not appropriate parameter.

Thanks,
Laura

**Comment by zrhhl** [comment]
Thanks！

Yes ,I agree with you.I divided the "output.sort.bam" into two parts at a line, which is the demarcation point of two different reference sequence name. The part one run without error,and part two reported the error "
[E::hts_idx_push] Chromosome blocks not continuous
samtools index: failed to create index for "chr_unplaced.sort.bam": No such file or directory
" 
And then I checked the part2.bam, there existed the reads map to the different reference sequence but with same position,so when the pos is same,the order will depend on the alphabetical order of its reference sequence name.I wonder maybe this situation cause the initial error.

And I am not sure how to deal with this situation,I try to use different parameters with  "samtools sort " function,but it seams that there is not appropriate parameter.

Thanks,
Laura

**Comment by valeriuo** [comment]
> samtools-1.10/bin/samtools index -c -@ 20 output.sort.bam output.sort.bam.csi

Does the single-thread (without **-@ 20**) version of this command give you the same result?
`samtools-1.10/bin/samtools index -c output.sort.bam output.sort.bam.csi`

**Comment by valeriuo** [comment]
Please try the latest HTSlib develop [HEAD](9979fac560319507cefe5d5682617304d609b589) and reopen with the requested information, if issue still persists.

**Comment by domewq** [comment]
> Thanks！
> 
> Yes ,I agree with you.I divided the "output.sort.bam" into two parts at a line, which is the demarcation point of two different reference sequence name. The part one run without error,and part two reported the error " [E::hts_idx_push] Chromosome blocks not continuous samtools index: failed to create index for "chr_unplaced.sort.bam": No such file or directory " And then I checked the part2.bam, there existed the reads map to the different reference sequence but with same position,so when the pos is same,the order will depend on the alphabetical order of its reference sequence name.I wonder maybe this situation cause the initial error.
> 
> And I am not sure how to deal with this situation,I try to use different parameters with "samtools sort " function,but it seams that there is not appropriate parameter.
> 
> Thanks, Laura

How you split into two parts
