### ISSUE TITLE
samtools sort is not stable

### ISSUE THREAD

**Issue by colinhercus** [samtools/samtools#1193]
Hi,

samtools sort used to be stable but testing samtools 1.10 with 32 threads the sort is not stable.

I know the current documentation doesn't specify it is stable and was just wondering if the change is intentional.

Thanks, Colin

**Comment by valeriuo** [comment]
Stable in what sense? Please use the issue template to offer more details about the problem you are experiencing.

**Comment by colinhercus** [comment]
As in

A sorting algorithm is said to be stable if two objects with equal keys appear in the same order in sorted output as they appear in the input array to be sorted. Some sorting algorithms are stable by nature like Insertion sort, Merge Sort, Bubble Sort, etc

**Comment by jkbonfield** [comment]
I don't believe this was an intended change and I thought the stable sort was intentional, albeit apparently never documented.

My guess is it'd be something to do with the radix sort changes in layout for the 64-bit pos work as that's the most significant change, but it'll need more investigation and maybe some bisect work.

**Comment by colinhercus** [comment]
Hi James,
It's not really a problem for me. I was just doing a compare of novosort markduplicates against samtools markdup and finding an order difference. I'm now using novosort rather than samtools sort so that I get a stable sort.
I do know Heng Li had emphasised that samtools sort was stable and that's why I made novosort stable.
The TLEN differences also surprised me as I thought fixmate would keep up with the spec's.
Kind Regards,Colin

**Comment by daviesrob** [comment]
It's supposed to be stable, and not being so would be a bug.  Does the lack of stability only happen with a high thread count?  And is it possible to make a small example that shows the problem, or do you need enough data to make it run the merging step?

**Comment by colinhercus** [comment]
It was a WES sample. I'll have a look tomorrow to see if I can reduce file size and threda count to reproduce it

**Comment by jkbonfield** [comment]
I tried and failed to reproduce this earlier.  For what it's worth, here was my process:

Firstly create some test data.  Lots of reads starting in relatively few sites in order to create lots of potential for reordering.

```
perl -e 'for ($r=0;$r<3;$r++){print "\@SQ\tSN:chr$r\tLN:200\n"} for ($r=0;$r<3;$r++) {for ($p=1;$p<=100;$p++) {for ($i=0;$i<1000;$i++) {print "$r:$p:$i\t0\tchr$r\t$p\t0\t10M\t*\t0\t0\tAAAAAAAAAA\tEEEEEEEEEE\n"}}}' > /tmp/_.sam
```

Randomise the order of lines in this file:

```
perl -e 'while (<>) {if (/^@/) {print} else {push(@lines,$_)}} $n = scalar(@lines);for ($i=0;$i<$n;$i++){$idx[$i]=$i};for ($i=0;$i<1000000;$i++) {$i1=int(rand()*$n);$i2=int(rand()*$n);$_=$idx[$i1];$idx[$i1]=$idx[$i2];$idx[$i2]=$_} for($i=0;$i<$n;$i++) {print $lines[$idx[$i]]}' /tmp/_.sam > _r.sam
```

Then sort the file using lots of threads and a minimum memory size to encourage lots of merge steps from both disk and memory.  Sorting by both name and pos.

```
samtools sort -O sam -n -@10 -m 1M  --no-PG /tmp/_r.sam|md5sum
samtools sort -O sam -@10 -m 1M --no-PG  /tmp/_r.sam|md5sum
```

Repeating this, or changing number of threads or size of memory limit always gives the same result.
It looks like it's stable to me unless it's an exceptionally rare event.

Maybe there's something in the flags that matters? I tried randomising those a bit and no change.

Are you sure it's unstable, rather than simply a different sort order to how you expect?  Note samtools sort uses more than chr/pos.  It has a secondary sort defined by flags too.

**Comment by colinhercus** [comment]
Hi James,
I think you are right and samtools sort is including the stand flag (0x10) in the key though I can't find any documentation of this. In the examples I've checked the order of read 1&2 was changed for fragments shorter than the read length (both reads of pair have same mapping locations) so that + strand alignment was before - strand.
Sorry to have bothered you,
Colin
