### ISSUE TITLE
samtools fixmate sets tlen to value that does not conform to spec's

### ISSUE THREAD

**Issue by colinhercus** [samtools/samtools#1194]
Hi,

Using samtools 1.10 fixmate TLEN was set to a value that does not confirm to the specifications "the unsigned observed template length equals the number of bases from the leftmost mapped base to the rightmost mapped base"
Before fixmate the TLEN was 97 which equals the mapped length of the first read in pair.
After fixmate...
NS500102:222:XXXXXXXXX:1:12204:5021:7226	83	chr1	18254	0	97M	=	18265	-86	GGTATGGGGACTACCTTGATGGCCTTCTTGCTGCCCTTGATCTTCTCAATCTTGGCCTGGGCCAAGGAGACCTTCTCTCCAATGGCCTGCACCTGGC	EAEEEEE<EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEAEEEEEEEEEEEEEEEEEEEEEEEAAAAA	PG:Z:novoalign	AS:i:0	UQ:i:0	NM:i:0	MD:Z:97	PQ:i:186	SM:i:0	AM:i:0	ZS:Z:R	NH:i:7	HI:i:1	IH:i:1	ZA:f:0.669	MQ:i:0	MC:Z:11S51M35H	ms:i:1050
NS500102:222:XXXXXXXXX:1:12204:5021:7226	163	chr1	18265	0	11S51M35H	=	18254	86	GTTTGGGGGCGTACCTTGATGGCGTTCTTGGTGCCCTTGATGTTGTCAATATTGGCCTGGGC	A////EEEE//A/E/AA///EAE////AAA//A/E/A<////A////<///EEEEE/AEEEE	PG:Z:novoalign	AS:i:184	UQ:i:184	NM:i:5	MD:Z:12C6C10C2C5C11	PQ:i:186	SM:i:0	AM:i:0	ZS:Z:R	NH:i:7	HI:i:1	IH:i:1	ZA:f:0.669	MQ:i:0	MC:Z:97M	ms:i:3451

Before fixmate...
NS500102:222:XXXXXXXXX:1:12204:5021:7226	83	chr1	18254	0	97M	=	18265	97	GGTATGGGGACTACCTTGATGGCCTTCTTGCTGCCCTTGATCTTCTCAATCTTGGCCTGGGCCAAGGAGACCTTCTCTCCAATGGCCTGCACCTGGC	EAEEEEE<EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEAEEEEEEEEEEEEEEEEEEEEEEEAAAAA	PG:Z:novoalign	AS:i:0	UQ:i:0	NM:i:0	MD:Z:97	PQ:i:186	SM:i:0	AM:i:0	ZS:Z:R	NH:i:7	HI:i:1	IH:i:1	ZA:f:0.669
NS500102:222:XXXXXXXXX:1:12204:5021:7226	163	chr1	18265	0	11S51M35H	=	18254	-97	GTTTGGGGGCGTACCTTGATGGCGTTCTTGGTGCCCTTGATGTTGTCAATATTGGCCTGGGC	A////EEEE//A/E/AA///EAE////AAA//A/E/A<////A////<///EEEEE/AEEEE	PG:Z:novoalign	AS:i:184	UQ:i:184	NM:i:5	MD:Z:12C6C10C2C5C11	PQ:i:186	SM:i:0	AM:i:0	ZS:Z:R	NH:i:7	HI:i:1	IH:i:1	ZA:f:0.669

Kind Regards, Colin

**Comment by jkbonfield** [comment]
You are correct in that it doesn't match the current specification.  Sadly this has been a problem forever.  Likewise you'll find Picard does the same thing, as do many other implementations.  It's rather a case of "I wouldn't start from here if I was you". :-(

The problem is the SAM specification used to state 5' to 5' which in this case works out as 86 long instead of 97.  Samtools and Picard adhered to the spec at that stage.  Later it was updated from 5' to 5' to leftmost to rightmost, but sadly the software wasn't updated to comply with it (even those written by the same author of the spec change).  Hence most continued to use 5' to 5'.  Since then some newer tools read the spec and derived TLEN "correctly".  CRAM does it that way too IIRC.  This rather unsatisfactory situation has ultimately lead to two different interpretations of TLEN (termed ISIZE in the older specs).

I and others tried to tidy it up in the past but it just bogged down in arguments about what the standard really is - the defacto implementations or the tex document.  In the end we agreed to draw a line under it and just document it as being poorly defined with two distinct possible definitions, and even that was a long drawn out thing to get right.

As of last week, the spec now contains a footnote about the split personality of TLEN.  See https://github.com/samtools/hts-specs/pull/366

It's not in the PDF yet.  I'll rebuild it, but I was hoping we could get some unsigned vs signed changes in promptly too so delayed the rebuild.
