### ISSUE TITLE
Can samtools resume an aborted sort?

### ISSUE THREAD

**Issue by calliza** [samtools/samtools#1195]
Hi,
I had an alignment with BWA piped to samtools sort that was killed by PBS due to surpassing requested walltime. The temp files and the partially-created sorted BAM are still on disk. Is it possible to resume this sort step, rather than start the process again?

The command:
bwa mem -M -t $NCPUS $ref \
	-R "@RG\tID:${sample}_${library}\tPL:${platform}\tSM:${sample}\tLB:${sample}_${library}\tCN:${seq_centre}" \
	$fq1 $fq2  \
	| samblaster -M -e -d $disc_out -s $split_out 2>$dup_log \
	| samtools sort -@ $NCPUS --write-index -m 4G -o $bam_out  -

Using BWA v0.7.17, samtools v1.10, samblaster v0.1.22

Thanks,
Cali

**Comment by dpryan79** [comment]
You can `samtools merge` the temp files since they're just regular (sorted) BAM files. If `$bam_out` exists and contains more than just a header then this will be equivalent to the case where `samtools sort` hadn't gotten killed by PBS.

**Comment by daviesrob** [comment]
Unfortunately this doesn't quite work, because not all of the data gets written out to the temporary files.  The last part would still have been in memory, so it would have been lost when the program was killed.

So I'm afraid you'll be able to get back some of the data, but part of it will be missing.

**Comment by calliza** [comment]
Ah that's what I was worried about. Thanks for your replies.
