### ISSUE TITLE
Enable multiple sequence retrieval from samtools faidx

### ISSUE THREAD

**Issue by mortonjt** [samtools/samtools#1213]
First off, thank you for making this tool available, it is incredibly useful for indexing / searching large files.

One thing that I'm noticing is that retrieving one sequence isn't that fast - here is an example with the stringv9 fasta file of a few million proteins.  
```
samtools faidx protein.sequences.v11.0.fa 190486.XAC0104
```
Below are the timing results
```
real	0m32.180s
user	0m29.119s
sys	0m1.609s
```

I'm guessing that most of this time is spent trying to load the actual fasta index in memory - and the actual retrieval is fast (on order milliseconds). If this is the case, it would be incredibly useful to allow for multiple sequences to be extracted simultaneously.  Specifically, something like the following option would be incredibly useful

```
samtools faidx protein.sequences.v11.0.fa -i <list_of_ids.txt>
```
Or even read from stdin
```
cat list_of_ids.txt | samtools faidx protein.sequences.v11.0.fa 
```
Let me know what this makes sense or if loading the index is the bottleneck here. I have implemented my own fastidx in python a while back, so converting that to C and creating a pull request is not outside the realm of possibility here.

**Comment by whitwham** [comment]
Does the -r (or --region-file) option not do what you want?

**Comment by whitwham** [comment]
No word from @mortonjt so I am going to close this.

**Comment by dstern** [comment]
I have been unable to get the -r flag to work. samtools faidx seems to recognize the the -r as the region, rather than as a flag. Using samtools 1.13 on MacOS11.5.2.

% samtools faidx ../../all.fa --region-file g25083.t1_MpCOO2_secreted.hits
>--region-file
[fai_fetch] Warning - Reference --region-file not found in FASTA file, returning empty sequence
Failed to fetch sequence in --region-file
% samtools faidx ../../all.fa -r g25083.t1_MpCOO2_secreted.hits
>-r
[fai_fetch] Warning - Reference -r not found in FASTA file, returning empty sequence
Failed to fetch sequence in -r

**Comment by jmarshall** [comment]
The phrasing of that `Warning - Reference … not found` message was changed in samtools/htslib@f0fc3eea33477ed45f5f9ffa34f6fea7365513d8, indicating that in fact the samtools that you are using is version 1.4.1 or earlier. Meanwhile the `-r`/`--region-file` option was added in version 1.9.

So you may need to examine your `$PATH` and see just which samtools installation you are really using.

Traditionally Unix command line options should be written before any non-option arguments such as `../../all.fa`. Programs that have long options use `getopt_long()` which allows options and arguments to be interleaved. Prior to 1.9, `samtools faidx` did not have long options and used the `getopt()` function — which on macOS (unlike on Linux with glibc) **does** require options to come before other arguments. This is why it treated `‑‑region-file`/`‑r` as an argument (namely, the region) rather than failing with `illegal option ‑r` or similar.

**Comment by dstern** [comment]
Woops! Apologies. Indeed, I thought I had installed 1.13 properly to /bin, but alas had not. -r option works fine immediately before region-file (and is fast!)!
Many thanks for your rapid response.
