### ISSUE TITLE
How can I include original base quality from FASTQ file into (OQ) existing bam file

### ISSUE THREAD

**Issue by justinjj24** [samtools/samtools#1223]
Hi all,
I need to append the base quality in fastq file to my existing bam file which does not contain OQ. The bam is generated by parabricks germline pipeline. Ultimately I need to convert the bam to cram with OQ.
Thanks.

**Comment by jkbonfield** [comment]
I'm curious why you need the OQ values?  I wasn't aware any pipelines still wanted them, and it's desireable not to include them because they vastly bloat the size of the files.

We don't have a tool for doing this.  I think your best bet would be to name sort the data, hopefully in the same order as the fastq, and output as SAM.  Turn the fastq into a one line per record file (it's a simple script to read 4 lines and output them as tab delimited instead), if required also name sort that.  Once you have fastq-a-like and SAM then it's just a matter of doing a "join" and some format hackery.  We don't have any scripts for this though, just ideas and unix command line experimentation.

Maybe someone else has a tool that does this properly, but you'd get more luck asking on BioStars or the samtools-help email list than this issue tracker.

**Comment by justinjj24** [comment]
Thanks you @jkbonfield for answering my query and apologies to post my question here. I could use the sam output and simple scripting to match with reformatted fastq.
