### ISSUE TITLE
Criticism and suggestion

### ISSUE THREAD

**Issue by zohalnew** [samtools/samtools#1322]
If the authors had compiled these commands graphically for Windows
Or they put video tutorials
They did not have to waste their time answering problems
And it is unfortunate that in 2020 we work with the command line

**Comment by valeriuo** [comment]
I was actually thinking of doing a few video tutorials on how to install and run the most used SAMtools commands, although the amount of support (problem answering) we do is quite low.
As for the graphical interface, SAMtools, BCFtools and HSTlib are mostly run in pipelines on *nix clusters, so developing a Windows GUI would not justify the effort. We are thinking, however, of a web based helper tool.
What difficulties did you encounter in using the commands with CLI?

**Comment by whitwham** [comment]
This account has left the same comment on several repositories.

**Comment by jkbonfield** [comment]
Rather than making the same complaint to multiple tools, you would probably be better off learning some rudimentary command line knowledge.   Fundamentally a GUI to samtools can be little more than a pointy-clicky interface to select command, select files, and then select a bunch of command line options.  There isn't really anything graphical to display bar a few stats, so all it could do is launch applications.

It may be painful to get started, but in the long term you'll find it's easier and faster to do this entirely via the command line than lots of to-ing and fro-ing from mouse to keyboard.  Likewise for the other packages you've reported the same issue with.

(Even Microsoft acknowledge this, which is one reason why they created PowerShell and why they've been actively moving towards more command line capabilities.)

**Comment by zohalnew** [comment]
Thank you all
I have no problem with the program
I just suggest like
https://usegalaxy.org
Put graphic tools on the web or in Windows to save researchers time
good luck
