### ISSUE TITLE
Assertion error when samtools merge is run with threading and auto indexing

### ISSUE THREAD

**Issue by lacek** [samtools/samtools#1328]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)?

Yes.
samtools 1.11
Using htslib 1.11

 #### Please describe your environment.
- OS: 4.15.0-46-generic
- machine architecture: x86_64
- compiler: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

Run merge command with threading and auto indexing options with these BAM files ([bam.tar.gz](https://github.com/samtools/samtools/files/5421531/bam.tar.gz)):

```sh
$ samtools merge -f --write-index -@1 test.bam##idx##test.bam.bai input/*.bam
samtools: bgzf.c:276: bgzf_idx_flush: Assertion `mt->idx_cache.nentries == 0 || mt->block_written >= e[0].block_number' failed.
Aborted (core dumped)
```

When either `--write-index` or `-@` is removed, the command works fine. `samtools index` works fine too on latter case.

The BAM files attached are subset from a WGS sample. So far I've only observed the problem when working with WGS samples, but not smaller dataset from other kinds of experiment, such as WES and amplicon.

**Comment by jkbonfield** [comment]
Sorry I realised I forgot to reply to this.

Thank you for the bug report, although I confess it fills me with dread!  I'm working on another issue right now but will look into this one.  The whole auto-indexing code is rather complicated when it comes to threading due to the nature of it going back and updating previously indexed values when a new block starts.  I *thought* I'd got it fully stable, but it sounds otherwise.

Many thanks for the test data too.  I can confirm that the problem is reproduced here.

**Comment by jkbonfield** [comment]
I *think* this is an easy one to fix, but it needs more checking to be sure.

The assertion is ensuring it never misses any blocks.  Our writer thread is incrementing block numbers of compressed bgzf blocks that we've written and the `hts_idx_push` calls is tracking the block numbers of data as we're processing it.  We use those block numbers to ensure we only flush to the index entries where we know we've gone beyond that block and no we'll no longer be affecting the index.

Where my wrong assumption in the assert statement is that every bgzf block will have an index entry associated and we'll never skip blocks.  We do.  Long reads, or in this case short reads with very long aux tags, mean a single entry can span multiple blocks.  Just commenting out the assert gave me a perfectly valid index and one that is binary identical to the index produced by `samtools index`.  I don't think that's quite the answer, as I thin we need a <= rather than == in the flushing loop, but as a heads up it's not looking as bad as I feared. :-)
