### ISSUE TITLE
bam to cram with changed CIGAR and MAPQ 

### ISSUE THREAD

**Issue by chenwenan** [samtools/samtools#1330]
Dear samtools developers,

I am trying to use samtools to convert bams to crams to reduce the storage space. But when I compare the converted cram with the original bam, it seems that there are few differences in CIGAR and MAPQ, mainly on the GL* contigs and some on MT, very few on Y or autosomal chromosomes. I don't know why the CIGAR and MAPQ are changed in the CRAM file. Here is a case of diff:

# cram
< 29005887      87      GL000234.1      40434   0       *       =       40392   -142    TGCATGAACACCCAAGGGCCCTGGGTAACCTGCCCTCCGAAGGGCCCAGAAACCACAGACACAGGGCCTTGTGTGGTAGGTGAAGGTGGGGCCAGATCAG       >BA=>A=<B<CCE?ACCDCBB?AAB<?=CC?CBBD?B=B@AAACAACAB@@>AC=CBB<B=C@A@CAB@@B?A?@A=@@A@A?@@AAAAACBCBC>>???

# original bam
> 29005887      87      GL000234.1      40434   60      100M    =       40392   -142    TGCATGAACACCCAAGGGCCCTGGGTAACCTGCCCTCCGAAGGGCCCAGAAACCACAGACACAGGGCCTTGTGTGGTAGGTGAAGGTGGGGCCAGATCAG       >BA=>A=<B<CCE?ACCDCBB?AAB<?=CC?CBBD?B=B@AAACAACAB@@>AC=CBB<B=C@A@CAB@@B?A?@A=@@A@A?@@AAAAACBCBC>>???

Any reason why this happens? And is this an important issue for using crams to archive bams to reduce storage. 

Thanks,
Wenan

**Comment by whitwham** [comment]
That is interesting.  The FLAG is 87 which translates as  PAIRED, PROPER_PAIR, UNMAP, REVERSE, READ1.

Why does an unmapped read have a MAPQ of 60 and a CIGAR string?

**Comment by jkbonfield** [comment]
This is a known bug of bwa.  It initially makes an alignment, generating MAPQ and CIGAR, but then it discovers the alignment it's made is wrong.  In this case  GL000234 is 40531bp long.  Your alignment starts at 40434 and extends for 100bp, which means it overhangs the end of the chromosome!  (BWA's initial alignment was to a concatenation of all chromosomes, so some sequences will inevitably span the junction.)

There used to be a long standing bug where bwa would then emit these alignments with duff CIGAR strings which understandably caused havoc for some tools.  The fix apparently is to spot them and change your mind on it being aligned by setting the unmapped flag.  However they forgot to also clear the other fields.  Hence more nonsensical data. :-(

CRAM 3 cannot store these fields; it's simply impossible as the specification states the mapping information is stored for mapped data only.  (It's something I was looking at with CRAM 4, but that's sadly taking a long while to appear.)

If you want to validate round trip, you probably need to write a sanity checking tool first that knows what differences are important and what are due to nonsense input.  I know that's rather annoying; sorry.  (The "compare_sam.pl" script in the Samtools or Htslib test harness may already be sufficient.)  The alternative could be a local hack / tweak where you look for MAPQ and CIGAR on unmapped reads and create custom aux tags to migrate the values to.  You'd need to then reverse this with an equivalent hack.

Note you may also find CRAM changes some other things.  Sometimes we find the alignment mate pairing data is wrong too, such as stating my mate is mapped when it is clearly not, or specifying a completely wrong insert size.  Modern CRAM implementations try to cover over these cracks by storing data verbatim when it doesn't round trip, but it's not true for some older htslib versions and I suspect there may still be other invalid data that doesn't round trip.  In these cases CRAM is basically "fixing" things, in the same manner than "samtools fixmates" would.

PS.  Another bug you may witness is changed cigar strings.  There have

**Comment by chenwenan** [comment]
Hi, whitwham and jkbonfield

Thank you so much for your quick reply. I also checked ~300 WES bams I converted and all diffs show the flags that include "reads unmapped". So I think this explains all the differences I detected. 

I previously worried about losing some information after converting from bam to cram. Now it seems that cram is correcting some mis-specified information in bam. This is a relief. I think I will simply ignore this inconsistency and convert to cram then. 

Thank you both again!

Wenan

**Comment by jmarshall** [comment]
> The fix apparently is to spot them and change your mind on it being aligned by setting the unmapped flag. However they forgot to also clear the other fields.

Not so much forgot as steadfastly refused. Recall e.g. this [samtools-devel thread](https://sourceforge.net/p/samtools/mailman/samtools-devel/thread/4B918209.5090506%40broadinstitute.org/). :cry:
