### ISSUE TITLE
MD5 cache vs -T

### ISSUE THREAD

**Issue by anderspitman** [samtools/samtools#1347]
If I understand correctly, samtools can view a CRAM file either by using an MD5 cache (which is what I'm currently doing) or by providing a reference with -T. I'm wondering if there are any pitfalls with -T that I might be missing.

We have [a server](https://github.com/iobio/iobio-gru-backend) that provides many bioinformatics functions to our frontend IOBIO apps. It requires a ~100GB data directory to support the various functionality (most of the space is taken up by a VEP cache).

Currently we have a complete copy of the MD5 reference cache. But some of the other functionality of our server requires full references, so we have those too. It would be nice to simply use the full references when viewing CRAMs, so we could drop the MD5 cache.

A few potential problems I could see:

* If there's a naming mismatch (ie "chr1" vs "1"), I would guess it wouldn't work at all? This isn't a problem with MD5 since it's based on the content of the references.
* Perhaps worse, if the name maps to the wrong reference, it would yield invalid results. I suppose that's like saying the wrong MD5 could be stored in the SQ though.
* There's an extra step in reading the fasta index, then opening the fasta, seeking to the correct place, and reading the reference. I wouldn't expect this to be a large difference but it could add up. Though it could just as easily go the other way and be faster due to data locality of having the reference in a single file.

Are these valid concerns, and am I missing any others?

**Comment by daviesrob** [comment]
I think our documentation needs an update.  While it [says](https://www.htslib.org/doc/samtools.html#REFERENCE_SEQUENCES) cram will ignore references with http `UR` tags, this is not true and a sufficiently new copy will try to download them.  So you don't need to use `M5` or `-T` if your `UR` tags point to the correct reference on your web server.  I expect you would need to supply a dummy REF_PATH though, otherwise samtools may try to get the references from the EBI's server.  You also need a web server that can serve partial content (range) requests, as cram gets very upset if it can't seek on the reference file (you probably do have this if `-T` works).

The cram conversion will fail if the names in your reference file don't match the ones in the header.  If your name maps to the wrong reference decoding should fail because each cram block stores a checksum for the reference segment(s) that is needs.  If you try writing cram with the wrong reference it might work, but the file will not be very well compressed and you will need to use the same "wrong" reference to decode it.

I doubt there's much difference in speed between using `-T` with an http URL and getting them via `M5` that way - in fact `-T` might be quicker as it generally makes fewer requests.  Using `M5` and files on a shared filesystem tends to be the fastest way of getting them though, as samtools can use memory mapping to read them, which is often much quicker than http.

If you want to store less data, another option might be to generate the `M5` reference files from the full fasta files (or if you prefer the fasta files from the `M5` references).  You would need to store a mapping between MD5 and the fasta entries, but that would be much smaller.  It should be possible to generate the `M5` fragments by using something like `samtools faidx` to get the part you want, and then stripping out the fasta header and any spaces or newlines.  If you wrote your own `faidx` equivalent I expect it would be possible to do this quite efficiently.

**Comment by jkbonfield** [comment]
The overhead of removing all the newlines from the fasta during reading is only likely to have an impact on very shallow data meaning a lot of reference is read for not much coverage of sequence.  Furthermore because it can't do direct mmap IO on the fasta file as it doesn't have a one to one mapping with file offsets.

Your best bet would be simply to benchmark it as the impact will differ depending on your file systems and machine CPU / IO.

Locally I see:

```
$ time samtools view -c /var/tmp/novaseq-10m.30.cram
10000000

real	0m13.251s
user	0m11.770s
sys	0m1.477s


$ time REF_PATH= samtools view -T $HREF38 -c /var/tmp/novaseq-10m.30.cram
10000000

real	0m13.439s
user	0m11.841s
sys	0m1.592s
```

These are the second runs, so both MD5 files and $HREF fasta were in disk cache.  Essentially it's identical timing.

I'd guess the main difference of mmaping the MD5 files vs reading the .fa files is if you have a lot of processes running simultaneously then the mmap will be sharing the same memory.

**Comment by anderspitman** [comment]
These are very helpful responses, and I believe cover everything I need to move forward. Thank you!
