### ISSUE TITLE
-r, --region REG        region in which pileup is generated      the region  can‘t more than 536M

### ISSUE THREAD

**Issue by jinyue10086** [samtools/samtools#1349]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
"""
samtools 1.3.1
Using htslib 1.3.1
Copyright (C) 2016 Genome Research Ltd.
"""
 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
"""Linux 2.6.32-504.16.2.el6.x86_64"""
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
"""x86_64"""
- compiler (run `gcc --version` or `clang --version`)
"""
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
"""
#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
cmd:
samtools mpileup -q 1 -C 50 -t SP -t DP -m 2 -F 0.002  -u -r CM007923.2:500000001-788782410 -f genomic.fa  a1.sorted.bam | bcftools call -m -f GQ  > outfile.vcf 
issue:
![image](https://user-images.githubusercontent.com/56353055/101463652-ab6f7800-3978-11eb-9282-3c603761a86a.png)
the capture come from last line of outfile.vcf 。I have a issue the last line is 536861751 of CM007923.2 , but  the "-r CM007923.2:500000001-788782410"  I given。
test：
samtools mpileup -q 1 -C 50 -t SP -t DP -m 2 -F 0.002  -u -r CM007923.2 -f genomic.fa  a1.sorted.bam | bcftools call -m -f GQ  > outfile.vcf
![image](https://user-images.githubusercontent.com/56353055/101464865-2edd9900-397a-11eb-907c-681ce6339df8.png)
this‘s  recover while  I give “-r CM007923.2”

**Comment by valeriuo** [comment]
**1.3.1** is quite an old version (more than 4 years ago) and, since then, the tools have been upgraded significantly, especially in the region filtering department.
Could you try updating to the latest [releases](http://www.htslib.org/download/) and see if this behaviour is still present?
Some of the `samtools mpileup` options that you are using have been deprecated (although still working), as the functionality has been passed over to `bcftools mpileup`, the manual for which can be found [here](https://samtools.github.io/bcftools/bcftools.html#mpileup).

**Comment by daviesrob** [comment]
As well as using newer versions of samtools and bcftools, you should also make sure you create a `.csi` index instead of `.bai`.  To do this, you need to use `samtools index -c genomic.fa a1.sorted.bam`.

The older `.bai` index format does not work for references longer than about 512Mbases.  The newer `.csi` format does not have this limitation.

**Comment by jinyue10086** [comment]
> As well as using newer versions of samtools and bcftools, you should also make sure you create a `.csi` index instead of `.bai`. To do this, you need to use `samtools index -c genomic.fa a1.sorted.bam`.
> 
> The older `.bai` index format does not work for references longer than about 512Mbases. The newer `.csi` format does not have this limitation.

**Comment by jinyue10086** [comment]
It's work.  Thank you every much!

**Comment by valeriuo** [comment]
> It's work. Thank you every much!

Any reason for reopening, then?
