### ISSUE TITLE
A clarification about calculating percent reads mapping to reference genomes + dealing with singletons

### ISSUE THREAD

**Issue by smb20200615** [samtools/samtools#1352]
Hello,

This may be a super easy question to you but I found conflicting solutions online. I am interested in finding the percent reads mapping to a set of genomes (% classified) in metagenomic reads. The input is a multifasta file of the reference genomes which have been concatenated to produce this multifasta file. Next what I used is:

bwa index [multifastafile]

bwa mem [multifastafile] [fwd_read] [reverse_read] | samtools view -bS - | samtools sort -@ {threads} -o [outputsortedaligned] - 
samtools index [outputsortedaligned]
samtools flagstat [outputsortedaligned] > [flagstatoutput]

My understanding is that the total reads mapping to multifasta genomes is total mapped - secondary - supplementary from the flagstat output. Then I divide by the total read count. Is this correct? Also, is it ok that I don't include the singletons?

Many thanks for your time and guidance.

**Comment by daviesrob** [comment]
Yes, `mapped - secondary - supplementary` will give you the number of primary alignments, then divide by the total number of forward and reverse reads to get the %age mapped.  Note that this counts the reads as individuals rather than pairs.

The singletons count is the number of paired reads which map themselves but have an unmapped mate.  You don't need to do anything with them.

With an up-to-date samtools, you can simplify your pipeline a bit as `samtools sort` understands sam files and can also now create an index as it writes the output file.  This should make the whole thing run a bit faster:

```
bwa index [multifastafile]

bwa mem [multifastafile] [fwd_read] [reverse_read] | samtools sort -@ {threads} --write-index -o [outputsortedaligned] -
samtools flagstat [outputsortedaligned] > [flagstatoutput]
```

**Comment by smb20200615** [comment]
Thank you so so much for your guidance on this!!
