### ISSUE TITLE
Build without libcrypto

### ISSUE THREAD

**Issue by anderspitman** [samtools/samtools#1362]
Hi, the documentation indicates that libcrypto is optional and only needed for S3 files, but doesn't show a way to disable building against it (such as --without-ncurses). What's the best way to do this?

**Comment by anderspitman** [comment]
I just tried uninstalling openssl-devel from the system before building, and that seemed to work. Is this the only way, or is there a configuration option?

**Comment by jkbonfield** [comment]
Have you tried `--disable-s3`?  I think by removing the dependency it may also remove the automatic linking against the library.

**Comment by jmarshall** [comment]
There's no ‘may’ about it :smile: but note that libcurl also uses an SSL library itself which might be configured on your system to be openssl. This won't require openssl-devel or other -devel packages, but note that the resulting executables would still have a dependency on libcrypto via libcurl, so depending on what you are trying to achieve you might also need `--disable-libcurl`.

Alternatively, again depending on what you are trying to achieve, you can use `--enable-plugins --disable-libcurl` to decouple the main executables and building them from needing openssl etc, while still having the functionality available if you were to compile the plugins alone separately.

That _openssl-devel_ package name suggests you are on a RedHat-based distribution, in which case your libcurl is probably configured to use NSS as its SSL backend. Is it that you want to avoid libcrypto because everything else is linked to libnss3.so/libnspr4.so/etc? After IIRC a suggestion from @dkj, a few years back I was working on adding configuration options to build _hfile_s3.c_ with any of openssl(ie libcrypto)/gnutls/nss, but there wasn't a lot of need at the time so it didn't get finished up.

**Comment by anderspitman** [comment]
Thanks for the responses. The immediate problem I'm trying to solve is building a reasonably portable executable of samtools which can be copied between Linux machines from the past few years.

I started by trying to build on Ubuntu 18.04, but the file links against libbz2.so.1.0, and CentOS systems (at least version 7) have libbz2.so.1, so it doesn't link properly at runtime. See [here][0].

Then I moved to building on CentOS 7. The resulting executable wouldn't run on Arch or Ubuntu 18.04 because of linking against libcrypto, which brought me to opening this issue.

I know it's possible to build a portable samtools because it [runs in WebAssembly][1], but it's been pretty difficult so far. It would be nice if there was a way to statically link against at least some of the dependencies. It links against a lot of stuff by default...

[0]: https://stackoverflow.com/questions/1835489/linking-an-application-to-libbz2-so-1-rather-than-libbz2-so-1-0/1841600

[1]: https://github.com/biowasm/biowasm

**Comment by jkbonfield** [comment]
@daviesrob has a portable binary building system somewhere.  Maybe he can advise as I know there were several pitfalls to contend with.

**Comment by anderspitman** [comment]
It doesn't have to be perfectly portable (though a purely static build would be amazing), just reasonably. I think only a few of the dependencies are problematic.

We (iobio) have been just wrapping samtools in a singularity container to get around these problems, but the added complexity and performance hit are annoying. If I run into problems with avoiding libcrypto, I might try [exodus](https://github.com/intoli/exodus) next.

Overall, what approach of the ones you listed do you think is the safest way to avoid libcrypto? I want to keep as close as possible to vanilla samtools, so I don't want to do anything funky like disabling libcurl.

**Comment by anderspitman** [comment]
Also is the plugins stuff you mention covered anywhere in the docs? I didn't see an option for --disable-s3 nor anything about plugins.

**Comment by daviesrob** [comment]
`--enable-plugins` and `--disable-s3` are HTSlib configure options.  If you build samtools with an embedded copy of HTSlib, the options will be passed through when you run `./configure` in your samtools directory.  Unfortunately due to autoconf-related reasons, the samtools configure help doesn't show these options, but you can see them if you run `./configure --help` in the htslib directory.

If you build using `--enable-plugins` HTSlib will put the code used to access remote files (https:, S3: etc) will be put into separate `.so` files which can be loaded on demand.  This massively reduces the number of dependencies for the main samtools binary, making it easier to build a portable version of that part.  The disadvantage is that you have to tell HTSlib where to look for the plugins - this can be set at compile time, but only if you know where the package will be installed.  Alternatively you can use an environment variable (`HTS_PATH`), but you'll need some way of setting it up for the user.  If you go down this route, samtools will work for local files even if there is no compatible libcurl (but remote files will not load unless you do).

If you do want a portable binary, you'll have to accept a few compromises and it's likely to be slower as it has to be built for a lowest common denominator platform.  You would need to use the oldest glibc you want to support.  Thanks to symbol versioning, the resulting binaries should work fine with a newer glibc.  The compression libraries (zlib, libdeflate, xz and bz2) are fairly easy to deal with - you can build them yourself to make static libraries (you may need  to enable `-fPIC` in `CFLAGS` to get them to play nicely with shared libraries) and then set `CFLAGS` and `LDFLAGS` when configuring samtools/htslib to pick up your copies (make sure you don't build shared libraries for them to ensure it only picks up the static ones).  You can actually get away with doing this for libcrypto as well, as HTSlib only uses a small part of the library, however building it is somewhat painful.

Alternatively to all that, you could gather up the shared libraries for the dependencies, and ship them with a copy of samtools built with a relative `RPATH` so that it can find them (e.g. configure with `LDFLAGS='-Wl,-R${ORIGIN}/lib'` and include them in a `lib` directory next to your `samtools` binary.  With a bit of luck it will find and use them in preference to anything else on the system.

The biggest problem with this is making a portable copy of `libcurl`.  Basically it isn't possible to get something that will work everywhere - even if you build your own copy plus its dependencies, and ship it with your copy of samtools (maybe using the RPATH trick above), you'll find it may not be able to find the certificate files it needs to validate TLS connections as there isn't a standard location to find them.  So a libcurl built for Debian probably won't work for RedHat, and vice versa.  Unfortunately it doesn't appear to support searching for them on a path, so you either have to support one or the other, or come up with a fairly major hack to set where they are at run time.  (You could also ship the certificates yourself, but they'll slowly go out of date and stop working as they expire).  The best solution for `libcurl` may be to go down the `--enable-plugins` route, linking to a recent `libcurl` shared library.  Anyone with a new enough copy will be able to use it, and if one isn't available the copy of `samtools` will work, albeit only on local files.

**Comment by anderspitman** [comment]
I believe you've provided all the information I need. Thank you!
