### ISSUE TITLE
mpileup report low coverage after deletion

### ISSUE THREAD

**Issue by chienchi** [samtools/samtools#1375]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
samtools v1.10 (using htslib 1.10)

 #### Please describe your environment.
- OS :Linux 3.10.0-862.2.3.el7.x86_64
- machine architecture :x86_64
- compiler: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
- 
#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

```samtools mpileup -a -f reference.fasta -q 60 -Q 20 -d 8000 -A  NC_045512.sort.bam```

Sorry, this is an old topic.  [#73](https://github.com/samtools/samtools/issues/73)

But we do notice it not always report low coverage after deletion in the same mapping result.  Below is an example (cut in short) that pos 11288 has correct asterisks and depth, but pos 21765 doesn't have asterisks and incorrect depth. In the ticket #73 suggestted to disable BAQ (-B).  To my understanding, turn on the BAQ will improve SNP discovery.  Is there any recommendation that we can use BAQ and also track the Deletion properly in the mpileup?

Thank you.

```
NC_045512     11287   G       886     .-9TCTGGT
TTT.-9TCTGGTTTT.-9TCTGGTTTT.-9TCTGGTTTT.-9TCTGGTTTT.-9TCTGGTTTT,.......
NC_045512     11288   T       2933    **************************************************************************************************************************

NC_045512     21764   A       236     ,-6tacatg,-6tacatg,-6tacatg,-6tacatg,-6tacatg,-6tacatg,,-6tacatg,-6tacatg,-6tacatg,-6tacatg,-6tacatg
,-6tacatg,-6tacatg,,-6tacatg,-6tacatg,-6tacatg,,,,-6tacatg,-6tacatg,-6tacatg,-6tacatg,,-6tacatg,-6tacatg,-6tacatg,,-6tacatg,,-6tacatg,,
NC_045512     21765   T       21      ,$,$,$,$,$,$,$,$,$,$,$,$,$,$,$,$,$.$.$,$.$      EcEiigEeggEEiEeiiEeEg
NC_045512     21766   A       0       *       *
```

**Comment by jkbonfield** [comment]
Is the data genuinely low depth after the deletion, eg if viewed in `samtools tview`?  If so there's nothing we'll be able to do obviously.

What about using "-Q 0" to show all data irrespective of depth?  If you then see it, then it's likely the BAQ algorithm as you say that's dropped the quality down essentially removing it.  BAQ does improve SNP discovery, especially on low depth data, but some anecdotal evidence shows it can harm SNP discovery in high depth regions and is not beneficial (actually slightly detrimental) to indel calling at multiple depths.  Basically BAQ does a good job of removing false positives, but it does so with a small cost in raising false negatives.

If -Q0 doesn't rescue the data and it's definitely there in the input then this looks to be more likely an artifact of the depth limit code, although I see you're using `-d 8000` so that would be surprising.  (In this case, try `-d 0` (unlimited) too.)

Anyway my expectation is that this is BAQ related.  It's fundamental to the way BAQ works that it zeros the quality of data it considers to have unreliable alignments.

PS.  You're talking about SNP discovery but this is `samtools mpileup`.  Are you piping the output of this into something else?  We'd normally recommend using `bcftools mpileup / call` instead and using VCF.

**Comment by chienchi** [comment]
Thank you. 

"-Q 0"  works to rescue the data.  

We have a script parsing the `samtools mpileup` result and check the variants. 

We will check out `bcftools mpileup/call`.

**Comment by jkbonfield** [comment]
Ok if `-Q 0` rescues it then it's probably quite likely that -B will too as BAQ is zero quality values almost certainly came from BAQ.
