### ISSUE TITLE
Overestimation of number of reads for nanopore data in flagstat

### ISSUE THREAD

**Issue by rebeelouise** [samtools/samtools#1382]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
samtools 1.10
Using htslib 1.10.2

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)  Linux 5.4.0-59-generic
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows) x86_64
- compiler (run `gcc --version` or `clang --version`)
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

Same issue as mentioned on the minimap2 tool: lh3/minimap2#236 (comment)

For example nanopore reads aligned to the host transcriptome the flagstat output is:

5953480 + 0 in total (QC-passed reads + QC-failed reads)
2961480 + 0 secondary
22696 + 0 supplementary
0 + 0 duplicates
4195469 + 0 mapped (70.47% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

However, the number of actual reads is: 2969304 - the read length of these are about 750nt. I am assuming this over reporting is due to the presence of long reads, is there a more appropriate way of calculating the number of reads and the % of reads mapped in an alignment file? Can the % of reads mapped still be a trusted value?

**Comment by daviesrob** [comment]
`flagstat` counts alignment records rather than reads, which is why the numbers seem to be bigger than you expect.  The now somewhat misleading "QC-passed reads + QC-failed reads" text is a historic artefact, as secondary and supplementary alignment records didn't exist when it was added.  To get the number of reads, you need to subtract the `secondary` and `supplementary` numbers from `total`:

```
5953480 - 2961480 - 22696 = 2969304
```

For the `mapped` reads, `flagstat` just counts the number of alignment records where the [`BAM_FUNMAP` flag bit is zero](https://github.com/samtools/samtools/blob/66593089/bam_stat.c#L68), so it will also include secondary and supplementary records if the aligner marks them as mapped.  Assuming `minimap2` does this for all secondary and supplementary alignments (which is reasonable as an unmapped one wouldn't really make sense) then you should be able to get the count of mapped reads by subtracting the `secondary` and `supplementary` numbers from `mapped`:

```
4195469 - 2961480 - 22696 = 1211293
```

So if I got this right, about 40.8% of them were mapped, and judging by the number of secondary alignment records, quite a lot of them were in multiple segments.

Possibly we should get `flagstat` to print extra rows for "primary" alignments, as this is often a source of confusion...

**Comment by valeriuo** [comment]
The total figure contains the actual reads plus supplementary and secondary reads.
Thus, `5953480 - 2961480 - 22696 = 2969304`

**Comment by rebeelouise** [comment]
> `flagstat` counts alignment records rather than reads, which is why the numbers seem to be bigger than you expect. The now somewhat misleading "QC-passed reads + QC-failed reads" text is a historic artefact, as secondary and supplementary alignment records didn't exist when it was added. To get the number of reads, you need to subtract the `secondary` and `supplementary` numbers from `total`:
> 
> ```
> 5953480 - 2961480 - 22696 = 2969304
> ```
> 
> For the `mapped` reads, `flagstat` just counts the number of alignment records where the [`BAM_FUNMAP` flag bit is zero](https://github.com/samtools/samtools/blob/66593089/bam_stat.c#L68), so it will also include secondary and supplementary records if the aligner marks them as mapped. Assuming `minimap2` does this for all secondary and supplementary alignments (which is reasonable as an unmapped one wouldn't really make sense) then you should be able to get the count of mapped reads by subtracting the `secondary` and `supplementary` numbers from `mapped`:
> 
> ```
> 4195469 - 2961480 - 22696 = 1211293
> ```
> 
> So if I got this right, about 40.8% of them were mapped, and judging by the number of secondary alignment records, quite a lot of them were in multiple segments.
> 
> Possibly we should get `flagstat` to print extra rows for "primary" alignments, as this is often a source of confusion...

That was a really valuable explanation! Thank you. 

I think maybe the latter would be useful!
