### ISSUE TITLE
samtools mpileup (deletions not called)

### ISSUE THREAD

**Issue by AroobAlhumaidy** [samtools/samtools#1385]
Hello, 
I am using this command:
$ samtools mpileup -uf references.fasta  sample1.sorted.bam | bcftools call --ploidy 1 -mv -Oz >  sample1.vcf.gz

sample1: when viewing the bam file in IGV it showed 2 deletions in 2 different sites. but when calling the variants these deletion dose not appear. any insights? 

Thanks

**Comment by valeriuo** [comment]
You are running two programs here (`samtools` and `bcftools`) and it would be better to isolate the issue.
First of all, what versions of each program are you using? Run `samtools --version` and `bcftools --version`, as instructed in the issue template.
Second, try running only `samtools mpileup -f references.fasta sample1.sorted.bam` and check the mpileup output. Do you see the deletions there (look for the `*` symbol in the 5th column)? 
If you still don't see them, you might be hitting the depth limit (default value **8000**) or the indel limit (default value **250**), which you can increase with `-d` and `-L` options. I.e.
`samtools mpileup -f references.fasta -d 500000 -L 1000 sample1.sorted.bam`

**Comment by jkbonfield** [comment]
It's probably another BAQ related issue too.

You'd be best using `bcftools mpileup` instead of the deprecated `samtools mpileup -u`, and try with/without the `-B` parameter to turn off BAQ.  Note it's not necessarily good to consider what's best on just one call though!  BAQ considerably reduces the false positive rate for many data sets, but this is at the expense of slightly higher false negative rates (sometimes ones that look really obvious).

**Comment by jkbonfield** [comment]
Closing this as no response and we think it is answered.
