### ISSUE TITLE
samtools sort 

### ISSUE THREAD

**Issue by lubocoix** [samtools/samtools#1391]
samtools-1.11 samtools sort -@ 4 -m 4G -O bam -o /Users/lubo/sorgum/propinquum.sorted.bam /Users/lubo/sorgum/propinquum.bam 
[bam_sort_core] merging from 0 files and 4 in-memory blocks...

I don't know what's wrong with my code. I used bwa to generate propinquum.bam,I want to sort by samtools.

**Comment by valeriuo** [comment]
It's not very clear what the problem is. That message has only informative value.

Do you obtain the file **propinquum.sorted.bam** ?
What size does it have, comparing to the original **propinquum.bam**?
Can you run `samtools view -c propinquum.sorted.bam` successfully?
Do you get the same value as with `samtools view -c propinquum.bam`?

**Comment by lubocoix** [comment]
> Do you get the same value as with `samtools view -c propinquum.bam`?

**Comment by lubocoix** [comment]
> It's not very clear what the problem is. That message has only informative value.
> 
> Do you obtain the file **propinquum.sorted.bam** ?
> What size does it have, comparing to the original **propinquum.bam**?
> Can you run `samtools view -c propinquum.sorted.bam` successfully?
> Do you get the same value as with `samtools view -c propinquum.bam`?

The  original propinquum.bam is about 13G.I work it with my MAC and samtools-1.11. I can obtain the file propinquum.sorted.bam ,but it just 200k ,absolutely something is wrong with my code. I have try this several times.

**Comment by valeriuo** [comment]
Can you try running the same command with a lower memory setting, `-m 1G` instead of `-m 4G`?

**Comment by lubocoix** [comment]
problem solved ，thanks
