### ISSUE TITLE
samtools ampliconstats - support for multi reference sequence genomes

### ISSUE THREAD

**Issue by ces** [samtools/samtools#1396]
samtools ampliconstats doesn't support multi reference sequence/contig genomes (known issue) but it would be really nice if could or if the lack of support was clearly documented and handled cleanly by the code (e.g. didn't seg fault).

[sanger only example data at /lustre/scratch117/sciops/team117/npg/ces/data/ampliconstats_multiseq/ ]

**Comment by jkbonfield** [comment]
What does it mean to have multiple references for amplicon sequencing?  Our bed format doesn't have a contig name, so what do we want to do?

Do we need a new format with a ref+pos instead of just pos?  This isn't something I can change as it's not my format.

If not, do we want to have one bed file per reference and run the command multiple times specifying the appropriate bed and the chromosome we want to process in the BAM/CRAM?

**Comment by jkbonfield** [comment]
My initial thought here was that the ampliconstats output would add an additional column per reference, eg instead of:

```
# AMPLICON	NUMBER	LEFT	RIGHT
AMPLICON	1	11-35,21-40	301-330
AMPLICON	2	261-275	441-460
AMPLICON	3	401-420	851-880,856-882
..
FREADS	file1	6	0	4
FREADS	file2	6	0	4
```

I'd have:

```
# AMPLICON	REF	NUMBER	LEFT	RIGHT
AMPLICON	r1	1	31-54	386-410
AMPLICON	r1	2	321-342	705-726
AMPLICON	r2	1	11-35,21-40	301-330
AMPLICON	r2	2	261-275	441-460
AMPLICON	r2	3	401-420	851-880,856-882
...
FREADS	file1	r1	5	1
FREADS	file1	r2	6	0	4
FREADS	file2	r1	5	1
FREADS	file2	r2	6	0	4
```

(And so on for all the types of data output.)

It occurs to me that maybe I'd want a single amplicon numbering across all refs.  Eg:

```
# AMPLICON	REF	NUMBER	LEFT	RIGHT
AMPLICON	r1	1	31-54	386-410
AMPLICON	r1	2	321-342	705-726
AMPLICON	r2	3	11-35,21-40	301-330
AMPLICON	r2	4	261-275	441-460
AMPLICON	r2	5	401-420	851-880,856-882
...
FREADS	file1	5	1	6	0	4
FREADS	file2	5	1	6	0	4
```

This is more succint, and the example given above (@ces) has 1 amplicon per reference for 68 refs.  However it'd still need the more expanded output format for some statistics, eg all the `SS`, `FSS` and `CSS` stats.  It would however make some of the combined stats such as FAMP for amplicon 0 (meaning all amplicons) count as all amplicons across all references.  Is that desireable?

**Comment by jkbonfield** [comment]
It's also unclear how the template coordinate plot should look.  Right now we have something like this:

![image](https://user-images.githubusercontent.com/2210525/114702131-90908400-9d1b-11eb-8786-9aecb012a44f.png)

It shows alternating green / blue for even / odd amplicons, with red for ones that hop primers (eg 17th LEFT to 19 RIGHT) and black for reads that don't match a recognised location correctly.  The Y axis is frequency, so here we see the vast bulk of data has been assigned well, but some amplicons (66, 74) with low counts.

If we have a couple refs with many amplicons each, then this plot could work (one plot per ref), but for the test data above with very few (ie 1!) amplicon per reference then clearly this plot is irrelevant.  I may consider simply omitting this data from the plots for multi-ref mode until I get a request / use case.

**Comment by jkbonfield** [comment]
Andrew's now done this for ampliconclip, merged as https://github.com/samtools/samtools/pull/1410.

I now have an implementation of this for ampliconstats, taking the strategy of a continuous numbering of amplicons from 1 to N across all references.  This produces plots like this, where each amplicon in your example data comes from a separate reference:

![image](https://user-images.githubusercontent.com/2210525/115040825-c07d8a00-9ec9-11eb-9945-95b719c740d7.png)

More images available locally at Sanger in ~jkb/lustre/ampliconstats/multi/*png

**Comment by jkbonfield** [comment]
@ces We've now merged both ampliconclip and ampliconstats PRs for supporting multi-ref bed files and BAM files.  We'll probably close this issue next week if we don't hear of further requirements.  Thanks for the suggestions.
