### ISSUE TITLE
a typical case which two pair of reads wrongly marked as duplication

### ISSUE THREAD

**Issue by wulj2** [samtools/samtools#1403]
I personally manually created an edge case which will lead to false duplication be marked

please see the test data
[test.data.gz](https://github.com/samtools/samtools/files/6217134/test.data.gz)

in the test data: input.bam is what i feet to samtools markdup
and mkdup.samtools.bam is the output
my command is `samtools markdup sort.bam mkdup.bam` as you can see in the BAM header

I know the bug lies in that samtools markdup only use the coordinates information, what's more, in the default mode, clipped bases will be taken into account to calculate the beg/end range position used for hash and duplication markdup.
I think the cigar content should also be taken into account? any advice on this?

I test the latest picard tools, it will generate the same results as well.

my samtools version information is listed below
```
samtools 1.12
Using htslib 1.12
Copyright (C) 2021 Genome Research Ltd.

Samtools compilation details:
    Features:       build=Makefile curses=yes
    CC:             gcc
    CPPFLAGS:
    CFLAGS:         -g -Wall -O2
    LDFLAGS:
    HTSDIR:         htslib-1.12
    LIBS:
    CURSES_LIB:     -lcurses

HTSlib compilation details:
    Features:       build=Makefile plugins=no libcurl=yes S3=no GCS=no libdeflate=no lzma=yes bzip2=yes htscodecs=1.0
    CC:             gcc
    CPPFLAGS:
    CFLAGS:         -g -Wall -O2 -fvisibility=hidden
    LDFLAGS:        -fvisibility=hidden

HTSlib URL scheme handlers present:
    built-in:	 preload, data, file
    libcurl:	 imaps, ftp, ldap, pop3, http, https, ldaps, gopher, smb, tftp, ftps, pop3s, imap, dict, smtp, smbs, smtps, telnet, rtsp
    crypt4gh-needed:	 crypt4gh
    mem:	 mem
```

**Comment by wulj2** [comment]
update!!!
```samtools markdup -m s``` will also mark the same duplication results

**Comment by wulj2** [comment]
maybe we can add another two field into 
```
typedef struct {
      hts_pos_t this_coord;
      hts_pos_t other_coord;
      int32_t this_ref;
      int32_t other_ref;
      int8_t single;
      int8_t leftmost;
      int8_t orientation;
  } key_data_t;
```
such as ```hts_pos_t pos``` and ```hts_pos_t  end``` to remember the alignment start pos ```b->core.pos``` and ```ban_endpos(b)```

then in the hash key check function
```
static int key_equal(key_data_t a, key_data_t b) {
      int match = 1;

      if (a.this_coord != b.this_coord)
          match = 0;
      else if (a.orientation != b.orientation)
          match = 0;
      else if (a.this_ref != b.this_ref)
          match = 0;
      else if (a.single != b.single)
          match = 0;

      if (!a.single) {
          if (a.other_coord != b.other_coord)
              match = 0;
          else if (a.leftmost != b.leftmost)
              match = 0;
          else if (a.other_ref != b.other_ref)
              match = 0;
      }

      return match;
  }
```
we check these two fields to make sure that ```pos``` and ```end``` equality are needed to be equal keys?
in the time, I did not think many disadvantages this will bring to the results, but I think they will make many previous duplicates identified not duplications anymore, and I do not know if these changes I thought about make sense or not?
any advice on this ?

**Comment by whitwham** [comment]
Well you are not wrong, all the duplicate marking software I know about run on approximations. So samtools markdup, Picard, Biobambam and others I have looked at will all mark as duplicates reads that are really not.  This is mainly done for speed, doing all the checks to make sure everything is exactly right would be prohibitively slow.

The reason we use the unclipped values it that we are trying to match a physical piece of DNA.  The alignment values might vary a little due to sequencing,  base calling, or aligner errors.  So we try to use the physical start only in order to minimise the wrong alignments.

We do not try and match cigar strings or the sequence itself for the same reasons.  We would have to build in error handling to determine the number of miss calls we would allow and still be marked as duplicates.  That would all be complex and slow.

You could try your proposed changes on real data.  See which duplicates it missing and which it marks correctly.  It would be interesting to see what effect it would have.

**Comment by wulj2** [comment]
thanks for your advice, I will have a try @whitwham
