### ISSUE TITLE
Samttols seemingly unable to detect an HTSlib element

### ISSUE THREAD

**Issue by Pawek-13** [samtools/samtools#1429]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)?
Yes.

 #### Please describe your environment.
- OS - Linux 4.12.14-197.56-default
- machine architecture - x86_64
- compiler - gcc (SUSE Linux) 7.5.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I am trying to instll samtools onto my personal folder on an HPC. Before that, I have downloaded the latest release of HTSlib. During the installation process for `samtools`, in the `./configure` step, I have specified the location of the HTS library and moved forward without any hiccups. However, when I try using one of the programs in the `samtools` package, I get such an error message:

`samtools: error while loading shared libraries: libhts.so.3: cannot open shared object file: No such file or directory`

This makes no sense, as I have spacified the location of the HTSlib subdirectory and when I do not specify it, the `./configure` step cannot proceed. Could someone help me out with this issue? Thanks in advance.

**Comment by daviesrob** [comment]
You need to tell the operating system where to find the HTSlib library when you run samtools.  On Linux you can do this by setting the `LD_LIBRARY_PATH` environment variable.  So if you built **HTSlib** like this:

```sh
./configure --prefix=$HOME/opt/htslib
make
make install
```
so that it's installed under `$HOME/opt/htslib`, you would need to use something like this:

```sh
export LD_LIBRARY_PATH=$HOME/opt/htslib/lib:$LD_LIBRARY_PATH
```

(Note that if you configured samtools to use the HTSlib source tree instead of an installed copy, you should use `$HOME/opt/htslib` instead of `$HOME/opt/htslib/lib`.)

Alternatively, when building **samtools**, you can bake this path into the samtools binary like this (again, miss out the `/lib` if `--with-htslib` points to the HTSlib source tree):
```sh
./configure --with-htslib=$HOME/opt/htslib LDFLAGS="-Wl,-R$HOME/opt/htslib/lib"
make
```

Your copy of samtools should then be able to find `libhts.so.3` without having to set `LD_LIBRARY_PATH`.

**Comment by Pawek-13** [comment]
Thank you so much for your quick response! My final issue with `samtools` installation has at last been resolved and I can merrily proceed with my analysis.
