### ISSUE TITLE
unable to parse the ':' in sam file while conversion from sam to bam

### ISSUE THREAD

**Issue by kishore556** [samtools/samtools#1430]
#### Is your feature request related to a problem? Please specify.
I mapped the illumina reads to contigs_assembly suing  bwa-mem with -C option to copy the BX tag in header file to alignment in sam format. Now trying to convert that sam format to bam using samtools but got this error as detailed bellow. 

acer@kishor:~/talasmbly/3r5fly3103$ samtools fixmate -O bam 5aptrim_aln1.sam.gz 5aptrim_aln1.bam.gz
[E::sam_parse1] unrecognized type ':'
[W::sam_read1_sam] Parse error at line 16
samtools fixmate: Couldn't read from input file

I am creating the input bam file for ARCS scaffolding program. I need to convert sam files to bam and then sort it.

**Comment by jkbonfield** [comment]
Unfortunately I don't know what Illumina mean by "Sanger/Illumina 1.9",  but I assume it refers to the original Fastq variant invented at Sanger rather than their rather non-standard (and fortunately short lived) fastq look-alike.

However as I say, Samtools gave you a line number in your file that it didn't like.  Take a look at it and if you're unsure post that line here.

**Comment by valeriuo** [comment]
The input SAM file is malformed. It appears one of the auxiliary tags at line 16 (including the header lines) is missing the type information (a single character). You should see two consecutive colon signs (::) after a tag key. It is only a samtools issue if this file was generated by a samtools command. Otherwise, you need to check the `@PG` lines and see which program in the pipeline might have added that incorrect formatted tag.
