### ISSUE TITLE
samtools hangs when using a named pipe

### ISSUE THREAD

**Issue by lczech** [samtools/samtools#1437]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
Yes, samtools 1.12

 #### Please describe your environment.
Ubuntu 20.04.2 LTS
Linux 5.8.0-53-generic, x86_64
samtools installed via conda

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
Using these [example](https://github.com/samtools/samtools/files/6550353/example.zip) files (please unzip first).

I can run:

```
samtools merge intermediary *.sorted.bam
samtools mpileup intermediary | gzip > all.mpileup.gz
```

but when trying to use a [named pipe](https://en.wikipedia.org/wiki/Named_pipe), the second command just hangs and does nothing:

```
mkfifo intermediary
samtools merge intermediary *.sorted.bam &
samtools mpileup intermediary | gzip > all.mpileup.gz
# rm intermediary
```

I have also [reported this to Snakemake](https://github.com/snakemake/snakemake/issues/1018), where this issue first came up when trying to bind different samtool steps without having to write out all intermediate files.

**Comment by jkbonfield** [comment]
It appears to be the `merge` which is hanging.  Even with a `cat intermediary > /dev/null` the merge doesn't complete.

It wedges in the `fopen` call:

```
Breakpoint 1, bam_merge (argc=6, argv=0x7fffffffd700) at bam_sort.c:1501
1501	        FILE *fp = fopen(argv[optind], "rb");
```

That line never completes.  It's because it's opening in for read, which is probably wrong.  It's only opening it in order to check whether the file exists, so I'm not sure that's going to work with a fifo.

However you can use `samtools merge -f` to override that, which works.

**Comment by jkbonfield** [comment]
I can confirm, replacing the `fopen` with `access` cures it.  We already use `access` in `samfaipath`, although that appears to be a totally unused and presumably deprecated function.  Sam.c does build at least, even on Windows, so this change shouldn't harm portability.

```
diff --git a/bam_sort.c b/bam_sort.c
index 6913c64..7bc5071 100644
--- a/bam_sort.c
+++ b/bam_sort.c
@@ -1498,9 +1498,7 @@ int bam_merge(int argc, char *argv[])
 
     hts_srand48(random_seed);
     if (!(flag & MERGE_FORCE) && strcmp(argv[optind], "-")) {
-        FILE *fp = fopen(argv[optind], "rb");
-        if (fp != NULL) {
-            fclose(fp);
+        if (access(argv[optind], F_OK) == 0) {
             fprintf(stderr, "[%s] File '%s' exists. Please apply '-f' to overwrite. Abort.\n", __func__, argv[optind]);
             ret = 1;
             goto end;
```

However it doesn't particularly help this issue, other than giving a clue to the user rather than wedging.  With the change we're now informed of the correct workaround.

```
@ [tmp/jkb]; samtools merge intermediary *.sorted.bam
[bam_merge] File 'intermediary' exists. Please apply '-f' to overwrite. Abort.
```

**Comment by lczech** [comment]
Thank you, that was an impressively quick response and fix time! Can confirm that it works when using `samtools merge -f`.

**Comment by jkbonfield** [comment]
It was a conveniently easy distraction. :-)

Thanks for the clear bug report.
