### ISSUE TITLE
How RNA editing on the genomic forward/reverse (reference) strand is represented?

### ISSUE THREAD

**Issue by twang15** [samtools/samtools#1444]
We are using samtools in our RNA editing research, but are confused by the following question.
Eager to know the answer, please help us!

        **How RNA editing on the genomic forward/reverse (reference) strand is represented by samtools?**

Here is our understanding:

        If the gene is on the forward genomic strand, we can get reads from both strands of cDNA.
        In the cDNA, the nucleotide for editing would be G for the second-strand cDNA, and C for the first strand cDNA.
        Samtools reports these as G and g.
    
        If the gene is on the reverse genomic strand, we can still get reads from both strands of cDNA.
        In the cDNA, the nucleotide for editing would be G for the second-strand cDNA, and C for the first strand cDNA.
        Samtools reports these as C and c.

**Comment by valeriuo** [comment]
> Samtools reports these as G and g.

Presumably, you are referring to the [mpielup](http://www.htslib.org/doc/samtools-mpileup.html) output. A single letter indicates a mismatch with the reference genome at that position. An upper-case letter indicates that the alignment from which the base came was mapped to the forward strand, while a lower-case letter indicates a reverse strand mapping.

The [standard](https://github.com/samtools/hts-specs/blob/master/SAMv1.pdf) also states:

> All mapped segments in alignment lines are represented on the forward genomic strand. For segments
> that have been mapped to the reverse strand, the recorded SEQ is reverse complemented from the original
> unmapped sequence and CIGAR, QUAL, and strand-sensitive optional fields are reversed and thus recorded
> consistently with the sequence bases as represented.

**Comment by daviesrob** [comment]
I think this may depend on exactly how your RNA sequencing works.  As @valeriuo states, the case in mpileup output will tell you which strand each base was mapped to.  If you're using paired reads you may also need to use the `--output-extra FLAG` option so that you can work out if the base was on `READ1` or `READ2`.  If your RNA sequencing preserves strandness, you should be able to use the two to work out which strand the base originally came from; if not then I'm afraid it won't be possible even with this information.
