### ISSUE TITLE
[E::sam_hrecs_error]

### ISSUE THREAD

**Issue by hchetia** [samtools/samtools#1458]

**Comment by hchetia** [comment]
I have merged the four multilane novaseq fastqs (L1_R1.fq, L1_R2.fq, L2_R1.fq, L2_R2.fq) into two files by doing cat for L1_R1 and L2_R1 naming it LC_R1 (similarly for L1_R2 and L2_R2 naming it LC_R2). These are fastqs from WGS experiments and I want to perform variant calling downstream.

I finished aligning these fqs with bwa mem (adding custom Read Group info) using the foll. command.
bwa mem -R '@rg\tID:S1\tSM:SAMPLE1' -t 6 -v 1 -A 1 -B 4 -O 6,6 -E 4,4 -L 5,5 -U 17 hg38.fa ${base}"_R1.fq "${base}"R2.fq > aligned_bwamem_hg38"${base}".bam

But, when I finally try to sort the bam file, I keep getting this error.
[E::sam_hrecs_error] Header line does not have a two character key at line 597: "@s[M::mem_pestat] analyzing insert size distribution for orientation FF..."
[E::sam_hrecs_error] Header line does not have a two character key at line 597: "@s[M::mem_pestat] analyzing insert size distribution for orientation FF..."
samtools sort: failed to change sort order header to 'SO:coordinate'

Samtools quickcheck qv echoes as "bad" for the bam file.
A snippet from the bam file (which has the ideal size ~120 G)
![image](https://user-images.githubusercontent.com/64626735/123665360-35dcd380-d806-11eb-93d4-0b7f9b236079.png)


I would like to know the step/s in which I am making a mistake.

best
hasna

**Comment by whitwham** [comment]
Well it looks like you have bwa mem logging output in your bam file.

Is that really the command line you used?  If I remember correctly bwa mem only writes out sam files.

**Comment by hchetia** [comment]
Thanks for pointing that out. Seems like the files were erroneously named as bam instead of sam.
I renamed these to sam.
All other errors remains the same.



> Well it looks like you have bwa mem logging output in your bam file.
> 
> Is that really the command line you used? If I remember correctly bwa mem only writes out sam format.

**Comment by whitwham** [comment]
Yes, but I wouldn't expect the error with just ">".  If you had "&>" instead I would have expected logging and normal output to go to the same file causing the kind of error you are seeing.

**Comment by valeriuo** [comment]
@hchetia Why do you need `-v 1`? Try to remove this option form the command. The output should be less verbose.

**Comment by hchetia** [comment]
WOULD YOU BOTH SUGGEST TO RERUN USING -o for output and removing -v 1?

**Comment by valeriuo** [comment]
The bwa log messages are coming over **stderr**, which somehow got redirected into your output file. Using the dedicated option (`-o`) could solve your problem. Use `-v 1`, or any option for that matter, only if you need it.

**Comment by hchetia** [comment]
Okay let me try that and get back to you. Thanks.

**Comment by daviesrob** [comment]
Were you using `nohup`?  That has a bad effect of mixing stdout and stderr, which can cause problems for pipelines.  The `-o` option should be a work-around, at least for `bwa mem`.

**Comment by hchetia** [comment]
I did use nohup. Infact, did it yesterday when rerunning it as well! :|
Will do another run without nohup, too!

**Comment by hchetia** [comment]
Why was this closed? The problem is not resolved yet.
Also, the run with nohup did give erroneous sam again.

**Comment by valeriuo** [comment]
Because it is not a samtools issue. It's the way you run your script. The simple fact that the input SAM file is corrupt should tell you that the issue is upstream of samtool in your pipeline. It has been explained to you that `nohup` mixes **stderr** with **stdout** in the final output, which is redirected (**>**) to your SAM file, and that is why you get valid SAM entries combined with bwa log messages. To fix this, you were advised to run bwa with `-o` option, which should produce a clean SAM file and leave only the log messages in the output stream.

**Comment by hchetia** [comment]
Hi @valeriuo I followed all the commands, got the perfect sam file and then I converted it to bam. Turns out the bam now lacks the header
 [W::bam_hdr_read] EOF marker is absent. The input is probably truncated.
Is there an easy way to add this to a bam file because I was able to sort and index the bam regardless of the missing EOF marker and think that the file is actually not truncated?
Samtools quickcheck marks it as bad but I am assuming that is because of the missing EOF marker?
Thanks.

**Comment by valeriuo** [comment]
Which version of samtools/htslib are you using and which command did you use to convert SAM to BAM?
The EOF block is just and indication that the BAM file is complete.
Do you get the same value if your run `samtools view -c SAM_FILE` and `samtools view -c BAM_FILE`?

**Comment by jkbonfield** [comment]
As an aside, note that a common source of error with getting stderr and stdout intermingled is the use of `nohup`.  It's not advised when you're redirecting output.  It's possible some batch submission tools may do the same, but I'm not sure.  Using `-o` as commented above is definitely the right fix and applies to many other tools too.

**Comment by hchetia** [comment]
> Which version of samtools/htslib are you using and which command did you use to convert SAM to BAM?
> The EOF block is just and indication that the BAM file is complete.
> Do you get the same value if your run `samtools view -c SAM_FILE` and `samtools view -c BAM_FILE`?

@valeriuo So, the problem with EOF marker didn't stop any of my downstream steps. 

I had two files (xyz and abc). Both the .sam files were generated using the advise provided above.

I was able to convert abc.sam to abc.bam successfully while getting the error (missing the EOF marker) displayed during the process. I got the same output of 196071236 and 196071236 when I did samtools view -c for both abc.bam and abc.sam. Seems like the run was successful.

But for xyz.sam, I get "bad" prompt from quickcechk and I get the foll. error displayed when I do samtools view -c SAM_FILE or samtools view -b SAM_FILE

[W::sam_read1_sam] Parse error at line 81504563
samtools view: error reading file "xyz.sam"

The line 81504563 reads as such-
81504563 A00815:188:H55YWDRXY:1:2242:31268:31626	163	chrX	19224221	60	107M	=	19224222	108	GTTTGATACAGTTCCAACGAAAACCTCAAAAGGTATTTTTTGTAAAACTTGAAAAGCTGAC 
Seems like it is missing the NM MC AS XS RG and SA fields.

Is there anything I can do to make this file parseable to samtools? Or is rerun the only option?

I am using samtools 1.12
Using htslib 1.12.

Best,
Hasna

**Comment by jkbonfield** [comment]
You're not only missing aux tags, which wouldn't be a format error, but also the quality string and some of the sequence (it's incompatible with the CIGAR string of 107M).  My guess is you either ran out of disk space writing the SAM or the program that writing it died for some reason.

It may be best to check how many lines (divided by 4) you have in the input fastq files to compare that against the `view -c` output.  If it's almost identical, you could likely get away with just deleting the last line (or two if it's mate-pair is just previous to it) so you have a valid file without too much effort recreating it.

**Comment by hchetia** [comment]
Hi @jkbonfield I am unable to run the view -c command for the problematic xyz.sam file at all.

**Comment by jkbonfield** [comment]
> Hi @jkbonfield I am unable to run the view -c command for the problematic xyz.sam file at all.

Well, I just mean the 81504563 number really.  Although with hindsight it may not be accurate as you'd need to filter out secondary / supplementary alignments to get a notion for the number of input sequences that made it through to the output file.   If you have issues regenerating it, just start again from scratch as it's safest.  However you need to find out why it failed and, importantly, why you didn't notice before.  Eg is it part of a pipeline?  Do you have `set -o pipefail` enabled?  Are your scripts even checking `$?` for exit codes? Etc.  Aligners shouldn't be silently failing with exit code 0 if the output is truncated!

For what it's worth, locally we use a checksumming algorithm (maybe Biobambam2's seqchksum tool, but I'm not sure) to validate the sequence hasn't been lost or changed in any way through the alignment and processing pipelines.  I'm not sure it copes with fastq though as we initially start with unaligned BAM as our raw format instead of fastq.  The idea though is sound and you may wish to consider investigating what tools are out there.  The most simplest form though is counting - count the input, and count the output (after filtering out secondary / supplementary alignments).  Just as a sanity check to ensure you didn't drop a bunch of records somewhere along the line via and undiagnosed bug or file truncation.

None of this however is a samtools issue.  It's a pipeline processing issue.

**Comment by hchetia** [comment]
Hi @jkbonfield Thanks for the tip of seqchksum! TBH, I was actually trying to understand why the program failed! This is not really a part of any pipeline but rather a basic bash script with the command "bwa mem -t 6 -A 1 -B 4 -O 6,6 -E 4,4 -L 5,5 -U 17 hg38 "${base}"_R1.fq "${base}"_R2.fq -o aligned_hg38_"${base}".sam 2>&1 | tee "${base}"_log.txt".
The rerun completed successfully and hence, it feels like the memory issue that you mentioned earlier. I should consult with the BWA team further regarding this!
Thanks to the Samtools team for the support! 👍
