### ISSUE TITLE
samtools import: confusing warnings with *.fq.gz inputs.

### ISSUE THREAD

**Issue by keiranmraine** [samtools/samtools#1467]
## Version

```
$ samtools --version
samtools 1.13
Using htslib 1.13
Copyright (C) 2021 Genome Research Ltd.

Samtools compilation details:
    Features:       build=configure curses=yes 
    CC:             gcc
    CPPFLAGS:       
    CFLAGS:         -Wall -g -O2
    LDFLAGS:        
    HTSDIR:         htslib-1.13
    LIBS:           
    CURSES_LIB:     -lncursesw

HTSlib compilation details:
    Features:       build=configure plugins=no libcurl=no S3=no GCS=no libdeflate=no lzma=yes bzip2=yes htscodecs=1.1.1
    CC:             gcc
    CPPFLAGS:       
    CFLAGS:         -Wall -g -O2 -fvisibility=hidden
    LDFLAGS:        -fvisibility=hidden 

HTSlib URL scheme handlers present:
    built-in:	 preload, data, file
    crypt4gh-needed:	 crypt4gh
    mem:	 mem

```

## Environment

```
$ uname -sr
Linux 5.4.0-65-generic
$ uname -m
x86_64
$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

## Issue

The new `samtools import` option produces warnings more commonly associated with BAM inputs when reading from compressed FASTQ:

```
$ samtools import -1 GIv1_lib_S5_L001_R1_001.fastq.gz -2 GIv1_lib_S5_L001_R2_001.fastq.gz -i -R GIv1_lib_S5 -o GIv1_lib_S5_L001.cram --output-fmt CRAM,no_ref=1 -@ 4
[W::bgzf_read_block] EOF marker is absent. The input is probably truncated
[W::bgzf_read_block] EOF marker is absent. The input is probably truncated
```

Inputs are not truncated and final output has expected number of rows.

**Comment by daviesrob** [comment]
Were your files compressed using plain-gzip, or bgzip?  The warning would be sensible for a BGZF file, but should not be emitted for plain gzip.

**Comment by keiranmraine** [comment]
Ah, yes they are bgzip, I didn't compress them.  Does bgzip have any benefit over plain gzip for fastq files?

```
$ file GIv1_lib_S5_L001_R1_001.fastq.gz 
GIv1_lib_S5_L001_R1_001.fastq.gz: Blocked GNU Zip Format (BGZF; gzip compatible), block length 11804
```

**Comment by keiranmraine** [comment]
I can confirm that when using a current version of bgzip the warning goes away:

```
$ zcat GIv1_lib_S5_L001_R1_001.fastq.gz | head -n 100 | bgzip -c > R1.fastq.bgz
$ zcat GIv1_lib_S5_L001_R2_001.fastq.gz | head -n 100 | bgzip -c > R2.fastq.bgz
$ samtools import -1 R1.fastq.bgz -2 R2.fastq.bgz -i -R GIv1_lib_S5 -o GIv1_lib_S5_L001.cram --output-fmt CRAM,no_ref=1 -@ 4
```

**Comment by jmarshall** [comment]
With filenames like that, these appear to have been produced by `bcl2fastq`. Bcl2fastq bgzf-compresses its output by default but does not add a BGZF EOF trailer. This can be considered a bug in bcl2fastq; and/or there might be a case for toning this warning down a bit for non-BAM files.

**Comment by jkbonfield** [comment]
> Ah, yes they are bgzip, I didn't compress them. Does bgzip have any benefit over plain gzip for fastq files?

In theory it would permit random access, but I doubt anyone uses it.  The main benefit is it's a library containing an efficient parallel gzip, which permits easy speedups of writing the data.   There is pigz too of course, but it's a program so makes using it messier from your own code and AFAIK doesn't permit use of the faster deflate implementations.

Bgzip format also permits parallel decompression, which also isn't doable with gzip format (so pigz can only multi-thread the encoder).

**Comment by whitwham** [comment]
I've tried and failed to reproduce this with gzip, modern bgzip and the latest version of bcl2fastq I could find.

**Comment by jmarshall** [comment]
I can reproduce this at will with e.g. the current version of bcl2fastq, 2.20.0.422:

1. Find some FASTQ files generated by bcl2fastq with default settings (at least, without `--no-bgzf-compression`), even just the `Undetermined_S0_L001_R1_001.fastq.gz` files.
2. Use them as is — don't recompress with gzip or bgzip or anything
3. Notice that `htsfile` reports the file is BGZF-compressed, `samtools quickcheck` reports it has no EOF block, and `samtools import` produces this warning:

```
$ htsfile Undetermined_S0_L001_R1_001.fastq.gz 
Undetermined_S0_L001_R1_001.fastq.gz:	FASTQ BGZF-compressed sequence data

$ samtools quickcheck Undetermined_S0_L001_R1_001.fastq.gz
Undetermined_S0_L001_R1_001.fastq.gz had no targets in header.
Undetermined_S0_L001_R1_001.fastq.gz was missing EOF block when one should be present.

$ samtools import -o /dev/null Undetermined_S0_L001_R1_001.fastq.gz
[W::bgzf_read_block] EOF marker is absent. The input is probably truncated
```

**Comment by whitwham** [comment]
Ah yes, I see my mistake.  I was assuming the `current` version on our system was linked to the latest version, rather than to version 2.15.

**Comment by jmarshall** [comment]
Wow! Even 2.19 is no longer available from Illumina's website. 2.15 is truly ancient!

**Comment by jkbonfield** [comment]
To be fair though, we don't use it any more as we go direct from BCL to unaligned BAM/CRAM via https://github.com/wtsi-npg/bambi.

Maybe "current" is a bit of a misnomer though. :-)

**Comment by whitwham** [comment]
After a bit of Zoom discussion we are going to with toning down the language of the warning.

**Comment by jmarshall** [comment]
Please also report the bug to Illumina (although considering they haven't published a bcl2fastq update since 2017, maybe don't hold your breath for a response!).

**Comment by daviesrob** [comment]
samtools/htslib#1323 has changed the warning from "is probably truncated" to "may be truncated".  Hopefully that will be a bit less alarming.

The successor to bcl2fastq is [BCL convert](https://support.illumina.com/sequencing/sequencing_software/bcl-convert.html).  We'll check to see if it has the same problem, and attempt to get in touch with Illumina if it does.

**Comment by Poshi** [comment]
Just for the record.

> In theory it would permit random access, but I doubt anyone uses it. The main benefit is it's a library containing an efficient parallel gzip, which permits easy speedups of writing the data. There is pigz too of course, but it's a program so makes using it messier from your own code and AFAIK doesn't permit use of the faster deflate implementations.

I'm using it!
I'm using bgzip for FastQ files in order to access them randomly so I can extract chunks of FastQ files for parallel aligning. With bgzip, I can extract any fixed size block from a randomly huge FastQ file with a fixed time (like I need 1 minute to extract any 1GiB block from a multi GiB file).

> Bgzip format also permits parallel decompression, which also isn't doable with gzip format (so pigz can only multi-thread the encoder).

Technically, pigz could allow some degree of parallel decompression (as many decompressing threads as gzip substreams exist int he file) if there were an index pointing at the beginning of each of the gzip substreams. But without the index, you can only search for it by decompressing sequentially.
With bgzip, if I'm not wrong, you can decompress in parallel as long as you have the index (gzi), otherwise you hit the same issue.

**Comment by jkbonfield** [comment]
Please don't resurrect old closed issues that haven't been commented on for years.

Your statement on bgzip is wrong - it can decompress in parallel without needing an index.  The index is only needed if you want random access.

Regarding pigz however, it's not ideal to have to support another format that doesn't really solve much due to the lack of an index.  It's also not worth us fixing it to cope with parallel decompression when we have our own, better, alternative already. 

I am working on a bgzf replacement as a bit of a backburner project: https://github.com/jkbonfield/htslib/tree/bgzf2

Basically that uses zstd instead of gzip for improved speed and compression of long reads (gzip's LZ history can only go back 32KB, which is shorter than some long reads now so can do no deduplication on them).  It has a self-contained index which hopefully resolves the myriad of index formats and even index filename disparities (htslib vs htsjdk).  It also aims to fix the disparity between block boundies and record boundaries, making random access of unsorted much simpler, and the ability to index unaligned data such as fastq files for purposes of parallel distributed processing pipelines.  That's still a work in progress however, but I've got a proof of principle working and a BAM.bgzf2 file with random access capability.

It's not ready for public testing though.

**Comment by Poshi** [comment]
Sorry, I just wanted to say that there's people under that use case (bgzipped FastQ files for random access). I'm not requesting anything. In particular, I'm not asking for pigz to be supported. I'll send a personal e-mail next time.
Thanks for the extra information!
