### ISSUE TITLE
Library Support

### ISSUE THREAD

**Issue by jvanalstine** [samtools/samtools#1482]
I have added library support on a fork off your master branch [here](https://github.com/jvanalstine/samtools/tree/library). I needed to use it similarly to how one uses htslib. 

```
#include bamlib/sam.h
#include bamlib/bam.h
```

I would like to submit a PR for this, but it's not clear what the dev lifecycle is like on this repo. If anyone has a note for contributors I can look at or a quick comment about how this can be merged (if it's even wanted) that would be helpful.

**Comment by jkbonfield** [comment]
This isn't really something Samtools supports, and it's likely to be flakey as a library as a lot of functions feel quite free in reporting an error and then simply calling `exit()`.

What is it you're trying to achieve here?  My recommended approach for doing things like merging and sorting from within another tool would be something like `fork` and `exec` the samtools binary, to capture exit status in order to spot errors.  (This is something PySAM gets wrong too IMO.)

If there are specific features you need, such as data merging, then perhaps we should consider adding support into htslib instead.    E.g. I coul dget behind the idea of a meta-file (or data) listing URIs which when opened using normal htslib functions will perform the redirect and auto-merge on the fly.

**Comment by jmarshall** [comment]
> E.g. I could get behind the idea of a meta-file (or data) listing URIs which when opened using normal htslib functions will perform the redirect and auto-merge on the fly.

You are in luck :smile: — I'm working on a form of `hts_open` (to be added to HTSlib) that takes an array of sorted `htsFiles` (or iterators) and enables a form of `sam_read1`/`bcf_read1` to read from the merged stream.

**Comment by jvanalstine** [comment]
> This isn't really something Samtools supports, and it's likely to be flakey as a library as a lot of functions feel quite free in reporting an error and then simply calling exit().

That is fair, I did bluntly expose all of the headers in the repo. Is it the case that samtools will never expose an API even if well crafted?

> What is it you're trying to achieve here?

I noticed in a number of other tools that people were including methods from samtools. For instance you can see an example [here](https://github.com/abyzovlab/CNVnator/blob/c73786d6160f17b020feae928148533ca036fad2/AliParser.hh#L10). They are often seem not thought out, and the way the tool uses samtools makes it difficult to work with a standard install. So, it looked simple enough to refactor the build to expose the functions. 

Although, it might be wrongheaded to do this instead of refactoring the tools to use htslib.

**Comment by jmarshall** [comment]
Your example, CNVnator, does not use any substantial facilities like merging or sorting that are unique to samtools (i.e., in samtools but not in HTSlib). It just uses the legacy samtools API wrappers for HTSlib facilities, and hence could be trivially refactored to use HTSlib directly. Doing so would simplify building CNVnator.

**Comment by jvanalstine** [comment]
Yes, and after looking more closely at some internal stuff, the same holds there. Ok, I agree that this is wrongheaded, and that it would be better to just refactor the tools to use htslib.

**Comment by jkbonfield** [comment]
> > This isn't really something Samtools supports, and it's likely to be flakey as a library as a lot of functions feel quite free in reporting an error and then simply calling exit().
> 
> That is fair, I did bluntly expose all of the headers in the repo. Is it the case that samtools will never expose an API even if well crafted?

I would argue that a well crafted interface to the data manipulation functions in Samtools is, infact, Htslib!

Now if there are things in Samtools that are required that aren't in Htslib then that is a different conversation, hence the discussions on a merge API above. 

Adding blanket support to call every samtools `main_*` function as a sub-command may seem simple, but if you want it to be robust then it puts a maintenance burden on us:  No more assuming errors can be handled by reporting and just bailing out.  All exit paths must also free every bit of memory, instead of accepting that the OS will do it on exit (we mostly do this anyway, but it's not a guarantee).   All return values would need to be documented.  API documentation would need to be written.  And so on.  In short it's effort to do right, and effort to keep it in that state.  Effort that prevents us doing other, IMO more useful, things.

The flip side is a basic API that lets you drive samtools but with no proper memory protection or error handling.  That's basically what some tools do, but I just know if we blessed it we'd be the ones fielding the bug reports.

**Comment by jvanalstine** [comment]
Agree generally. I think this ought to be passed on and I’ll refactor the other tools to use htslib proper. 

> Now if there are things in Samtools that are required that aren't in Htslib then that is a different conversation, hence the discussions on a merge API above.

How about this, we close this, but if, while in the process of refactoring these other tools, I come across some bit of functionality that I need in htslib, then I’ll open up another issue to discuss the feature and submit a PR. It might be that the tools are just out dated and can easily be refactored to use htslib.

**Comment by jkbonfield** [comment]
I'm happy with that.  Best of luck.

**Comment by jmarshall** [comment]
If in the course of converting from the legacy Samtools API you find things that cannot be expressed with HTSlib facilities, then that is indeed something interesting and worth raising as an HTSlib issue.

BTW have you seen the release notes in _NEWS_:

> The legacy samtools API (libbam.a, bam.h, sam.h, etc) has not been actively maintained since 2015. It is deprecated and will be removed entirely in a future SAMtools release. We recommend coding against the HTSlib API directly.

**Comment by jvanalstine** [comment]
> The legacy samtools API (libbam.a, bam.h, sam.h, etc) has not been actively maintained since 2015. It is deprecated and will be removed entirely in a future SAMtools release. We recommend coding against the HTSlib API directly.

I have not seen this. Where did this come from?

**Comment by jmarshall** [comment]
The release notes, as found in the [relevant release on GitHub](https://github.com/samtools/samtools/releases/tag/1.12) and in the _NEWS_ file in samtools tarballs and repositories.

Perhaps the maintainers should copy this note to the top of each new release's entry until #1483 is applied.

**Comment by jkbonfield** [comment]
I'd hope we won't have any new releases without #1483 being in there!  It's long overdue culling. (And thanks for the PR.  It may get delayed assignment until our next weekly meeting, but it's been noted.)
