### ISSUE TITLE
Reheader Causes htsjdk Errors if Index isn't Regenerated

### ISSUE THREAD

**Issue by DarioS** [samtools/samtools#1492]
I was confused when I got errors like:

```
[September 1, 2021 10:47:54 PM GMT+10:00] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 0.09 minutes.
Runtime.totalMemory()=1793064960
htsjdk.samtools.util.RuntimeIOException: /scratch/hm82/OSCC/Somatic-ShortV/../Final_bams/OSCC_24-N_rep2.final.bam has invalid uncompressedLength: -759668589
        at htsjdk.samtools.util.BlockCompressedInputStream.inflateBlock(BlockCompressedInputStream.java:543)
        at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:532)
```

I use `samtools reheader` to change the value of SM in RG. I eventually figured out by myself that I need to run `samtools index` afterwards to make the accompanying index up-to-date. I didn't realise that changing some text in the header would make it necessary to rebuild the index from scratch. Could there be a warning about this shown when the user runs `samtools reheader -h`? Should index recreation automatically be done by `samtools reheader` perhaps?

**Comment by jkbonfield** [comment]
This is to be expected, although I concede the point that perhaps if an index existing before then it could optionally be rebuilt (or deleted if the option to rebuild isn't selected).  It only makes sense for inplace header editing though, which I didn't think we had for bam.  With BAM you always have to specify a new output file.

We did add `--write-index` to many samtools commands to create an index at the same time as creating a new BAM/CRAM, so that would work here I think too.

**Comment by jkbonfield** [comment]
Looking at the syntax for `samtools reheader`, it appears impossible to update the index.  It's usage is particularly weak:

```
Usage: samtools reheader [-P] in.header.sam in.bam > out.bam
```

Because the output is just stdout, the program doesn't know the filenames.  It's not possible for it to automatically rebuild the index, or even to remove it, as it doesn't know what the file is called.

We could potentially add an extra argument for the index filename, but it would be rather an odd syntax.  Eg `samtools reheader in.hdr in.bam -i out.bam.bai > out.bam`.  This also doesn't really solve the problem.  Forgetting to rebuild the index is no different than forgetting to add the extra argument to rebuild the index, so the same errors would surface.

Furthermore, if I try to do this operation using samtools and then view the file with the outdated header, it tells me so:

```
[W::hts_idx_load3] The index file is older than the data file: /tmp/9827_2#49.1m.bam.bai
```

Therefore I'm closing this as it would be better fixed in htsjdk/Mutech2.
