### ISSUE TITLE
mpileup: --output-BP-5 switches output column 7 and 8

### ISSUE THREAD

**Issue by koriege** [samtools/samtools#1534]
when using the --output-BP-5 option, the position and read id columns are switched
```
samtools mpileup --output-QNAME --output-BP in.bam
test_chr	25	A	1	^!,	I	1	id_1

```
```
samtools mpileup --output-QNAME --output-BP-5 in.bam
test_chr	25	A	1	^!,	I	id_1	24
```

**Comment by jkbonfield** [comment]
Oops.  That's definitely a bug, sorry about that.  Thanks for reporting.

**Comment by daviesrob** [comment]
As currently implemented, `--output-BP-5` writes to its own column (currently the last one) rather than replacing the one for `--output-BP`.  As we've now shipped a version that works this way, we need to consider if it would be better to fix the documentation to reflect this, and possibly also relax the constraint on enabling `--output-BP` and `--output-BP-5` at the same time.
