### ISSUE TITLE
samtools 1.10 csi vs 1.13 generation/reading

### ISSUE THREAD

**Issue by keiranmraine** [samtools/samtools#1535]
Can anyone comment on any possible reason for the following, specifically the single comment:

https://github.com/PapenfussLab/gridss/issues/520#issuecomment-946856411

**Comment by daviesrob** [comment]
I think we would need a bit more information, but there have been a few bug-fixes to the `--write-index` option between 1.10 and 1.13.  For example, samtools/htslib#1028 fixed a bug where multi-threaded programs could occasionally produce index offsets that pointed at the end of a BGZF block instead of the start of the next one.  Where that happened, reading from the offset would also be reported incorrectly as EOF, which may explain your results.  The fix both made the index offsets consistently point to the start of the next block, and allowed HTSlib (and so SAMtools) to read the old indexes without being tripped up.

We recommend using the latest release if you can, but if you do need to use 1.10 then a work-around would be to use `samtools index` the old-fashioned way on the output file.

**Comment by keiranmraine** [comment]
Ah thanks, so it's not csi vs bai, but the multi threaded component of the "build during generation".  This doesn't impact `samtools index -@ $threads some.bam` from what I can see.
