### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by hidvegin** [samtools/samtools#1571]
I use `hisat` v2.2.1 for align some mRNA-seq data to the reference genome. I use also `samtools` v1.14 for generate the aligned files into BAM file. I use this code for the whole process:

`python3 /home/fk8jybr/hisat2-2.2.1/hisat2 -x /home/fk8jybr/input/reference/triticum_aestivum/mRNA/hisat2/triticum_aestivum_index --known-splicesite-infile /home/fk8jybr/input/reference/triticum_aestivum/mRNA/triticum_aestivum_splice.txt -p 16 -1 /home/fk8jybr/output/trimmed/Novogene_buza_mRNA_2021/K1_1/K1_1_paired.fq.gz -2 /home/fk8jybr/output/trimmed/Novogene_buza_mRNA_2021/K1_1/K1_2_paired.fq.gz | samtools view -bS -o /home/fk8jybr/output/hisat2/Novogene_buza_mRNA_2021/K1_1/K1_1.bam`

I got this error:

```
File "/home/fk8jybr/hisat2-2.2.1/hisat2", line 31
    use strict;
        ^
SyntaxError: invalid syntax
[main_samview] fail to read the header from "-".
```

How could I resolve this error?

**Comment by jkbonfield** [comment]
This isn't a samtools error so I'm closing this.

However it looks like your problem is you're attempting to run hisat2 (which it appears is a perl script) using python3.  If the script is executable, you should just be able to execute it without adding python in there (or perl, which would be the correct tool to use).

**Comment by hidvegin** [comment]
@jkbonfield Thank you for your answer.
