### ISSUE TITLE
Undocumented: what does square bracket "]" mean in mpileup output

### ISSUE THREAD

**Issue by pd3** [samtools/samtools#1578]
The `samtools mpileup` output contains square bracket characters which are not documented in the manual page. For example one could have an output like this
```
19  99993 G 1  ^],   D
19  99994 T 1  ,     B
19  99995 G 0  *     *
19  99996 T 2  ,^],  =@
```

**Comment by jmarshall** [comment]
The square brackets in your example appear immediately after a `^` character, which is documented as follows (emphasis added):

> If this is the first position covered by the read, a “`^`” character **followed by the alignment's mapping quality encoded as an ASCII character**.

**Comment by jkbonfield** [comment]
If you're attempting to process the output in some way, the `--no-output-ends` removes this output.  They were never reliable anyway and IMO a mistake to add in the first place.  If the base is omitted due to a region query, quality filtering, or any other possible reason, then the marker for read-start and read-end vanished.  That made their use in parsing the output rather pointless.
