### ISSUE TITLE
Make the arguments in all samtools subcommand for compatible? 

### ISSUE THREAD

**Issue by yech1990** [samtools/samtools#1580]
The naming of arguments in different subcommand is quite different. For example, in `mpileup` command, `-q`  means min **mapping quality**, while `-Q` means min **base quality**. However, the `depth`  command show a opposite naming, which is  `-q` means min base quality, and `-Q` means min mapping quality. 
Some other examples like, `-r` in `mpileup` and `-p` in `tview`. 
Is it possible to more the arguments into a similar naming style?

**Comment by jkbonfield** [comment]
The is, sadly, true.  I also discovered this while rewriting the depth subcommand recently.

Unfortunately changing it risks breaking peoples scripts, so it's not something we can do without consequences.  Depth has been this way since 2011: e6ca3f825fea0a18b6068905e3173ff19104e756 and pileup since 2010: 921db5eb (although we could perhaps have corrected it when mpileup was added, it's too late now).

**Comment by yech1990** [comment]
Cool. Thank you for the improvement.

**Comment by jkbonfield** [comment]
I surveyed the other options and it's a right mixed bag!  #1584 adds long options everywhere that didn't have them, so at least sanity can prevail for people who wish to be more explicit.

```
                base    mqual                                                   
mpileup         -Q      -q                                                      
bedcov                  -Q                                                      
coverage        -Q      -q                                                      
depth           -q      -Q                                                      
phase           -Q                                                              
view                    -q                                                      
```
