### ISSUE TITLE
`depth` hangs when streaming from GCS over BED

### ISSUE THREAD

**Issue by SHuang-Broad** [samtools/samtools#1581]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

```
samtools 1.14
Using htslib 1.14
```

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
```
Darwin 20.6.0
```
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
```
x86_64
```
- compiler (run `gcc --version` or `clang --version`)
```
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

The command hangs indefinitely, when streaming + using BED

```bash
# test 2-line bed
$ cat test.bed
chr1	11873	12227	gene_ids|DDX11L1;exon_ids|NR_046018.2.1
chr1	12612	12721	gene_ids|DDX11L1;exon_ids|NR_046018.2.2
$ export GCS_OAUTH_TOKEN=`gcloud auth application-default print-access-token`
$ samtools depth -aa -b test.bed -o test.depth.txt gs://<path_to_bam>
# wait for 1 minute
$ tail -n 2 test.depth.txt
chr1	12165	14
chr1	121%
# if use region explicitly, runs fine, even when provided the full regions
$ samtools depth -aa -r chr1:12164-12167 gs://<path_to_bam>
chr1	12164	14
chr1	12165	14
chr1	12166	14
chr1	12167	14
```

Looking at internet traffic, samtools seem to receive unreasonably large amount of incoming traffic, for such small regions.

**Comment by daviesrob** [comment]
This is because the depth `-b` option has always worked as a filter - so it reads the entire input, and uses the BED data to accept or reject records as it goes.  It means it will work without an index, and can be used on non-seekable inputs like pipes.  It does mean it can read a lot more data than you need, though - although you can also mix it with the region option `-r` to limit the amount you stream through.

I think the best solution at the moment would be to filter the data with `samtools view` first.  That has a `--region-file` option that will use an index to quickly jump to the locations listed in a BED file.  So you could try something like:

```
samtools view -u --region-file test.bed gs://<path_to_bam> | samtools depth -aa -b test.bed -o test.depth.bed -
```

Unfortunately `depth` doesn't have an equivalent of the `--region-file` option at the moment.  We'll try to add it in a future version.

**Comment by SHuang-Broad** [comment]
Thanks @daviesrob !
That's essentially what I ended up doing.

Feel free to close the ticket, if appropriate.
