### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by luisafmc** [samtools/samtools#1588]
#### Is your feature request related to a problem? Please specify.
Hi, 
I'm triying to sort some BAM files that I have as output from STAR. The biggest one size is 9.4M. I'm using samtools:1.14--hb421002_0 version with 32G and the next command:

for f in /*.bam
do
singularity exec /usr/local/biotools/s/samtools:1.14--hb421002_0 samtools sort -m 80000000K --threads 8 -O BAM -@ 8 $f > $f"_sorted.bam"
done

But the same error always appears:
samtools sort: couldn't allocate memory for bam_mem

I just want to know how to figure out the size of RAM memory that I need and if I doing something wrong in the command.

**Comment by jkbonfield** [comment]
Note the -m argument is *per thread*.  Also 80000000K is 80GB.  Did you really mean that?  Multiplied by 8 threads that's 640GB.

You can use e.g. `free -h` to list the memory available on your system (or `top`), to get an idea of how much you have.  Samtools sort doesn't need large quantities of memory.  It simply makes it a little bit more efficient.  So you can just give it a lower value.

Also you're best using `-o ${f}_sorted.bam` instead of `>`.

**Comment by luisafmc** [comment]
Thank you!

It finally works.
