### ISSUE TITLE
samtools view: Iterator could not be created. Aborting.

### ISSUE THREAD

**Issue by VJalili** [samtools/samtools#1621]
I would like to get reads overlapping regions given in a BED file using `samtools view`. Accordingly, I use the following command:

```
samtools view \
    -b --use-index \
    -T GRCh38_full_analysis_set_plus_decoy_hla.fa \
    --targets-file targets.bed \
    --output subset.bam \
    HG00096.final.cram
samtools view: Iterator could not be created. Aborting.
```

The `targets.bed` file contains only one region (for simplicity):
```
% head targets.bed
chr5	148506776	148506785
```

Both the reference and the cram files have an index file: 
```
% ls -lha GRCh38_full_analysis_set_plus_decoy_hla*
-rwxrwxrwx  5 user  staff   3.0G Aug  2  2021 GRCh38_full_analysis_set_plus_decoy_hla.fa
-rwxrwxrwx  5 user  staff   151K Aug  2  2021 GRCh38_full_analysis_set_plus_decoy_hla.fa.fai

% ls -lha HG00096.final*
-rw-r--r--  1 user  staff    15G Mar 17 12:26 HG00096.final.cram
-rw-r--r--  1 user  staff   1.3M Mar 17 12:29 HG00096.final.cram.crai
```

Environment description: 

    % samtools --version 
    samtools 1.15
    Using htslib 1.15

    % uname -sr
    Darwin 21.3.0

    % uname -m 
    arm64

    % gcc --version 
    Apple clang version 13.1.6 (clang-1316.0.21.2)
    Target: arm64-apple-darwin21.3.0
    Thread model: posix
    InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by jkbonfield** [comment]
I believe this is a regression that appeared in 1.15, now fixed in this PR:  https://github.com/samtools/samtools/pull/1617/files

You can either downgrade to 1.14 or apply this simple patch to the 1.15 source tree.  If this doesn't cure it, please let us know.

As an aside, a workaround is to manually provide a list of chromosomes to query against (ie all of them) and it'll filter the BED contents through those arguments and it should then also work.  That's rather messy though, and maybe impractical for many SQ entries such as GRCh38.

**Comment by VJalili** [comment]
Thank you @jkbonfield, downgrading to version `1.14` fixed the issue.
