### ISSUE TITLE
Build fails when using separately installed HTSlib 

### ISSUE THREAD

**Issue by nadyawilliams** [samtools/samtools#1636]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib]
Using the latest 1.15.1 source distribution

 #### Please describe your environment.
- Rocky Linux 8.4
- x86_64
- compiler gcc 11.2.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
Using separately build HTSlib 1.15.1 and gcc compiler via modules:
**module load gcc/11.2.0  htslib/1.15.1**  
**tar xjvf samtools-1.15.1.tar.bz2** 
**cd Rsamtools-1.15.1
./configure --prefix=/opt/apps/samtools/1.15.1 --with-htslib=/opt/apps/htslib/1.15.1 \\
                   --mandir=/opt/apps/samtools/1.15.1/share/man**
**make** 
cd /opt/apps/htslib/1.15.1 && make htslib.pc.tmp
make[1]: Entering directory '/opt/apps/htslib/1.15.1'
make[1]: *** No rule to make target 'htslib.pc.tmp'.  Stop.

Per above output, make tries to do compile in already installed directory which is wrong.

The culprit is in configure file, line 3554:
3549 system) ax_cv_htslib_which=system ;;
3550 *)
3551   HTSDIR=$with_htslib
3552   if test -f "$HTSDIR/hts.c" && test -f "$HTSDIR/htslib/hts.h"; then
3553     ax_cv_htslib_which=source
3554   elif test -f "$HTSDIR/htslib_vars.mk"; then
3555     ax_cv_htslib_which=build 
3556   else
3557     ax_cv_htslib_which=install
3558   fi
3559   ;;

File htslib_vars.mk indeed exists in the installation directory and so does the same file in version of 1.10.2 which compiles
without any issue. 

If i disable the above check in configure  file, and rerun configure then i can compile without an issue.

Looking over the configure i see there are now 3 cases: install, build and source but i don't see that there are sufficient modifications in m4/* files to accommodate for it. 

I should be able to configure/make with my own install of htslib and do not depend on one provided in the source of samtools.

**Comment by daviesrob** [comment]
`htslib_vars.mk` shouldn't be present in the installation directory.  How did you install your copy of HTSlib?

The following recipe works for me. Note that as a throw-away test, I'm installing in `/tmp/opt`.  You would probably need something like `sudo make install` if your `--prefix` is somewhere under `/opt`.  I also set `rpath` (via `LDFLAGS`) when configuring `samtools` so that it will find the correct HTSlib shared library when I try to run it without needing any hints like `LD_LIBRARY_PATH`.

```
mkdir /tmp/opt
tar xvf htslib-1.15.1.tar.bz2 
cd htslib-1.15.1/
./configure --prefix=/tmp/opt/htslib
make -j 8
make install
cd ..
rm -rf htslib-1.15.1/
tar xvf samtools-1.15.1.tar.bz2
cd samtools-1.15.1/
./configure --prefix=/tmp/opt/samtools --with-htslib=/tmp/opt/htslib LDFLAGS='-Wl,-R/tmp/opt/htslib/lib'
make -j 8
make install
cd ..
rm -rf samtools-1.15.1
/tmp/opt/samtools/bin/samtools
```

The last line prints the normal `samtools` usage:
```
Program: samtools (Tools for alignments in the SAM format)
Version: 1.15.1 (using htslib 1.15.1)

Usage:   samtools <command> [options]
 ... etc ...
```

**Comment by nadyawilliams** [comment]
The htslib_vars.mk were added to the install as some bio software packages needed it for the previous version. Looks like this is causing  an issue with the newest version where configure  makes additional checks. The build outline you provided is nearly identical to what i am using except that we set LD_LIBRARY_FLAGS and do not set LDFLAGS. I am going to redo the install of htslib adding CPPFLAGS and LDFLAGS and go from there. Thank you for the pointer!

**Comment by jmarshall** [comment]
As you found, _htslib_vars.mk_ is present in an HTSlib source (or build) directory, but is not present in an installation directory.[^1] If “some bio software packages needed it”, then that was because those packages can only be built against an HTSlib source code directory, not an installation of HTSlib.

Perhaps you could say what bio software packages those were, so that they can be encouraged to make their installation procedures more flexible and work with a separately installed HTSlib as well.

[^1]: The reasons for this are explained in the comments in _htslib_vars.mk_ and _htslib.mk_.
