### ISSUE TITLE
Remove mitochondrial reads from genome

### ISSUE THREAD

**Issue by cpavloud** [samtools/samtools#1639]
Hello!
I have a question, rather than an issue.

I am using [minimap2](https://github.com/lh3/minimap2) (v 2.17) to map mitochondrial reads (downloaded from NCBI) to a genome (assembled from nanopore reads). 
`minimap2 -ax map-ont mtDNA.fasta my_genome_pilon.fasta -t 3 -2 > mapped.sam`

And then, I am using samtools (v 1.9) to get the unmapped reads
`samtools view -b -f 4 mapped.sam -@ 20 > genome.bam`

and to get only the mapped reads
`samtools view -b -F 4 mapped.sam -@ 20 > mitochondrion.bam`

My original genome file (my_genome_pilon.fasta) is ~0.78 Gb and the mapped.sam file is ~0.77 Gb. 
The mitochondrion.bam is 202 Kb.
However, the genome.bam is only ~0.21 Gb. 
Does this make sense? It looks like it has been reduced a lot in size and I am wondering if I did something wrong. 

Thank you!

**Comment by mp15** [comment]
The reduced size is the result of lossless GZIP compression. Your mapped SAM file coming from minimap2 is by default uncompressed (which is why people tend to pipe it straight into samtools), whereas your output BAM files are by default GZIP compressed.

Sent from my iPhone

On 22 Apr 2022, at 17:43, Christina Pavloudi ***@***.***> wrote:

﻿

Hello!
I have a question, rather than an issue.

I am using minimap2 [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lh3_minimap2&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=G0VcQIYnuldSWxHRQBhdPRFs_mQMJZ2jKzdJVtGelRQ&m=mOamLAxXU9dIw373XY6smNa-3468J2Fl2QS_uvbMy-tFtqPCPIGWWmOLJjJ9D14e&s=DJDeqzb6E9HIDOztlW8dfb4HiZim6d2pROkNY8MZpVA&e=> (v 2.17) to map mitochondrial reads (downloaded from NCBI) to a genome (assembled from nanopore reads).
minimap2 -ax map-ont mtDNA.fasta my_genome_pilon.fasta -t 3 -2 > mapped.sam

And then, I am using samtools (v 1.9) to get the unmapped reads
samtools view -b -f 4 mapped.sam -@ 20 > genome.bam

and to get only the mapped reads
samtools view -b -F 4 mapped.sam -@ 20 > mitochondrion.bam

My original genome file (my_genome_pilon.fasta) is ~0.78 Gb and the mapped.sam file is ~0.77 Gb.
The mitochondrion.bam is 202 Kb.
However, the genome.bam is only ~0.21 Gb.
Does this make sense? It looks like it has been reduced a lot in size and I am wondering if I did something wrong.

Thank you!

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_samtools_samtools_issues_1639&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=G0VcQIYnuldSWxHRQBhdPRFs_mQMJZ2jKzdJVtGelRQ&m=mOamLAxXU9dIw373XY6smNa-3468J2Fl2QS_uvbMy-tFtqPCPIGWWmOLJjJ9D14e&s=Qb32EtZPiN0doQ1qhosUuvuQkBcDtyWlIIT3RL-3O2g&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAMUCWJK4PAP6VPPZASQXJLVGLJMDANCNFSM5UC2SPLA&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=G0VcQIYnuldSWxHRQBhdPRFs_mQMJZ2jKzdJVtGelRQ&m=mOamLAxXU9dIw373XY6smNa-3468J2Fl2QS_uvbMy-tFtqPCPIGWWmOLJjJ9D14e&s=t5p6vxf1BhlCXZX5qU3QxEiMX4RBp86Q8tAL3EZUgH0&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by cpavloud** [comment]
Then it makes sense. Thank you very much! 
It is the first time I am trying this and I was concerned.
