### ISSUE TITLE
samtools depth missing global --reference option (was working in 1.12 and earlier)

### ISSUE THREAD

**Issue by RandyHarr** [samtools/samtools#1643]
The --reference global option was working in 1.12 and 1.10 .
 
samtools 1.15.1 Using htslib 1.15.1 (macports 2.7.2 and self-compiled Cygwin64 gcc version 11.2.0 on x86_64 arch)
samtools 1.13  Using htslib 1.13+ds (Ubuntu 22.04 apt install on x86_64 arch)

 #### Please describe your environment.
- OS  Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101 arm64
- machine architecture arm64
- compiler macports 2.7.2

samtools depth --reference hs38.fa.gz NB2764362.cram

Usage: samtools depth [options] in.bam [in.bam ...]

**Comment by jkbonfield** [comment]
Thank you for reporting this.  It appears I forgot to add this option when I rewrote the depth subcommand.  I will add it so that existing pipelines do not fail.

However note that the reference is no longer needed as `depth` no longer uses the "mpileup" interface for reporting.  Also, even with the older version, `--reference $REF` is just shorthand for `--input-fmt-option reference=$REF`, which is supported by both old and new samtools, so there is a common command line which can be used across all versions.

I'll fix it though to aid compatability.

**Comment by RandyHarr** [comment]
Thank you for the response and the workaround.  And all you do to keep the tools going.

How do you decode CRAMs without the reference spec?  When either the reference is not in the EBI servers (e.g. most of the working T2T models the past year and a half) or the tool cannot otherwise use the EBI servers for  the reference sequences? That is why we specify the reference; only when starting with CRAMs.  There are other cases, like this one now, where we seemingly have to fall back to samtools view on the CRAM and pipe it, uncompressed, into another copy of samtools.  But we find this often slower and error prone with large files (over 100x read depths on a WGS).

**Comment by jkbonfield** [comment]
The short answer is you don't... if you want the entire file back.

However, for depth you don't need to know the bases, just where they lie.  So CHR, POS and CIGAR string are sufficient to anchor each base to a location on the genome and compute depth.  Plus QUAL and MAPQ if you're doing quality based filtering.

CRAM is columnar, meaning you can decode some SAM columns without the others.  Eg try `samtools view --input-fmt-option required_fields=0x29 in.cram` and you'll see a cut down SAM file being produced with just the columns necessary.  No sequence necessary, which means no reference necessary either.  The old depth subcommand however was basically mpileup with a few columns removed.  It made it unnecessarily slow too, which is why we rewrote it from scratch.
