### ISSUE TITLE
ampliconstats Problem

### ISSUE THREAD

**Issue by jPontix** [samtools/samtools#1650]
Hi, I want to know the coverage of each amplicons.
I have the list of my primers, so based on the primers sequences information I created the .bed file
```
chr7	55248957	55248984	p1f	+
chr7	55249173	55249194	p1r	-
chr7	55241584	55241612	p2f	+
chr7	55241767	55241796	p2r	-
chr7	55259375	55259404	p3f	+
chr7	55259569	55259589	p3r	-
chr7	55242379	55242408	p4f	+
chr7	55242545	55242574	p4r	-
```

Then I ran samtools:

`samtools ampliconstats primers.bed *.bam > astats.txt` 

but I got the following error:

```
[amplicon] error: bad bed file format in line 1 of primers.bed.
(N.B. ref/chrom name limited to 1023 characters.)
samtools ampliconstats: Could not read file "primers.bed"
```
I do not know how to figure out this error, what am I doing wrong?

Thank you

**Comment by daviesrob** [comment]
Your BED file doesn't have enough columns in it.  There should be a score column between the primer name and the strand - for an example, take a look at the [manual page](https://daviesrob.github.io/www.htslib.org/doc/samtools-ampliconstats.html).  The score is actually ignored, but it has to be in there to follow the [BED specification](https://samtools.github.io/hts-specs/BEDv1.pdf#subsection.1.5).

Arguably the error message is a bit misleading as it points out a limit on the reference name length, when the actual problem is that it couldn't find enough columns in the input.

**Comment by jPontix** [comment]
Ok thank you.

I updated my bed file:

```
chr7	55248957	55248984	28	p1f	+
chr7	55249173	55249194	22	p1r	-
chr7	55241584	55241612	29	p2f	+
chr7	55241767	55241796	30	p2r	-
chr7	55259375	55259404	30  p3f	+
chr7	55259569	55259589	21	p3r	-
chr7	55242379	55242408	30	p4f	+
chr7	55242545	55242574	30	p4r	-
```

`samtools ampliconstats primers.bed aln_sorted.bam > astats.txt`

But another error comes up:

`samtools ampliconstats: SAM headers are not consistent across input files`

**Comment by daviesrob** [comment]
It looks like you hit this error because when ampliconstats [checks that the input SAM headers all match](https://github.com/samtools/samtools/blob/44b11db4/amplicon_stats.c#L1478), it fails to account for ones that were [skipped](https://github.com/samtools/samtools/blob/44b11db4/amplicon_stats.c#L1387) because they didn't appear in the BED file.  I suspect that is a mistake as everywhere else it checks `amps[r].sites` before trying to gather stats, which implies it should support primer lists that don't include every reference listed in the SAM header.

It shouldn't be too hard to fix this, but if you can't wait there are a couple of work-arounds you could try.  You could either add dummy amplicons into your BED file, so it mentions all the other references that could be in the SAM header; or you could remove the unwanted references from both the header and alignment sections of your BAM file.  The latter could be done, albeit not very efficiently, with something like this:

```
samtools index aln_sorted.bam
samtools view -H aln_sorted.bam | grep -v '^@SQ' > filtered.sam
samtools view -H aln_sorted.bam | grep '^@SQ' | grep -w -f <(cut -f 1 primers.bed | sort -u | sed 's/^/SN:/') >> filtered.sam
samtools view -u -M aln_sorted.bam `cut -f 1 primers.bed | sort -u` | samtools sort -n - | samtools fixmate - - | samtools sort -O sam - | grep -v '^@' >> filtered.sam
samtools ampliconstats primers.bed filtered.sam > astats.txt
```

**Comment by jPontix** [comment]
It works. Thank you.

**Comment by JHarrisonEcoEvo** [comment]
A bit late here, but I have been getting this same"samtools ampliconstats: SAM headers are not consistent across input files" 

Apologies but I am not quite following the explanation provided above: "it looks like you hit this error because when ampliconstats checks that the input SAM headers all match, it fails to account for ones that were skipped because they didn't appear in the BED file". Could you explain what this means? Is it that the headers from the sam file are not in the bed file...and, if so, wouldn't this happen fairly regularly? 

Thanks. I might be able to resolve my issue with some digging, but I am having a hard time interpreting this error message.

**Comment by jkbonfield** [comment]
It means you have a BED file with a subset of the chromosomes listed in the `@SQ` headers, and not all of your input BAM files share the same list of SQ headers.

The obvious fix for this is to ensure that all of your input files are aligned to an identical reference.  Without that even if we could get the software to work, you'll find it hard to draw any conclusions between the relative stats between files.  (And if you don't want to compare between files, just do ampliconstats one file at a time and you'll avoid the issue also.)

**Comment by daviesrob** [comment]
Actually, this can happen with only one input file, for example:

```
$ ./samtools ampliconstats test/ampliconclip/ac_test.bed test/ampliconstats/mixed_clipped.sam 
# Summary statistics, used for scaling the plots.
SS	Samtools version: 1.16.1-22-gaddfc28-dirty
SS	Command line: ampliconstats test/ampliconclip/ac_test.bed test/ampliconstats/mixed_clipped.sam
SS	Number of files:	1
SS	Number of amplicons:	vir1	2
SS	Reference length:	vir1	800
SS	End of summary
# Amplicon locations from BED file.
# LEFT/RIGHT are <start>-<end> format and comma-separated for alt-primers.
#
# AMPLICON	REF	NUMBER	LEFT	RIGHT
AMPLICON	vir1	1	31-54	386-410
AMPLICON	vir1	2	321-342	705-726
samtools ampliconstats: SAM headers are not consistent across input files
```

It's also quite likely if, say, you're doing genotyping by sequencing, you aligned to a standard Human reference but you only designed primers for a subset of the chromosomes.  I think it's just an oversight that this isn't working, and shouldn't be too difficult to fix.

**Comment by JHarrisonEcoEvo** [comment]
Great, thanks for the explanation! That makes sense to me.
