### ISSUE TITLE
samtools merge -> 'No @HD tag found'

### ISSUE THREAD

**Issue by Sarah-Elna** [samtools/samtools#1651]
#### VERSION
- samtools 1.15.1
- Using htslib 1.15.1

 #### ENVIRONMENT
- OS: Linux 3.10.0-1160.15.2.el7.x86_64
- machine architecture: x86_64
- compiler (run `gcc --version` or `clang --version`)

#### STEPS
I am working with a gwf workflow on a windows computer running Linux with WSL.
I am trying to use samtools merge, but keep getting 'No @HD tag found.' in my error logs.
I then tried running the commands one by one with a single test file from start to finish. I get the same error when running the following code as an interactive job:

samtools merge -f '/home/sarahe/Dypsis_Chloroplast_Phylogeny/BSc/02_Coverage/Dypsis_acaulis_161017-1_S21_L001_all.bam' '/home/sarahe/Dypsis_Chloroplast_Phylogeny/BSc/02_Coverage/Dypsis_acaulis_161017-1_S21_L001.bam' '/home/sarahe/Dypsis_Chloroplast_Phylogeny/BSc/02_Coverage/Dypsis_acaulis_161017-1_S21_L001_up.bam'

I have seen a similar problem in a previous Issue, but could not find a resolution to the issue ( samtools merge fails with [trans_tbl_add_hd] No @HD tag found. #475 ). If I am missing somthing obvious, please inform me of it.

**Comment by Sarah-Elna** [comment]
The way I ended up fixing this was by installing BamUtil, which has PolishBam where you can run the command:

bam polishbam --in file_no_header.bam --out  file_with_header.bam --HD "@HD	VN:1.3 SO:coordinate"

I ran this before the samtools merge, and now it works.

**Comment by jkbonfield** [comment]
Prior to e066deb7f40245578f308c616db1ee23d4e83655 (added in #476) the error message would have been `[trans_tbl_add_hd] No @HD tag found` and it's a hard error causing failure.

Since then it is a warning and reports `[W::bam_merge_core2] No @HD tag found`.

The issue is already closed as you found a workaround, but I think also you are not running samtools 1.15 as you believe, as this bug was fixed in 1.3.
