### ISSUE TITLE
Compression presets for cram

### ISSUE THREAD

**Issue by matthdsm** [samtools/samtools#1656]
#### Is your feature request related to a problem? Please specify.
To make cram compression more user friendly, some algorithm presets for `--output-fmt-option` would be nice to have.

#### Describe the solution you would like.
Add preset options for `--output-fmt-option` as implemented in [scramble](https://github.com/jkbonfield) by @jkbonfield.
Examples for presets are in the README, with corresponding settings in the code.

https://github.com/jkbonfield/io_lib/blob/master/io_lib/cram_io.c#L6392-L6422
https://github.com/samtools/htslib/blob/develop/cram/cram_io.c#L5805-L5838

**Comment by jkbonfield** [comment]
This is already possible since 1.12.  Samtools accepts "fast", "normal", "small" and "archive" profiles which mostly match Scramble's definitions.

To use them you can do e.g. `--output-fmt-option small` or just add it to the comma separate listed after the format such as in `-O cram,small`.  The profiles are just predefined sets of options, so you can amend them with additional things, such as `-O fast,seqs_per_slice=3000`.

I thought I'd documented these, but they appear to be missing from the doc/samtools.1 file so I will task myself with adding this.

**Comment by matthdsm** [comment]
Awesome. Thanks!
Unrelated, but I see a mention of cram 3.1. Is this now officially supported by htslib?
