### ISSUE TITLE
Incorrect base quality of samtools mpileup with --min-BQ=0 but without --ignore-overlaps

### ISSUE THREAD

**Issue by yangdingyangding** [samtools/samtools#1663]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
Yes, I'm using 1.15.1.

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
Linux 5.4.0
  
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
  - x86_64   
  
- compiler (run `gcc --version` or `clang --version`)
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

Dear samtools staff,

Hello. Recently I used samtools to diagnose some BAMs along with IGV, and found some inconsistency of the mpileup function. Could you help us with this problem? Thanks!

Uncompress this [test_sam.zip](https://github.com/samtools/samtools/files/8837284/test_sam.zip) and put test.sam at the working directoy.

Run `samtools view test.sam` gave the following (only a read pair whose two ends overlap with each other):

<pre>
SRR2130089.4032033      99      chr8    28190664        60      124M    =       28190738        198     AAGCGATTCTCCCGCCTCAGCCTCCTGAGTAGCTGGGATTACAGGCACCCGCCGCTGCTGATTTTTGTATTTTTAGTGGAGATGGGGGTTTCACCATGTTGGTCAGGCTGGTCTCGAACTCCTG    CCCCCGGGGGGGGGGGGGGGGGGGGGGGGCGGGGGGGGFGGGGEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCGGGGGGGEGGGGGGGGGGGGGGGEGGGGGGGGGGG    X0:i:1  X1:i:0  MC:Z:124M       MD:Z:59A17A19A26        PG:Z:MarkDuplicates     RG:Z:GSM1833283XG:i:0   AM:i:37 NM:i:3  SM:i:37 XM:i:3  XO:i:0  MQ:i:60 XT:A:U
SRR2130089.4032033      147     chr8    28190738        60      124M    =       28190664        -198    AGTGGAGATGGGGGTTTCACCATGTTGGTCAGGCTGGTCTCGAACTCCTGACCTCAGGTGATCAACCCACCTTGGCCTCCCTAGATGCCGGGATTACAGGCATGAGCCACCGCTCCCAGCCTTT    EGGGGGGGGGGGGEGGGGGGFGFGGGGGGGGGFGGFGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGEGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCBCBC    X0:i:1  X1:i:0  MC:Z:124M       MD:Z:3A19A59A40 PG:Z:MarkDuplicates     RG:Z:GSM1833283 XG:i:0 AM:i:37  NM:i:3  SM:i:37 XM:i:3  XO:i:0  MQ:i:60 XT:A:U
</pre>

But `samtools mpileup --min-BQ=0 test.sam | grep 28190741` did not  report the base qualities in the overlap region correctly:

<pre>
[mpileup] 1 samples in 1 input files
chr8    28190741        N       2       Gg      m!
</pre>

Run `samtools mpileup --ignore-overlaps test.sam | grep 28190741` reported the correct base qualities:

<pre>
[mpileup] 1 samples in 1 input files
chr8    28190741        N       2       Gg      GG
</pre>

However, this is not documented in samtools mpileup (http://www.htslib.org/doc/samtools-mpileup.html), and is also inconsistent with the description for --min-BQ that "Note base-quality 0 is used as a filtering mechanism for overlap removal. Hence using --min-BQ 0 will disable the overlap removal code and act as if the --ignore-overlaps option has been set."

**Comment by jkbonfield** [comment]
You are correct in your analysis of how it's working.  Note it only sums the qualities when they agree.  When they disagree it uses 0.8*qual for the highest quality base.  I don't understand the 0.8 bit.  It doesn't match the mathematics of using phred scaled probabilities for independent events.

I'm with you on that option being totally confusing.  It baffled me when I first saw it too.  By default it ignores overlapping bases when producing the output, unless you explicitly add `--ignore-overlaps` in which case it no longer ignores them!  I can't begin to understand the logic that went into choosing that option name, but I'm assuming it was intended to mean "skip the overlap-removal algorithm" and the description in the usage statement implies that way of thinking.

I did think about changing it once I realised what it did, but thought it may cause even more confusion not to mention breaking scripts as it's been this way since 2013 and looks like it arrived before the github PR and review model was in use.  Thinking again, we could leave both an old and a new name.  Maybe we could get away with a very similar renamed option.  Eg `--ignore-overlaps-removal`.  The latter is longer, but is a double-negative so at least has the benefit of making people pause to think and maybe read the description, instead of just taking the option at face value and making wrong assumptions.

(Note `-overlaps-` instead of `-overlap-` isn't ideal, but GNU getopt-long permits `--ignore-overlaps` to be a synonym for `--ignore-overlaps-removal` as it has prefix matching on long options, so this would be a trivially forwards-compatible path.  Alternatively we just add a direct synonym which also works)
