### ISSUE TITLE
"[E::bam_write1] Positional data is too large for BAM format"

### ISSUE THREAD

**Issue by Zeyu-An** [samtools/samtools#1669]
Hello, 

samtools 1.15.1
Using htslib 1.15.1
Linux 2.6.32-754.29.1.el6.x86_64
 
My reference genome is 27Gb. And per chromosome is over 2Gb.

I used bowtie to mapping small RNA, and it could get the SAM file succefully.

But when I tried to covert SAM to BAM by using `samtools view -bS -@ 16 file.sam > file.bam`, the program reminded the following message: 
[E::bam_write1] Positional data is too large for BAM format
samtools view: writing to standard output failed.

What should I do for this? 

Thanks.

**Comment by mp15** [comment]
BAM uses a signed 32 bit integer to hold position data. Thus about 2 billion is the largest chromosome size it can represent. BAI has similar issues.
We recommend you select SAM for when you need human readable data and CRAM for your on disk format. Neither of these formats have the same problem as BAM.

On 18 Jun 2022, at 06:50, Zeyu An ***@***.***> wrote:

﻿

Hello,

samtools 1.15.1
Using htslib 1.15.1
Linux 2.6.32-754.29.1.el6.x86_64

My reference genome is 27Gb. And per chromosome is over 2Gb.

I used bowtie to mapping small RNA, and it could get the SAM file succefully.

But when I tried to covert SAM to BAM by using samtools view -bS -@ 16 file.sam > file.bam, the program reminded the following message:
[E::bam_write1] Positional data is too large for BAM format
samtools view: writing to standard output failed.

What should I do for this?

Thanks.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_samtools_samtools_issues_1669&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=G0VcQIYnuldSWxHRQBhdPRFs_mQMJZ2jKzdJVtGelRQ&m=JYbhiwS9MoFbYIQsU37tbd8Q9Em1KvDFPelwF8SJwqekPcIRwfpTmZQ6mMSAdsHR&s=8B8LC7cY6Mt9MO7HZovWzz8PYRiGUk7VMecU2Gw-uqw&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAMUCWN7OUHEQAWHN6YQFH3VPVPQVANCNFSM5ZEHJ3FQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=G0VcQIYnuldSWxHRQBhdPRFs_mQMJZ2jKzdJVtGelRQ&m=JYbhiwS9MoFbYIQsU37tbd8Q9Em1KvDFPelwF8SJwqekPcIRwfpTmZQ6mMSAdsHR&s=V70dmQejDZQtcOEyf1VX57uXvYdW0eizlgu8Ko-Ebqc&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by daviesrob** [comment]
Sadly there isn't a good solution for BAM at the moment.  For now, the workarounds are:
1. Break your large chromosome at some convenient point(s) so no part is longer than 2Gbases.  This will give the best compatibility with other tools.
2. Use the sam.gz output format, which will work for long chromosomes in samtools; but be aware that the files you make may not be usable in other tools.

There's some discussion in samtools/hts-specs#655 on how the limitations in BAM could be better worked around.  I expect this will be revisited once that looks like it's heading to a consensus on how the changes would work.
