### ISSUE TITLE
libcrypto

### ISSUE THREAD

**Issue by tanasa** [samtools/samtools#1686]
I am using an Apple M1 Pro with macOS Monterrey, I am installing samtools via conda, however I am getting the error that is listed below when I do start "samtools". How shall I fix it ?

```
(base) PHF0CV41YY:PROJECT_SEVILLA tanasab$ conda install -c bioconda samtools
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

(base) PHF0CV41YY:PROJECT_SEVILLA tanasab$ samtools
dyld[27091]: Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /Users/tanasab/opt/miniconda3/bin/samtools
  Reason: tried: '/Users/tanasab/opt/miniconda3/bin/../lib/libcrypto.1.0.0.dylib' (no such file), '/Users/tanasab/opt/miniconda3/bin/../lib/libcrypto.1.0.0.dylib' (no such file), '/usr/local/lib/libcrypto.1.0.0.dylib' (no such file), '/usr/lib/libcrypto.1.0.0.dylib' (no such file)
Abort trap: 6

```

**Comment by mp15** [comment]
Could try installing a version of OpenSSL that matches the version samtools was compiled with?Conda should have done this but apparently it didn’t. Probably because whoever omitted packaged it for conda forgot or hit a bug. 


-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by tanasa** [comment]
I have installed samtools as it is described in : https://anaconda.org/bioconda/samtools

It looks that the samtools version is 1.6. I do not know which version of openSSL has been used.

**Comment by jmarshall** [comment]
You can query the package version installed via the usual `conda list samtools` command.

I suspect the problem is that you have not activated the **conda-forge** channel as described in the [bioconda documentation](https://bioconda.github.io/#usage), as not having that activated will prevent more recent samtools versions being selected, as bioconda builds them using dependencies from conda-forge.

Note also that bioconda on Apple Silicon is a work in progress (see bioconda/bioconda-utils#706 et al); at present you're using the x86 macOS packages via emulation.

**Comment by jkbonfield** [comment]
This is really a [Conda packaging issue ](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/samtools)rather than samtools one.  I would recommend raising an issue at https://github.com/bioconda/bioconda-recipes
