### ISSUE TITLE
Conan package for samtools

### ISSUE THREAD

**Issue by Krakada** [samtools/samtools#1729]
Hi,

I'm contacting you because I'd like to know whether samtools is available as a [Conan](https://conan.io/) package, or at least if there is any "unofficial" conanfile.py recipe that could be used as a starting point (I'd like to pack version 1.3.1, so I doubt that I could find the right recipe out of the box).

Thanks in advance for your help,

**Comment by daviesrob** [comment]
It isn't at the moment, and I don't know of any `conanfile.py` recipes for it.  If you were to do this properly, you'd probably want to make three packages - samtools, htslib and htscodecs (needed for samtools and htslib versions 1.12+).

Why are you using version 1.3.1?  It's quite old and includes quite a lot of bugs that have been fixed since it came out.  I'd strongly recommend using the latest version if you can.

**Comment by jkbonfield** [comment]
Are people factoring in the cost of known bugs in their impact assessment?  These include security related issues, and data validity (eg checking for CRC errors in bam files).

Any cost-benefit analysis needs to include both cost and benefit!

**Comment by Krakada** [comment]
You're preaching to a converted here :) I'm already pushing in that direction, but actually, having a Conan package (even just for the latest version) would greatly help.

I have a small side question: is there a way to somehow force samtools (latest version) to statically link against zlib? I'm not familiar with auto tools, and did not find a clean way to achieve that.

Thanks in advance.

**Comment by daviesrob** [comment]
I don't think we have much appetite for making a Conan package at the moment (it looks a bit complicated).  We may revisit this if there's popular demand though.

Of course, if any conan developers want to add the packages themselves then we can give advice on the best way to build them.  Please do let us know if you want to try this.
