### ISSUE TITLE
samtools cat fails if the first argument is a stream

### ISSUE THREAD

**Issue by julianhess** [samtools/samtools#1731]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib]

Yes, v1.16.1

 #### Please describe your environment.

Ubuntu 20.04.2 LTS

```
$ uname -sr
Linux 4.4.0-210-generic
$ uname -m
x86_64
$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

If you attempt to specify a stream as the first argument to `samtools cat`, it will fail. The simplest possible example:

```
$ samtools cat <(cat example.bam)
[E::bam_hdr_read] Invalid BAM binary header
[bam_cat] ERROR: couldn't read header for '/dev/fd/63'.
```

(Obviously, in a real-world use case, the stream would be something nontrivial, like another samtools command.)

It appears that this is due to the fact that `samtools cat` attempts to infer the format of the first argument by running it through `hts_get_format`:

https://github.com/samtools/samtools/blob/ce9b492b131e271bcff28b449c7bbc019a612abe/bam_cat.c#L548-L571

This consumes the first few bytes of the stream, which makes it impossible to subsequently read the header,

https://github.com/samtools/samtools/blob/c29d3123c0f9d4c1bd3adca8d9bbd3d9c4d42446/bam_cat.c#L376

since `bam_hdr_read` assumes that the file pointer is set to the beginning.

I would recommend adding options `-B`/`-c` to `samtools cat` to allow the user to explicitly specify whether the inputs are BAM or CRAM, respectively. I would also explicitly raise an error message when a user attempts to pass a stream as the first argument without explicitly specifying the input file format. I am happy to make these changes myself and submit a PR.

For now, I am hacking around this problem by creating a dummy empty BAM consisting solely of the header of the first file I'm concatenating, and passing that in as the first argument, e.g. 

```
samtools view -uH file1.bam > dummy.bam
samtools cat dummy.bam <(mytool file1.bam) ... <(mytool fileN.bam)
```

**Comment by jmarshall** [comment]
Your analysis that this is due to the first file being opened, closed, and then opened again is correct.

But a better fix would be to refactor `bam_cat()` and `cram_cat()` (and also `cram_cat_check_hdr()` which might be a little harder) to take the already-opened first file handle as an argument in addition to the list of filenames, and reuse it instead of reopening the first filename. No explicit input format option would be required (indeed `-b` is already taken anyway).

Probably the best way to do that would be to have `main_cat()` open it as an `hFILE *` and use `hts_detect_format2()` directly on that. Then `bam_cat()` could use `hts_hopen()`, and `cram_cat()` could probably be refactored to use `cram_dopen()`, to get a file handle of the kind they respectively need.
