### ISSUE TITLE
samtools filter by single reads

### ISSUE THREAD

**Issue by MonaLiu421** [samtools/samtools#1768]
Hi, thanks for developing such a wonderful tool. It did help me a lot in my work. But now i have a problem, i wanna keep paired reads in my BAM files, so i run the command `samtools view -bF 8 old.bam > new.bam`.But there are single reads in the new.bam.

![image](https://user-images.githubusercontent.com/45484925/207056829-301e80dc-03c7-403e-b742-c3ac306638f5.png)

 By the way, the old.bam have already filterd by alignment length. I just wanna get a new.bam that is filtered by length and contains mate and paired reads. Could you give me some advice?

**Comment by daviesrob** [comment]
You need to use [`samtools fixmate`](https://www.htslib.org/doc/samtools-fixmate.html).  As you've noticed, `samtools view` does not try to adjust the flags when it filters reads - it's not easy to get them right, and often unnecessary.  If you do need accurate flags, `fixmate` will do the extra work needed to make them consistent.

Note that `samtools fixmate` requires a name collated input file.  It looks like the data in your screenshot is grouped by name.  If that's true for the whole file then you can just run it though `fixmate`; otherwise you will need to use `samtools collate` or `samtools sort -n` to get it in the right order.

**Comment by MonaLiu421** [comment]
Thanks a million, my problem is solved.
