### ISSUE TITLE
mpileup seem to ignore the flags passed to --ff

### ISSUE THREAD

**Issue by LukaP-BB** [samtools/samtools#1791]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.

samtools 1.16.1
Using htslib 1.16
Copyright (C) 2022 Genome Research Ltd.

I can update with the wall of text coming after if necessary, but will skip for now for concision.

 #### Please describe your environment.
- OS : `Linux 5.15.0-60-generic`
- machine architecture `x86_64`
- compiler : installed via conda (`conda create -n samtools -c bioconda samtools=1.16`)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I have a bam file with reads flagged as duplicate by `picard MarkDuplicates`. 
I still want to have all the reads appearing in the pileup, so I passed the option `--ff UNMAP,SECONDARY,QCFAIL,DUP`.
The reads appeared to still be filtered.
```
└─> samtools depth test_data/alignment_dup.bam -r chr1:117624144-117624144 -g 3340
chr1    117624144       1206
└─> samtools mpileup     test_data/alignment_dup.bam     -A -Q 0 -d 0 -R     -r chr1:117624144-117624144     -f ~/Projet/genome/hg38.fasta     --ff UNMAP,SECONDARY,QCFAIL,DUP  
[mpileup] 1 samples in 1 input files
[mpileup] Max depth set to maximum value (2147483647)
chr1    117624144       G       32      ,$,$,$,$,$,$,$,.....$,$.,,.,.,..,,.,,,,,,       :::::::AEEEE!S!EE!EAiAAEE!eEEEiE
```

Instead of having a pilup depth of 1206, I have 32

Am I doing something wrong in my mpileup command or is this a bug ?

**Comment by jkbonfield** [comment]
`samtools mpileup --ff` is filtering data out.  From the usage:

```
  --ff, --excl-flags STR|INT  filter flags: skip reads with any of the mask bits set
                                            [UNMAP,SECONDARY,QCFAIL,DUP]
```

By specifying `--ff UNMAP,SECONDARY,QCFAIL,DUP` you are simply reiterating the default set to filter.  You need `--ff 0` if you wish to change the default list to nothing (no filtering).

**Comment by LukaP-BB** [comment]
Yes, the `-g` was used to explicitely turn off most of the filters in `samtools depth`
Then the documentation is a bit confusing, because I tried with `--rf UNMAP,SECONDARY,QCFAIL,DUP` and still got my reads filtered, while if I understand correctly, `--rf` is supposed to do the opposite of `--ff`
I also tried `--rf 3340` which should do the same as `-g 3340`, but nope.
So yeah, big missunderstanding on my end, that could maybe justify to make the documentation more explicit ?

**Comment by jkbonfield** [comment]
Unfortunately these command line interfaces were developed a long while ago and without too much consistency, so each subcommand works slightly different.  It's not something we can fix as it'd break pipelines and scripts. :/

Some commands, such as depth, have a default exclusion list and the option to change it is simply ORing on new values, so there is a second option than ANDs off values to remove them again (-G vs -g).  Others such as mpileup having a default exclusion list use the command line option to SET the bit pattern, so you can use that same option to nullify the default setting.  This disparity is rather annoying sadly.

I'm unsure however how best to document this mess of options.  Mpileup man page currently states:

```
       --rf, --incl-flags STR|INT
                 Required flags: include reads with any of the mask bits set [null]

       --ff, --excl-flags STR|INT
                 Filter  flags:  skip  reads  with  any  of  the  mask  bits  set   [UNMAP,SECONDARY,QCFAIL,DUP]
```

`--rf` has no default option, and `--ff` has the usual default for secondaries etc.  You passed in `--ff`, which it did exactly as documented.   What would you suggest for improving this?  It sounds pretty water-tight in description already, but obviously there's an ambiguity somewhere if you interpretted it differently.

What's not stated in the docs however is what happens if you specify both.  If we ask to both exclude and include the same values, which is a logical impossibility, then it ought to clarify the precedence rules.  That's a failure of documentation, but it wasn't what your command line was triggering.  Or are you saying you previously tried it and rejected it as it didn't work?

**Comment by LukaP-BB** [comment]
Thanks for taking the time to answer my questions where you could have simply said RTFM, I appreciate it.

Using the option `--ff 0` is doing exactly what I need, and I believe it could be specified in the docs in a way similar to this : 
```
       --ff, --excl-flags STR|INT
                 Filter  flags:  skip  reads  with  any  of  the  mask  bits  set   [UNMAP,SECONDARY,QCFAIL,DUP]. 
                 Pass 0 to this option in order to deactivate all filtering
```

But then, if I understand correctly, passing `--rf 4095` (eg require all flags) should do the same as `--ff 0`, or maybe I'm still missunderstanding some logic ? Because the outcome is different : 

```
└─> samtools mpileup     test_data/alignment_dup.bam     -A -Q 0 -d 0 -R     -r chr1:117624144-117624144     -f ~/Projet/genome/hg38.fasta     --rf 4095
[mpileup] 1 samples in 1 input files
[mpileup] Max depth set to maximum value (2147483647)
chr1    117624144       G       32      ,$,$,$,$,$,$,$,.....$,$.,,.,.,..,,.,,,,,,       :::::::AEEEE!S!EE!EAiAAEE!eEEEiE
# vs
└─> samtools mpileup     test_data/alignment_dup.bam     -A -Q 0 -d 0 -R     -r chr1:117624144-117624144     -f ~/Projet/genome/hg38.fasta     --ff 0
[mpileup] 1 samples in 1 input files
[mpileup] Max depth set to maximum value (2147483647)
chr1    117624144       G       1206    ,$,$,$,$,$,$,$,$,$,$,$, [ skipped the rest of the line]

**Comment by jkbonfield** [comment]
I think this is indeed confusing, although like a lot of things I wonder if we can fix it without breaking things.  I think yes, as the only things we'd break are where people have logical impossibilities right now.  (Do people do that?  Maybe...)

Looking at the [logic in the code](https://github.com/samtools/samtools/blob/develop/bam_plcmd.c#L393-L394) I see:

```
        if (ma->conf->rflag_require && !(ma->conf->rflag_require&b->core.flag)) { skip = 1; continue; }
        if (ma->conf->rflag_filter && ma->conf->rflag_filter&b->core.flag) { skip = 1; continue; }
```

Basically everything is accepted unless it is filtered out.  The `--rf` option, in `rflag_require`, is negated in order to turn it into a "discard if not-found" operation.  Hence there's no logic here of them being opposites and one overwriting the other as both are implemented in terms of discarding data.

This is ambiguous and I totally accept you could (and probably should) argue that if you've specified you wish to include secondary reads then this should override the defaults of excluding them.  I'll see what can be done to resolve this.

**Comment by LukaP-BB** [comment]
Thanks a lot for the explanations !

At least it is clear for me for now :+1: 

Since the problem is fixed on my end, should I close the issue or let it open until you've seen what can be done ?

**Comment by jkbonfield** [comment]
Leave it open please until we decide what fix to do (either docs or code logic).

**Comment by jkbonfield** [comment]
Exploring some more on this,  I see assuming `--rf` is a way to negate `--ff` option is doomed to failure.  Even with `--ff 0 --rf 0xffff` I don't get all the reads, because I have some records that have FLAG of 0 and they're *excluded* by `--rf 0xffff`.  So enabling required-flags isn't really going to be a reliable way to remove them from the filter-flags option.  You'd just replace one gotcha with another.

I think the correct solution is to fix the documentation to explain what it actually does, rather than paraphrase it in ambiguous language.
