### ISSUE TITLE
Excessive memory usage on samtools merge

### ISSUE THREAD

**Issue by Poshi** [samtools/samtools#1800]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
samtools 1.17
Using htslib 1.17

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
Linux 2.6.32-754.10.1.el6.x86_64
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
x86_64
- compiler (run `gcc --version` or `clang --version`)
gcc (GCC) 9.3.0
(not sure if it was the one used to compile this version, as it was not compiled by me)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
I'm trying to merge a set of aligned and sorted bam files that comes from the same experiment. I'm using
```
samtools merge -c -p -@ 4 merged.bam 0.bam ... 67.bam
```

Being a merge, I expect it to use a ridiculously low amount of memory, but my surprise comes when I see it is using a very sensible amount of memory:
```
$ ps -p 12330 -o size
   SZ
181384792
```
Which is around 173GiB.

Obviously, I understand that I cannot expect zero (the image itself, libraries, runtime, buffers...), but more than a single GiB for a merge seems overkill. Is it a bug or I should be doing things differently?

**Comment by Poshi** [comment]
I think I start to see the root cause of this behavior. I tried the same procedure with some old version of samtools, memory explodes. I tried with Picard MergeSamFiles, memory exploded. In all cases, memory explode even before creating the output file. This points me to some kind of setup. And a plausible setup would be to load the sequence dictionary to know which is the first chromosome/scaffold/contig to output.
It happens that those particular alignments are of Abies alba, a nice christmas tree whose published genome have 37192295 contigs and the corresponding dict file weights 6GiB (and the fai file "only" 1.4GiB). Could it be that loading this entire file into memory somehow multiplies the raw 6GiB of data into something a lot bigger?
Then, the bug would be the assumption that the references always have a manageable number of contigs and that they can be loaded entirely into memory. The solution would be to load the reference contig by contig, when needed.
Does it make sense?

**Comment by jkbonfield** [comment]
There is a step in merge which validates the SAM headers are compatible between all files, because people just love to try the impossible and merge data with SQ headers in different orders. (Why?  I've absolutely no idea!)  So it's helpful to be able to load the entire headers up.

Even so, 68 bams consuming 173GiB implies 2.5G per header.  That's ~73 bytes per contig.  Sounds like the right ballpark.

Attempting to partially load the headers and do one contig at a time is problematic and would require a huge rewrite as our header API isn't designed to do line-by-line processing, plus it would drop support for those (IMO admittedly broken) scenarios of differing contig ordering.  I think your best bet here is step-wise merging.  Merge 10 files at a time, then merge the resulting 7 files together.  That would limit memory usage to under 30GB.

Or... don't merge until you get a better assembly!  That's just an insane number of contigs to want to be storing in BAM format.  I was going to suggest that it's pointless to have that many small contigs and for the tiny contigs you're better off adding them in as scaffold SQ lines instead to reduce the number of contigs you have to deal with, but hunting for 37,192,295 shows that's actually the number of scaffolds!  The contig count is 45,280,944 though, so most scaffolds are 1-contig affairs.  Clearly this needs better data to produce more scaffolds out of those contigs, or alternatively if the single contig scaffolds are also very short then maybe almagamate them together into "misc" scaffolds to reduce the number down.  (They may even be environmental contamination if no match can be found with the primary contigs.)

**Comment by Poshi** [comment]
Well, technically, the header validation could be done in the same way as the merge itself: read the first SQ line of each file and, if they match, go to the next.
The main issue here is that the current architecture makes it difficult to change to this new procedure. Maybe a flag to bypass the checks (under responsibility of the user) could help in those cases, just use the header of the first file and proceed like the check passed. That should lower the memory usage to a single copy of the header (it is still too much, but it would be more easily manageable).

Breaking the scenarios of different contig ordering should not be an issue: you have to randomly choose an ordering and data won't come in the proper order in some of the files, so the merge should fail anyways.

In any case, I can try to reduce the number of files to merge. Even go single-file (at the cost of longer mapping times). But I cannot wait until I have a better assembly, I need to do this whole procedure before 10 days for QC purposes.

As you said, about 10% of sequence data is distributed in 106bp long scaffolds. That's non-sense. I'm thinking on different ways to solve the issue. Plainly slashing 30% of the reference to get the number of scaffolds down a around a million. Or concatenating the small scaffolds in a single, big scaffold, with the source scaffolds separated by Ns. Trying the pipeline in a non-parallel way to avoid the merge entirely and prey for samtools markdup not to scream to loud. Jumping from the window could also be an option to end all of this suffering XD

Thanks for the diagnosis, it gives me another way to tackle the issue. And, in any case, consider any solution on your side, as it could help everybody that works with this kind of crappy data. Rewriting the header processing code in samtools 3 or adding a flag to avoid checks are possibilities :-)

**Comment by jkbonfield** [comment]
I was hoping maybe the `samtools merge -h header.txt` option would solve this, but it looks like the code opens and caches each header anyway.

Totally untested - just a very quick perusal of the code - you could replace [this line ](https://github.com/samtools/samtools/blob/develop/bam_sort.c#L1195 ) with

```
    sam_hdr_destroy(hin);
    hdr[i] = NULL;
```

Plus remove the `sam_hdr_destroy(hdr[i]);` from the end of the file.  This would break any region based work so bed files would cease working, and it's break merging of SAM files too, maybe CRAM (although that may just work and keep its own copy of the header so not resolve it).  However I *think* merging of BAM without any bells or whistles being applied would work.

Like I say, I haven't tested it yet, but may give it a try if I get some spare time.  You have the data though and the change is literally 2-3 lines of code to see.  Obviously a full change would be much more as we'd need to stop everything else crashing and burning messily, but there may be a route to holding just 1 header in memory.

It's still parsing the header per file though and holding a translation table in memory per BAM, so it can handle differing sets of SQ lines per file.  This is messy and it's threaded throughout the core merge algorithm so isn't trivial to just skip and do a "fast mode" short of a reimplementing a second version.    It looks though like it's int to int mapping, so ~10 GB worth of translation tables.  Still a lot less than the full header.

**Comment by jkbonfield** [comment]
A couple more thoughts.

> As you said, about 10% of sequence data is distributed in 106bp long scaffolds. That's non-sense. I'm thinking on different ways to solve the issue

There may be some benefit to just rejecting any scaffold or contig smaller than a certain size and labelling those reads as unmapped.  For sure if a read isn't forming a significant cluster with other reads then we can hardly call them "assembled".  Exact matches piling on top of each other doesn't really count either in my book as if they don't extend then it's highly likely just some artifact.

However in our meeting we did think of another cheaty solution which may resolve this.

If we have identical headers, then it's possible to use `samtools cat` to concatenate them together (basically strip off the headers and join the rest of the BAMs together), giving a single partially sorted BAM, and then pass that into `samtools sort`.  It may not be as efficient as a merge, but the sort bit can be parallelised and it may end quick enough.

**Comment by Poshi** [comment]
The cat and sort sounds like a possibility. Currently, I'm splitting the FastQ file for parallel alignment and sorting the end, so only a merge is needed. But it could be delayed to the next step and perform the sort of everything at once. Performance will suffer, but it could work.

Regarding on how to process the data, we are having an internal discussion, but nothing decided yet. From joining all the small contigs into a single one with interleaved Ns to mutilating the reference with a cutoff (at 1kbp or at 2x read length). But I would really prefer to be able to use the public reference as is. That will solve issues when someone downstream decides to use the public reference instead of the specially prepared one.

**Comment by Poshi** [comment]
It looks like you nailed the issue. I managed to run the merge with half the files (34 input BAMs) without overflowing the node memory (256GiB). I also tried the cat+sort approach. With 8 CPUs, the cat ran in 9m39s using up to 9684900K (~9GiB), and the sort ran in 94m59s using up to 24252088K (~23GiB). I would expect similar merge and cat times, so this is adding up a sensible amount of time... but it worked.
Next issue in the pipeline is with MarkDuplicates and the final output format... MarkDuplicates complains about the header size:
```[E::cram_write_SAM_hdr] Header is too long for CRAM format```.
This cannot be solved by any patch other that changing the format. I'll try changing that format to BAM for these samples and see where it goes.

**Comment by jkbonfield** [comment]
I'm not sure I understand this.

Which suggestion nailed it?  Is your test of 34 BAMs with the few lines of code I suggested changing?  If this works, then we'll need to think more about how to do it in an official capacity. (Lots more error checking, documentation, etc).  Sort splits to files and merges them, so we ought to be able to bypass some of the early checks and call the underlying algorithm, but I'd need to experiment.

Also I don't understand the cat+sort.  It's not at all efficient to try this in two steps.  As you did, I'm surprised it took 9m39s to cat.  It's literally little more than file concatenation.  I assume it was mostly idle rather than CPU bound?  I wouldn't assume merge to be remotely close to cat for CPU - probably at least half the time of sort (as the merge bit is usually the slowest part).  One way of minimising overhead is using pipes - just cat | sort pretty much.

As for CRAM, I don't see what that has to do with MarkDuplicates.  You're correct though that the size of header is a fundamental road block.  The additional M5 tags make things hard.  If you *really* need so many contigs and a hard requirement on using CRAM, then about all I can think of is using embed_ref=2 output option of the latest samtools (`samtools view -O cram,embed_ref=2`) and *maybe* it won't add M5 tags.  Not sure on that though...

**Comment by Poshi** [comment]
Sorry, I was not quite specific. You nailed the diagnostic that merge was loading the entire headers of all bam files and that was the cause of the high memory consumption. When the number of files was reduced (half the number of files, double the size), it fitted inside our nodes.

You also were right that a simple cat should work and a posterior sort would polish the file. This approach also worked without skyrocketing the memory usage. I tried it in two steps to check their resource usage individually (if some fails, I wanted a single program failure). When implemented in a pipeline, they would be connected thru pipes and using uncompressed output.
Regarding the times, despite having 8 CPUs, the cat run single threaded (real time ~= system time + user time). The sort took advantage of the multiple CPUs with a speedup of 3.2x.
I was not expecting that the merge were around half the time of the sorting process. That means that the time difference is not so big.

I didn't applied yet the code modifications you suggested. I prefer to use standard unmodified tools. In terms of explainability of what have you done with the data, using standard tools makes it easy; using custom tools makes it hard to support the results correctness.

Finally, The relation between CRAM and MarkDuplicates... well, I meant samtools markdup. I asked markdup to write a CRAM output, as it would be our final file in this pipeline. And markdup refused to create a CRAM. But when asked to do a BAM, it processed the input in less than 30 minutes (I didn't save the exact timing). Using CRAM at this stage is not a hard requirement, but it will be a potential hard requirement in the mid-future in the next pipeline, the one that gathers all experiments for a sample and generates an unified file for the whole sample. But, in any case and despite being a hard requirement, I'm pretty sure we can always use BAM if CRAM cannot handle it (because the alternative is not doing the work).
This is another thing to think about in the future: using 64-bit pointers in the CRAM format.

**Comment by jkbonfield** [comment]
64-bit sizes everywhere was a design for CRAM 4, but currently it's not being worked on due to lack of community interest (we need multiple implementations for major format revisions to be considered for acceptance).  It does need to be shaken up again.  Maybe once CRAM 3.1 is accepted (imminent) we can start working on version 4 again.

I'll look at ways to squeeze the header a bit further.

**Comment by jkbonfield** [comment]
So one thing you can try, with a modern samtools, is:

`samtools view -T ref.fa -O cram,embed_ref=2 -o foo.cram foo.bam`

If the BAM header has no M5 tags then CRAM will normally add them so they can be used to identify the appropriate external reference.  However with `embed_ref=2` it stores the reference in the CRAM file.  You could also try omitting `-T ref.fa` too and it'll either derive the ref from sequence MD:Z tags or via consensus.  Both of these will limit the size of header change.

Anyway, I don't think we have anything more to say on this matter.  Fundamentally enormous headers will always require enormous memory without a major tooling rewrite, which we don't have time to work on.  It sounds like you have suitable workarounds now.
