### ISSUE TITLE
samtools 1.14 mpileup excludes duplicates - not documented behavior

### ISSUE THREAD

**Issue by gevro** [samtools/samtools#1801]
Hi,
samtools 1.14 mpileup excludes 'duplicate' reads, but this is not documented in the official documentation.

In my opinion, this should not be the correct behavior. The correct behavior should be to include all reads, and then the -rf and -ff flags control which reads are considered.

**Comment by jkbonfield** [comment]
It is documented, see `--ff` option at http://www.htslib.org/doc/samtools-mpileup.html#OPTIONS

Indeed the correct behaviour you suggest is already the way it is implemented.   To control whether or not duplicates are filtered you use the `--rf` and `--ff` option sas you recommend.  The misunderstanding here is that these don't default to zero.  I think it is correct that the default behaviour is to drop data that has been labelled as duplicate, as the purpose of mpileup is presenting evidence to variant calling algorithms.

Also changing this now would break all sorts of pipelines, that rely on this assumption.

**Comment by gevro** [comment]
What I meant was that in my testing samtools mpileup seems to filter out duplicates by default, even without the -ff option set. Shouldn't the default be to *not* filter out duplicates?

**Comment by jkbonfield** [comment]
The purpose of mpileup is to present the evidence as it stands to variant callers and similar processing tools.  If we've done some QC and concluded some data is duplicated, then that evidence shouldn't be passed on to these tools.

Further more, changing this now would be very problematic.  Instead I suggest you add e.g. `--ff 0` to disable the removal of duplicates.  (Or, if you want to use duplicates, simply don't do duplicate marking before hand.)

**Comment by gevro** [comment]
Thanks I understand that - but the issue I think is that the documentation is not clear that this is the default behavior, unless I'm missing it somewhere.

For example, the --ff documentation says: "Filter flags: skip reads with any of the mask bits set [UNMAP,SECONDARY,QCFAIL,DUP]. Note this does not override the --incl-flags option. "

That makes it seem like those are *not* filtered by default. However, they are filtered by default.

I think somewhere at the top of the mpileup documentation it should say exactly which flags are filtered by default.

**Comment by jkbonfield** [comment]
Can you please check if #1802 clarifies your understanding on how these options work?

**Comment by gevro** [comment]
Thanks! I would suggest just a few things:
1) Specify flag integer or bit values, to be very specific which flags it is per SAM specs.
2) Does it also filter out supplementary alignments by default? If so add that.
3) Add example code to whichever option would allow this for how to force mpileup to include all reads, including those filtered out by default (assuming there is a way to do this).

**Comment by jkbonfield** [comment]
1.  Disagreed.  Samtools permits hex flags, but it's unfriendly and everywhere we document them we refer to them in symbolic form.  This is what is documented in `--ff` already and I don't want to obfuscate it by quoting numerics instead.
2. No, it doesn't filter out supplementaries, as they are a unique mapping (those bases only align to one location)
3. This can be done, and the fact you're unaware of how to do this indicates that the manual is still apparently not clear enough.

**Comment by jkbonfield** [comment]
I pushed an update based on your suggestions.  I haven't gone to the full extend of a complete command line, as I think this is a rather unusual case and definitely not something we recommend.  However I agree it's not immediately clear that you can remove filtering by specifying a new `--ff` option.

This isn't consistently applied in all samtools subcommands either.  Some work in an additive fashion so you can specify the same option multiple times and build up a list of filters.  So I have sympathy.  (Another "wouldn't start from here" scenario, but we are where we are!)

**Comment by gevro** [comment]
Thanks!

**Comment by daz10000** [comment]
I know this is closed, but I stumbled onto the discussion after realizing recently that mpileup wasn't faithfully dumping all of the aligned reads.  I've read all the docs, and to be honest, it's still utterly unclear how to ask samtools politely to just hand over all the alignments.  I would have loved a full example... do this to just get the raw data.  The data set I'm looking at has 149ish x coverage,  and in IGV, the reads are fairly evenly distributed fwd/rev.  The mpileup dump somehow by default only emits 80x overage and unfortunately severely skews the reads towards one orientation (I see no physical evidence of that in the data set), and as a consequence, it's highly misleading for downstream analysis.  I've played with the cmdline options for an hour and squeezed a few extra reads out of mpileup but it took me maybe 1.5 hours to get the full data set back.  Please please consider just adding a simple 'do X to get all the results out'.  Even instructions like `--ff INT|STR` are quite cryptic.

**Comment by whitwham** [comment]
Setting -ff to 0 should probably do it.  You are not the first person to have this problem (though on different tools).  We should probably go through the man pages again and improve the documentation.

**Comment by daz10000** [comment]
I almost filed a ticket on this, but it turns out I have an older version of samtools (1.10) installed.  If you're interested, I can reproduce this with current build and rerun the numbers, but what happened to my surprise was the `-ff 0` didn't do anything,  `-A` didnt' help.

To summarize the below,  I see 149 reads on the browser, nearly evenly fwd/rev.  There's nothing at all unusual about the region,  it has even dense coverage (illumina paired reads).  There's a perfect SNP right in the middle.

The default mpileup dump gets just 81 reads.  What's disturbing is that the orientation is quite skewed, so it looked suspicious.   The `-ff 0` option gets 7 reads back.  It was ignoring overlaps that restored most but not all the reads,  and the orientation goes back to random and it looks like a SNP should look.  I am happy to repeat this with current release if that's helpful, just let me know.  I guess the take home, is find all the flags and switch them off, but I found it quite disturbing that the default dump was quite misleading.


```
IGV 149 reads,  75+, 74-

default mpileup 
X       xxx896  T       81      C$CCCCCCCCCccCCCCCCCccCCCcCCcCCCCCCcCCCCCCCCCCCCCCCCCcCcCcCCcCcCCCCCCccCCCCCCCCCCC      HhhkmlSlAmHGlkUkFlEH2nlmEmiGennlinFlnnnlEfnnnknSmknkHmHmHGnFkHnmmFnEH1mJGnFElnnGf

--ff 0
X       xxx896  T       88      C$CCCCCCCCCCCccCCCCCCCccCCCcCCcCCCCCCCcCCCCCCCCCCCCCCCCCCCcCcCcCCcCcCCCcCCCccCCCCCCCCCCCC  

--ff 0 --ignore-overlaps
X       xxx896  T       141     CCCCCCCCCcCCccCCCCCCCccCCCccCCcccCcCCcCCCCccccCCCCcccccCCcCCCcCCCCcCccCccCCCCccCccCccccccCcCccCccc
```

**Comment by daz10000** [comment]
I wanted to give you accurate and useful information, so I built samtools and htslib from scratch with current code, and rerunning to see if this is still accurate. 

I can confirm that with current code, it produces just the 81 reads out of the 149 that IGV shows covering that section of the genome, but the read orientation is much more random than before.  With the 110 version, it was 67 fwd, 14 reverse, and now 43 fwd, 38 rev.  I assume that's a bug fix probably ?  So in summary,  still showing me less data than I am comfortable with, but at least not skewing (n=1) badly, so it wouldn't break my use base.

**Comment by whitwham** [comment]
I think you should open a new issue for this.

**Comment by jkbonfield** [comment]
As an aside, you may also find `samtools consensus -f pileup` to be a better starting point for some processing tools.  Being a newer command, it doesn't come with a decade of baggage behind it and we changed the defaults.  So it doesn't filter by flags (it's assumed you'll do an upfront `samtools view -F` before hand if you desire that, and things like minimum base quality are 0 by default.

It does however have a different slant on things.  It's attempting to show consensus bases rather than reference bases, meaning deletions are absent and insertions get shown as their own individual rows.  You can change that with `--show-ins no --show-del yes`.  It's not a total drop up replacement for mpileup format though.  It's quite deliberately designed to be easier to process.

It also brings back a basic consensus base, which is one of the more often complained about omissions when samtools switched from `pileup` to `mpileup` format.  (Although how you compute the consensus is a complex issue and one that does indeed require lots of heuristics to be robust.)
