### ISSUE TITLE
Transient(?) runtime increase when sorting cram files

### ISSUE THREAD

**Issue by wongkarenhy-hex** [samtools/samtools#1804]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
samtools 1.15.1
Using htslib 1.16

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)
```
(hxenv) kwong@karen-dev:~/hx$ uname -m
x86_64
(hxenv) kwong@karen-dev:~/hx$ gcc --version
gcc (Debian 8.3.0-6) 8.3.0
```
#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
I was trying to sort a relatively small cram file and it took an unusually long time to finish today. It also spat out some error-like messages but the job did eventually finish after ~10 mins. This task (with the same input file) took less than 4 mins (our server timeout) just a few days ago with the same environment.
```
(hxenv) kwong@karen-dev /tmp % ls -l /tmp/iHX116312_str1_HovsDd5P1DDp.cram
-rw-r--r--  1 karenwong  wheel  668803 Mar  8 14:39 /tmp/iHX116312_str1_HovsDd5P1DDp.cram

(hxenv) kwong@karen-dev /tmp % samtools sort -O cram -o /tmp/iHX116312_str1_HovsDd5P1DDp.sorted.cram -l 9 /tmp/iHX116312_str1_HovsDd5P1DDp.cram
[E::easy_errno] Libcurl reported error 52 (Server returned nothing (no headers, no data))
[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/8ace48730422dbade3796af824cae425": Input/output error
```
I don't understand why it needs to access EBI for a reference file when I'm simply attempting to sort. I also found a similar issue described [here](https://github.com/samtools/samtools/issues/1340). I was wondering if this is truly transient or if something else is going on with my OS. Any insight would be greatly appreciated!

**Comment by jkbonfield** [comment]
Such large variations in run times for CRAM are probably down to reference fetching.  My bet is it's downloaded a reference and cached it in ~/.cache/hts-ref.

As to why it needs the reference for sort, it'll be because it's decoding and re-encoding.  Internally htslib isn't working in CRAM objects, but an in-memory BAM syntax.  Hence it must turn the CRAM's reference-deltaed SEQ back into a full sequence in BAM, sort, and then reverse the process back to CRAM again.  It's pointless work, but unfortunately that's just how it is as CRAM came well after the htslib internals had solidified.

We were musing on the idea of being able to turn CRAM into BAM and back out again without reference using "=" as in the sequence, to avoid such reference complications.  However ultimately this is mainly indicative of not having a central cache of all your used references, or running a local caching reference server.

The EBI have guidance on this here:  https://ena-docs.readthedocs.io/en/latest/retrieval/programmatic-access/cram-reference-cache.html

An alternative has also been discussed here: https://github.com/samtools/samtools/issues/1290#issuecomment-664237199

**Comment by wongkarenhy-hex** [comment]
Thanks for clarifying! I think the EBI server was either very slow or unresponsive at some point yesterday and so `samtools sort` just stalled. I'll check out the alternative solution to hopefully bypass this issue.
