### ISSUE TITLE
samtools consensus, chromosome size discrepancy

### ISSUE THREAD

**Issue by muratiskar** [samtools/samtools#1806]
#### 
samtools 1.17
Using htslib 1.17
    Features:       build=configure libcurl=yes S3=yes GCS=yes libdeflate=no lzma=yes bzip2=yes plugins=no htscodecs=1.4.0
    CC:             gcc
    CPPFLAGS:
    CFLAGS:         -Wall -g -O2 -fvisibility=hidden
    LDFLAGS:        -fvisibility=hidden

HTSlib URL scheme handlers present:
    built-in:    preload, data, file
    S3 Multipart Upload:         s3w, s3w+https, s3w+http
    Amazon S3:   s3+https, s3+http, s3
    Google Cloud Storage:        gs+http, gs+https, gs
    libcurl:     imaps, pop3, gophers, http, smb, gopher, ftps, imap, smtp, smtps, rtsp, ftp, telnet, mqtt, https, smbs, tftp, pop3s, dict
    crypt4gh-needed:     crypt4gh

- OS:  Linux 3.10.0-1160.76.1.el7.x86_64
- machine architecture: x86_64
- compiler: gcc (GCC) 11.3.0
HTSlib compilation details:

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
samtools consensus -a -f fasta  --region chr1 --show-del no --show-ins no -m simple bamfile-input.bam -o consensus-output-mm10.fa
Great tool and Works fine with the 'simple' consensus algorithm (chr1 test: 195471971 bases) and serves the purpose well.
Issue: 
samtools consensus -a -f fasta  --region chr1 --show-del no --show-ins no -m bayesian bamfile-input.bam -o consensus-output-mm10.fa
Running with 'bayesian' or 'bayesian_116' resulted in 195471200 bases and also slightly lower number of bases for all chromosomes (without --region). Missing bases look like distributed along the chromosome. Reads were aligned to mm10 using Bowtie2. Not sure, if this difference is due to compilation or environment (same error with SAMtools/1.16.1-GCC-11.3.0).
 'bayesian' algorithm being the default might be misleading for generating consensus sequences that are perfectly aligned with the reference genome. And, it would be great to have the 'bayesian' option. Thanks.

**Comment by jkbonfield** [comment]
Firstly, there were quite a few improvements to this code with 1.17, so please try the latest version.

Secondly, you're using `--show-del no` which means if the consensus call is "*" for a reference base then it'll be removed, giving a smaller chromosome.  If you want an exact 1:1 mapping of reference and consensus you need `--show-del yes --show-ins no` so that every reference coordinate is covered by exactly one character.

You may find that using `samtools consensus -f pileup --show-del yes` and a simple search for reference base "*" which would have been filtered out in your command.  That'll give you much more evidence that the consensus algorithm is working off.  
It may be correct of course for the base call to be "*", so I'd need some real data to demonstrate what's happening.

**Comment by muratiskar** [comment]
Thank you for the detailed explanation. I will try again with all the options.
