### ISSUE TITLE
Calling with samtools mpileup calls fewer SNPs than expected.

### ISSUE THREAD

**Issue by kimgeng5512** [samtools/samtools#1807]
samtools --version
samtools 1.10
Using htslib 1.10.2-3ubuntu0.1
Copyright (C) 2019 Genome Research Ltd.

Hello, I'm master course student, and I'm embarrased that I'm very poor at controlling bam files and samtools

I tried to variant_calling with samtools mpileup, but as a result, I got a few SNPs (fewer SNPs than expected. My bam file showed about 5x average depth, but the result file of mpileup had few amount of SNPs)

for example,
As you can see in the picture below, the region chr1:5838170~5838179 showed >=15 depth when I used the command "samtools depth -q30 -Q30"
However, they showed only 1 depth when I called variants with mpileup command.
I used same threshold (-q30 -Q30), but the results were very different.

I don't know what should I do to solve this problem.
What's the problem with my file?

![Calling](https://user-images.githubusercontent.com/85051494/224539461-2b2758c8-9463-44c6-9307-da7ed80dde4e.png)

**Comment by jkbonfield** [comment]
Firstly, 1.10 is old.  Please update.
Secondly, if you actually want to do variant calling rather than just visually inspect pileups, then bcftools mpileup | bcftools call is the recommended solution.

As for the specifics of why so little data is shown here, it's possibly due to either BAQ or the "anomalous" pair detection in mpileup, which for speed isn't implemented in the simpler depth command.   Look at the `-A` and `-B` options of mpileup.

**Comment by jkbonfield** [comment]
Closing as no response, and problem is almost certainly answered with the difference in depth vs mpileup filtering options.
