### ISSUE TITLE
extract reads from a region with '-P' parameter will be chunk  

### ISSUE THREAD

**Issue by xuxif** [samtools/samtools#1808]
The latest version

I'am trying to extract read from a region and include all pair from a cram file. In the mate (outsize previous region) position I found three reads have same names with the mate. And the samtools program will be never stop.

**Comment by xuxif** [comment]
Script is 'samtools view -h -P -T Homo_sapiens_assembly38.fasta HG01529.final.cram chr11:73816315-73816415'
reference genome is HG38, cram file is HG01529 from 1kGP high coverage phase 4 and you can get it from 1000g ftp site.

**Comment by xuxif** [comment]
> 



> I ran your command and it finished in about 2 seconds with output that looks (at least at first glance) reasonable.
> 
> Are you running the latest version of samtools?

Yes, I ran it again with another server. And it's chunk too. If I extract pair read with 'P' from bam file the same result wa shown. But cram do chunk.

**Comment by xuxif** [comment]
> 



> > 
> 
> > I ran your command and it finished in about 2 seconds with output that looks (at least at first glance) reasonable.
> > Are you running the latest version of samtools?
> 
> Yes, I ran it again with another server. And it's chunk too. If I extract pair read with 'P' from bam file the same result wa shown. But cram do chunk.

In my server the samtools version is  1.17 and  htslib is 1.17.

**Comment by whitwham** [comment]
What you mean by "chunk"?  I am not sure what you are getting at.

**Comment by xuxif** [comment]
Get stuck. The samtools output a few reads and seems stopped. And no additional error or warning message.

**Comment by whitwham** [comment]
The sam file I produced had this flagstat output:

> 182 + 0 in total (QC-passed reads + QC-failed reads)
179 + 0 primary
0 + 0 secondary
3 + 0 supplementary
20 + 0 duplicates
20 + 0 primary duplicates
182 + 0 mapped (100.00% : N/A)
179 + 0 primary mapped (100.00% : N/A)
179 + 0 paired in sequencing
90 + 0 read1
89 + 0 read2
116 + 0 properly paired (64.80% : N/A)
179 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
62 + 0 with mate mapped to a different chr
32 + 0 with mate mapped to a different chr (mapQ>=5)

So I got 182 records out (plus the header of course).  How many are  you getting?

**Comment by xuxif** [comment]
I got 180 reads and the program still not finished! It's about 24 minutes.

**Comment by xuxif** [comment]
The final read is 'A00404:158:HV2LNDSXX:3:2663:21178:23202	145	chr19	20148529'. I guss samtools is still searching the mate read of 'A00404:158:HV2LNDSXX:3:2663:21178:23202'

**Comment by whitwham** [comment]
The mate to that one is in chr11 so should have already been written out.  The last two of mine are A00404:158:HV2LNDSXX:2:1236:1217:27461 (chr22) and A00404:158:HV2LNDSXX:3:1125:32832:3615 (chrx).

**Comment by xuxif** [comment]
You can test in a container. I work on '  docker pull xuxiaofeiscu/deepmei:v1.6.2  '

**Comment by whitwham** [comment]
Okay, I'll give it a go.

**Comment by whitwham** [comment]
I ran it in your docker container and it finished in 14 minutes.  I had to use a new HG01529.final.cram but otherwise I used everything else from the container.  It worked though it was very slow.

**Comment by jkbonfield** [comment]
Does it run slow the second time you run the command in the same container?

Does upping the verbosity explain anything?  My experience of CRAM being slow is it's nearly always down to EBI and the reference server.  (Although you are specifying a reference, it's possible that it's not correct and it's still going elsewhere to find the correct data.)

**Comment by xuxif** [comment]
The problem might not be the reference. Because I ran it in a centos server in a few seconds. This phemonon emerged in docker container and a ubunutu (metal server).

**Comment by whitwham** [comment]
I tried it in a new Ubuntu container and it was equally slow.  I have a few more tests to do.

**Comment by whitwham** [comment]
All the tests with samtools 1.17 (in docker, cloud and bare metal) took about 14 minutes.  My original test (of 2 seconds) was run against the latest development version of samtools.  The development version has a fix to make the index more efficient and run faster, which is why I was getting much better results.

All my runs finished, but we found that there may be a bug in the indexing code which could affect the output.

I don't know why your centos test was so fast.

**Comment by jkbonfield** [comment]
I've been digging into this to diagnose the fault, given it appears to be in part of my own code.

Basically CRAM multi-region iterator queries (as used by -P) has one query for the start coordinate and a second query for the end coord to get two file offsets.  It then specifies these as limits for the CRAM decoding.  The latter of these queries however had a bug, fixed in https://github.com/samtools/htslib/pull/1574, which could lead to random looking "end" file offsets.

The bug was very hard to trigger, but it's related to region queries that map to CRAM slices with start/end coords which can entirely fit within the previous slice coords.  Eg a slice covering a large region followed by a slice with just a few bases, due to an overwhelming depth of short soft-clipped reads.   In some cases, this could then trigger reading uninitialised memory and using data from that for the second "end" file offset.

So it may be fast, or it may be very slow (eg reading to end of file), depending on what unitialised data gets returned.  This may explain why there is different behaviour in/outside of a container or between different OSes, even with identical program versions.

**Comment by whitwham** [comment]
This is a bug in 1.17 that has already been fixed in the development version and will be put in the next release.
