### ISSUE TITLE
Documentation clarification request (samtools split)

### ISSUE THREAD

**Issue by SHuang-Broad** [samtools/samtools#1817]
Hi,

Based on my observation, its current behavior is such that if `-u` is specified, a bam is generated regardless of whether such reads exist or not in the input BAM. And, this "noRG.bam" retains all RG lines from the input BAM. If this anecdotal observation is in concordance with the intention, this should be documented.

Also, the current [documentation](http://www.htslib.org/doc/samtools-split.html) doesn't specify what the result is for records with RG tags which are not defined in the header section. Does the tool error out? Or does it classify them the same as those without-RG-tag records?

Having these clarifications will help us design how our pipelines handle edge cases.

Thanks,
Steve

**Comment by whitwham** [comment]
> Based on my observation, its current behavior is such that if `-u` is specified, a bam is generated regardless of whether such reads exist or not in the input BAM. And, this "noRG.bam" retains all RG lines from the input BAM. If this anecdotal observation is in concordance with the intention, this should be documented.

The "noRG.bam" is always created when the -u option is used and at the very least will contain a copy of the input header (if -h is not used).  Whether it should do this is an arguable point but since it does I don't think we should change it now.

Also, any RG entries in the header with no records will generate a file with only a header.
 
> Also, the current [documentation](http://www.htslib.org/doc/samtools-split.html) doesn't specify what the result is for records with RG tags which are not defined in the header section. Does the tool error out? Or does it classify them the same as those without-RG-tag records?

As it says in the -u option,  records with an undefined RG tag go into the same file as those without an RG tag.  What is doesn't say is that if -u is not specified then the program will exit with an error.

I will update the man page as well as fix the small bug I have found.
