### ISSUE TITLE
samtools: /home/administrator/miniconda3/envs/breakseq/bin/../lib/libtinfow.so.6: no version information available (required by samtools)

### ISSUE THREAD

**Issue by Rohit-Satyam** [samtools/samtools#1822]
I am getting this error with samtools. How to fix it?

```
samtools: /home/administrator/miniconda3/envs/breakseq/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
samtools: /home/administrator/miniconda3/envs/breakseq/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /home/administrator/miniconda3/envs/breakseq/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools 1.16.1
Using htslib 1.17
Copyright (C) 2022 Genome Research Ltd.
```

**Comment by whitwham** [comment]
Well, you're using htslib 1.17 with samtools 1.16.1 so something is wrong with your installation somewhere.

[This](https://github.com/bioconda/bioconda-recipes/issues/8210) might be relevant to you.  Otherwise this is really a conda problem.

**Comment by jmarshall** [comment]
For …reasons… bioconda has updated to htslib 1.17 but has not yet merged the PRs to release samtools and bcftools 1.17 packages. Hence the most current samtools package is [1.16.1 built against htslib 1.17](https://anaconda.org/bioconda/samtools/files).

Bioconda packages are indeed built using conda-forge packages in preference to default packages, and users should [set up their channels following the bioconda instructions](https://bioconda.github.io/#usage) accordingly.

Problems like this one are indeed usually due to not having conda-forge set up. As a workaround you can use `conda install -c conda-forge …` every time, but it is better to run the `conda config` commands given in the instructions (just once) so you don't have to.

**Comment by whitwham** [comment]
I'm going to close this as a conda issue.

**Comment by Naveen9182** [comment]
I am getting the same issue when working on bam files with Concoct. 
I have multiple sets of samples where a few are working fine with same command and few others are giving me this issue.
Any help will be greatly appreciated.

**Comment by jkbonfield** [comment]
Please file concoct issues with Concoct, and bioconda issues with bioconda.  The samtools team cannot act as support for other teams that provide binary installs of our software, sorry.

(Also locking this as resurrecting long-closed issues is problematic for issue tracking)
