### ISSUE TITLE
How to explain samtools calculation result when the reference has N in the middle？

### ISSUE THREAD

**Issue by yangjw1996** [samtools/samtools#1823]
Hi, thank you for creating samtools! My question is not about any problem of the software. I don't konw how to explain some of the samtools calculation results and therefore asking for your help. 

I am analysing NGS data of human mtDNA. The reference is called rCRS, which has a N at position 3107, and it total length is 16569 bp. The reference is like this .......CN.......... 

I used bwa mem for alignment and 'samtools depth' to calculate the depths at every single base.
I expect that the 3107 will have depths close to 0, but the result is that 3106 has depths close to 0 and 3107N has normal depths. 

The result is like this : 
MT	3105	3082
MT	3106	15
MT	3107	6173  this position in reference is N
MT	3108	6170
MT	3109	6182

By the way, I also use gatk DepthOfCoverage to calculate depths and get the similar result. 

I check the bam file by IGV and also check the sam file:  3106 is judged as del, 3107 is judged as C ALT.

The raw fastq is also checked, and 3106 position is the same as reference.  Variant calling result has no problem (3106 is not judged as del, also 3107 is not judged as a variant).

I don't know how to explain the above situation. Could you please share you idea on this?

**Comment by jkbonfield** [comment]
Without seeing the data it's impossible to say. Maybe it's just a deletion, as they won't count to depth.

Try `samtools mpileup` over the same region and look.  It'll give you a better understanding for what's going on.  Or `samtools tview` / IGV to visualise the alignments.

**Comment by yangjw1996** [comment]
Hi, jk, thank you very much. Sorry for not replying earlier.

I have uploaded the bam file, reference fasta and a IGV screenshot of  MT3107 where I am confused about the depth counting. I would be very appreciate it if you would like to look at this issue further. 
Here is the link:
https://github.com/yangjw1996/question-on-samtools.git

The data is amplicon seqenced, so you will find the mapped reads look similar with each other.  I also upload a vcf result called by  ' bcftools mpileup -E -p -Q 0' , through which I still can't figure out what's going on in MT3106-3107.

I have another question, which I am not very confident of the answer. As we know, mtDNA is a circular genome. There must be some reads across the starting and ending position. For example, a read starts at 16500  but ends at 100 . And when counting depth, the depths of 1-100 can't be counted from such reads. I suppose that samtools depth (as well as some other tools) dosesn't have any pattern of counting such reads for a circular genome, is this right? 

Thank you for helping!

**Comment by jkbonfield** [comment]
I suggested running `samtools mpileup` and looking at the results, and sure enough it's there to see.  I used options to show absolutely everything rather than discard low quality etc, as the default filtering in `mpileup` and `depth` differs slightly.

```
samtools mpileup -Q0 -q0 -B -A https://github.com/yangjw1996/question-on-samtools/raw/main/MT3107.bam -r MT:3106-3107     
[mpileup] 1 samples in 1 input files
MT	3106	N	3087	*********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************G*********************************************************************************G***********************************************************************************************************************************************************C*************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************C*************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************G***************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************C****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************A*******************************************************G***************************************************************************************************************************************************************************************************************************************************************************************************ccccca^]a	BbA@AA@AA@@<@@AABA... [qual trimmed]
```

I count 15 non-del bases present (GGCCGCAGcccccaa).  That exactly matches `samtools depth`.  The correct call here is almost certainly DEL.  However there is a clear difference between looking at the call made by a variant caller and looking at the sequence evidence underlying that call.   Depth shows the latter, so it's not expected to match.

As for 3107:

```
samtools mpileup --no-output-ends -Q0 -q0 -B -A https://github.com/yangjw1996/question-on-samtools/raw/main/MT3107.bam -r MT:3107-3107
[mpileup] 1 samples in 1 input files
MT	3107	N	6173	CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCTCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCTCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC-1NCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC-1NCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC-1NCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCccccccccccccccccccccccccccccc-1nc-1nc-1nc-1nccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc  [qual trimmed]
```

So that's basically a C call, with a couple Ts and 7 dels.  Depth again is just showing the evidence from the underlying data here.  I do not know what you expect it to show.  It seems both depth and the variant callers are working as intended.

As for the second part of your question, you are correct that these tools do not understand circular genomes.  We discussed this last week infact, as it's been on our to-do list for some time.  The SAM format does now have the ability to label references are circular.  However this BAM file doesn't annotate it that way and I've no idea if the aligners yet support it either.  It's not worth us implementing support for this in samtools/htslib until upstream aligners are supporting it, as otherwise the data won't be available.   Your reads are 129 bases long, so it's possible you could fudge it by editing your reference and pasting the first 128 bases to the end of the reference so complete reads can always align somewhere, and then reedit the headers to shrink it back down again.  That then means there are reads with alignments overhanging the end of the reference.  If labelled as circular, we 
could (but don't yet do) the appropriate module-arithmetic to correctly assign those bases off the end as belonging to the start.

**Comment by jkbonfield** [comment]
I'd also add that probably a sequence viewer is a better way of really trying to understand what the data is showing you than looking at pictorial summaries like IGV.  I personally use Gap5, but it's got a steep learning curve and non-existant support, with a convoluted BAM import step.  Other tools include things like samtools tview or tablet.  Anyway here are some demonstrations of the issues with sequence aligners and reference bias:

![image](https://user-images.githubusercontent.com/2210525/229740852-c36d7b40-419f-4409-a356-95817e6623e0.png)

The data here is collated by sequence, but it's showing a whole bunch of apparent Cs in the 3106-del column.  In isolation, as viewed in mpileup (or depth) we can't see the true story.  Visually though it's obvious.  All those Cs are also DEL, because every one of those reads has a T DEL 2 bases further on.  The reason for that is simply that the reference differs.

```
REF TACNTTC...
SEQ TA-CCTC...  correct alignment
SEQ TACC-TC...  incorrect alignment
```

Moving the placement of the gap is cost effective here because C vs N scores less than C vs T.  However for bwa is may be more nuanced because N is possibly hashed as another base type when seeding the alignments.   Hence it's not entirely consistent.

A variant caller will likely be doing some level of local realignment surrounding indels, so will get all of those gaps aligned up correctly.  Note you need `bcftools mpileup ... | bcftools call` and not just the first part.  Ideally add `-a AD` (IIRC) to show the allele depths too in the FORMAT data.  That will give you information on what the variant caller actually thinks the depth is per allele, rather than the raw alignments with their original reference bias.

Note further down we also see the cause of some other bases in that column:

![image](https://user-images.githubusercontent.com/2210525/229742771-7a38957e-7d68-44b4-bf6d-aef6cbdde6f3.png)

Again this is just bad alignment caused by pair-wise alignment (seq-vs-ref) rather than seq-vs-seq alignment.  A local realignment tool, or us eye-balling it, will clearly view that as an A to G miscall, and not a neighbouring insertion and deletion.  Bwa has called it this way however simply because compared to the reference it has a choice of DEL+SNP vs SNP+DEL, giving equal cost (but we know the second DEL is actually a match to everything else).

**Comment by yangjw1996** [comment]
Thank you for your kindness and patience in explaining this issue.  It helps me better understand what confused me，and teaches me a way how to explain and  figure out such issue.   I am heartily grateful to your help. 

Best whishes!
