### ISSUE TITLE
Feature request: read length plot for samtools stat

### ISSUE THREAD

**Issue by mp15** [samtools/samtools#1824]
Previously we have not included a plot that gives us a histogram of read lengths because most of our reads have been Illumina reads with a fixed cycle length per run. With 3rd generation platforms read lengths now vary considerably, plotting this as part of samtools stats would be helpful. This feature should be able to be switched on or off manually but if neither of these is supplied it should detect known 3rd gen platforms in the RG tag.

**Comment by jkbonfield** [comment]
I like this idea.  If it was always on it wouldn't take up much room for fixed-cycle instruments anyway, and it ought to be fast enough.   This sort of thing is normally done at the fastq level by e.g. FastQC, but with more instruments giving uBAM or even fully aligned BAM/CRAM as output format then a tool to run off BAMs makes sense.

I assume it'd be for primary alignments only and full unclipped length regardless of CIGAR, so it reports the instrument / library data rather than alignment statistics.  For completeness we'd probably want to support read-pair protocols too and separate READ1 from READ2 (or possibly the sum of the two for protocols where the pair is implemented by library prep and an embedded adapter to remove post single-ended sequencing).

**Comment by jkbonfield** [comment]
I'd think we need some way of adjusting the bin size so small sizes go in increments of 1 and larger sizes start to be binned in bigger widths, as we may have reads 100Kb+ long.  That would also mean potentially columns showing the total count within that bin and the bin-averaged count, so a 100 wide bin with 2730 reads in it would be an average of 27.3 per length.  That makes it easy to plot still.  I think so anyway.  Would have to mock something up to see...

An ONT example without any binning (logscale x):

![image](https://github.com/samtools/samtools/assets/2210525/3eea79c6-12c2-4513-8d2f-8bc0b6e11235)

An ONT example with log-binning via

```
awk '$1>1 {b=int(log($1)/log(10)*10);bin[b]++} END {for (i in bin) {st=10**(i/10);en=10**((i+1)/10);print bin[i]/(en-st),bin[i],st,en}}' _l|sort -k 3n

gnuplot: plot "_b" using 3:1 with boxes
```

![image](https://github.com/samtools/samtools/assets/2210525/3e38597c-59f3-4e22-af1f-ef31357a8533)

The spike at length 62 vanished though.  I guess a clever algorithm could look for outliers and make specific boxes for that size?

**Comment by erboone** [comment]
Ok, with your feedback in mind I've implemented a new version that plots both a linear scale and a log scale version of the data, so that either can be viewed easily.  I wanted to include both because, as you mentioned, while the log scale is more readable it does remove information about outlier peaks, which I find useful to have on hand.  Additionally, after trying both dividing by binwidth and not, I've decided that I will implement bin heights NOT divided by width, as it does put more weight near the average read length, which I think is a more intuitive representation of the data and will minimize confusion among users.  Below are examples, let me know if I am off base with my reasoning or if there is anything that should be cleaned up.

This is the current implementation graphing short read data (Illumina)
![read_length_sr](https://github.com/samtools/samtools/assets/143131066/f9bc2619-9f6f-4a3a-bf87-1eb11dd9bd17)

This is the current implementation graphing long read data (Oxford Nanopore)
![read_length_lr](https://github.com/samtools/samtools/assets/143131066/b4dd6801-9471-4b0f-9e05-e3874e23f73d)

**Comment by jkbonfield** [comment]
Checking poretools (https://poretools.readthedocs.io/en/latest/content/examples.html#poretools-hist,  https://github.com/arq5x/poretools/blob/master/poretools/hist.py) I see they just show quantity in bin and use linear scale, so no exponential sized bins.  That makes plotting easy and there's really no normalisation necessary.

That's the easiest mechanism.  Linear / ;ogscale plot of x makes no difference to the shape.  Eg unbinned, and binning into fixed width 100bp bins:

```
$ samtools stats Ecoli_r10.4_sup.bam > _.stats
$ awk '/^RL/ {b=$2;bin[b]+=$3} END {for (i in bin) {print i,bin[i]}}' _.stats|sort -n > _len.hist
$ awk '/^RL/ {b=int($2/100)*100;bin[b]+=$3} END {for (i in bin) {print i+50,bin[i],100}}' _.stats|sort -n > _linear.hist

$ gnuplot
set xrange [*:30000]
set y2tic
# fudge for binning smoothing out the maximum height spike so we can see both side by side
set y2range [*:160000]
plot '_len.hist' with boxes, "_linear.hist" using with boxes axis x1y2
```


I had to use y2 axis (right hand side) for the 100-wide binned histogram as each element had 100 times as much data, so to see both unbinned and binned on the same plot we'd need two axis or to divide the binned values by 100 to normalise again.

![image](https://github.com/samtools/samtools/assets/2210525/98e1d275-8ade-4c37-9d5e-0078ed53bc16)

Similarly, with `set logscale x` and the same gnuplot plot function:

![image](https://github.com/samtools/samtools/assets/2210525/a60a9223-4635-404b-8d29-350c1c862300)


However if you logscale the *bin widths* in x, then you do get weird skews without bin normalisation because the larger bins will have larger counts due to their width, not just their traditional height. 

```
$ awk '/^RL/ {b=int(log($2)/log(10)*10);bin[b]+=$3} END {for (i in bin) {st=10**(i/10);en=10**((i+1)/10);print (st+en)/2,bin[i],en-st}}' _.stats|sort -n > _log.hist
```

![image](https://github.com/samtools/samtools/assets/2210525/734ea66c-d2c8-421c-8790-b93322150da6)

As our bin widths are exponential, the number of elements per bin increases as an artifact of bin width.  They look linear widths again because we're plotting in logscale x, but we need to normalise by their sizes.  Ie:

```
gnuplot> plot '_len.hist' with boxes, "_log.hist" with boxes axis x1y2, "_log.hist" using 1:($2/$3) lw 2 lt 5 with boxes x1y1
```
![image](https://github.com/samtools/samtools/assets/2210525/ed0f2a82-c385-4898-984c-7c592437c75b)

Anyway, I am assuming this will turn up at some point as a PR to the plot-bamstats perl script?

Thanks

**Comment by daviesrob** [comment]
I think normalised along with an indicator to show the highest count in a bin might be a good way to show the distribution while indicating that there's a spike in one of the bins.

**Comment by erboone** [comment]
OK, after assessing your feedback, I've produced the attached version.  
![read_length](https://github.com/samtools/samtools/assets/143131066/c9503e5b-4315-4eff-add3-05790ece4d42)
There are a couple design choices this is meant to address:
1.) By including the unbinned data in the normalized plot, we maintain the ability to see large spikes. Additionally, including the unbinned data in the non-normalized chart, we provide a "baseline" distribution with which to compare differences. 
2.) Inclusion of the normalized logarithmic histogram to provide meaningful smoothing of the unbinned data.
3.) Inclusion of the non-normalized histogram in order to more accurately display where reads are concentrated at a glance.  The example I attached provides a good example of why this is important to include, as the normalized histogram biases the weight of the 10 - 100 bp reads.   If users are expecting their long read data to predominantly be in the 1000 - 10000 bp range, they should be able to confirm that quickly. 

I feel strongly that both visualizations should be included. 

Additionally @jkbonfield; is there any way to access the Ecoli_r10.4_sup.bam you used in your examples? I would like to have another example to test.  Thank you.

**Comment by jkbonfield** [comment]
I'm not sure where I got the bam from.  It may be from aligning them myself.  I think it was probably data from this paper:

https://www.microbiologyresearch.org/docserver/fulltext/mgen/9/1/mgen000910.pdf?expires=1695633475&id=id&accname=guest&checksum=9BDD248519F78500C079C9B56556CFD6
https://www.ebi.ac.uk/ena/browser/view/PRJEB51164

For purposes of read length histograms though the fastq should be sufficient to process.

**Comment by erboone** [comment]
If everyone is satisfied with the above presentation of the data, I'll make a final pull request.

**Comment by erboone** [comment]
Ok, I've changed the color scheme that is more amenable to colorblind users.  Additionally, I've modified the legend to make it more clear to users what is meant by normalized vs unnormalized:
![read_length1](https://github.com/samtools/samtools/assets/143131066/9c296298-f2fd-43f8-9034-45ae6ae30331)

On the topic of a bases from read count histogram: I graphed it as a test just to check it out, but as you can see in the image below, when normalizing based on bin widths (top), we are left with an identical graph to the unnormalized plot.  

When not normalizing based on bin widths (bottom), we have a new graph, but without a clearly relevant purpose.  This distribution skews very far right, and represents the read size where a majority of the read base-pairs can be found.  However, I cannot think of a common reason this would be useful to users.  In theory, if you found a bunch of features, and recorded and averaged the length of read they were found on, this could be compared with the graph to show that the feature is more or less likely to be found in easily mapped areas.  However, this is a very niche hypothetical use, and the majority of our users will be using this for QC before more interesting analysis down the pipeline.  For these cases, the vast majority of users are more concerned with the distribution of individual reads.  With that in mind, any visualization elucidating the distribution of base pairs does not add anything but visual noise to most users.
![read_length2](https://github.com/samtools/samtools/assets/143131066/0f4e0944-7156-4088-b7c5-b41255ff7410)

I think that the first set of graphs is a succinct and visually pleasing way to present the data that the majority of users are looking for. For now it's ready to be released, and further improvements and features can be discussed as a separate PR.

**Comment by erboone** [comment]
@jkbonfield @mp15 Are you comfortable with this implementation? I think this version is ready to be merged to the develop branch. Thoughts?``

**Comment by mp15** [comment]
Looks good to me

**Comment by jkbonfield** [comment]
Thanks Martin.

I'll take a look at the PR.
