### ISSUE TITLE
Not reading input from stdin

### ISSUE THREAD

**Issue by mariamnawaz1** [samtools/samtools#1844]
Hi,

I am trying to read input to a samtools command from stdin but it is failing throwing an error as below:

Command- 
_samtools view -@ 2 -h abc.bam | awk -F '\t' '{if ($3=="1" && $4=="18628575") print $0}' | samtools view -bS - > output.bam_ 
or
_samtools view -@ 2 -h abc.bam | awk -F '\t' '{if ($3=="1" && $4=="18628575") print $0}' | samtools view -bS -o output.bam -_
or
_samtools view -@ 2 -h abc.bam | awk -F '\t' '{if ($3=="1" && $4=="18628575") print $0}' | samtools view -bS -o output.bam /dev/stdin_

Error-
[E::sam_parse1] no SQ lines present in the header
samtools view: error reading file "-": No such file or directory

The input does have SQ lines.

Please help me out. I have been facing this issue for a while.

Thanks in advance!

**Comment by whitwham** [comment]
At first glance it looks like your **awk** command would not print out any header entries.

**Comment by mariamnawaz1** [comment]
Hi, thanks for pointing that out. Is it not possible to not print header and create the output.bam?

**Comment by jkbonfield** [comment]
The entire thing is best done via another strategy anyway, unless this is simply an example.  Eg

`samtools view -o out.bam -e 'pos==18628575' abc.bam 1:18628575-18628575`

The view specifies a region matching a single coordinate, but samtools will return all data that overlaps that region rather than starting only at that region.  We can amend that by requiring an exact match using `-e`.  If we don't have an index and wish to stream and filter instead, then you could omit the region query path and use `-e 'rname=="1" && pos==18628575`.

This will be considerably faster than converting to text, doing awk, and converting back again to BAM.

**Comment by mariamnawaz1** [comment]
@whitwham - thank you for letting know!
@jkbonfield - this is what I was trying to do, thank you so much!

**Comment by whitwham** [comment]
> A quick question, if I need to print reads that start on or after the specified position, how can I do that?

Change `pos==18628575` to `pos>=18628575`.

The expression documentation can be found [here](https://www.htslib.org/doc/samtools.html#FILTER_EXPRESSIONS)
