### ISSUE TITLE
samtools import produces incomplete bam output using large fastq input files

### ISSUE THREAD

**Issue by ftian9** [samtools/samtools#1847]
Version: samtools 1.16.1

Input:
R1.fastq.gz and R2.fastq.gz (2,616,908,830 read pairs)

Command:
`samtools import -i R1.fastq.gz R2.fastq.gz --order ro -O bam,level=0 > RX.bam`

Output:
RX.bam (4,294,967,296 reads)
In the first line, the ro tag is "ro:i:0"
In the last line: the ro tag is "ro:i:4294967295"

The key point:
bam_aux_update_int
https://github.com/samtools/samtools/blob/develop/bam_import.c#L361

In `bam_aux_update_int`, the read number cannot be greater than UINT32_MAX:
https://github.com/samtools/htslib/blob/develop/sam.c#L4760

**Comment by jkbonfield** [comment]
This is tricky, as the BAM specification also doesn't support numbers larger than 2^32 so fundamentally it's not possible unless we use more than one aux tag.

How are you consuming / using the aux tag generated?  What limitations do we have on that?  We could for example produce a string that's lexicographically sortable in string form instead of numeric form.

**Comment by ftian9** [comment]
I need to add the "ro" tag into the cram file (the following code line 1).
When I convert the cram file back into the fastq file, the "to" tag will be used (the following code line 2).
As shown [here](http://www.htslib.org/doc/samtools-import.html):
```
samtools import -i in_1.fq in_2.fq --order ro -O bam,level=0 | samtools sort -@4 -M -o out.srt.cram -

samtools sort -@4 -O bam -u -t ro out.srt.cram | samtools fastq -1 out_1.fq -2 out_2.fq -i --index-format "i*i*"
```

**Comment by jkbonfield** [comment]
Unfortunately as I've explained, numbers up to 2^64 are not supported by the BAM format (and hence CRAM which used the same tag encoding).  The `sort -t` option does support text sorting though, so we could use a string equivalent instead.  An 8 character base-64 encoded string would give 2^48 alignments (281 trillion).  Or we could just have an option to specify the length.

This isn't something that can be done automatically though as there's no way to know upfront how many records import will be dealing with.

I'm curious though why you need to sort by tag instead of just read name?  Is this to ensure absolutely 100% bit identical output after the round trip?  The order of pairs of records in fastq is arbitrary, and as long as they're not clumped too strongly by genomic region it generally makes no difference to alignment tools.

**Comment by ftian9** [comment]
Thank you.
My current strategy is to add the "ro:Z:(20-width number)" to the bam/sam file using a Python script, and then use these strings for sorting.
```
samtools import -i test_1.fastq.gz test_2.fastq.gz | python do_addOrder.py - | samtools sort -@10 -m10G -M -O cram,small -o test_X.cram
```
The 10^20 alignments could be covered.
I need to sort the bam file by the ro tag because I need to regenerate the identical fastq files using the cram file.

**Comment by jkbonfield** [comment]
I understand the reasoning behind wanting this, and was really just confirming it.  Should have been obvious really as I expect it's why we added the option in the first place.

I'll look at a way to get it to use a string instead of a number.  For sorting purposes all we care about is the correct ordering and not something that's human readable.

**Comment by jkbonfield** [comment]
Also, the latest samtools has a `-I` option to use an index on a fasta file to order the minimisers, further reducing file size.  That may sound like you now need the reference genome, but a quick and dirty assembly will do too.  It doesn't have to be accurate, just better than random.

I've had some success using https://github.com/ekimb/rust-mdbg which is very very fast.  Used in conjunction with `-M -I` or `-M -I -H` this can improve local reordering further.
