### ISSUE TITLE
samtools consensus -a omits contigs that have zero mapped reads

### ISSUE THREAD

**Issue by tfenne** [samtools/samtools#1849]
#### Are you using the latest version of [samtools]
Tested with 1.16.1

 #### Please describe your environment.
`Linux 3.10.0-957.el7.x86_64`, installed via bioconda

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I'm running `samtools consensus -a` to generate consensus sequences over a number of contigs.  Occasionally one or more of the contigs in my reference ends up with zero reads mapped to it, and when that happens `samtools consensus` does not generate any output for that contig.  I'm not sure if this is a bug or if it's intentional.  But I can't find a way to have it produce an output when there are no reads for the contig.

Would be nice if `-a` produced output for the full length of all contigs in the reference / sequence dictionary.  Or failing that if one could specify `-aa` or `-a -a` to turn on such behavior that would be nice.

**Comment by jkbonfield** [comment]
That sounds like a reasonable request.  Thanks.

I think I'd be inclined to go along the `-aa` approach used elsewhere like depth.  That means a split BAM file with one chromosome but (wisely) containing the full header works more or less as intended by the split command, unless explicitly requesting "absolutely all" data.

How are you finding the command in general?  It's still a work in progress with regards to improving it for various instrument types, and I originally wrote it mainly as a way of generating references for embedding into CRAM (but since chose a simpler on-the-fly route anyway).  It's not really intended to be a replacement for variant calling, and it lacks all the niceities needed for that such as local reassembly, but even there it doesn't seem wildly inaccurate given the age of the core algorithm (which predates samtools I think!). :)
