### ISSUE TITLE
samtools fastq to enable filter by tag "-d"

### ISSUE THREAD

**Issue by Kirk3gaard** [samtools/samtools#1854]
It would be great if samtools fastq could be used to extract reads from a bam file with a certain tag using the "-d" option as for samtools view (https://github.com/nanoporetech/dorado/issues/199).

**Comment by jmarshall** [comment]
You should be able to use `samtools fastq --input-fmt-option 'filter=[dx]==0' …`, but that currently doesn't work. Fixed by PR #1855.

The `fastq` command is similar to `view` in that it is essentially a `cat` command with transformations. Hence it may be worth adding `view`'s `-e`/`--expr` option to the `fastq` command as a way of surfacing the filtering capability more explicitly and conveniently. (Filter expressions are more general purpose than `view`'s `-d` so IMHO a better addition.)

The `fastq` command has all the bells and whistles, but `view` can also output basic FASTQ that may suffice for your purposes. So you might try `samtools view -Ofastq -ddx:0 …`.

**Comment by jkbonfield** [comment]
Good comments both.  The `-e` option is more versatile, but it's parsed (for every record because it was a quick and dirty implementation) and interpreted, so slower than `-d`.  Whether that matters in practice I don't know.

Note you can always do a `samtools view ... | samtools fastq` combo too.

**Comment by jkbonfield** [comment]
Do we care about the more complex `view -D` option?  `view -d` is trivial, and can also be more efficient if it only accepts a single value.  Wanting multiple values changes it to use a hash table and entirely string comparisons too.  It's also a bit more work, but I'm unsure if it's necessary given the more complex logic is always available with `samtools view ... | samtools fastq ...`.
