### ISSUE TITLE
samtools mpileup got invalid base quality.

### ISSUE THREAD

**Issue by ydLiu-HIT** [samtools/samtools#1858]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
>version 1.17

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
  >Linux 3.10.0-862.14.4.el7.centos.plus.x86_64
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
  >x86_64
- compiler (run `gcc --version` or `clang --version`)
  >gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
When I use `mpileup` to pile up the alignments at single genomic position with the following command:
`samtools mpileup example.bam --min-MQ 20 --min-BQ 13 --no-output-ends -r chr22:34950636-34950636`
and I got the following pileup result:
`chr22   34950636        N       21      AggagGGGGGGGagGGgaGgg   2=DFJDB2???@5AF5laHCD`

But, I found that the fourth last base quality is 'a' (ord(a)-33=64) which seems exceptionally high and rarely met, then I traverse all the alignments covered chr22:34950636 and extract all the original base quality with the following command:
`samtools view exmaple.bam chr22:34950636-34950636| cut -f 11`
and I can not find any base quality with ASCII code 'a'. 

I don't know why the base quality 'a' appeared in the pileup result.

Looking forward to your reply！
Thanks.
Yadong.

**Comment by daviesrob** [comment]
This could be due to `mpileup`'s overlap removal, which is designed to prevent double-counting where the ends of read-pairs overlap each other.  Where this happens, the bases on one of the reads will be retained, while those on the other will be discarded.  Where the overlapping bases are the same, the quality of the retained base will be set to the sum of the original quality values; while if they differ it's set to 0.8 times the higher of the two qualities.  So your `a` quality value most likely comes from one of these overlaps.

You can use `samtools mpileup -x` to disable overlap removal.  If you try this, you should see more bases on the line, with quality values more like the original ones.

**Comment by ydLiu-HIT** [comment]
Thank you. It solves my doubts. I have another question, when I use `samtools mpileup -x` to disable overlap removal, whether the total number of base quality ASCII codes will more than the total number of bases if there are overlaps at the ends of some read pairs?

**Comment by daviesrob** [comment]
No, the number of bases and quality values should always be the same.

**Comment by ydLiu-HIT** [comment]
Thank you.  I will close the issue.
