### ISSUE TITLE
`consensus` man page does not describe `-t`/`--qual-calibration` option

### ISSUE THREAD

**Issue by jmarshall** [samtools/samtools#1879]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.

Observed on current **develop** branch.

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

The `samtools consensus` usage says:

```
$ samtools consensus
[…]
  -t, --qual-calibration FILE / :config (see man page)
                        Load quality calibration file
```

However the man page does not describe this option. (It is referred to in the man page's description of `‑X`, `‑‑config`.)

**Comment by jkbonfield** [comment]
I wrote a tool to evaluate instrument data by computing the heterozygous consensus and using the CIGAR alignments to anchor reads to the consensus and work out which SNPs and Indels are probably real and which are probably erroneous, in order to then track instrument specific calibrations for substitutions, insertions and deletions.  It sort of worked, but the auto-tuned calibration never gave the best results and it then needed rounds of manual manipulation. :(

I think I had the use of the calibration data in the wrong place in the algorithm, so it never quite worked as intended.  Maybe I was hoping some day to fix that.  I forget now.  It probably needed to go the other side of heuristic hacking of the quality scores for STRs and the like, or better still to put the same logic into the assessment / tuning tool so the recalibration was valid.

Anyway, we can document the format easily enough.  Thanks for pointing it out.
