### ISSUE TITLE
When I use the 'make' command to install the software, an error is reported

### ISSUE THREAD

**Issue by Lucky-Andy** [samtools/samtools#1898]
The following is the detailed error message from the console:

cd htslib-1.9 && make htslib.pc.tmp
make[1]: Entering directory '/home/haicheng/samtools-1.9/htslib-1.9'
config.mk:2: *** Resolve configure error first.  Stop.
make[1]: Leaving directory '/home/haicheng/samtools-1.9/htslib-1.9'
config.mk:45: htslib-1.9/htslib_static.mk: No such file or directory
make: *** [htslib-1.9/htslib.mk:171: htslib-1.9/htslib.pc.tmp] Error 2

**Comment by daviesrob** [comment]
You're getting the message "Resolve configure error first" because running `./configure` failed.  You'll need to fix that problem before running `make`.  You can find hints on running configure, and how to install dependencies on various systems in the [INSTALL](https://github.com/samtools/samtools/blob/develop/INSTALL) file.

Also, version 1.9 is very old.  You should use the [latest release](https://github.com/samtools/samtools/releases/latest) instead.

**Comment by daviesrob** [comment]
Hopefully you managed to track down the configure error and got this to build.  Please reopen if you're still having trouble.
