### ISSUE TITLE
curses.h missing upon compiling

### ISSUE THREAD

**Issue by dgodin19** [samtools/samtools#1901]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
Version is 1.18
 #### Please describe your environment.
Linux 3.10.0-1160.81.1.el7.x86_64
x86_64
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
After installing samtools, I cd into the directory and type `make`. 

Make gives the error: 

```
bam_tview_curses.c:42:20: fatal error: curses.h: No such file or directory
 #include <curses.h>
                    ^
compilation terminated.
make: *** [bam_tview_curses.o] Error 1
```
I have tried ` yum install ncurses-devel ncurses` , but I am not a root user. This is on an university system, and I am wondering if there is a way around this that doesn't involve being root.

**Comment by jkbonfield** [comment]
Curses is only needed for the `tview` subcommand, which isn't used often so if you can live without it then you build using `./configure && make` it'll automatically detect the absence of curses and build without it.

You can of course download the source code for ncurses yourself and build it, but that's perhaps a step too far for most.  Alternatively if you can wrangle bioconda then binaries are available there, but be sure to check the version that gets installed is the latest one.  (It should be on a new bioconda setup, but it's easy to have an incorrect conda config or to get clashes in the base environment that lead to outdated versions being picked up.)

**Comment by daviesrob** [comment]
Hopefully `./configure && make` worked for you.  Please reopen if that's not the case and you're still having problems.

**Comment by Daisy-Chilin** [comment]
Hi. I also have this same issue were I cannot use sudo due to being a university super computer. 
`./configure && make` did not work me. Is there alternative solution for this ?

This is my command and output/error:
$ ./configure && make --prefix=/mypath/samtools/samtools-1.18 --without-curses
checking for gawk... gawk
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for C compiler warning flags... -Wall
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking location of HTSlib source tree... htslib-1.18
checking for NcursesW wide-character library... no
checking for Ncurses library... no
checking for Curses library... no
configure: error: curses development files not found

The 'samtools tview' command uses the curses text user interface library.
Building samtools with tview requires curses/ncurses/etc development files
to be installed on the build machine; you may need to ensure a package such
as libncurses5-dev (on Debian or Ubuntu Linux) or ncurses-devel (on RPM-based
Linux distributions) is installed.

FAILED.  Either configure --without-curses or resolve this error to build
samtools successfully.

**Comment by jkbonfield** [comment]
> Hi. I also have this same issue were I cannot use sudo due to being a university super computer. `./configure && make` did not work me. Is there alternative solution for this ?
...
> FAILED. Either configure --without-curses or resolve this error to build samtools successfully.

Please see the error message.  `./configure --without-curses` should work.
