### ISSUE TITLE
`ALL_LDFLAGS` should come *after* object file list in Makefile

### ISSUE THREAD

**Issue by bruno-digitbio** [samtools/samtools#1904]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib]
Issue affects all versions of SAMtools.

 #### Please describe your environment.
Issue largely affects users of `ld.gold` (as opposed to the GNU linker). 
```bash
$ uname -a
Linux server-01 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-1 (2023-07-14) x86_64 GNU/Linux
$ gcc --version
gcc (Debian 12.2.0-14) 12.2.0
$ ld --version
GNU ld (GNU Binutils for Debian) 2.40
```

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
The current Makefile cannot be used to build against a static version of HTSlib with a non-ancient version of GCC.

As discussed [here](https://stackoverflow.com/questions/35897290/what-is-the-right-order-of-linker-flags-in-gcc), link options should really always come *after* the object files.

The current order "magically works anyway" when linking shared libraries on most systems, but at least on Debian 12 it simply gives up when the static library is requested:

```bash
$ git diff
diff --git a/config.mk.in b/config.mk.in
index 2e28e7c..240ffc3 100644
--- a/config.mk.in
+++ b/config.mk.in
@@ -50,6 +50,6 @@ LIBS     = @LIBS@
 @Hsource@BGZIP = $(HTSDIR)/bgzip
 HTSLIB_CPPFLAGS = @HTSLIB_CPPFLAGS@
 @Hinstall@HTSLIB_LDFLAGS = @HTSLIB_LDFLAGS@
-@Hinstall@HTSLIB_LIB = -lhts
+@Hinstall@HTSLIB_LIB = -l:libhts.a
$ autoheader
$ autoconf -Wno-syntax
$ ./configure
$ make
<SNIP>
/usr/bin/gcc -o samtools <MANY FLAGS>
dd44be474a39/bin/external/samtools/samtools_build_.ext_build_deps//htslib_build_/lib/libhts.a(hts.o):hts.c:function decompress_peek_xz: error: undefined reference to 'lzma_easy_decoder_memusage'
<MANY SIMILAR undefined references>
```

The patch required to "fix" this should not negatively affect (most) users that still want to link dynamically, since the new flag order will still work for them:
```diff
❯ git diff
diff --git a/Makefile b/Makefile
index 2fff2ed..74202a4 100644
--- a/Makefile
+++ b/Makefile
@@ -142,7 +142,7 @@ LIBST_OBJS = sam_opts.o sam_utils.o bedidx.o bam.o


 samtools: $(AOBJS) $(LZ4OBJS) libst.a $(HTSLIB)
-       $(CC) $(ALL_LDFLAGS) -o $@ $(AOBJS) $(LZ4OBJS) libst.a $(HTSLIB_LIB) $(CURSES_LIB) -lm $(ALL_LIBS) -lpthread
+       $(CC) -o $@ $(AOBJS) $(LZ4OBJS) libst.a $(HTSLIB_LIB) $(CURSES_LIB) -lm $(ALL_LIBS) -lpthread $(ALL_LDFLAGS)

 # For building samtools and its test suite only: NOT to be installed.
 libst.a: $(LIBST_OBJS)
@@ -249,28 +249,28 @@ check test: samtools $(BGZIP) $(TEST_PROGRAMS)


 test/merge/test_bam_translate: test/merge/test_bam_translate.o test/test.o libst.a $(HTSLIB)
-       $(CC) $(ALL_LDFLAGS) -o $@ test/merge/test_bam_translate.o test/test.o libst.a $(HTSLIB_LIB) $(ALL_LIBS) -lpthread
+       $(CC) -o $@ test/merge/test_bam_translate.o test/test.o libst.a $(HTSLIB_LIB) $(ALL_LIBS) -lpthread $(ALL_LDFLAGS)

 test/merge/test_rtrans_build: test/merge/test_rtrans_build.o test/test.o libst.a $(HTSLIB)
-       $(CC) $(ALL_LDFLAGS) -o $@ test/merge/test_rtrans_build.o test/test.o libst.a $(HTSLIB_LIB) $(ALL_LIBS) -lpthread
+       $(CC) -o $@ test/merge/test_rtrans_build.o test/test.o libst.a $(HTSLIB_LIB) $(ALL_LIBS) -lpthread $(ALL_LDFLAGS)

 test/merge/test_trans_tbl_init: test/merge/test_trans_tbl_init.o test/test.o libst.a $(HTSLIB)
-       $(CC) $(ALL_LDFLAGS) -o $@ test/merge/test_trans_tbl_init.o test/test.o libst.a $(HTSLIB_LIB) $(ALL_LIBS) -lpthread
+       $(CC) -o $@ test/merge/test_trans_tbl_init.o test/test.o libst.a $(HTSLIB_LIB) $(ALL_LIBS) -lpthread $(ALL_LDFLAGS)

 test/split/test_count_rg: test/split/test_count_rg.o test/test.o libst.a $(HTSLIB)
-       $(CC) $(ALL_LDFLAGS) -o $@ test/split/test_count_rg.o test/test.o libst.a $(HTSLIB_LIB) $(ALL_LIBS) -lpthread
+       $(CC) -o $@ test/split/test_count_rg.o test/test.o libst.a $(HTSLIB_LIB) $(ALL_LIBS) -lpthread $(ALL_LDFLAGS)

 test/split/test_expand_format_string: test/split/test_expand_format_string.o test/test.o libst.a $(HTSLIB)
-       $(CC) $(ALL_LDFLAGS) -o $@ test/split/test_expand_format_string.o test/test.o libst.a $(HTSLIB_LIB) $(ALL_LIBS) -lpthread
+       $(CC) -o $@ test/split/test_expand_format_string.o test/test.o libst.a $(HTSLIB_LIB) $(ALL_LIBS) -lpthread $(ALL_LDFLAGS)

 test/split/test_filter_header_rg: test/split/test_filter_header_rg.o test/test.o libst.a $(HTSLIB)
-       $(CC) $(ALL_LDFLAGS) -o $@ test/split/test_filter_header_rg.o test/test.o libst.a $(HTSLIB_LIB) $(ALL_LIBS) -lpthread
+       $(CC) -o $@ test/split/test_filter_header_rg.o test/test.o libst.a $(HTSLIB_LIB) $(ALL_LIBS) -lpthread $(ALL_LDFLAGS)

 test/split/test_parse_args: test/split/test_parse_args.o test/test.o libst.a $(HTSLIB)
-       $(CC) $(ALL_LDFLAGS) -o $@ test/split/test_parse_args.o test/test.o libst.a $(HTSLIB_LIB) $(ALL_LIBS) -lpthread
+       $(CC) -o $@ test/split/test_parse_args.o test/test.o libst.a $(HTSLIB_LIB) $(ALL_LIBS) -lpthread $(ALL_LDFLAGS)

 test/vcf-miniview: test/vcf-miniview.o $(HTSLIB)
-       $(CC) $(ALL_LDFLAGS) -o $@ test/vcf-miniview.o $(HTSLIB_LIB) $(ALL_LIBS) -lpthread
+       $(CC) -o $@ test/vcf-miniview.o $(HTSLIB_LIB) $(ALL_LIBS) -lpthread $(ALL_LDFLAGS)

 test_test_h = test/test.h $(htslib_sam_h)

@@ -291,7 +291,7 @@ check-all test-all: test-htslib test
 # misc programs

 misc/ace2sam: misc/ace2sam.o $(HTSLIB)
-       $(CC) $(ALL_LDFLAGS) -o $@ misc/ace2sam.o $(HTSLIB_LIB) $(ALL_LIBS)
+       $(CC) -o $@ misc/ace2sam.o $(HTSLIB_LIB) $(ALL_LIBS) $(ALL_LDFLAGS)

 misc/maq2sam-short: misc/maq2sam-short.o
        $(CC) $(LDFLAGS) -o $@ misc/maq2sam-short.o $(ALL_LIBS)
@@ -300,13 +300,13 @@ misc/maq2sam-long: misc/maq2sam-long.o
        $(CC) $(LDFLAGS) -o $@ misc/maq2sam-long.o $(ALL_LIBS)

 misc/md5fa: misc/md5fa.o $(HTSLIB)
-       $(CC) $(ALL_LDFLAGS) -o $@ misc/md5fa.o $(HTSLIB_LIB) $(ALL_LIBS)
+       $(CC) -o $@ misc/md5fa.o $(HTSLIB_LIB) $(ALL_LIBS) $(ALL_LDFLAGS)

 misc/md5sum-lite: misc/md5sum-lite.o $(HTSLIB)
-       $(CC) $(ALL_LDFLAGS) -o $@ misc/md5sum-lite.o $(HTSLIB_LIB) $(ALL_LIBS)
+       $(CC) -o $@ misc/md5sum-lite.o $(HTSLIB_LIB) $(ALL_LIBS) $(ALL_LDFLAGS)

 misc/wgsim: misc/wgsim.o $(HTSLIB)
-       $(CC) $(ALL_LDFLAGS) -o $@ misc/wgsim.o -lm $(HTSLIB_LIB) $(ALL_LIBS)
+       $(CC) -o $@ misc/wgsim.o -lm $(HTSLIB_LIB) $(ALL_LIBS) $(ALL_LDFLAGS)

 misc/ace2sam.o: misc/ace2sam.c config.h $(htslib_kstring_h) $(htslib_kseq_h)
 misc/md5fa.o: misc/md5fa.c config.h $(htslib_kseq_h) $(htslib_hts_h)
 ```
 
With `$(ALL_LDFLAGS)` suffixing the compiler command, the same `make` command above succeeds.

Happy to submit a PR, but wanted to gauge interest in accepting such a patch and ask what types of testing would be required before blindsiding anyone with a PR out of the blue! :)

**Comment by daviesrob** [comment]
I don't think this is correct.  The linker requires that libraries come after the object files that need to link against them, and that does happen in samtools' Makefile.  It's also necessary for any path-related options like `-L/library/dir` appear before the `-l` library options as otherwise the linker will not search for libraries in the desired locations.  Therefore `$(ALL_LDFLAGS)` needs to come at least before `$(ALL_LIBS)`.  Note that `$(ALL_LIBS)` includes `$(LIBS)`, which starts out empty.  You should use `LIBS` if you want to add extra libraries to the link, while `LDFLAGS` should only be used for non-library options like search paths.

It looks like you're trying to link against the static `libhts.a` in an installed copy of HTSlib.  SAMtools configure currently doesn't support that as it expects to use the shared library and therefore makes no attempt to add HTSlib's dependencies when linking the programs that it's building.  If we did want to support this, we'd need to alter [m4/ax_with_htslib.m4](https://github.com/samtools/samtools/blob/develop/m4/ax_with_htslib.m4) to make it pull the `static_ldflags` and `static_libs` lines out of the `lib/pkgconfig/htslib.pc` file in the installed directory to get the information it needs to complete the link.

If you do want to link statically against `libhts.a` then the supported way to do this is to build against an HTSlib source tree.  You can either configure and make (but don't install) HTSlib separately and then point SAMtools to it using `./configure --with-htslib=/path/to/htslib/source`; or you can put the htslib directory in the top level of your samtools source tree, in which case samtools' `./configure` will automatically find it and configure htslib for you (this is how the release tarballs work).
