### ISSUE TITLE
Any plans to use lz4 to compress temporary files?

### ISSUE THREAD

**Issue by karlestira** [samtools/samtools#1914]
#### Is your feature request related to a problem? Please specify.
In some case, the samtools sort still looks slow when using temporary files.

#### Describe the solution you would like.
Is any plans to give a choice to use lz4 to compress temporary bam file?
I know this may cause some problem(such as index). But you can disable index function when lz4 used, and I think there is no need to build index on samtools sort's temporary files.

**Comment by whitwham** [comment]
We did do a test version using lz4 to compress temporary files.  The speed gains were modest and the tmp files took up more space.  At the time we did not think trade off was worth it.

**Comment by karlestira** [comment]
ok, so lz4 is just so so~, I think I may need SSD to speed up samtools sort.

**Comment by jkbonfield** [comment]
If you're not using a recent version of samtools, it's worth upgrading too.  Various speed ups to sort occurred in 1.16 I believe, in particular in handling many temp files.

The other thing that will speed up sort is giving it more memory.  If you have the spare memory, then it's far better to use it instead of spilling temp files to disk.  I assume you're already doing that though.

**Comment by karlestira** [comment]
> If you're not using a recent version of samtools, it's worth upgrading too. Various speed ups to sort occurred in 1.16 I believe, in particular in handling many temp files.
> 
> The other thing that will speed up sort is giving it more memory. If you have the spare memory, then it's far better to use it instead of spilling temp files to disk. I assume you're already doing that though. (Remember memory specified is per thread.)

Thank you, I'm using 1.15, 20 thread and 1G mem for each of them, I will try the lastest version.
