### ISSUE TITLE
samtools view: "Numerical result out of range"

### ISSUE THREAD

**Issue by gevro** [samtools/samtools#1923]
Hi,
With samtools version 1.18, I'm getting a strange error. On a 34 Gb BAM file, I'm getting this error when it outputs about 32 Gb.

```samtools view -b input.bam > output.bam```
input.bam -> size = 34438358191 (34 Gb)
output.bam -> size after error occurs = 32025153027 (32 Gb)

Error:
```
samtools view: error reading file "input.bam": Numerical result out of range
```

I can see what the last read is in output.bam, but I don't see anything wrong with it. And I have no idea how to retrieve the subsequent read in input.bam to track down what read is causing this fatal error.

Note: I tried running samtools view with a higher log level, but it is not outputting any extra information.

**Comment by jkbonfield** [comment]
It's probably the length of a chromosome.  BAM can't handle chromosomes longer than 2GB.  What's the longest chromosome in your header's `@SQ` lines?

**Comment by gevro** [comment]
I checked for that already, and the largest contig in @SQ is ~25 kb. Much less than the limit.

I just isolated the bad set of reads (using a ZMW filter, since it is a PacBio BAM file) on its own in a small BAM file, but I can't actually see what the issue is because samtools view crashes immediately.

Do you have an e-mail address I can send it to if you are able to take a look?

**Comment by jkbonfield** [comment]
If it's small, jkb at sanger.ac.uk will work directly, but for anything sizeable it's probably easier to host it somewhere and send me the link.

It's possible it could also be a numeric tag.  Eg XX:i:999999999999.  They have to fit within 32-bit for BAM, but obviously in text they can be anything.

**Comment by jkbonfield** [comment]
Thanks for the sample data.

The problem is you have a malformed BAM file. 

The BAM header has a textual string representation, the same as in SAM, and a binary list of chromosome names and lengths.  The number of `@SQ` lines is 125214, which is also the same as the binary `n_ref` value in the header.  That all matches.  However the `refID` field ("tid" in htslib code) is required to be `>= 0 and < n_ref`.  The read you sent me has this as 125214, which triggers an error.

I cannot read your file with htslib/samtools, Picard, nor Scramble.  Picard gives a better error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Reference name for '125214' not found in sequence dictionary.
```

Hacking the htslib source code allows me to read this file (and accompanying increase in memory allocation):

```
static inline int sam_read1_bam(htsFile *fp, sam_hdr_t *h, bam1_t *b) {         
    int ret = bam_read1(fp->fp.bgzf, b);                                        
    if (h && ret >= 0) {                                                        
        if (b->core.tid  >= h->n_targets || b->core.tid  < -1 ||                
            b->core.mtid >= h->n_targets || b->core.mtid < -1) {                
            //errno = ERANGE;                                                   
            //return -3;                                                        
            h->target_name[h->n_targets] = "?";                                 
        }                                                                       
    }                                                                           
    return ret;                                                                 
}                                                                               
```

Sure enough the read gets printed up, with "?" as the chromosome.

How was the file produced?  Has it gone through some reheader tool at some point?

Either way, this isn't a samtools issue as every BAM implementation I've tried is, correctly, rejecting the file as being invalid.

**Comment by gevro** [comment]
Thank you very much for checking! The file was made by [actc](https://github.com/PacificBiosciences/actc). I will follow-up with that to see if we can figure out the root cause.
