### ISSUE TITLE
BAM Sequencing Integrity Hash

### ISSUE THREAD

**Issue by hammad93** [samtools/samtools#1935]
#### Is your feature request related to a problem? Please specify.

If I wanted to be sure if a BAM or related file is exactly the same with any alterations, I can use hashing algorithms. There exist some popular ones,
- MD5
- SHA256

#### Describe the solution you would like.
https://github.com/hammad93/BAM-integrity-hash/tree/main

I utilized MD5 because it is faster than SHA256 and is sufficient.

**Comment by jkbonfield** [comment]
Is it like this:  https://manpages.debian.org/unstable/biobambam2/bamseqchksum.1.en.html

I believe we use this locally to offer similar functionality, but there has been discussion about having something native to samtools too.  That tool allows us to compute sequence and quality checksums on FASTQs or unaligned bams, and then post alignment, sorting, and various other steps recompute it again to ensure all the data is still present and correct.  (It did spot errors too, which turned out to be hardware memory corruptions.)

**Comment by jkbonfield** [comment]
I'm closing this as there was no reply to my initial comment and looking at the python code it appears to be little more than the "md5sum" command line utility.  That already exists, so I do not see a need for reinventing it in samtools.
