### ISSUE TITLE
Clarification on improvements brought by libdeflate

### ISSUE THREAD

**Issue by SHuang-Broad** [samtools/samtools#1940]
#### Is your feature request related to a problem? Please specify.

No, there is no problem encountered.
This is more likely to be classified as a documentation/WiKi request.

#### Describe the solution you would like.

The following comment made in #1931 got me curious

> Finally, do try to use the latest version where possible, and to ensure it is compiled with libdeflate support. Both of these can give considerable performance gains over old versions.

After some searching in `Issues`, there doesn't seem to be many discussions about `libdeflate`'s impact specifically. 
And the library isn't mentioned in [INSTALL](https://github.com/samtools/samtools/blob/develop/INSTALL) either (except in the Windows section).

Can you please offer a bit more details? E.g. any benchmarking?
How should one update the installation script to compile with `libdeflate`?

Thanks!
Steve

(also cc @rlorigro)

**Comment by jkbonfield** [comment]
There are some old benchmarks here:  https://www.htslib.org/benchmarks/zlib.html
I think libdeflate has had further speed improvements since then as well.

Libdeflate isn't a requirement, but we should probably improve the INSTALL notes with a recommended section.  Thanks for the idea.

The [htslib INSTALL](https://github.com/samtools/htslib/blob/develop/INSTALL#L178-L182) notes give more details on enabling it.
