### ISSUE TITLE
-d option behaves differently  between samtools fastq and view modes

### ISSUE THREAD

**Issue by TristanLefebure** [samtools/samtools#1958]
Hello

Say you have a BAM file produced by dorado with reads having different dx tags (1, 0, or -1)
If you do :

```bash
samtools fastq -d dx:1 -d dx:0 BAMFILE
samtools view -d dx:1 -d dx:0  BAMFILE | samtools fastq
```
You are not getting the same output. It seems that the -d option within the fastq mode only considers the latest -d call, while the view mode aggregates all the calls. The latest sound much better...

Regards,

Version:
samtools 1.18
Using htslib 1.18

**Comment by jkbonfield** [comment]
I can confirm this is the case.  `samtools view` uses a hash table and permits multiple options to be specified.  I hadn't really considered multiple uses of `-d` as something that view permitted, and it's not documented as allowing this.   I assume this is because of the addition of the `-D` option (which specifies multiple tags from a file) made this the natural way to implement the single tag option too. 

I did consider this at the time of adding `-d` to `fastq` (see https://github.com/samtools/samtools/issues/1854#issuecomment-1607744629), but there was silence on the question so I took the simple solution given no demand for anything more complex.

How important is it to have `-D` style functionality (and improving `-d` in the process since it's essentially the same deal) for `samtools fastq`?  I can see it's nice for consistency though.

**Comment by TristanLefebure** [comment]
I do have a user case where this would be useful: the latest nanopore basecaller (Dorado) produces a single BAM file containing duplex reads (~Q30) and simplex reads (~Q15, those producing the duplex and those not producing duplex), all of which have different dx tag values (1, 0 or -1; [dorado duplex documentation](https://github.com/nanoporetech/dorado#duplex)).  Depending on what you want to do downstream, you may only want the duplex, the duplex and simplex without redundancy, ... and since most tools require inputs in FASTQ, you also want to go from BAM to FASTQ. A single tool to do these 2 steps is convenient. The -D option could be used, though I find it less appealing and more prone to mistakes (I prefer to have all the program options centralized in a single script or snakemake file, I find it easier to read and to deploy). I actually prefer to pipe `samtools view` into `samtools fastq`, than using the -D option. 

I found this issue because I mistakenly thought that the -d option would behave the same way in `view` and `fastq`. I think that `samtools` managed to keep a coherent user interface over the years, and this can be viewed as a little setback. If you keep the actual behavior, it should be better documented; right now `samtools view -d` and  `samtools fastq -d` documentations are quite similar:

`  -d, --tag STR1[:STR2]      ...have a tag STR1 (with associated value STR2)`
```
  -d, --tag TAG[:VAL]
               only include reads containing TAG, optionally with value V
```



Best,
