### ISSUE TITLE
Output directory for split

### ISSUE THREAD

**Issue by mbhall88** [samtools/samtools#1965]
It would be nice to have an option in `split` to specify the directory to place the output files in.

**Comment by daviesrob** [comment]
You can do this using the `-f` option, for example:

```
samtools split -f '/tmp/out-%#.bam' -u /tmp/out-leftover.bam in.bam
```

where `%#` is the index of the read group in the header (you can also use `%!` for the read group ID).

Note that if you're using the `-d` option to split on an alternate tag, you must (in samtools version 1.19) put the `-f` option _after_ `-d` or it will be overridden.  Hopefully that bug will be fixed in the next release.

**Comment by mbhall88** [comment]
Ahhh can’t believe I didn’t think of that!  Thanks
