### ISSUE TITLE
Samtools 1.19 bam-cram conversion produce cram bigger than bam

### ISSUE THREAD

**Issue by Clockris** [samtools/samtools#1968]
Hi,

I am opening this issue because I experienced a wired Samtools behavior: when I try to convert a bam to a cram, I get a cram slightly bigger than the original bam. The following is the code I run

`samtools view -C --output-fmt-option store_md=1 --output-fmt-option store_nm=1 input.bam -T ref.bgz -O cram,version=3.1 -o output.cram`

I experienced this issue using Samtools 1.19, while when I am using an older version (I tested 1.17, 1.15, 1.13) the output cram is 50% smaller than the bam (as expected). The issue does not seem to be related with the cram version: I tried the 3.0 and the 3.1 versions.

Other information that could be relevant:
- when I reconvert the information from cram to bam (with Samtools 1.19) the last two columns are switched
- the bam I am talking about has been created with an old version of Samtools (1.17) 

Do you have any idea why this happen and how overcome the problem? 

Thanks,

Cristiano

> htslib
> I am using htslib 1.19
> 
> OS
> Linux based operative system (RedHat 9.2)
> 
> Machine architecture
> x86_64
> 
> Compiler
> I tried the galaxy singularity image and conda installation

**Comment by Clockris** [comment]
Hi jkbonfield,

thanks for your answer, here it is the output of 

```
samtools cram-size bam_converted_with_samtools1.17.cram
#   Content_ID  Uncomp.size    Comp.size   Ratio Method  Data_series
BLOCK     CORE            0            0 100.00% .      
BLOCK       11    959085164    164166093  17.12% n       RN
BLOCK       12   1743475250    575925643  33.03% 1       QS
BLOCK       13        18390        17935  97.53% .20     IN
BLOCK       15     48601090      6114094  12.58% 20      BF
BLOCK       17     53556911     41429617  77.36% 0_g.    AP
BLOCK       19     48601090      6215113  12.79% 00.     MQ
BLOCK       25     48601090      1914620   3.94% 0       RL
BLOCK       26     48601090      3715585   7.65% 01.     FN
BLOCK       27      6724813       227880   3.39% 02.     FC
BLOCK       28      6730175      4501712  66.89% 0_g.    FP
BLOCK       29        39411        23211  58.89% 2.0     DL
BLOCK       30        42375        35247  83.18% .20     BA
BLOCK       31      6626151      1410050  21.28% 01.     BS
BLOCK       32     48601090      1751991   3.60% 10.     TL
BLOCK  5063770    209830694     18787845   8.95% 1.      MDZ
BLOCK  5131619     48601090      3719535   7.65% 01.     NMc
BLOCK  5261146    777617440       492033   0.06% 1       PGZ
BLOCK  5779555     48601090        29225   0.06% 2       X0c
BLOCK  5779779        75175        74863  99.58% .0      X1C
BLOCK  5779811     48525915      6339248  13.06% 00g2.   X1c
BLOCK  5783898     99442580     25010140  25.15% g       XAZ
BLOCK  5785443     48601090       247007   0.51% 0120    XGc
BLOCK  5786979     48601090      3679696   7.57% 01.     XMc
BLOCK  5787235          275          219  79.64% .02     XNc
BLOCK  5787491     48601090       236643   0.49% 012     XOc
BLOCK  5788737     48601090        29225   0.06% 2       XTA

Number of containers                4871
Number of slices                    4871
Number of sequences             48601090
Number of bases               1743475250
Total file size                870391950
Format overhead size             4297480
```

while here there is the output of 

```
samtools cram-size bam_converted_with_samtools1.19.cram
#   Content_ID  Uncomp.size    Comp.size   Ratio Method  Data_series
BLOCK     CORE            0            0 100.00% .      
BLOCK       11    959085164    164166093  17.12% n       RN
BLOCK       12   1743475250    576772864  33.08% 51      QS
BLOCK       13        18390        17935  97.53% .20     IN
BLOCK       15     48601090      6114094  12.58% 20      BF
BLOCK       17     53556911     41429617  77.36% 0_g.    AP
BLOCK       19     48601090      6215113  12.79% 00.     MQ
BLOCK       25     48601090      1914620   3.94% 0       RL
BLOCK       26     48601090      3715585   7.65% 01.     FN
BLOCK       27      6724813       227880   3.39% 02.     FC
BLOCK       28      6730175      4501875  66.89% 0_g.    FP
BLOCK       29        39411        23211  58.89% 2.0     DL
BLOCK       30        42375        35247  83.18% .20     BA
BLOCK       31      6626151      1410050  21.28% 01.     BS
BLOCK       32     48601090      1751991   3.60% 10.     TL
BLOCK  5063770    209830694    209830694 100.00% .       MDZ
BLOCK  5131619     48601090     48601090 100.00% .       NMc
BLOCK  5261146    777617440    777617440 100.00% .       PGZ
BLOCK  5779555     48601090     48601090 100.00% .       X0c
BLOCK  5779779        75175        75175 100.00% .       X1C
BLOCK  5779811     48525915     48525915 100.00% .       X1c
BLOCK  5783898     99442580     99442580 100.00% .       XAZ
BLOCK  5785443     48601090     48601090 100.00% .       XGc
BLOCK  5786979     48601090     48601090 100.00% .       XMc
BLOCK  5787235          275          275 100.00% .       XNc
BLOCK  5787491     48601090     48601090 100.00% .       XOc
BLOCK  5788737     48601090     48601090 100.00% .       XTA

Number of containers                4871
Number of slices                    4871
Number of sequences             48601090
Number of bases               1743475250
Total file size               2239728296
Format overhead size             4333502
```

**Comment by jkbonfield** [comment]
It appears to have done no compression of PG:Z and MD:Z (amongst others).  That seems odd indeed.  Maybe it auto-tuned incorrectly, but I'm unsure why it would think they don't need compressing.  Is the data public?

**Comment by Clockris** [comment]
The data have been generated from a public fastq I got from GEO (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2258718 and https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2258719) that have been merged first and then aligned to hg38 genome. I can try to reproduce the same error on a public dataset.

**Comment by jkbonfield** [comment]
I can reproduce this on our own data.  Pretty much any file triggers it!  Horror...

Odd that we didn't spot this.  1.18 is fine.  I'll bisect the commits and see what broke it.  Thanks for the bug report.

**Comment by Clockris** [comment]
Can you provide me/us a patched version of Samtools1.19 where this bug has been fixed? Thanks!

**Comment by jkbonfield** [comment]
Current develop of Samtools and Htslib would work.  We're putting together a 1.19.1 currently,  hopefully today.  Sorry it's been slow to do.  (We really need to get better at rapid point releases for major bug fixes)

**Comment by jkbonfield** [comment]
It's now been released.  Thanks for reporting this bug.

**Comment by Clockris** [comment]
Sorry, 

I tried cloning the Samtools developer repository, I compiled it, but the bug it is still there and the output cram has the same size of the bam. While, if I compiled the htslib patched and I link it to Samtools at the configuring step through `--with-htslib` the output cram is actually ~50% smaller than the bam (as expected).

Should I clone a different version of Samtools?

Thanks.

**Comment by gpertea** [comment]
I  am not sure if this was fully fixed or it's a totally different issue. I keep running into this problem with _some_ of my samples aligned with HISAT2 using `-k 60` (so some reads have tens of alignments reported).  I also store the unaligned reads in the CRAM file, and the mapping rate is relatively low (the HISAT2 alignment summary is attached).  
The unsorted CRAM file has 11G (written with `-O cram,version=3.1`, but after sorting, the CRAM file becomes 27G (with the same output options), or 29G with just `view -C` option. 

Converting the same unsorted CRAM  file to BAM it has 19G, and the sorted BAM has 30G.  All these files were obtained with v1.20 of samtools and htslib, and the same genome reference sequence was used for the CRAM files, but it's as if the reference sequence is not being used in the case of the sorted CRAM file.  Yet I do not see any warning message about that. 

Besides the alignment summary, I attached  the outputs of `samtools cram-size -v` for the unsorted and sorted CRAM files.

[R3580_C4CK7ACXX_AGCGATAG_L00_001_trimmed.align_summary.txt](https://github.com/user-attachments/files/15875170/R3580_C4CK7ACXX_AGCGATAG_L00_001_trimmed.align_summary.txt)

[cram-size.v.unsorted.txt](https://github.com/user-attachments/files/15875183/cram-size.v.unsorted.txt)
[cram-size.v.sorted.txt](https://github.com/user-attachments/files/15875185/cram-size.v.sorted.txt)

**Comment by jkbonfield** [comment]
I am guessing given the many repeated sequences that they are possibly secondaries rather than supplementaries and you therefore have a lot of totally duplicated strings of quality scores.  When name-sorted they're adjacent and LZ compression works well (hence gzip).  When position sorted they're spread all over the file and no qual-dedup is possible.  To a lesser extent the same also applies to read names and soft-clipped sequence.  This is the fundamental cause of pos-sorted being so much bigger than name-sorted for both CRAM and BAM and there's very little you can do to prevent that, however the impact can be reduced.

The qualities in pos-sorted CRAM are consuming 21GB, which is huge!  You have ~68GB of base calls and they're using <600MB of storage, so it is using reference based compression.  It's just everything else which has bloated it enormously.

What does one of your quality strings look like?  I am assuming it's "full fat" without any binning and having a lot of discrete values.  It's using ~3bits per quality value, so it's definitely not something like Illumina NovaSeq as the most naive encoding would be 2-bits.   Is it really necessary to store full quality values?  What's the sequencing platform?

Also for all your secondary alignments, is it storing the full sequence with soft-clips, or is it storing only the aligned portion and using hard-clips?  The latter is the technique used by many tools (including bwa) to avoid unnecessary bloat.    I'm assuming given the relatively small size of "SC" (soft clips) that it's hard clipping, but then I don't see an HC data series.  Maybe most reads are aligning nearly full-length in many places.  What sort of library type is this?

PS.  This is a totally different problem to the issue you posted too.  Please don't add new things on to old tickets like this as it makes tracking them hard.  (Ie we may just forget about it entirely as it's already "closed" and therefore needs no further action.)

**Comment by gpertea** [comment]
Thank you so much for the detailed reply and taking a look at my data above, despite my wrong posting, I am very grateful.

To be fair, it may be a strange coincidence that I began noticing this issue with my samples when 1.19 was first released and this issue was posted which I followed closely and I thought it was the real cause. 

Before that I had mostly used your excellent `scramble` tool for better CRAM support/conversion, which was performing qv binning (`-B`) and I used other storage/compression optimization options that did not seem to have been integrated in samtools (at least the last time I had checked samtools CRAM support, which was way before 1.18 admittedly). 

Another surprising fact that apparently tied my problem with this issue is that the sorted CRAM file is only 1GB smaller than the BAM file.
Since 91% of the reads are aligned, it was hard for me to wrap my head around the fact that reference-based compression of read alignments can only account for 1GB in storage savings, compared to the BAM file..  
 
But I can see now there are many other issues that affect the compressibility of data blocks when the file is sorted, mostly the broken redundancy of the qv data, which indeed I do not even need stored in full (or at all, for most of my RNAseq processing needs..).

This is an old TruSeq Stranded Total RNA Library, RiboZero Gold (rRNA depletion). 
There is no HC, only SC, as you noticed, so the full read sequence is there for every alignment. The qvs are just as they come from the SAM output of HISAT2 which I plainly convert to CRAM using samtools.

I guess I was expecting too much in terms of storage optimization from samtools' CRAM conversion, e.g. for the unsorted file to store the qv (maybe even the sequence) only for the first alignment of a read etc.  But I can see how such "optimization" can become an issue when the file is sorted. 

For high multi-mapped data (with only SC reads) like I have, it would be great if maybe the CRAM format would have an option to store the sequence and qv data only once per read, even for sorted files (only keep those for the first alignment of a read in the file, while all the other records for that same read would store some kind of reference to that first record, for full sequence and qv data retrieval only when those are really needed, e.g. for a MSA display, SNV calling etc.)

**Comment by jkbonfield** [comment]
My understanding of TruSeq is that it's Illumina specific. Pretty much all modern Illumina machines have heavy quality binning.  Yet your quality values appear to be quite bad at compression.

In the past I know people used things like GATK's BQSR to modify quality values, but this had the unfortunate side effect of broadly scramblng them and making them vastly less compressible.  Locally some groups found it was also of no benefit to variant calling so I don't think it often gets used now.  Also, the modern way of applying BQSR is to leave the qualities intact and provide a mapping table which gets applied on-the-fly.

Fundamentally though, CRAM isn't magic and no compression tool can compress random looking data well, at least not beyond the "shape" of the random distribution being applied. Is it possible to see a couple of your quality strings?  So the more random the data the more similar CRAM and BAM are likely to become.

The latter part of your reply is an aligner issue.  Many aligners already have options for governing what data to retain.  Even down to writing "*" in both SEQ and QUAl and just providing a dummy alignment for location data only.  This is really an issue to take up with the HiSat team if they don't already support it.
