### ISSUE TITLE
samtools merge BAM from different aligners

### ISSUE THREAD

**Issue by ckuanglim85** [samtools/samtools#2015]
Let say I align a RNA-Seq FASTQ to a reference genome using 3 different alignment software. I get 3 alignment BAM/SAM. The purpose of doing this is to increase the sensitivity and alignment rate. Then I want to merge the output of 3 aligners. Many reads ID are definitely duplicate, and it needed to be collapsed. It should not affect the read count and normalization calculation in following analysis. The merged BAM/SAM will be used for expression analysis.

How should I run samtools merge and what are the parameter to consider?
Thank you.

**Comment by jkbonfield** [comment]
This doesn't seem like the sort of thing we'd want to implement, as it's questionable as to whether this is the correct approach and there are lots of corner cases.  How do you resolve conflicts?  What happens if the same read is aligned in two entirely different chromosomes? etc.

If you're just attempting to improve sensitivity then maybe align with a fast but accurate aligner that may miss some alignments.  Then split out the aligned from the unaligned records (eg `samtools view -F -U ...` ) and then convert the unaligned data back to fastq (if the aligner doesn't accept SAM) and realign the unaligned data only with a 2nd tool (eg a more sensitive by slower tool).  That can give you a speed up while retaining sensitivity.

Attempting to align everything 3 times over simply sounds like a large amount of extra CPU time with a lot of questions to resolve when disparities happen.

**Comment by ckuanglim85** [comment]
Thanks. You're right. It will be conflicts between aligners.

As for your suggestion, mapping with a first aligner, followed by mapping the unaligned reads with a second aligner. And then merge the two output with samtools merge. In this case, any parameter that I need to specify in samtools merge?

**Comment by jkbonfield** [comment]
As long as you've done appropriate filtering and every read occurs exactly once across all of your files, then it should work provided all the files have the same sort order.  Note that may depend on aligners, particularly multi-threading ones.  Some preserve input order while some shuffle.  If they're shuffled so the files may not be in the same ordering, you'd need to sort them before merging.

However you probably want to position sort at some point anyway so it'd be easier to position sort your separate unmerged files and merge in position order (the default) than to do name sort, merge, then position sort.
