### ISSUE TITLE
[E::aux_parse] unrecognized type ':'

### ISSUE THREAD

**Issue by chilampoon** [samtools/samtools#2041]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
```
samtools 1.19.2
Using htslib 1.19.1
Copyright (C) 2024 Genome Research Ltd.
```
 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

```
$ uname -sr
Linux 3.10.0-957.12.2.el7.x86_64

$ uname -m
x86_64

$ gcc --version
gcc (conda-forge gcc 13.2.0-6) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
```

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I ran the minimap2 short read mode:

```
minimap2 -y -ax sr --secondary=no -t 14 /data/reference/genome.fa /data/fastqs/MIG_r1_R1_001.fastq.gz /data/fastqs/MIG_r1_R2_001.fastq.gz

samtools view MIG_r1.sam
[E::aux_parse] unrecognized type ':'
[W::sam_read1_sam] Parse error at line 28
samtools view: error reading file "MIG_r1.sam"
```

that line 28 is the alignment
```
A01494:319:HNNK7DSX7:3:1101:4490:1000	97	chr2	218731124	60	10S91M	=	218739743	8722	AGGTGTTCATGCAGGAGTTCAAAGAAGGACGCAGAGCCAGCCACACAGCCCCACAGGTCCTCTTTAGCCACAGGGAACCTCCTCTGGAGCTGAAAGACACA	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:0	ms:i:182	AS:i:182	nn:i:0	tp:A:P	cm:i:12	s1:i:88	s2:i:0	de:f:0	rl:i:0	1:N:0:TAAGATTA+AGCCTGCG
```
seems like it's one of the tags raises the parse error..?

**Comment by jkbonfield** [comment]
Yes, this `1:N:0:TAAGATTA+AGCCTGCG` is an Illumina CASAVA barcode sequence.  Your input fastq likely had a mix of aux tags and the CASAVA tags mixed together.

This is a processing problem therefore.  You may need extra options to get minimap2 to handle CASAVA fastq format, but it's not something I know much about.  It's not a samtools problem though (it is correctly reporting the malformed data).

**Comment by chilampoon** [comment]
actually i just noticed i specified `-y` that passes `1:N:0:TAAGATTA+AGCCTGCG` from fastq to output, I think if I don't specify -y maybe it'd be fine

**Comment by chilampoon** [comment]
Yes it's exactly that Illumina CASAVA barcode raises the error in SAM, but if samtools can handle that ':' it might be better.. thanks!

**Comment by jkbonfield** [comment]
The SAM format you've created is invalid.  This isn't a samtools issue and samtools/htslib should not be going out of their way to support invalid data.

If you feel this should work fine, then you can try submitting a minimap2 issue as this is the correct place to add CASAVA support.  That way it could parse the FASTQ headers and generate correct SAM files with the CASAVA string correctly converted to their SAM barcode tags.

**Comment by colindaven** [comment]
I think this issue might come up a lot now because with ONT methylation, you must run `minimap2 -y` to pass on the full fastq header with methylation tags (MM and ML from memory).

So is there a way to turn off the SAM aux format parsing, or do I need to write alternative processes in my nextflow alignment to align either standard fastqs (`minimap, no -y`) or methylation fastqs (`minimap -y`).

**Comment by jkbonfield** [comment]
We can't turn off SAM aux format parsing as the output with a CASAVA string in the middle of the aux fields would just break everything (not just samtools, but most related bioinformatics tools).   Plus you'd be committing yourself to only ever using SAM as it's not even possible to store that broken non-SAM in BAM or CRAM.

The problem lies elsewhere and I suggest you raise the issues there.  Alternatively, preprocess your data to either remove CASAVA tags or to rewrite them in their SAM tag equivalents.
