### ISSUE TITLE
Progress monitor

### ISSUE THREAD

**Issue by chaplin89** [samtools/samtools#2065]
#### Is your feature request related to a problem? Please specify.
No.

#### Describe the solution you would like.
Hi,

I'm doing some black magic tricks to be able to provide a progress bar in my tool when I'm launching some samtools tasks (i.e., I'm starting a thread to monitor I/O stats on the samtools process and comparing these stats to what I estimate it would be the total I/O needed for the process to complete). Unless I'm missing something, samtools/htslib/bcftools don't seem provide any native way to monitor the progress of activities that can go on for several hours. Is there a reason for that? Would there be any interest in implementing something like that?

Thanks,
Marco

**Comment by whitwham** [comment]
No, we don't provide any way to track progress in any of our programs.  This is partly because we expect samtools to be run as a batch job (or part as a pipeline or similar) a lot of the time with no one to monitor the progress.  It is also quite hard to do.  The programs do different things in different ways so every program would need its own method of monitoring its own progress.  Sometimes, even measuring progress is difficult.

Essentially, it is a lot of work for a small team to do with only a limited benefit.
