### ISSUE TITLE
Header loading time depends on header names

### ISSUE THREAD

**Issue by hjruscheweyh** [samtools/samtools#2066]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.

```
samtools 1.12
Using htslib 1.12
```

Same behaviour under:

```
samtools 1.20
Using htslib 1.20
```

 #### Please describe your environment.
- Linux 4.18.0-513.24.1.el8_9.x86_64
- x86_64
- samtools downloaded via conda

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I have generated a fasta file with ~40 mio dereplicated genes. Header names are unique and are just 6 alphanumeric values [A-Z][A-Za-z0-9]*5 (e.g CaA3xL, CaA3xM, CaA3xN, CaA3xQ). Next I used BWA (0.7.17-r1188) to build an index and started aligning reads, alignments are stored in a sam file.

e.g.
```
bwa mem -a -t 1 index reads.fq.gz > reads_vs_index.sam
```

Alignments were produced quickly. Next I translated the sam into a bam file

```
cat reads_vs_index.sam | samtools view -bh -  > reads_vs_index.bam
```

The BAM file remained empty for 15 hours until samtools started writing the header. samtools was constantly using 100% of a single core (so wasnt idle) and used between 1GB and 8GB of RAM.

I have tried the same exercise but renamed the genes in the fasta file (A_00000001, A_000000002,...). In that case the samtools command started writing the header within 1-2 minutes.  There seems to be an internal process in samtools which performs differently depending on header names (maybe some hashing that creates too many collisions?). Any clue where this issue comes from and how to pick the shortest possible header name (needed for large catalogs where we run into the 2^31 header limit) which doesnt need hours to load with samtools?

Best and thanks,
Hans

**Comment by whitwham** [comment]
Just for clarity; you have about 40 million unique reference names (the ones that go in the SN entry in the `@SQ`  header line)?

**Comment by hjruscheweyh** [comment]
There are NO duplicate reference names and NO duplicate sequences.

**Comment by daviesrob** [comment]
It's likely that you've hit an unfortunate case where the hash function used in the header code is getting a lot of collisions.  It's actually a bit weak as hash functions go, in particular the last letters of the string don't get mixed in very well, but has resisted being changed because oddly it ends up being faster for normal small headers because the entries tend to group together in memory.

To make a header that's faster to read, you could try to make sure that the names vary mostly at the start.  For example, this script produces names in an alphabetical sequence:
```
perl -le 'BEGIN { $n = "AAAAAA"; } for ($i = 0; $i < 40000000; $i++) { print "\@SQ\tSN:$n\tLN:100"; $n++; }'
@SQ     SN:AAAAAA       LN:100
@SQ     SN:AAAAAB       LN:100
@SQ     SN:AAAAAC       LN:100
@SQ     SN:AAAAAD       LN:100
.. etc
```

Trying to convert that header to BAM took about 4 minutes 30 seconds on my machine.  Simply reversing the names like this:

```
perl -le 'BEGIN { $n = "AAAAAA"; } for ($i = 0; $i < 40000000; $i++) { $r = reverse($n); print "\@SQ\tSN:$r\tLN:100"; $n++; }'
@SQ     SN:AAAAAA       LN:100
@SQ     SN:BAAAAA       LN:100
@SQ     SN:CAAAAA       LN:100
@SQ     SN:DAAAAA       LN:100
... etc
```

was much faster (about 1 minute 23 seconds).

Unfortunately there's no easy solution to this, as with a deterministic hash it's always possible to come up with an input that collides massively and gives the slow-down that you had.

**Comment by hjruscheweyh** [comment]
thank you for your feedback. I agree that the hash function might be the issue. Just generating a more diverse set of headers might solve issue. I will give it a try. thanks,
Hans
