### ISSUE TITLE
Is minhash really sorted by coordinate?

### ISSUE THREAD

**Issue by armintoepfer** [samtools/samtools#2105]
#### Is your feature request related to a problem? Please specify.
On the PacBio Revio instrument we are sorting our `hifi_reads.bam` files with `samtools sort -M -R` to save disk space and improve file transfer time. The `SO:coordinate` results in a lot of confusion, as users think that the file is already aligned.

#### Describe the solution you would like.
I could override the sort order using a new option and set it to `unknown` in my use case. If I were to implement this, would you accept such solution or do you have a different idea?

**Comment by jmarshall** [comment]
It's pretty clear from both the source code that mapped (and placed) reads are sorted by coordinate in this mode. So `SO:coordinate` is in general appropriate.

Presumably the salient point is that your files have not yet been aligned, so **all** the reads are unmapped. So `SO:coordinate` is trivially true, but also misleading.

It would be possible for samtools sort to notice that all reads have tid = -1, and suppress writing any SO or SS header fields in this case. (Or implementing that might be nontrivial enough that it would be preferable to add a `‑‑file-is-unaligned` option (with a better name) with the same effect.) IMHO either of those would be preferable to an option that enabled setting arbitrary SO values.

**Comment by armintoepfer** [comment]
Your `--file-is-unaliged` option would be the preferred implementation of my suggestion, I wouldn't ask for arbitrary SO values. Your other suggestion – checking for `tid = -1` – would have an implicit component that doesn't feel right.

**Comment by jmarshall** [comment]
:shrug: Needing to use an option like `‑‑file-is-unaligned` and having the ability to use it erroneous (so really it would need a more noncommittal name) also don't feel great…

**Comment by armintoepfer** [comment]
`--set-so-unknown`

**Comment by jkbonfield** [comment]
I'm not sure what the best route forward here is.  I can think of three possible solutions though.

1. Use `SO:unknown`.  It's a bit of a "shrug" when it comes to meta-data and it doesn't mean unsorted, simply under-specified.  So I don't like that as a solution.

2. Make the minhash sort just use `SO:unsorted`.  The SAM spec has an example of `@HD SO:unsorted SS:unsorted:MI:coordinate` suggesting that we already are abusing "unsorted" to be known-but-not-categorised sorts.  So if we combine it with sub-sort then we can elaborate further maybe.   I'm guessing we chose this route because SO is a controlled vocabulary and there's just too many tools with overly strict checking to make adding to the vocabulary an easy solution (sadly).

3. Do nothing.  We already output `SO:coordinate	SS:coordinate:minhash` so this is quite explicit that it isn't a classical coordinate sort.  It may come under the "you can lead a horse to water but you cannot make it drink" category.  All the information is present in the header already to tell what these files are, and technically this is more correct than `unsorted` as it most definitely is sorted by coordinate.  There is also the risk that people are already looking for `SS:coordinate:minhash` to detect these files, and we can't have a sub-sort that doesn't match the primary sort order as the SAM spec explicitly forbids this.

How is it that users are misinterpreting this?  I'm assuming it's use of automated tools rather than eyeballing it, because that ought to be pretty obvious (if they spot the SS field).  However it would be good to know exactly how this confusion is taking place as without that understanding we can't really evaluate if a change fixes it.

My instinct is to use unsorted:minhash as a solution as any ambiguity caused by solely looking at `SO` is less problematic.

**Comment by daviesrob** [comment]
I think 2 is probably the best solution.

**Comment by armintoepfer** [comment]
I like (2) too.

**Comment by armintoepfer** [comment]
Put yourself in the shoes of 99% of people who use BAM files. Most of them aren't hardcore bioinformaticians. They look at  `SO` and if it says `coordinate` they assume the file is aligned and sorted. No matter how detailed the man page or documentation is, this is essentially a case of Hyrum's law in action.

If it's not aligned but still sorted, it's not `SO:coordinate` to me and many users that complain to us.

Please reconsider and implement `SO:unsorted SS:unsorted:MI:coordinate`

**Comment by jkbonfield** [comment]
So you're saying it's humans that are confused and not software?  That's a starting point at least.   Also, how lazy are these bioinformaticians if they don't read _the very next word_ which states SS:coordinate:minhash? :)

Good point though on sort specifically preloading the data.  So it's perhaps possible to decide before hand whether or not it is entirely unmapped.  I'll think on it a bit and see how tricky it is to collate that through the threading and make it available to the final stage that writes the header.

**Comment by armintoepfer** [comment]
Thank you. It's mostly humans and then implicitly code that they write for their employers :)

**Comment by jmarshall** [comment]
Somewhat to my surprise, it seems like `bam_sort_core_ext()` has everything needed without threading complications — see the proof of concept in jmarshall/samtools@c1bb93a7b75c8e573acec1895e4df0acfc13c25c. (Though it might be better to move the main SO/GO/SS setting code down to just above `// write the final output`too,  or into a subroutine.)

**Comment by jkbonfield** [comment]
I've just been looking at that same code and coming to the same conclusion, also suprising myself.

Although my PR brewing has some other refactoring of this code too, as you suggest by putting it into a subroutine.
