### ISSUE TITLE
samtools fastq converts U bases to N

### ISSUE THREAD

**Issue by Psy-Fer** [samtools/samtools#2131]
After I have basecalled some nanopore direct RNA data, the output contains U bases (because that is the actual base that was sequenced)
This data is in a sam/bam file. When I run `samtools fastq reads.sam` the U bases are converted to N

Is there a way to retain the U base or if it is going to do conversion of bases, at least control the conversion to a T?

My current solution is just doing a global `sed 's/N/U/g'` after, or in the case of converting to T, doing `sed 's/U/T/g'` but that can also have unintended consequences on quality scores.

**Comment by jkbonfield** [comment]
My first question is how are you getting a SAM file with a letter U in it?  Ideally this shouldn't be possible.  The alphabet permitted in BAM is strictly the IUPAC ambiguity codes.  While theoretically (and officially according to the specification) SAM doesn't have this restriction, practically speaking given htslib is holding BAM encoding in memory it applies the same limitations to SAM.

This means that the U to N conversion happens when reading SAM in, and not when outputting fastq, so it's nigh on impossible to solve by this stage and it would be easier to fix it as the SAM generation stage.

**Comment by jkbonfield** [comment]
I'm guessing buttery-eel or dorado are writing out unaligned SAM as its own text format, and that's where the U comes from?  Given htslib internally stores sequence in nibbles (ie BAM), it's possible we could tweak the `seq_nt16_table` to silently just convert U to T at this point.

https://github.com/samtools/htslib/blob/develop/hts.c#L242

Ie:

```
100644
--- a/hts.c
+++ b/hts.c
@@ -239,9 +239,9 @@ const unsigned char seq_nt16_table[256] = {
     15,15,15,15, 15,15,15,15, 15,15,15,15, 15,15,15,15,
      1, 2, 4, 8, 15,15,15,15, 15,15,15,15, 15, 0 /*=*/,15,15,
     15, 1,14, 2, 13,15,15, 4, 11,15,15,12, 15, 3,15,15,
-    15,15, 5, 6,  8,15, 7, 9, 15,10,15,15, 15,15,15,15,
+    15,15, 5, 6,  8, 8, 7, 9, 15,10,15,15, 15,15,15,15,
     15, 1,14, 2, 13,15,15, 4, 11,15,15,12, 15, 3,15,15,
-    15,15, 5, 6,  8,15, 7, 9, 15,10,15,15, 15,15,15,15,
+    15,15, 5, 6,  8, 8, 7, 9, 15,10,15,15, 15,15,15,15,
```

This code looks to have been unchanged since the earliest days of samtools.

**Comment by Psy-Fer** [comment]
I just tested putting a fastq with U (also written by buttery-eel) into minimap2 directly, and the sam output has T's.
So I think that could be a good solution, given that is what minimap2 seems to do.

**Comment by jkbonfield** [comment]
Infact I see this lookup table in the original 0.1.1 commit of samtools, the first one in this repository!

https://github.com/samtools/samtools/blob/f93dae0d03856955f9424e8b2aaf261304ca647e/bam_import.c#L19-L36

I'm not averse to changing it as tbh there can be little else that U could mean, but it's clear that the original intent that SAM wasn't meant to store RNA.  RNA does get a mention in the spec, but there's no provision made for it in BAM and it's evident neither was it expected to be in SAM, so I guess the original author (ie Heng) always expected RNA to be changed to T first.

**Comment by Psy-Fer** [comment]
I'll just clarify too.

Buttery-eel writes what dorado-server writes. I'm not sure what dorado itself is writing to file, but I imagine they are converting U to T on writing bam.

So in the meantime I can add a flag to do the U->T conversion, but i think it's whole reasonable to have that U->T conversion happen during a samtools fastq call given the IUPAC restrictions rather than converting it to N

**Comment by jkbonfield** [comment]
> So in the meantime I can add a flag to do the U->T conversion, but i think it's whole reasonable to have that U->T conversion happen during a samtools fastq call given the IUPAC restrictions rather than converting it to N

Specifically it wouldn't be in `samtools fastq`.  Rather htslib's reading of SAM would automatically convert U->T instead of U->N, meaning all commands silently do this conversion.  By the time it gets to samtools fastq it's already converted, but it amounts to the same thing.

Curiously reading the table above it's reminded me that 0,1,2,3 also get converted to A,C,G,T.  I'm assuming this is undocumented support for ABI SOLiD's colourspace encoding.

**Comment by Psy-Fer** [comment]
oh wow colourspace! That's well before my time

I saw on dorado, they are doing the conversion after the calling.
https://github.com/nanoporetech/dorado?tab=readme-ov-file#rna-models
Where they say bam doesn't support U
I think more accurately bam seems to only be supporting IUPAC, but the spec itself can support A-Z in the SEQ field.
I guess practically speaking, IUPAC support is going to make things 1000x easier to support.

Anway, could we update that table to do the U->T conversion? I think that would be some good future proofing.

**Comment by jkbonfield** [comment]
We have our weekly Samtools meeting today so we'll discuss it.  Personally I don't see changing it to be a problem.  Infact I'm rather surprised it wasn't done before.

**Comment by jkbonfield** [comment]
It's curious that both [bwa](https://github.com/bwa-mem2/bwa-mem2/blob/master/src/bntseq.cpp#L54-L71) and [minimap2](https://github.com/lh3/minimap2/blob/master/sdust.c#L24-L41) have lookup tables that don't treat U as T, but minimap2 has an [explicit U to T conversion](https://github.com/lh3/minimap2/blob/master/bseq.c#L72-L74) step which you'd think would be far easier to implement just by editing the lookup table.  I assume the sequence is used elsewhere in ASCII too, such as when writing back out and there was a concious decision to sanitise the output?

I couldn't see such a thing in bwa, but I admit I didn't test it so I may have missed some code somewhere.

**Comment by Psy-Fer** [comment]
I feel like i've stumbled onto something interesting. I'm honestly surprised ONT haven't been barking up this tree before. I wonder when the minimap2 change happened and if it coincided with direct RNA release from ONT.
