### ISSUE TITLE
Samtools segfaults when directory isn't writeable

### ISSUE THREAD

**Issue by semenko** [samtools/samtools#312]
When running `samtools index` in a read-only directory (accidentally), samtools segfaults instead of printing a sane error message.

Built with the current head at 6b249e2c682

    Starting program: /home/semenko/git/riesling/dist/samtools-1.1 < ../dist/samtools-1.1 index IsoA-M1-CD4_S1.bt2.srt.rmdup.bam
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

    Program received signal SIGSEGV, Segmentation fault.
    __GI__IO_fwrite (buf=0x4a02c8, size=1, count=4, fp=0x0) at iofwrite.c:41
    41	iofwrite.c: No such file or directory.

**Comment by jmarshall** [comment]
No longer segfaults, but the error message is misleading:

> samtools index: "seq.bam" is corrupted or unsorted

This is because `hts_idx_save_as()` needs to return -2 when opening its output file fails, expect that then the error message will talk about the wrong filename:

> samtools index: failed to open "seq.bam": Permission denied

This could be fixed easily by inventing a -3 return code or by rewording the message to be more vague; or it could require souped up error handling infrastructure in htslib.
