### ISSUE TITLE
iRODS woes on SIGPIPE?

### ISSUE THREAD

**Issue by dkj** [samtools/samtools#350]
/software/solexa/pkg/samtools/samtools-1.2/samtools merge - irods:/seq/15415/15415_1#64.cram irods:/seq/15415/15415_2#64.cram  | /software/solexa/pkg/samtools/samtools-1.2/samtools view -H -
causes lots of
```
Client Caught broken pipe signal. Connection to server may be down
Client Caught broken pipe signal. Connection to server may be down
Client Caught broken pipe signal. Connection to server may be down
```
messages

**Comment by dkj** [comment]
Note suggested iRODS patch added ready for iRODS 4.0 and then removed?
https://github.com/irods/irods/issues/1970

**Comment by keithj** [comment]
Still present in iRODS 4.0.3 (using htslib test_view). Confirmed after working around samtools/htslib#175

````
./test/test_view irods:xx#large_aux.bam | head -1
@SQ	SN:xx	LN:20
Client Caught broken pipe signal. Connection to server may be down
Error writing output.
Client Caught broken pipe signal. Connection to server may be down
Error closing output.
````

**Comment by jmarshall** [comment]
The theory I mentioned over lunch was incorrect; instead, the enormous number of messages from `samtools merge` is because iRODS's signal handler effectively ignores the signal, so `merge` carries on merging the files until completion (getting another signal every time it writes to stdout!), rather than aborting early when `view -H`/`head` says it's no longer listening.

So the problem is wasted CPU as well as annoying messages.

So htslib too will likely do the dance of restoring the previous SIGPIPE handling after calling `rcConnect()`.  I have prepared such a patch, but I also want to investigate why `samtools merge` didn't abort early anyway in response to EPIPE on stdout after iRODS caught SIGPIPE.
