### ISSUE TITLE
samtools 1.2 flagstats prints NaNs for zero percentage values

### ISSUE THREAD

**Issue by keithj** [samtools/samtools#365]
e.g.

````
136919 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
84287 + 0 duplicates
136919 + 0 mapped (100.00%:-nan%)
136919 + 0 paired in sequencing
64918 + 0 read1
72001 + 0 read2
115896 + 0 properly paired (84.65%:-nan%)
116826 + 0 with itself and mate mapped
20093 + 0 singletons (14.68%:-nan%)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
````

**Comment by mp15** [comment]
I'm not convinced this is wrong after all 0/0 is an indeterminate form not 0.

**Comment by keithj** [comment]
I think "nan percent" looks a little odd. I don't mean it should be 0. Perhaps "100.00%: -" or "100.00%: NA"

**Comment by jmarshall** [comment]
This QC-failed stats printing code is unchanged since it was introduced in 0.1.15 and has been printing `‑nan%` since then.  Is this output likely to be ever machine-parsed, or is it solely for human consumption?

IMHO there would be a case for printing an appropriate percentage to maintain continuousness and least-surprise (i.e., `100%` for mapped and properly paired, `0%` for singletons) especially if this were machine-parsed.

However anything parsing this to date has had to have special cases for `nan%`, so there's probably not much harm in needing a different special case like `N/A` instead.

(Re non-wrongness of indeterminate forms, we've a bit of a policy of not printing them out to unsuspecting users nonetheless, cf _stats.c_ changes to print `0` instead of `nan`.)

Anyone reacting with horror to the thought of synthesising an appropriate `0%` or `100%`?  I suppose `(100.00% : N/A)` is about as readable, so probably wiser...

**Comment by keithj** [comment]
The style of output appears to me to be for human consumption only. I guess that some systems are parsing it, so if it remains unchanged for that reason, I don't object.
