### ISSUE TITLE
mpileup test fails in non-English locale

### ISSUE THREAD

**Issue by charles-plessy** [samtools/samtools#410]
Hello,

this is quite minor, but the mpileup test fails in non-English locales:

```
UNEXPECTED FAIL: Output mismatch for $samtools mpileup -u -x -f mpileup.ref.fa mpileup.1.bam | GREP_OPTIONS= egrep -v '^##samtools'
See FAIL-52.out.1 vs expected/52.out

$ cat expected/52.out
Binary file (standard input) matches

$ cat FAIL-52.out.1 
Fichier binaire (entrée standard) correspondant
```

Obviously, the locale should be set to `C` somewhere, but I am not sure where it would be most appropriate; sorry for not proposing a patch. Adding `LC_ALL=C` in front of `egrep` would solve this problem but would not prevent it from happening somewhere else…

-- 
Charles

**Comment by jkbonfield** [comment]
I can't easily test this, but editing the Makefile to set LC_ALL=C before running test/test.pl and regression.sh would work for all tests (in the same way that we already have a REF_PATH=: setting).

I'll discuss it with the others at our developer meeting today.

**Comment by jmarshall** [comment]
I think we're just lucky that both GNU and BSD grep output the same `Binary file %s matches` text at all; it's not just locales that can kill this test (we've already papered over some $GREP_OPTIONS cracks).

What is this checking for anyway?  Non-empty output (modulo a `##samtools` header)?  Could we use `wc` (or even `strings`+`grep`) instead?

**Comment by jkbonfield** [comment]
On Tue, Jun 30, 2015 at 02:47:29AM -0700, John Marshall wrote:
> What is this checking for anyway?  Non-empty output (modulo a `##samtools` header)?  Could we use `wc` (or even `strings`+`grep`) instead?

Hmm I see your point - it's a borked test basically.

When I did the testing of mpileup it was largely as a naive uneducated
user of mpileup.  Infact there are still mpileup functionality that I
don't understand!  My aim, and indeed the groups aim, was to checking
that the new samtools 1.0 mpileup worked the same as the old samtools
0.1.19 mpileup so we could spot any breakages by our grand
reorganisations; hence calling it a regression test rather than a
functionality test.  Therefore my expected outputs were basically
generated by running my battery of tests with the old samtools so I
could validate the new one gives the same output.  (Although I did
file numerous bugs I discovered on the way too.)

What it was attempting to check was that the bcf file generated is
correct, minus the ##samtools line which differs on each and every
version and so would break regression testing.

What it actually did without me noticing somehow (sorry) was convert
all that to a meaningless "binary file matches" statement.  I think
when I initially wrote it it was using bcftools view, but that adds
annoying dependencies between packages so it got hacked to a grep,
badly.

A ...|sed 's/^##samtools//' seems to work, but I'm not sure if that is
going to trip us up elsewhere too.  Note that strings wouldn't work as
it can only check the text portions.

James

PS.  The BCF format has radically changed between 0.1.19 and 1.2
anyway, so this would have broken ages ago, possible multiple times.
I think it's still a valid test to have though, even if we have to
update the expected output periodically.  Alternatively if Petr
believes the VCF to BCF conversion is adequately tested in bcftools or
in htslib then we can skip this test here and only check that VCF
output works.

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by jmarshall** [comment]
> What it actually did without me noticing somehow (sorry) was convert all that to a meaningless "binary file matches" statement.  I think when I initially wrote it it was using bcftools view, but that adds annoying dependencies between packages so it got hacked to a grep, badly.

We now have _samtools_/test/vcf-miniview (and also _htslib_/htsfile -c) which may be of use for this job…
