### ISSUE TITLE
build with installed htslib rather than src

### ISSUE THREAD

**Issue by dkj** [samtools/samtools#414]
build currently (1.2 +) requires source tree of htslib - I _wish_ it could use an installed htslib ( which already provides pkgconfig stuff) instead.

**Comment by wookietreiber** [comment]
:+1:

**Comment by wookietreiber** [comment]
[This is the patch](https://raw.githubusercontent.com/wookietreiber/PKGBUILDs/master/samtools/makefile-system-htslib.patch) I am using to make samtools 1.2 build with a system-provided htslib for my [Arch Linux PKGBUILD](https://raw.githubusercontent.com/wookietreiber/PKGBUILDs/master/samtools/PKGBUILD).

**Comment by jkbonfield** [comment]
Setting HTSDIR to /usr/include is counterintuitive.  I'd expect it to be /usr and get include, lib etc appended.

The problem with that though is that htslib doesn't have an include directory.  IMO this would be best remedied by moving the htslib/*.h files to include/htslib/*.h so that the source directory more closely mirrors and installed directory, and adding -I./include -L./libs instead of -I. in the htslib Makefile.  Then it feels fairly natural to link against either installed path or source path as they're identical layouts.

**Comment by wookietreiber** [comment]
Setting `HTSDIR=/usr/include` may be counterintuitive, however, it is the most minimal `Makefile` hack to use a system-provided htslib. I would very much prefer using `pkg-config` to figure out where htslib is installed and which flags are needed.

**Comment by jmarshall** [comment]
The HTSDIR variable exists for the purposes of building against an in-development htslib directory, which may be a moving target so it is good to be able to express dependencies on the files within.

This is not a concern when building against an installed htslib.

In that case, `$(HTSDIR)`, `$(BGZIP)`, `include htslib.mk` et al can all evaporate and be empty (modulo some link command fixups to add `-lhts` (and no dependency) rather than `libhts.a`).  Instead all samtools needs is a `-I` in CPPFLAGS and a `-L` in LDFLAGS — and if htslib is installed in /usr or somewhere else the compiler is already looking, not even that.

There is no need for :+1:… all this has always been on the road map.

**Comment by wookietreiber** [comment]
I understand your need as a developer of samtools to do such an in-development htslib build ...

... and here comes the *but*: but your current approach of hard-coding this in-development htslib directory as `HTSLIB = ../htslib`, using `include $(HTSDIR)/htslib.mk`, etc. is a burden to bear for all of us who don't work with such an in-development htslib. We have htslib installed at our system, usually at `/usr`, and want to link samtools against this system-installed htslib. We have to manually edit the Makefile for this to work. Everytime. The patch I wrote and mentioned above was not meant to be applied to samtools as is, it was just the quickest and maybe dirtiest reproducible hack for me to get samtools working with a system-installed htslib.

Also, I understand enough about Makefiles, etc. that I am able to make these changes, but not necessarily all of your users out there are able to do this. If they can't apply these changes, they are forced to locally download the htslib sources and build with them, because there aren't even up-to-date build and installation instructions in neither your `README[.md]` nor your `INSTALL` files. The `INSTALL` file mentions changing `HTSDIR` but only to a source tree where `htslib.mk` exists, but this obviously will not work for a system-installed htslib.

So I can completely understand @dkj's wish for an easier workflow and I hope you can empathize with both his wish and with my above reasoning.

I would like to find a solution that supports both workflows, i.e. having a simple build for users that supports system-installed htslib and the flexibility for developers to work with an in-development htslib. The simplest solution I can come up with at the moment is the following:

1.  Patch `Makefile`:

    ```diff
    diff --git a/Makefile b/Makefile
    index fadb289..d8b5d76 100644
    --- a/Makefile
    +++ b/Makefile
    @@ -85,7 +85,9 @@ all: $(PROGRAMS) $(BUILT_MISC_PROGRAMS) $(BUILT_TEST_PROGRAMS)
     
     # Adjust $(HTSDIR) to point to your top-level htslib directory
     HTSDIR = ../htslib
    +ifneq ("$(wildcard $(HTSDIR)/htslib.mk)","")
     include $(HTSDIR)/htslib.mk
    +endif
     HTSLIB = $(HTSDIR)/libhts.a
     BGZIP  = $(HTSDIR)/bgzip
     
    ```

2.  Build with:

    ```
    make HTSDIR=/usr/include HTSLIB= BGZIP= LDLIBS=-lhts
    ```

This works if installed to `/usr`. It would be really great if you could incorporate the conditional inclusion of `htslib.mk` in `Makefile` and update either `README[.md]` or `INSTALL` with the above `make` command line as an installation instruction for system-provided htslib. I think this would help a lot.

**Comment by wookietreiber** [comment]
Did you just delete my previous comment?

**Comment by jmarshall** [comment]
> all this has always been on the road map.

In case this was unclear, by “on the road map” I mean both

* it has always been the plan to support building against a development htslib or an installed htslib
* while the latter is not currently supported in **develop**, I have much of it in a dusty branch waiting to percolate up my management's priority list

Issues like this one are useful for aiding that list percolation.  But rest assured that we're aware of the problem and have a solution in the works.  Probably in time for the upcoming release,  for various reasons.

Re @wookietreiber's previous comments:  Perhaps someone's fingers slipped.  Apologies if so.

**Comment by jmarshall** [comment]
Samtools now has a configure script; the incantation you want is `--with-htslib=system`.  (There are a few documentation and other additions yet to come.)
