### ISSUE TITLE
Remove wgsim

### ISSUE THREAD

**Issue by sjackman** [samtools/samtools#429]
The canonical repository for `wgsim` is https://github.com/lh3/wgsim
See https://github.com/samtools/samtools/issues/355

**Comment by sjackman** [comment]
`lh3/wgsim` hasn't been updated since 2011-10-17. Would `samtools` considering forking and adopting the maintenance of https://github.com/lh3/wgsim ?

**Comment by jkbonfield** [comment]
On Thu, Jul 09, 2015 at 09:54:24AM -0700, Shaun Jackman wrote:
> `lh3/wgsim` hasn't been updated since 2011-10-17. Would `samtools` considering forking and adopting the maintenance of https://github.com/lh3/wgsim ?

In realising that it is a useful tool for something else I'm working
on, I tried to use it and promptly found two bugs (now fixed).

I don't know what Heng's plans are for wgsim so I'm not sure who
should maintain it.  Let's see what happens to the issues over there.

James

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by charles-plessy** [comment]
In Debian we are wondering which version of `wgsim` we should distribute.  I looked at the history in both Git repositories, and samtools/samtools does not contain the commits posterior to January 2011.  Here they are for your convenience:

 - lh3/wgsim@cac058fdce454a0ac0cedd504de368529eb40fec
 - lh3/wgsim@838e8b64a50c053d315d4b9a35d3670f9bc4a64b
 - lh3/wgsim@588f1504945580d7fcfef361344ed204b9de2750
 - lh3/wgsim@a12da3375ff3b51a5594d4b6fa35591173ecc229

One confusing thing is that `wgsim` distributed here is versionned 0.3.0 and mentions Heng Li at Sanger as the contact person.  It would be nice if this could be clarified.

Regardless where the source is managed, from Debian's point of view of software integrator, having wgsim built on the htslib would be better, so that if a bug is found in in files related to klib, it would be fixed by a single package upgrade.

Have a nice day,

Charles

-- 
Charles Plessy
Debian Med packaging team

**Comment by jkbonfield** [comment]
Having just noticed that one of the bugs I spotted and fixed in Samtools' copy of wgsim was reported with a pull request to the upstream wgsim in 2013 (https://github.com/lh3/wgsim/pull/5), I think we can conclude that it is defunct.

As a consequence, my wgsim_bug_fix branch now contains the other commits listed above.  Thanks Charles.

**Comment by sjackman** [comment]
@jkbonfield Would you prefer to maintain your copy in `samtools/samtools` or `samtools/wgsim`? I have no strong preference.

**Comment by kdmurray91** [comment]
Subscribing to this thread as I'm the author of a `wgsim` Debian package from lh3's repo. I can supply (via PR) a `wgsim.1` man page to whichever repo ends up being the extant copy of wgsim, if one would be desired.

**Comment by sjackman** [comment]
I like man pages. Thanks, Kevin.

**Comment by kdmurray91** [comment]
Cool, no worries Shaun :)

PR incoming to @jkbonfield's wgsim_bug_fix branch

**Comment by kdmurray91** [comment]
PR #438

**Comment by jkbonfield** [comment]
Merged, although we still haven't decided who should take ownership of wgsim.

**Comment by sjackman** [comment]
@lh3 Would you like @samtools to adopt the maintenance of `wgsim`?

**Comment by lh3** [comment]
I think we should pull wgsim out of samtools.

**Comment by jkbonfield** [comment]
Do you mean samtools/wgsim or lh3/wgsim?  I assume the former (given the latter already exists and is dormant).

What is the benefit to this? It's a tradeoff between clarity vs ease of access I guess.

**Comment by lh3** [comment]
I think it is not necessary for samtools to maintain wgsim. There are better simulators. Nils also has his improved dwgsim.

**Comment by jmarshall** [comment]
There are now two questions here:
* whether wgsim should be maintained;
* if so, whether it should be maintained within the samtools package or on its own.

I don't have a strong opinion on the former, other than that it wouldn't take much to merge the various strains and fix a bug or two, and people will notice if it disappears (whether or not other simulators exist).

As to the latter, the reason for having separate samtools and wgsim distributions would be if they each had their own release schedules and active development.  Neither of these wgsims has moved in four years.  So I would strongly suggest that, from the users' point of view, it would be better to update the wgsim within the samtools distribution rather than to tell them to go off and get a separate wgsim.

We would want to update wgsim_eval.pl as well.

**Comment by jkbonfield** [comment]
Agreed on wgsim_eval.pl.

Wgsim is very light traffic. W e haven't had much to do for ages, but it has more recently moved forward a bit. I merged in some changes and made some bug fixes too. I think there is one outstanding request (template orientation to be in read name), but otherwise I don't see it changing again for some time so I doubt a release schedule is a critical problem for it.

**Comment by jkbonfield** [comment]
At our weekly core meeting we discussed wgsim and felt that it was worth having a final release with all the bug fixes and improvements consolidated, so at least people have a central location to refer to the most up to date version.  This will be in samtools 1.3.

However given that there are better tools out there now we felt that we should no longer feel required to keep it up to date.  If anyone has any pressing reason why they need wgsim to have long term support over other tools then shout now, otherwise we'll retire it after 1.3.

What does retire mean?  I don't think we really got a concrete decision, but it likely means removal from samtools code base.  (Personally I don't see a need to move it to its own code base unless there is a need to keep it maintained, albeit without new features.  If that is the case though then we shouldn't be retiring it either.)

**Comment by sjackman** [comment]
I'd like to see it continued to be maintained with a "no new features" caveat just to support old pipelines and manuscript results that depend on it. Basically just keep it compiling and running, nothing more. For all I know it may never need another release. If you don't want it in `samtools/samtools`, I'd suggest moving it to its own repository.

**Comment by kdmurray91** [comment]
I'd like to echo what Shaun says; it would be extremely useful to have an extant, canonical `wgsim` to package and use in existing pipelines or unit testing, where the more modern or sophisticated tools are not required

**Comment by jmarshall** [comment]
Okay, _retirement_ as modified by @sjackman and @kdmurray91's comments.  We'll bring it up to date with the lh3/wgsim repo's improvements and other improvements, and thereafter it can remain (with mostly "no new features") within the samtools distribution, as it has for the last few years.  There's no particular reason to remove it from the code base, as there's mostly no cost to having it there.

So closing this in favour of PR #428 wgsim basic maintenance.
