### ISSUE TITLE
segmentation fault with reheader (v1.2)

### ISSUE THREAD

**Issue by tdelhomme** [samtools/samtools#477]
I have a segmentation fault with samtools reheader on a small bam file test.
If I use -P option it works, but why I can not generate a PG line?

You can find my small bam here https://github.com/mfoll/NGS_data_test/tree/master/1000G_CEU_TP53/BAM/ (NA06984.bam)
and this is the commands : 

samtools view -H NA06984.bam > test.header.sam
samtools reheader test.header.sam NA06984.bam > test.bam (segmentation fault)
samtools reheader -P test.header.sam NA06984.bam > test.bam (it works)

**Comment by jkbonfield** [comment]
I believe it's a configure script issue.

Specifically the code has #ifdef HAVE_VA_COPY so it knows whether it needs to use va_copy when doing varargs work.  My guess is that this should be defined on your platform, but it's not.  Our problem is that there is nowhere in the Makefile to do this, nor in the configure script.

Io_lib's equivalent, where this code originated from, has this in the configure script:

```
dnl Do we have the va_copy function?
#
# Checks whether we the ability to use va_copy().
# AC_DEFINEs HAVE_VA_COPY if you do.
#
AC_DEFUN([AX_FUNC_VA_COPY],
[AC_LANG_PUSH(C)
AC_LINK_IFELSE([AC_LANG_SOURCE(
[[#include <stdarg.h>
void va_test(va_list ap) {
    va_list ap_local;
    va_copy(ap_local, ap);
    va_end(ap_local);
}
int main(void) { return 0; }
]])],
AC_DEFINE([HAVE_VA_COPY],1,[Define to 1 if you have the va_copy() function.]),
)
AC_LANG_POP(C)])

AX_FUNC_VA_COPY
```

You can test whether this actually solves your problem by rebuilding htslib with something like
```make clean; make CFLAGS="-g -DHAVE_VA_COPY"``` and then relink samtools.  If this does solve the problem then we'll look into patching this in properly.

That reminds me, while we're there, we should probably add a note to htslib (it's already in the samtools side) that the header API stuff isn't canonical and is just a temporary hack until something concrete comes along, or maybe just block it.  I confess I forgot this existed and was suprised the -P made it in as I recall a conversation about it and the header API.

**Comment by jkbonfield** [comment]
Or thinking about it more, possibly -P should simply be removed.  It was only added recently (at the request of a local Sanger person), but the lack of header API makes it problematic.   Unofficially calling CRAM's header API works, but if we ever want old samtools binaries working against newer htslib libraries (with a new header API) then we get compatibility issues.

Is that actually likely to happen?  Most distributions update both packages at the same time and we have version numbers that track each other too.

**Comment by jmarshall** [comment]
The things you're calling are `sam_hdr_parse_()` and `sam_hdr_add_PG()`, which you added to htslib's public _cram.h_ API.  No detailed header API is exposed, and the underlying implementation can be changed out at will.  So the only small compatibility problems are the slightly tacky `sam_hdr_parse_()` and the name of the opaque `SAM_hdr` type.  More or less.

The bug here is that your code ought to work when HAVE_VA_COPY is not defined too.  I would recommend documenting that `sam_hdr_vadd()` eats _ap_ so that _ap_ is undefined after it is called (cf [vprintf et al documentation](http://en.cppreference.com/w/c/io/vfprintf#Notes), or C99 §7.19.6.8/2).  Then the loop in `sam_hdr_add_PG()` will need to reset _args_ each time around the loop, which fixes this crash.  Also your desire for `va_copy()` will evaporate :smile:.

**Comment by jmarshall** [comment]
…My previous comment reflects how one would write this stuff in C90.

The alternative would be to assume C99 varargs and just use `va_copy()` unconditionally.  Probably the most backwards of the platforms we vaguely care about is MSVC, which added support for `va_copy()` in VC++ 2013 / 12.0.  This is the same version that added support for other C99isms, notably variable declarations in the middle of blocks, which we use fairly widely.  So to the extent that VC++2013 is already a prerequisite, unconditional `va_copy` is fine for Windows.  To the extent that you can compile htslib with previous VC++ versions by compiling as C++, unconditional `va_copy` would break this.

I wonder what versions of what compilers the Windows-using folks are using for htslib these days (@ctsa, @iqbal-lab, @nhayden, @dalexander)?

**Comment by iqbal-lab** [comment]
I'm using mingw, but we are still on an ancient version of htslib that we have modified, have not moved up to latest

**Comment by ctsa** [comment]
No problems with a VS2013+ (or even 2015+) limitation.

**Comment by tdelhomme** [comment]
Now it works with ` make CFLAGS="-g -DHAVE_VA_COPY" ` for HTSlib

**Comment by jkbonfield** [comment]
Great.   That confirms the cause of the problem is the same thing we identified here.  Thanks for testing that.

I have two possible solutions so I'll look to fixing it soon, but you have an easy workaround for now. (You may want to reenable optimisation with -O3 etc in CFLAGS, or just hack the makefile and add -DHAVE_VA_COPY for now.)

**Comment by tdelhomme** [comment]
Ok ! many thanks for your support.
