### ISSUE TITLE
minor: samtools merge usage message on '-p' option

### ISSUE THREAD

**Issue by plijnzaad** [samtools/samtools#482]
The documentation of the -p option to samtools merge is obscure:
> combine PG tags with colliding IDs rather than amending them

When I do a little test run it turns out that what actually happens is

> keep the PG tags of just the first of the files being merged, rather than concatenating those of all

(The fact that in the default case the IDs are made artificially unique by appending a random string is trivial). Or am I overlooking something?

**Comment by mp15** [comment]
I was thinking of the following two use cases when I made this:
- In the default case if you see an @RG tag in two BAM files you are merging, unless you know they came from a previous split of a given BAM (aka they had a common ancestor) you do not want to merge them, thus why we force them to be unique.
- If however the BAMs were originally one (say you split by chromosome to speed processing) you don't want to duplicate the @RG's because they're actually descendants of the same original record.
I agree the documentation could and should be a lot clearer so I'll modify it before we release 1.3.
