### ISSUE TITLE
memory issue with samtools sort

### ISSUE THREAD

**Issue by silvia-s** [samtools/samtools#494]
I have asked samtools sort to use several combinations of threads and max memory per thread, but in each case it uses much more memory than requested and goes in the swap... Why is that? 
Here's some of the trials I've done (shown as stdout of "top"):

32060 silvia     18   0 16.3g  16g  892 R 172.1 68.9  55:39.99 /usr/local/genetics/samtools-1.2/samtools sort -n -@ 2 -m 5G [ARGS]

12400 silvia     18   0 12.6g  11g  648 R 35.6 50.7  16:46.94 /usr/local/genetics/samtools-1.2/samtools sort -n -@ 4 -m 2G [ARGS]

12438 silvia     23   0 6996m 6.5g  636 S 399.8 27.5  23:36.72 /usr/local/genetics/samtools-1.2/samtools sort -n -@ 4 -m 1G [ARGS]

Am I doing something wrong or is this a bug?
Thanks for your help!

**Comment by daviesrob** [comment]
I don't think you're doing anything wrong.  I've done some tests and it turns out that samtools sort isn't very good at keeping track of how much memory it's using under certain conditions.

The quick solution for now would be to allow for this when setting the memory limit.  Judging by your tests, it's using about 50% more than you asked for, so if you reduce the limit by the same factor it should end up using about the right amount.  The only disadvantage of doing this is the sort might be a bit slower than it would otherwise be, but at least it won't go into swap and take forever.

Analysis:

The problem is with how bam_sort_core_ext counts the memory it has used when re-using bam structures.  Basically, it adds up the total space used by the data it's read, but doesn't account for that used by previously allocated structures that haven't been recycled yet.  This can be easily shown by adding a couple of printfs and running a test:

```
k = 1743091 max_k = 2097152 mem = 805306456 max_mem = 805306368
k = 1530684 max_k = 2097152 mem = 805306592 max_mem = 805306368
k = 291277 max_k = 2097152 mem = 155341736 max_mem = 805306368
```

On the second chunk, 212407 structs are still allocated but were not reused, so aren't accounted for in mem.

**Comment by jmarshall** [comment]
Good fixes here probably require htslib changes to coalesce mallocs.
