### ISSUE TITLE
samtools sort crashes

### ISSUE THREAD

**Issue by trifud** [samtools/samtools#495]
samtools has been very shaky recently - it crashes when sorting almost any BAM file. Here is how it goes:

samtools sort SATP_86.bam -o foo
[bam_sort_core] merging from 32 files...
*** Error in `samtools': double free or corruption (!prev): 0x0000000032b611b0 ***
Aborted (core dumped)

I've had similar problems for a month or two. I update both samtools and htslib regularly and compile them "as is". Version 1.2 does not have this issue.

**Comment by jmarshall** [comment]
It works fine for us and on the test suite, so there would appear to be something in your particular BAM files causing trouble.  To track this down we would need to know when the problem was introduced, where the message was produced, and/or a sample BAM file exhibiting the problem — so next time you might consider reporting problems when they first occur and noting the actual version numbers involved (as reported by `samtools --version`).

If version 1.2 works on your files, then probably the problem is to do with the header merging code in _bam_sort.c_ that has been added since the last release.  So to produce an actionable bug report, you could do some or all of:

* Use `git bisect` on samtools to identify when this problem was introduced;
* Build a version of samtools with `-g` and run it under a debugger on your BAM file, and show us a backtrace showing which `free()` detected the problem;
* Show us _SATP_86.bam_'s headers.

**Comment by trifud** [comment]
Now I noticed that the BAM file does not have a header. The sort does not crash if the BAM has a header.

**Comment by daviesrob** [comment]
As far as I can tell, the problem was caused by **unaligned** files.  They have no `@SQ` lines, so there aren't any targets.  A bug in finish_merged_header in this case led to a double free of the `hdr->target_name` and `hdr->target_len` arrays.
