### ISSUE TITLE
Configure script's AX_WITH_HTSLIB is missing

### ISSUE THREAD

**Issue by jmarshall** [samtools/samtools#500]
Before running `autoconf`, for samtools you need to run `aclocal` to pull `AX_WITH_CURSES` and `AX_WITH_HTSLIB` in from the autoconf-archive.  (This will soon be noted in the README.)

`AX_WITH_HTSLIB` will soon be submitted to the autoconf-archive.  In the meantime, here is a draft:

[ax_with_htslib.m4](https://github.com/samtools/samtools/files/62424/ax_with_htslib.m4.txt)

**Comment by blaiseli** [comment]
Where is this file supposed to be put in order for one to be able to compile samtools from git repository ?

**Comment by reedacartwright** [comment]
Is there any issue with including this file in the source code?

**Comment by jmarshall** [comment]
@blaiseli You need to put it in _…/autoconf-archive/m4_, or in general somewhere that `aclocal` will find it, and of course you need to remove the `.txt` that this GitHub attached file needs, as `aclocal` looks for macros only in `.m4` files.  If you're not sure what you're doing, you might prefer to build from a release tarball, as these include all the configury files pre-generated.  (Or you might just copy _aclocal.m4_ from the samtools-1.3 release to avoid all this autoconf-archive malarky.)

@reedacartwright This file is either not part of samtools or a generated file, depending on your point of view; either way we prefer not to add it to the samtools source code.  The appropriate place for it would be a _contrib_ directory over in HTSlib.  I may add a _contrib_ directory there in the next release, as I have a few other things as well that would be appropriate for such a directory.

As samtools is currently the only thing using `AX_WITH_HTSLIB` and samtools also needs the curses macros from the autoconf-archive, adding _ax_with_htslib.m4_ to the autoconf-archive too seems natural.

**Comment by reedacartwright** [comment]
@jmarshall `autoconf-archive` will not always be installed on users machines even if `autoconf` is installed.  It is very common for software using autoconf to include an `m4` directory that contains the required modules from the archive.  Using `AC_CONFIG_MACRO_DIR([m4])` will allow `aclocal` to find them.  This is what I did with my software before I switched to using `cmake`.

When I updated the FreeBSD ports of `samtools` to 1.3, I had to patch the archive to include `ax_with_curses.m4` and `ax_with_htslib.m4`.  See https://svnweb.freebsd.org/ports?view=revision&revision=404398

**Comment by jmarshall** [comment]
We are familiar with _m4_ directories, and will consider adding one.  As you no doubt appreciate, having external files checked into source control is pure maintenance overhead, so there are reasons not to.

@reedacartwright Why are the FreeBSD ports working from the samtools git repository at all?  Your ports have to date corresponded to actual samtools releases rather than interim commits, so you could be building them from [release tarballs](https://github.com/samtools/samtools/releases) rather than git checkouts.  Our release tarballs (of course) come with `configure` etc already generated for your convenience.

**Comment by reedacartwright** [comment]
@jmarshall I'm just following standard FreeBSD practice for working with Github-hosted projects.  I'll look into whether it is beneficial to pull the source-code release instead.

**Comment by jkbonfield** [comment]
At the very least, ax_with_htslib.m4 should be in the htslib directory as a contrib file, so that anyone using the package can copy it and so that it's version controlled.  Having it outside of version control at a site we don't control isn't correct.

However I don't see the problem with copying it and curses one to samtools so that it "just works" out of the box when we do git clone.  It's not an issue having a second copy and simply patching it on the (very rare?) occasions the upstream copy changes.

**Comment by jkbonfield** [comment]
New idea, in discussion .m4 files (irods, but that's another ticket):

Clearly the ax_with_htslib.m4 belongs somewhere in the htslib directory, as it's only likely to need edits if we do something to htslib that invalidates the current config.  Plus it needs to be version controlled somewhere and htslib is the obvious place.

So... samtools could just use autoreconf -I $HTSDIR/share/htslib or some such approach so it can find .m4 files in the source tree or in the installed tree (provided we install a copy of the .m4 too).  Put simply, the autoconf config comes from whatever your htslib you're linking against provides.  It's a bit circular, but maybe works.

Although personally I'd just duplicate it and be done with it! :)

**Comment by dkj** [comment]
I'd find having copies of the ax_with_htslib.m4 file in the dependant source tree(s) the least surprising - this is the only package I've come across so far where I have to go hunting for m4 files to get autoreconf working following a git clone.

**Comment by kulvait** [comment]
I don't think that it is a good idea to have crippled versions of samtools or any other tools in the git repository. If it does not build according to INSTALL file, if it does not even contain configure file and if it even does not compile by running simple autoconf command.

You probably did not get the whole idea of GIT and writing code for community.  I really appreciate samtools package but the documentation of some functions is horrible (I really do not know what samtools rmdup does and how to set its parameters because its undocumented). I think your project is very big in terms whole sequencing community use it. So its git version should be probably managed in the way that anyone who likes to work on it gets the chance to do so.

Anyway If I need to build samtools 1.3.1 (while using Debian) from git tree I have to do following steps:
```
apt-get install autoconf autoconf-archive
git clone https://github.com/samtools/samtools
git clone https://github.com/samtools/htslib
mv samtools samtools-1.3.1
cd samtools
git checkout 1.3.1
mkdir autoconf-archive
mv ax_with_htslib.m4.txt autoconf-archive/ax_with_htslib.m4
cd ..
mv htslib htslib-1.3.1
cd htslib-1.3.1
git checkout 1.3.1
aclocal
autoconf
cd ..
cd samtools-1.3.1
aclocal -Iautoconf-archive
autoconf
./configure
make
make install
```

**Comment by mp15** [comment]
@kulvait Bear in mind that the current maintainers of samtools are not necessarily the original authors of all of those functions you're moaning about. If you've managed to decipher a function that is not labelled then by all means document it and then write a pull request and we'll probably at some point pull it in.

Incidentally samtools rmdup is deprecated, biobambam or Picard markduplicates do a better job with modern paired end reads (rmdup only considers each end of the read individually).

**Comment by kulvait** [comment]
@mp15 Regarding  the rmdup the documentation tells me  _By default, the command works for paired-end reads only. _, you are the first one telling me it is deprecated. But thanks for your work, I will review that code and we will se what we can do :+1:

**Comment by kulvait** [comment]
@jkbonfield Well the reason for renaming directories is that for my sequencing project I need some stability of code I am working with. So I picked most recent stable version of the tool and work with it. I know technically it is possible to work with HEAD from github but since I am not samtools developer I would better not do that. But that is not something that would be good to add to INSTALL for example. But I think it is good idea to add some info to INSTALL or README for those who are compilling from git source.

Probably its not good adding configure script but it would be nice to add htslib as samtools git submodule https://git-scm.com/book/en/v2/Git-Tools-Submodules for user to be able to checkout samtools using 
`git clone --recursive https://github.com/samtools/samtools`
where https://github.com/samtools/htsjdk is used as submodule. Then there is no need for even bothering with the source directory to htsjdk and since these projects are from the same family it is way to go.

Sorry for my off topic comment about rmdup I was quite frustrated since I had to learn new stuff about autoconf while not being able to get things compiled :-) But I am glad to have asked this question. For now I will use biobambam2 but I might try to somehow implement some rmdup algorithm and ask for pull request, would be fun :-) Btw, I use java version htsjdk lib to manipulate with cigar strings for soft clipping adapter sequences and it works fine (when I then repair the bam file using samtools calmd -rb). I am also using samtools mpileup.  Thus I am using this toolbox a lot in my analyses, so if there are some other parts of code that you consider DEPRECATED, please let me know which are those parts and what are the alternatives you suggest. Thanks for the development of these tools.

**Comment by jmarshall** [comment]
> I need some stability of code I am working with. So I picked most recent stable version of the tool and work with it

Perhaps you should consider using the stable releases that we produce for precisely this purpose: see http://www.htslib.org/download/ and/or [the current release](https://github.com/samtools/samtools/releases/latest).  Unlike the more raw developer-orientated git repository code, these formal releases (of course) have pre-built _configure_ etc.

Re _rmdup_, you might read the [release notes](https://github.com/samtools/samtools/blob/1.3.1/NEWS#L78-L80) or [man page](https://github.com/samtools/samtools/blob/1.3.1/samtools.1#L1964-L1967).  I thought this was also mentioned in the `samtools rmdup` usage display and _rmdup_ section of the manual, but it seems not — PRs welcome.

**Comment by kulvait** [comment]
@jmarshall But I am more flexible this way. I can easily downgrade, upgrade or even edit source code. I can also use last stable version (from 12/2015) before it is officially packed (4/2016).

**Comment by sambrightman** [comment]
Perhaps another non-circular option would be making htslib a submodule. That would also allow ensuring that that right version is built against.

If this not desirable for some reason (avoiding multiple htslib clones for multiple projects? It's only 13MB), then is there an issue for including this in autoconf-archive? I am looking [here](http://savannah.gnu.org/patch/?group=autoconf-archive) and in the Git checkout and find nothing.
