### ISSUE TITLE
samtools sort -n: comparing canonical query names instead?

### ISSUE THREAD

**Issue by bli25wisc** [samtools/samtools#521]
Dear SAMtools developers,

Sometimes, aligners may fail to parse the tag line of reads in FASTQ files correctly and result in the two mates of a same paired-end read having different query names. For example, the SAM lines below describe a paired-end read which two mate names are different.

SRR1003772.1	77	*	0	0	*	*	0	0	CAGAAGCAGGGATGACAATGAGACACTGAAGACACACGAAGGTGAATGCTGAAGACCATCAGAGTCCCAGCAGGGGGTCACGTCTTTC	IJJIJIJIJIIIIIIGHIJJJJJIJJJG
IIGIJIIJJJIIIICGIIJJIHHAEHFFFFFEEECECCDDDDDDDDBBD09BCB?ADDDD	XM:i:0
SRR1003772.1 DJG84KN1:343:C1Y0AACXX:6:1101:1910:2190 length=121	141	*	0	0	*	*	0	0	ATTTTACGTCTCTACGGCCCAAAAAAAGACAAAAATAAAAATTCCTTTTTATTCCTGTCAACTGGATGGAAACACA
AATTTCATGGAGCTGTGTACCATCGAAGAAA	FGHIJGHGJGHGHGIJJJJIEHIJIIIJHIGIJEIHGGFHFDFDEDFEEEDEEEEDDDDDDDCCCCCDB?@CCCD@?BCDDDEDDDA@CBDDDDEDDDCCDCCB39<	XM:i:0

In the above case, samtools sort -n will separate the two mates apart according to their query names. I wonder if it is possible to compare the canonical query name to make sure the mates having the same name? For example, if we assume the query name string ends either with '\0' or any white spaces, the above two SAM lines will have the same names.

Thanks,
Bo

**Comment by jmarshall** [comment]
When processing SAM/BAM/CRAM, tools determine whether two alignment records pertain to the same sequenced template by checking whether the QNAME fields are identical.  So the problem is not just with sorting — the SAM file is just plain broken as no tools will be able to correctly match up these mates.  (Other than approximately by looking at RNEXT/PNEXT, but that is not unique and doesn't help when the mate is unmapped.)

What is needed is to fix the bug in these aligners (which aligner does this?) or to write a tool to fix up these QNAMEs (for SAM, this could just be **awk** or **sed**).  Possibly one could add a samtools command or fixmate/calmd option to fix up QNAMEs with such whitespace, but before we spent time doing so it would be good to know how widespread this problem is.
