### ISSUE TITLE
When configured without curses samtools tries to link @CURSES_LIB@

### ISSUE THREAD

**Issue by mp15** [samtools/samtools#528]
With
```
$ ./configure --with-htslib=../htslib --without-curses
```

```
gcc -pthread -rdynamic   -o samtools bam_index.o bam_plcmd.o sam_view.o bam_cat.o bam_md.o bam_reheader.o bam_sort.o bedidx.o kprobaln.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_stat.o bam_color.o bamtk.o bam2bcf.o bam2bcf_indel.o errmod.o sample.o sam_opts.o cut_target.o phase.o bam2depth.o padding.o bedcov.o bamshuf.o faidx.o dict.o stats.o stats_isize.o bam_flags.o bam_split.o bam_tview.o bam_tview_curses.o bam_tview_html.o bam_lpileup.o bam_quickcheck.o bam_addrprg.o libbam.a ../htslib/libhts.a @CURSES_LIB@ -lm -lz -ldl 
clang: error: no such file or directory: '@CURSES_LIB@'
```

**Comment by jmarshall** [comment]
Works for me.  Likely you have not regenerated _configure_ since pulling the last commit that affected _configure.ac_.

**Comment by mp15** [comment]
That wouldn't make any sense because this is a bug in the Makefile not the configure script. I thought the configure script is supposed to generate the Makefile or rather convert the config.mk.in to config.mk?

**Comment by jmarshall** [comment]
Problem was a bit more interesting: _configure_ had been regenerated, but without seeing its subroutines and `AX_WITH_CURSES` had been left verbatim in _configure_.  This would normally lead to 

> bash: AX_WITH_CURSES: command not found

and a rapid diagnosis of the problem, but not when `--without-curses` avoids that branch of the `if` statement.

Perhaps that `if` can be rewritten to preset `ax_cv_curses` or similar instead, so that AX_WITH_CURSES is always executed (but does nothing with `--without-curses`) and this mysterious bad build is made less mysterious.
