### ISSUE TITLE
Improve Makefiles not to override user setting unless absolutely needed

### ISSUE THREAD

**Issue by mmokrejs** [samtools/samtools#533]
Hi,
  I am helping Gentoo Linux to keep up with samtools package changes. I do not know if anybody raised this already but would you mind considering the changes in https://github.com/gentoo-science/sci/blob/master/sci-biology/samtools/files/samtools-1.2-buildsystem.patch ?

  Also, it would be a good idea to fix the varfilter to look for python in a common location:

`sed -i 's~/software/bin/python~/usr/bin/env python~' "${S}"/misc/varfilter.py`

  FYI: https://github.com/gentoo-science/sci/tree/master/sci-biology/samtools

Thank you

**Comment by jmarshall** [comment]
Samtools 1.3 has a configure script, so you can override the makefile's default settings in the usual configure way:

    ./configure CC=gcc-whatever LDFLAGS=…

or if you don't use configure (though it's increasingly recommended for samtools and will likely become non-optional), similarly with make:

    make CC=… LDFLAGS=…

or if you have such settings in the environment, with [`-e`](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html#tag_20_76_04):

    export CC=…
    export LDFLAGS=…
    make -e

Is there a reason why Gentoo cannot use one of these methods in its downstream packaging?

----

Your other patches are mostly long-since already fixed:

1. The [HTSlib API](https://github.com/samtools/htslib) is the one we support as a shared library, so we do not wish to make or support a shared libbam.so, as libbam is of only legacy interest.  See #403 for more details.

2. I think you will find your `check`/`test` patch is unnecessary: I believe the rule works fine when `$(BGZIP)` is empty.

3. The remainder and the _varfilter.py_ shebang are long-since fixed in 1.3.

**Comment by jmarshall** [comment]
No further replies, so presumably Gentoo is now using the supported methods of overriding configure or make settings.

**Comment by mmokrejs** [comment]
As far as I understand the methods you propose are merely forcibly overriding whatever configure did. Gentoo of course use this but that defeats the purpose of configure in terms of tweaking the CFLAGS, etc. Let me use examples:

CFLAGS=foo configure ... # lets configure to eventually tweak CFLAGS but it starts with whatever user provided at first

configure ... CFLAGS=foo # this forcibly zaps whatever configure did

That is the reason why Gentoo does not use the approach you mentioned - it would just forcibly override whatever logic you put into configure.

Although we could alter the *.ebuild files to do what you proposed, it is the wrong way IMHO.

As you could see in the GHentoo git tree, we need to keep even older version because other packages require them (typically do not work with samtools >= 1.0 , also because you used the command line switches for a different purpose). I did not say the above patches are not needed for 1.3 but it is hard for us to always check the current code. Thank you for confirming they should not be needed anymore.

BTW, would you mind releasing bugfixes for say 0.1.19? You can see the patches in our tree and also say in Debian.

**Comment by jmarshall** [comment]
> configure ... CFLAGS=foo # this forcibly zaps whatever configure did

Either you are mistaken or I do not understand what you mean by “forcibly zaps”.  Please give an example of something that you would be able to achieve if the Makefile used `?=` and `+=` as in your patch, but which you cannot achieve equivalently via `configure VAR=value …`.

> BTW, would you mind releasing bugfixes for say 0.1.19?

We no longer support 0.1.x.

**Comment by mmokrejs** [comment]
> Either you are mistaken or I do not understand what you mean by “forcibly zaps”.

I edited my previous response. The two examples are not doing the same thing. Specifying the environment variable on the right side ensures it is passed untouched to a downstream code (in this case to GNU make).

> Please give an example of something that you would be able to achieve if the Makefile used ?= and += as in your patch, but which you cannot achieve equivalently via configure VAR=value ….

Gentoo exports CC, CFLAGS and other variables in the parent shell. The unpatched Makefile does not respect them -- no matter the examples 1. and 2. you gave would work around. I believe your third example would work as well but it is not standard and merely doing same as your example 2.

**Comment by jmarshall** [comment]
> Specifying the environment variable on the right side ensures it is passed untouched to a downstream code (in this case to GNU make).

That is incorrect.  Variables such as `CFLAGS` and `LIBS` specified on the right side (of `configure`) will be **added to** as appropriate by configure.  Try reading [/usr/share/autoconf/INSTALL](http://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Compilers-and-Options.html).

> Gentoo exports CC, CFLAGS and other variables in the parent shell.

Then you have two sensible options:

1. Use `make -e`, which is entirely standard — the link I gave you previously is to the relevant POSIX page.

2. Use `./configure CC='$(CC)' CFLAGS='$(CFLAGS)' …`, or similarly with `make` if you don't use our configure script.

Either or both of these is surely standard practice in Gentoo packaging scripts.  I would recommend the latter as being more flexible and explicit.

**Comment by jlec** [comment]
@mmokrejs what exactly is the argument against using

```makefile
emake CC=$(tc-getCC) CFLAGS="${CFLAGS}"
```
in Gentoo?

**Comment by mmokrejs** [comment]
None, except the fact that 'emake' should be enough like with other packages (CC and CFLAGS are inherited from parent shell).

**Comment by jmarshall** [comment]
It turns out that configure takes variables from its environment as well as from `VAR=VALUE` arguments on its command line (no surprises, really).  So just use the configure script:

    ./configure

Just like with other packages.

**Comment by jkbonfield** [comment]
I don't understand this whole discussion.

The Makefile produced by autoconf has the exact same issue in that typing ```CFLAGS=-foo make``` will not honour those CFLAGS.  As discussed above, you need ```make CFLAGS=-foo``` instead.  This isn't something specific to Samtools, but how Makefiles have worked forever.  Yes configure itself checks the environment, but not the Makefile it produces.

There is no solution we can offer that changes the behaviour of the "make" program itself without resorting to various nasties of manually checking the environment and using it when present, otherwise using a local variable (this may make it gnu-make specific?).   I've never seen a Makefile jump through such hoops before.  How does gentoo do this in other packages that don't use configure scripts?  Whatever you do to get those working must also apply to Samtools surely?  (We do offer a configure script, so using it as John suggests avoids the whole issue anyway.)
