### ISSUE TITLE
sam_read1 function declared in sam.h

### ISSUE THREAD

**Issue by bli25wisc** [samtools/samtools#559]
Hi,

I found that in the declaration of sam_read1, we used bam_hdr_t* h instead of const bam_hdr_t* h:

int sam_read1(htsFile *fp, bam_hdr_t *h, bam1_t *b)

However, in sam_write1, it is "const bam_hdr_t *h":

int sam_write1(samFile *fp, const bam_hdr_t *h, const bam1_t *b);

In addition, I have looked at the code of sam_read1 in sam.c, there is no modification of the header.

I wonder why don't we make bam_hdr_t *h in sam_read1 to const bam_hdr_t *h?

Thanks,
Bo

**Comment by jmarshall** [comment]
It is possible for SAM files to have no `@SQ` headers.  HTSlib does not currently support this, but if we were to implement it, when `sam_read1()` encounters a new `RNAME` or `RNEXT` field value for the first time, it will need to be able to add an entry for it to the header -- which thus needs to be non-`const`.

[This is really an **htslib** question rather than samtools, and in future it would be better to ask questions on the [mailing lists](http://www.htslib.org/support/) rather than as issues here.  Thanks.]
