### ISSUE TITLE
pass region as stdin to samtools view 

### ISSUE THREAD

**Issue by mayelasoto** [samtools/samtools#609]
Hi,

I want to use the command samtools view to retrieve alignments. I would like to pass the regions as stdin but I get the following error:

echo "chr1:1000-2000"|samtools view  bamfile -
[main_samview] region "-" specifies an unknown reference name. Continue anyway.

In the documentation it says you can use "-" but is it then only for the main files? Thank you.

I have samtools 1.3.1 and htslib 1.3.1.

**Comment by dpryan79** [comment]
`-` is only for BAM/SAM/CRAM files, you want `echo "chr1:1000-2000 | xargs samtools view bamfile`.

**Comment by jkbonfield** [comment]
Yes, this is only for main data files.  What you need is back-quotes or the ```$(``` commands ```)``` shell syntax if you find yourself in the situation of wanting nested back-quotes..

Eg:
```
samtools view bamfile `echo chr1:1000-2000`
```

This performs much the same action - taking the output of the echo command and feeding in as a *argument* to samtools rather than via stdin.

**Comment by mayelasoto** [comment]
Thanks, all the options above work.
