### ISSUE TITLE
advice on installing samtools 1.3.1 in ubuntu 16.04LTS

### ISSUE THREAD

**Issue by sumudu-rangika** [samtools/samtools#610]
Hi,

I don't have much experience in this regard. I have used "sudo apt-get install samtools" & used functions of samtools. But I wanted samtools stats to check statistics for a BAM file. But running this command gave me [main]command not found. 

I thought the reason is the version installed in ubuntu -0.1.19 doesn't have this functionality. So I downloaded samtools new version and ran the following.
./configure
make
sudo make install

please let me explain how to run commands now. I'm confused.

Regards
Rangi

**Comment by jmarshall** [comment]
If those commands completed without error, you have an up-to-date _samtools_ installed in _/usr/local/bin_.  However the out-of-date one you installed via _apt-get_ is ahead of it in your $PATH, so is the one that is executed when you just type `samtools` without an explicit path.  So you should probably remove the outdated package via `sudo apt-get remove samtools` so that your new version is the one invoked by default.

If you need further details please post on the [samtools-help mailing list](http://www.htslib.org/support/) (and include more information about what happened when you ran those commands!), where there are many more people sharing the load of answering questions, and many more reading postings and learning from the resulting conversations.

**Comment by sumudu-rangika** [comment]
Dear All,

Thank you very much for the solution. I removed the old version using the
apt-get command and the new version works nicely.

Thanks again.
Best Regards
Sumudu
