### ISSUE TITLE
sort and index

### ISSUE THREAD

**Issue by jdmontenegro** [samtools/samtools#615]
Hi,
I just finished mapping some reads to a large reference genome (>10Gb) with bowtie2 and used samtools to process the sam files to bam file:

samtools view -bh@ 15 in.sam | samtools sort -T in.tmp -@ 15 -o out.sorted.bam -
samtools index out.sorted.bam

But when indexing I get this error:

[E::hts_idx_push] NO_COOR reads not in a single block at the end 16 -1
samtools index: "SORT.0.bam" is corrupted or unsorted

I checked the headers of the out.sorted.bam file and it says it is sorted:

@HD VN:1.0  SO:coordinate
@SQ SN:1A_concat    LN:767671999
@SQ SN:1B_concat    LN:849204565
@SQ SN:1D_concat    LN:517151168
@SQ SN:2A_concat    LN:722555572
@SQ SN:2B_concat    LN:768397166
@SQ SN:2D_concat    LN:452948141
@SQ SN:3A_concat    LN:469763317
@SQ SN:3B_concat    LN:833081624
@SQ SN:3D_concat    LN:837519628
@SQ SN:4A_concat    LN:736810118
@SQ SN:4B_concat    LN:622430763
@SQ SN:4D_concat    LN:486825932
@SQ SN:5A_concat    LN:566001571
@SQ SN:5B_concat    LN:662671179
@SQ SN:5D_concat    LN:865375255
@SQ SN:6A_concat    LN:483240098
@SQ SN:6B_concat    LN:1140901169
@SQ SN:6D_concat    LN:397672489
@SQ SN:7A_concat    LN:523710223
@SQ SN:7B_concat    LN:531761060
@SQ SN:7D_concat    LN:501893127
@SQ SN:Chapman_unm  LN:7841969
@SQ SN:Unmapped_IDBAUD  LN:364356282
@SQ SN:gi|14017551|ref|NC_002762.1| LN:134545
@SQ SN:gi|81176508|ref|NC_007579.1| LN:452528
@PG ID:bowtie2  PN:bowtie2  VN:2.2.9    CL:"bowtie2-align-l --wrapper basic-0 -p 16 -I 0 -X 1000 -x Pangenome_v2.concat -S sample_0.sam -1 SRR1170581_1.fastq -2 SRR1170581_2.fastq"

I do not understand why the index complains that it is not sorted when the header says it is. I checked the end of the file and it appears that the sorting step did not actually put the unmapped reads as a single block at the end of the file.

samtools view out.sorted.bam | tail -n 1

SRR1170581.40429763 83  6B_concat   1140900431  15  150M    =   1140899925  -656    CACTCGGCGTTCTTTTTCAAGCACCTCATAGCGGTCGGTAACATCTTTCAGCTTCACGGCCATTTCGGCCATCTCCTCCCTGCTTCGGCAGTGAGCAGCCCTTCCAGCTTCTAGCTCTTCGGCCGCCCTCGAGGCAGCCGCATCACTCCT  ##BDDB@DCDBBDC@DDDDDCACDDDDDDDDDDDDDDDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDFFHJJJIJJJJJJJJJJJJHHHHHFEDFFCCC  AS:i:-10    XS:i:-20    XN:i:0  XM:i:2  XO:i:0  XG:i:0  NM:i:2  MD:Z:56T46T46   YS:i:-33    YT:Z:CP

I have tried resorting the "out.sorted.bam" but the problem persists. I am using samtools 1.3.1. samtools view does not complain about a corrupted file nor an EOF marker missing, so I assume the sorted bam file is complete.
Am I doing something wrong? Do you have any suggestions?

Best regards,

Juan Montenegro

**Comment by jmarshall** [comment]
> [E::hts_idx_push] NO_COOR reads not in a single block at the end 16 -1
> samtools index: "SORT.0.bam" is corrupted or unsorted

(I assume _SORT.0.bam_ is the same file as _out.sorted.bam_?)

“16” refers to 6B_concat, probably the last record that you saw with `tail`, and apparently it comes after a REF `*` record (-1).  This is the lack of sortedness that the index command is complaining about.

This could be because this record got appended after sorting, or it could be a bug in sorting.  It would be useful to see the whole BAM file to investigate this further.

In the first instance, please post problems using the tools like this on the [samtools-help mailing list](http://www.htslib.org/support/), where there are many more people sharing the load of answering questions, and many more reading postings and learning from the resulting conversations.

If you can post the last half dozen records of the file or a link to the complete file to the mailing list, we and others will be able to investigate further.

**Comment by jdmontenegro** [comment]
Thanks John,

I will post it on the sourceforge.net mailing list.
SORT.0.bam is the file I obtained after resorting out.sorted.bam. Nothing
was appended after sorting, that's why I do not undersatnd why 6B_concat is
in the last position instead of the unmapped reads. I just checked the file
and effectively the 6B_concat reads appear right after the unmapped reads.

I just changed the header to unsorted, extracted the reads to a sam file
and resorted everything from sam to bam, but the 6B_concat reads keep
appearing at then end of the file. It seems to be a problem with the
samtools sort.

Regards,

Juan Montenegro

2016-10-07 14:34 GMT+10:00 John Marshall <notifications@github.com>:

**Comment by jmarshall** [comment]
Sample file posted to samtools-help shows the following:

> Reads sorted correctly…
> ERR016397.780888        16      6B_concat       1072299209      0       8M8I4M1…
> ERR016397.113636        16      6B_concat       1073401597      0       455M   …
> Reads sorted to the bottom, incorrectly…
> ERR016397.180949        16      6B_concat       1074622366      33      459M   …
> ERR016397.164654        0       6B_concat       1079014940      2       165M13I…

1073401597 is 0x3ffacefd; 1074622366 is 0x400d6f9e.  This shows that sort's bit-packing ([here](https://github.com/samtools/samtools/blob/1.3.1/bam_sort.c#L1612) and maybe elsewhere) needs to be recalibrated now that chromosome lengths may be > 2<sup>29</sup>.

**Comment by jdmontenegro** [comment]
So the main problem is that the chromosomes are too large for samtools to
put them in a single block and that's why there is a block after the
unmapped reads?

Regards,

Juan Montenegro

2016-10-10 18:20 GMT+10:00 John Marshall <notifications@github.com>:

**Comment by jmarshall** [comment]
Not really; there's a simple samtools-internal bug preventing it putting them in a single block in the right place.  There is bit-packing code in there that was written when chromosome length in BAM was limited to 2<sup>29</sup>-1 and hasn't been updated since.  The code still works fine for smaller chromosomes but breaks past 2<sup>30</sup> as your example demonstrates.  Thanks for the bug report — this will be fairly easy to fix.
