### ISSUE TITLE
Reheader big sam without converting to bam

### ISSUE THREAD

**Issue by demis001** [samtools/samtools#629]
Is it possible to reheader sam file without converting to bam?

Thanks
Dereje

**Comment by mp15** [comment]
Yes, though not using samtools. If you want to do this in-place I'm afraid you're going to find that this is difficult because of how filesystems store files. I would recommend you do something like:

```
$ (cat newheader.sam; grep -v '^@' file.sam) > newfile.sam
```

Though to be honest if you're working with a large SAM file you shouldn't be. You're wasting a lot of disk space and BAM or CRAM is much faster because you can index them directly.
