### ISSUE TITLE
 Samtools sort CIGAR operations limitation, despite not using BAM

### ISSUE THREAD

**Issue by AlexanderDilthey** [samtools/samtools#667]
samtools 1.4 sort gives me an error when trying to sort a SAM or CRAM file with more than 64K CIGAR operations.

Example command:

/data/projects/phillippy/software/samtools-1.4/samtools sort combined_with_header.sam -o combined_with_header_and_sorted.sam

Example output:

[E::bam_write1] too many CIGAR operations (66411 >= 64K for QNAME "CHM1.gi|929855600|gb|LJII01000029.1|")
samtools sort: failed to create temporary file "combined_with_header_and_sorted.sam.tmp.0000.bam": Value too large for defined data type

I have exactly the same problem when trying to sort a CRAM file.

**Comment by daviesrob** [comment]
The problem here is that if sort runs out of memory and saves partially-sorted data to disk, it does so in bam format.  So you are using bam, behind the scenes.

It might be possible to get sort to save the intermediate files in cram format, which would solve this problem.  We would need to do some tests to see what impact this would have on the merging stage, especially in terms of speed and memory usage.

Otherwise some more radical surgery may be needed on sort to properly cure this.

**Comment by jkbonfield** [comment]
I'm experimenting still, but with CRAM as a temporary output format we need two tweaks:  referenceless mode so it's fast and works everywhere, and reducing the number of reads per slice to ~1,000 (instead of 10,000) in order to keep memory low when merging from many files.  Both of those are only 4 lines of extra code combined.

Testing this shows our temporary output files are maybe 30% smaller than BAM, but speed slows down by around 30% too.  We can tweak cram a bit more to manually disable some slower codecs which has a only a minimal file growth (still much smaller than BAM), but it's still around 15% slower when multi-threaded and 2-3% slower when not multi-threaded.   This is doable though and is a very minor tweak.

@daviesrob also pointed out we could mix and match formats, so only output CRAM temporaries when the number of cigar operations gets too high.  That's more work as we'd need to track the maximum number of cigar ops per file to flush, but it's also a workable solution.

The ideal, but far more complex scenario is to dump out a new format entirely, eg the LZ4 compressed memory block (we'd need merge to be able to read it back too).  That would be far faster as well, but it's not likely to be done initially as it needs a lot more code to implement this.

**Comment by AlexanderDilthey** [comment]
@jkbonfield I can also confirm that this fixes the problem I've observed and that it produces a beautifully sorted SAM with exceptionally long CIGAR strings :-)
