### ISSUE TITLE
New -T, --copy-tags option for samtools fastq

### ISSUE THREAD

**Issue by pd3** [samtools/samtools#671]
@jenniferliddle, in addition to the existing option

     -t  ... copy RG, BC and QT tags to the FASTQ header line

and the new extension `--barcode-tag` added by https://github.com/samtools/samtools/commit/6d612fea9cb324b15525e172a63270c32420494a, it would be useful to be able to copy arbitrary tags. I'd like to propose a new option for that, say

    -T, --copy-tags .. list of comma-separated tags to copy
 
My use case is copying the BX tag in 10x Genomics data.

**Comment by jenniferliddle** [comment]
My first step was to add a unit test for the existing -t option. I discovered that if the -s option is given, then -t *only* copies the tags to the -s file, not to the -1 or -2 files.

Is this the expected behaviour?

Do we want the new -T option to follow this behaviour?

**Comment by pd3** [comment]
Not sure what is the expected behavior for the `-t` option, but I'd expect it to do it for all files and the same for `-T`.  Thank you for looking into this.

**Comment by jkbonfield** [comment]
The copy tags functionality arrived with 84d070296492e86e450c4f2abda8e9521ccd6da2, but at this point there wasn't any -1 and -2 option.  @mcshane can you please clarify that the intention was to write to all files?

I suspect this omission arrived with the -1 and -2 code subsequently added inf0cb72c7 or subsequent  20b5b13d or b73d36e9 updates (ping @mp15).  I haven't checked though.  We should check out those various commits to see when this difference arrived so we can see if it was accidental or by design.  (I strongly suspect it's an accidental difference.)

**Comment by mcshane** [comment]
The tags should be copied to all output files.

**Comment by jenniferliddle** [comment]
Thanks people. I'm always hesitant to make any changes that affect current functionality, but since we seem to have a consensus on this, I shall make the change.
