### ISSUE TITLE
[rmdup] Add option to reduce log size

### ISSUE THREAD

**Issue by Actal** [samtools/samtools#680]
Hi,

I have a reference of millions of fragments and I make several alignments on it and then use rmdup. But the log files of rmdup takes a lot of place, about 30G, because of the lines:
[bam_rmdup_core] processing reference ...

Is it possible to add an option to not print this lines?

Thanks,
Actal

**Comment by jkbonfield** [comment]
We have a test file with 160,000 fragments and it expanded the output to ~9Mb.  This header was 47Mb in size (due to all the other fields present).  To reach 30Gb on similar data implies around 500 million fragments and a SAM header of around 140Gb which wouldn't work.  Even the tiniest SAM headers I could think of only show ~2x expansion from header to rmdup message:

```
$ perl -e 'for ($i=0; $i<1000000;$i++) {print "\@SQ\tSN:$i\tLN:100\n"}'|w-c 
20888890
$ perl -e 'for ($i=0; $i<1000000;$i++) {print "[bam_rmdup_core] processing reference $i\n"}'|wc -c
44888890
```

SAM's header can't go above 2Gb uncompressed without breaking, which means there can be no more than 2Gb of output.  What am I missing here?  That said, try gzipping the output first. 

Unfortunately when it comes to rmdup, we're not going to make any changes to the current implementation.  It isn't very robust and has been deprecated for some time and we advise against using it (https://github.com/samtools/samtools/blob/develop/NEWS#L144-L146). 

We are working on a new implementation (from scratch), but cannot give a date when this will be ready.

**Comment by Actal** [comment]
Thanks for the answer,
my reference contains 150 million fragments, and the error output of several rmdup are merged. So i think it's "normal" that the error file is so big. But it's a bit annoying. I will wait for the new implementation.
