### ISSUE TITLE
allow index jumps with BED query

### ISSUE THREAD

**Issue by brentp** [samtools/samtools#694]
currently `-L $BED` reads the entire $bam and checks if each alignment overlaps an interval in the given BED file. 

It would be nice to have an option to allow index-skipping rather than streaming.

I implemented this some time ago here: https://github.com/brentp/samtools/commit/2198b3284f0cc412cdd8fd88dfcaeb1a7e0a370e

I'm happy to put that into a proper PR if there is interest and some guidance on how to let the user decide on streaming vs index-jumps a la `bcftools view`

**Comment by mfoll** [comment]
We are very much interested by this feature in our group for the `mpileup`command. We overcome this at the moment by looping over regions of a bed file: https://github.com/IARCbioinfo/needlestack/blob/master/needlestack.nf#L379.

**Comment by jmarshall** [comment]
The problem with the approach that @brentp points to is that if there are reads spanning a wide enough stretch of genome coordinates that they intersect with two adjacent BED intervals, then those reads will be output twice.  (This will apply to a lot of reads if there are overlapping intervals in the BED file.)  This would be a change in behaviour (for the worse!) from the way the existing streaming `-L` implementation works.

The better approach is to improve HTSlib iterators so they can represent a set of regions (i.e. a BED file) rather than just a single region.

For BGZF/BAM iterators, I believe the `hts_itr_t::bins` data structure can already represent bins corresponding to a number of regions rather than just one. So with the addition of either an additional `hts_itr_queryb(set_of_intervals_t*)` constructor or perhaps a `hts_itr_query_add(tid,beg,end)` function to add another interval to a newly-constructed iterator, an iterator can be made with the right set of bins. Then the existing `hts_itr_t`'s `tid`/`beg`/`end` fine filtering fields need to be replaced with a sorted list of `tid`/`beg`/`end` to filter against. (The latter is probably an api-breaking change, as it changes the layout of `hts_itr_t`.)

Hopefully something similar can be done for CRAM iterators.

**Comment by valeriuo** [comment]
There is work in progress on this issue, in the direction @jmarshall mentioned.

The features we consider are:
1. The BED intervals are filtered by the intervals specified in the command line, if any.
2. The iterator is created from the intervals retrieved from the BED hash table.
3. The iterator will support multiple regions.

We will send an update by the end of August.

**Comment by valeriuo** [comment]
Implemented in https://github.com/samtools/htslib/commit/b36740b6f82a74d8ccec022f0f641a966339fa70
