### ISSUE TITLE
How to extract embedded reference from CRAM file?

### ISSUE THREAD

**Issue by tseemann** [samtools/samtools#723]
If I have a CRAM file with `embed_ref=1` how do I get the reference out?

I can't find any `samtools` gateway to this, which I assume is probably in the `htslib` API ?

A use case for this is to for calling SNPs to a reference, where the reference is in the CRAM file you supply to the variant caller, removing the need to provide an external reference file. Or just for storing genome assemblies with the reads.

**Comment by jkbonfield** [comment]
Sadly there isn't a way to do this, but I like the idea.

Note it may not be complete.  The reference stored is anywhere that data aligns against, but if we have a lack of coverage in the sequencing we'll get a lack of coverage in the stored reference.  That's probably fine for SNP calling as you don't need reference outside of sequenced regions.  We'd just need to pad it out with Ns.

**Comment by tseemann** [comment]
Sorry - are you saying the embedded reference in a CRAM file is *not* the complete reference?

So using an external reference is *different* to using an embedded reference?

Say it ain't so!

**Comment by jkbonfield** [comment]
It's the same reference, but not necessarily complete.

Imagine encoding a 10Mb region of chrX using an embedded reference.  Do we really want 3Gb of reference added to the CRAM file?  It's not helpful in any way!  So instead we have the reference for the 10Mb region we encode.

In practice, each random access CRAM slice contains its own little bit of reference.  This makes it fast and easy to fetch the relevant reference.  Each slice states it covers <ref>:<from>-<to> which normally would trigger a query to fetch the reference, by file, url, whatever, but here it finds it embedded so uses the locally embedded copy instead. 

Potentially (very likely) some slices will overlap slightly, due to reads overlapping, while some may have clear space between them due to lack of coverage.  That second case means there is no reference embedded at that point - just as with the example of a 10Mb chrX cram file.  That's what I mean about being incomplete.  It doesn't mean that the encoded records are in any way different to using an external reference.  The same data will be stored, we're just using an internally cached copy of the reference instead of the external one.

(Although note in theory we could generate the consensus and supply that as the reference to store.  It saves space as we're no longer encoding the same SNPs over and over again, but we have to offset that with the cost of storing NM/MD instead of computing them on-the-fly.)

**Comment by tseemann** [comment]
Ok, this means it is unsuitable for my needs.  With bacteria, the reference is smaller than the data given the reference.   

I understand human/mouse are important use cases, and save LOTS of space by not embedding them and using a remote reference. Caching is simple in these cases too, you only have a handful of references.

But for bacteria, we will soon have >1 Million bacterial SRA illumina FASTQ sets, and soon the same in assemblies (NCBI is ploughing through them).  Performing  a simple de novo assembly and aligning to that and storing reads in CRAM with that reference also helps compression.

I don't want to be caching millions of reference files, embedding them makes so much more sense.

**Comment by jkbonfield** [comment]
I agree that embedding them makes sense in this scenario and assemblies is precisely the reason I made sure to implement it.  It just makes no sense to have an external dependency when that "reference" isn't share with anything else.

It's highly likely though that anything denovo assembled with associated sequencing data is going to have 100% coverage, otherwise how did the assembler ever produce that consensus in the first place?  If the assembler made a mistake, and we have data aligned against the consensus which then doesn't work properly, then does it make sense to be treating the original consensus as the truth or the aligned data as the truth?  My instinct says the latter.

However if embedded guaranteed-complete references are deemed an important feature, then in theory it is doable within the CRAM format without changes there.  it would need changes to the implementation though.

For example we could create empty slices containing an embedded reference and zero reads aligned against it, simply to ensure that every base of reference is represented somewhere in the cram file.  Note this then also permits extraction of reference from CRAM as a whole or as a portion, much like samtools faidx works.  We'd also need to implement the tool that stitches the slices together to rebuild the reference.

**Comment by tseemann** [comment]
I am relieved to hear that it is at least *possible* in the design framework to embed an arbitrary genome into the CRAM file.  I guess one could always "hack" it in as a single 6 Mbp unmapped read with a special ID if needed too. But I'd rather avoid that :)

I understand it will take implementation time, and will help test where possible. 

As you state, the de novo assembly example is not the best use case. But aligning reads against reference genomes is. A very good example applicable to the UK in particular is the CRYPTIC project which is sequencing > 100,000 **M.tuberculosis* genomes, each of which is *very* close to the standard reference H37Rv.  The EBI @iqbal-lab is working with this data.

**Comment by jkbonfield** [comment]
Embedding a reference doesn't reduce storage costs, it simply avoids having an external file.  Infact it's likely embedding it would increase storage as someone is bound to want to extract the reference again and leave it on disk in fasta.  (That's a thought - do we ever need reference embedded as anything other than raw sequence - no fastq?)

There are some other wrinkles that would need fixing too to ensure 100% embedding.  Right now if htslib detects lots of containers end up having a handful of reads, possible at the tail end of very fragmented assemblies, we would suffer a lot of overhead in creating new containers and slices for every few reads (as we would in storing name sorted data too).  For this scenario, even with position sorted data, htslib uses the mechanisms designed for name sorted data whereby it stops storing reference:start-end in the container header and instead adds a reference ID field for each and every read in that container.  This is incompatible with embedded references as the format only permits one embedded sequence per slice.  If the user tries to embed in this scenario it simply switches to non-reference mode, but we could instead force it to emit tiny containers still each with their own embedded reference sequence.

While we're thinking about tweaks, and I have a hypothetical CRAM v4 in mind too, one thing that Deez does that is superior to CRAM is a two-phase difference.  Each Deez block stores the consensus as a delta against the reference and reads which are then delta against the consensus.  This means fewer differences to encode as all homozygous edits are stored once only (in the consensus) rather than once per read (as in CRAM).

This is orthogonal to storing the reference though.

**Comment by davmlaw** [comment]
@tseemann the command is  ```samtools reference```
