### ISSUE TITLE
mpileup hangs if samtools would give empty output

### ISSUE THREAD

**Issue by vladmihaisima** [samtools/samtools#725]
In case mpileup command is run with a BED file to restrict the regions, sambamba will hang if there is no output from samtools (ie: there is nothing in those specific regions).

Attached you can find some simple files to reproduce the error. The script assumes that samtools and sambamba_v0.6.6 are in PATH.

The command "sambamba_v0.6.6 mpileup -L toy.bed toy.sorted.bam -o pileup_with_bed.txt" will hang.

I have found this while doing unit tests for a more complex case, but I guess issue could show on a real case as well and it might be quite confusing.

[bug_sambamba_pileup.tar.gz](https://github.com/samtools/samtools/files/1315218/bug_sambamba_pileup.tar.gz)

**Comment by jkbonfield** [comment]
Did you mean to post this to samtools rather than sambamba?

I'm not sure this is a samtools issue, unless it's something that can be fixed by closing stdout at the end to notify downstream tools no more data is incoming.  That may lead to other problems though so it's not something to consider lightly.

**Comment by vladmihaisima** [comment]
Oops my mistake. Indeed should have been in sambamba.

**Comment by vladmihaisima** [comment]
For reference, re-opened at: https://github.com/lomereiter/sambamba/issues/315
