### ISSUE TITLE
rmdup error 

### ISSUE THREAD

**Issue by ttsutsui** [samtools/samtools#750]
I am now trying to remove duplicate from my WGBS mapping read.
When I tried rmdup like below, It would be aborted in the middle of precessing.
`samtools rmdup my_data.sam my_data_rmdup.sam`
`[bam_rmdup_core] processing reference chr6...`
`samtools(5713,0x7fffa2def340) malloc: *** error for object 0x7f999f600508: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6`

My condition is
ProductName:	Mac OS X
ProductVersion:	10.13.2
32G memory
Program: samtools (Tools for alignments in the SAM format)
Version: 1.6 (using htslib 1.6)

Is this rmdup bag or my mistake?
I would like to kwon advice.

Thanks.

**Comment by dkj** [comment]
@ttsutsui would you be able to share this file?

**Comment by jkbonfield** [comment]
Since 1.6 there was a markdup command, which has been further improved on in the develop branch.  This has a -r option for removal too.

The old rmdup command is there for legacy usage, but we really ought to just remove it and make it run markdup -r.  That said, I'm still curious to know where it dies so we can check if the error is infact in rmdup and not in some other code used elsewhere (please provide a stack trace if you cannot provide the data, or run valgrind on the executable).

Thanks.

**Comment by whitwham** [comment]
This has been open for over a year with no response.  As rmdup is a program we no longer support I am closing this issue.
