### ISSUE TITLE
[bam_rmdup_core] inconsistent BAM file for pair... Continue anyway.

### ISSUE THREAD

**Issue by NicolasHipp** [samtools/samtools#756]
Hello,
First, I would like to wish you all the best for 2018 :D.

I have some problems to remove duplicates from bam files. I started with fastq files from RNAsequencing (PE, 2X 75pb on Illumina Hiseq4000) , I used trimmomatic to remove adapters from theses files. I used STAR aligner to map these reads to Hg38 (annotated with GRCh38.91.gtf). Bam were "SortedByCoordinate" with STAR.

So I have duplicates contamination (fastQC), and I would like to removed them.

I work with samtools-1.3.1 with this command:

samtools rmdup ./...... _Aligned.sortedByCoord.out.bam ./...._Aligned.sortedByCoord.out.bam_DEDUP.bam

I get the output in the correct directory, but when I look in the logfile, I get these errors : 

[bam_rmdup_core] inconsistent BAM file for pair 'H4:1:HLG2FBBXX:8:1204:1377:33949'. Continue anyway. ...

I looked on google, and on this GitHub but there is only few posts and I cannot find an answer.
Does-anybody know what happens? 

Thanks a lot,
Nicolas

**Comment by jkbonfield** [comment]
Happy New Year to you too and thanks for a clear description of the problem. :-)

I'm not sure why this occurs, but suspect it's something to do with having more than 2 reads per name (eg supplementary data?).  I haven't checked however as rmdup is considered deprecated.

It was removed for a while, but added back due to user pressure (which was a mistake perhaps), however we've never really maintained it.

The latest samtools has a markdup command, which includes ```markdup -r``` for removal.  We should retire rmdup properly soon.  I would recommend upgrading and trying that instead.

**Comment by NicolasHipp** [comment]
hi, thanks for this very quick answer, I asked for the updating, hope that It will be done this afternoon. I come back when I have results to tell you more ;)

**Comment by NicolasHipp** [comment]
Oups ,

Got another error with another function :o 
So I tried samtools markdup -r ./in.bam ./out.bam
I got [markdup] error: no MC tag.
[markdup] error: unable to assign pair hash key.

I tried samtools fixmate [-rpcm] ./in.bam ./out.fixmate.bam
I get [W::sam_read1] Parse error at line 1

so I try to solve it and come back to tell you if markdup -r works ;)

**Comment by NicolasHipp** [comment]
Finally It worked perfectly with markdup -r , thanks for the help :D
