### ISSUE TITLE
bam => cram => bam, MD and NM change in new bam file

### ISSUE THREAD

**Issue by qinquan123** [samtools/samtools#762]
1. Samtools version is 1.5.
2. Convert bam to cram : samtools view -C -o some.cram -T hg38.fa old.bam.
3. Convert cram to bam : samtools view -b -o new.bam some.cram.
4. For some record MD and NM change in new bam compare to the old one.
    example:
    old record: qname1	161	chr1	10000	0	100M	chr14	67352327	0	ATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTATCCCTAACCCTAC	0BBB=@AC<B=AABAC>AACAC<AACBB>AABAB?AACAB>AACBC=@AB@;>AABA16AABAB0=ABA+=?ABA3<?@BA/>@3@;&A>AB?A:7@95&	**MD:Z:87A11A0**	ME:i:67352426	RG:Z:ZWH8X3RKLL_0	**NM:i:2**	AS:i:94	MS:i:67352327	XS:i:93

    new record: qname1	161	chr1	10000	0	100M	chr14	67352327	0	ATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTATCCCTAACCCTAC	0BBB=@AC<B=AABAC>AACAC<AACBB>AABAB?AACAB>AACBC=@AB@;>AABA16AABAB0=ABA+=?ABA3<?@BA/>@3@;&A>AB?A:7@95&	ME:i:67352426	AS:i:94	MS:i:67352327	XS:i:93	**MD:Z:0N86A11A0**	**NM:i:3**	RG:Z:ZWH8X3RKLL_0

**Comment by jkbonfield** [comment]
The new record is what `samtools calmd` also changes this field to.  This is because the reference starts with N instead of A at this point, and samtools counts that as a difference.  The definition of NM is a bit woolly so some people count base vs N as mismatch and others do not.  (Even more confusing is whether N vs N is counted.)  MD I assumed would be more tightly defined.  Clearly the input here is incorrect.

What's not appropriate is that samtools is changing the data.  In theory is should spot that the round-trip would change things and store MD/NM verbatim instead of calculating them on-the-fly during CRAM decode, however it seems that was simply an aspiration that never made it into the code.

**Comment by qinquan123** [comment]
It is accepted to "store MD/NM verbatim", wait for the new release.

**Comment by jkbonfield** [comment]
Fixed in https://github.com/samtools/htslib/commit/a5dc7e00543219580859454c94ee237653950517
