### ISSUE TITLE
fast paired collate

### ISSUE THREAD

**Issue by keiranmraine** [samtools/samtools#781]
Could a tool be created/modified to produce collated pairs, read 1 and read 2 primary only, in a slightly less I/O intensive fashion?

Admittedly I don't know the internals of `samtools collate` but an option to indicate reads should be output on detection of 2nd read (still spilling to disk when distant) that could be run as follows would be a great addition:

```
samtools view -uF 2304 in.bam | \
  samtools collate -2 --output-fmt SAM -O - collate_tmp | \
    progNeedingSamPairs
```

It would be sensible to output r1/r2 ordered with this option

**Comment by daviesrob** [comment]
Collate is pretty I/O intensive by design.  It puts the reads in buckets chosen by a hash of the name.  It then reads each bucket in turn, sorts by the full hash key (then query name as a secondary comparison) and outputs the sorted records.  You end up with all the reads with the same name together, but the names occur in a pseudo-random order.

`samtools sort -n` will also group the reads with the same name together.  In that case they obviously come out in strict name order.  If you have enough memory to fit all the uncompressed data then it won't do any intermediate I/O.

We could try implementing a collate that outputs pairs as soon as possible (which I know biobambam can do).  But for sorted inputs can't this cause some problems with, for example, bwa's insert size calculation as the resulting output tends to keep reads from a given genomic location together?  Both name sort and collate do a much better job of redistributing them.

**Comment by keiranmraine** [comment]
This would not be intended for use with mapping but for feeding into tools that want full information of a pairs mapping at the same time (not just the location).
