### ISSUE TITLE
quickcheck exiting with code 0 for truncated bams

### ISSUE THREAD

**Issue by pjongeneel** [samtools/samtools#785]
Hi there!  I have tried samtools 1.7 and now the latest dev branch, and it appears samtools quickcheck is still returning exit code 0 for bams that are truncated. 

./samtools quickcheck -v test.bam for instance returns 0 , while ./samtools flagstat test.bam produces the proper error:
[E::bgzf_uncompress] Inflate operation failed: progress temporarily not possible, or in() / out() returned an error
[E::bgzf_read] Read block operation failed with error -1 after 190 of 273 bytes
[bam_flagstat_core] Truncated file? Continue anyway.

**Comment by daviesrob** [comment]
samtools quickcheck only does some very basic tests:
- The file can be opened
- It looks like the right type (sam, bam or cram)
- It can read the header
- For bam and cram files, that the end-of-file block is present

The last check will spot files that end prematurely.  It won't spot problems somewhere in the middle (it wouldn't be quick if it could as it would have to read through all the data).

You might want to check that your file does end with the correct sequence, which should look like this:
```
$ tail -c 28 test.bam | hexdump -C
00000000  1f 8b 08 04 00 00 00 00  00 ff 06 00 42 43 02 00  |............BC..|
00000010  1b 00 03 00 00 00 00 00  00 00 00 00              |............|
0000001c
```

Unfortunately finding out where the problem is can be a bit tricky -- we really need to make bgzf_read print out the file position where it fails.  You could try `samtools view test.bam | tail`.  Assuming it also fails, the last record it prints out should be just before the place where the problem is.

**Comment by pjongeneel** [comment]
Thanks daviesrob for the quick reply and information! I will try out these solutions! 
Just so that I am on the same page, "For bam and cram files, that the end-of-file block is present" means that if the bam is truncated - it should error out correct? So I guess I am confused as to how I could have a truncated file according to samtools flagstat that would still have the EOF block present

**Comment by daviesrob** [comment]
The message from flagstat is a bit misleading, although I guess from its point of view the file was truncated as it finished reading before it got to the end.  That's just what it prints out if anything goes wrong.

If the file really does end prematurely quickcheck will spot that it has.  So it should detect files where the writer crashed part way through.  It won't find cases where the corruption appears in the middle, though.  That is most likely to be caused by bugs in whatever wrote the file, although very occasionally it can be due to file servers losing bits of data, or dodgy hardware flipping the occasional bit.

Out of interest, what wrote the file in question?

**Comment by pjongeneel** [comment]
Hey @daviesrob  thanks again for the clarification. This really does help.  I was just writing the bam via bwa alignment piped to samtools view save as bam.

${bwa_cmd} | samtools view -bo $bam -S -

Generally it works but sometimes disk issues cause corruption for whatever reason and I was looking for a quick way to check that any given bam is not corrupt due to this issue, but like you said it appears the only solution would be to read through the bam to check that. 

Appreciate all the help you have been 👍 :)
