### ISSUE TITLE
Different MAPQ scores reported for bam and pileup files

### ISSUE THREAD

**Issue by suzyhh** [samtools/samtools#808]
Hello,

I'm running a second round of SNP calling using a SNP list I generated from samtools mpileup. I was getting inconsistent results with some previous work (SNPs not being called in my data) and upon looking into it, I seem to be getting different MAPQ scores in my pileup files than I do in the bam files. Assembly was carried out with bwa mem.

My second SNP calling command is as follows and I am using v.1.3.1:
samtools mpileup -s -Q 23 -q 26 -d 2000 -c 50 -f ref.fa -l snplist.bed sample.bam > sample.pileup

for example: at position 32,634, I get a read depth of 9, with a MAPQ string of:
SSSNNNNF<

However, when I look at the bam files in artemis, there are 20 reads covering this base, each with a MAPQ of 60. I then looked in the .sam file and the MAPQ there is also 60.

I then ran the samtools mpileup command again but removed the MAPQ filter:
samtools mpileup -s -q 26 -d 2000 -c 50 -f ref.fa -l snplist.bed sample.bam > sample_noMAPQ.pileup

Position 32,634 is now covered by 18 reads with the following MAPQ string:
SSSNNNNF:9999<:7:8

My question is - if the sam file (and bam file in artemis) are both reporting a MAPQ of 60 for all of the reads, 1) why are the MAPQ strings in the pileup file not just a single character, and 2) why are 9 reads seemingly filtered out when they apparently have a MAP! of 60 prior to SNP calling?

Thank you!

**Comment by daviesrob** [comment]
I think you're seeing the effect of some of the options you used:

`-C 50` will have adjusted the MAPQ scores
`-q 26` will filter out low adjusted MAPQs.
`-Q 23` will filter out low base quality scores.  Note that these will have been BAQ-adjusted so that they may be lower than the base qualities in the input files.

Try running `samtools mpileup -s -Q 0 -d 2000 -B -f ref.fa -l snplist.bed sample.bam > sample.pileup`.  That should disable BAQ and remove the base quality and MAPQ filters, so you should see all of the results.
