### ISSUE TITLE
README's plugin-showing “typical installation recipes” no longer present

### ISSUE THREAD

**Issue by jmarshall** [samtools/samtools#812]
While discussing installation and configure/make/make install, samtools's _INSTALL_ file says

> Typically you will want to enable HTSlib's HTTPS/etc plugin etc.
> See README for recipes for typical installation.

However these recipes were removed in c9e7bf488ee6c976c1ff633289372a077b3a7a12. They were added (in 4b4e6880c8c7c4d6cf8ca5b6d3bb4227f7681048) expressly so that there would be some documentation to point to that discusses how to build a fully-featured remote-capable samtools — both via the desirable `make install` method, and via the sadly-favoured-by-neophytes run-in-place method.

Have the configure option defaults changed such that these recipes are no longer needed? (Surely not — surely the `--with-plugin-path=$PWD/htslib-1.x` option is still needed for the run-in-place method!) Are they no longer useful documentation?

CC @tk2 who pushed for this documentation at the time :smile:

**Comment by daviesrob** [comment]
It was simplified when htslib's configure was updated to detect if libcurl is available.  It's also not really necessary to build separate plugins as `hfile_libcurl` etc. get built into libhts itself if plugins are not enabled.  The only real inconvenience to not having plugins is that you have extra dependencies when linking against the static archive (and you already have this problem from libbz2 and liblzma).

On my to-do list is to allow a choice of which plugins to build in at configure time.  Then we could have a library with built-in libcurl support that also allows use of external plugins like irods.

It would also be useful (e.g. for binary releases) to be able to use something like `$ORIGIN` to specify where the plugins can be found.  The main problem there is where `$ORIGIN` should be relative to - the shared library would I think make the most sense, but that flops when the library is statically linked.  Making it relative to the executable might work for binaries that we ship, but then if you tried to link your own programs they would probably not be in the right place for the path to work.  Any ideas to solve this would be most welcome.

**Comment by jmarshall** [comment]
The plugin mechanism was added to HTSlib for the purpose of isolating downstream executables (such as samtools) from needing to link against additional dependencies, with the additional motivation of enabling separately-developed esoteric file access methods (like the iRODS plugin).

There are fundamentally three ways of isolating downstream executables from HTSlib's link-time dependencies:

1. Encourage third-party client executables to link against _libhts.so_ rather than _libhts.a_. Shared libraries carry their own library dependencies, so downstream executables can link against a shared _libhts.so_ without needing to know anything about what weird libraries libhts might be using.

    (This gets complicated when many users run in-place or install into an ad-hoc prefix rather than installing into a system prefix — thus _libhts.so_ is not in a directory already known to ld.so.)

2. Use htslib's plugin mechanism, so that the dependencies are limited to the plugin dynamic objects and _libhts.a_ itself gains no additional library dependencies whatever weird libraries the separate plugins might be using.

3. Maintain an accurate _htslib.pc_ pkgconfig-style file listing the weird libraries that downstream executables will need to link against if linking with _libhts.a_, and provide an example of how to use it  (either when installed or in-place from a built HTSlib source directory) to construct `$LIBS` both via `pkg-config` and in the absence of a pkg-config executable (e.g., a sed recipe).

The plugin mechanism is not limited to hFILE, and even now libbz2, liblzma, and libdeflate dependencies could be isolated via a newly-written compression plugin entrypoint, should someone wish to write that code.

It seems like the maintainers now wish to de-emphasise the plugin approach. Fair enough if so, but it would be good to facilitate or improve the other approaches at the same time if that is the case.

**Comment by jkbonfield** [comment]
By "the maintainers", don't take my recent comment to be the be all and end all of it.  I know Rob has other views, but he's not around this week.  However as he pointed out above, he wants to make some of this optional so that having plugins don't *require* libcurl to be a plugin too.  Generalising the plugins to support other things such as compression codecs is a nice idea.  I already have an experimental cram_modules branch in io_lib for just this purpose, mainly as an investigation.  It may offer routes for upgrading CRAM in the future without further complicating the build process.

Some of this can be mitigated using rpath (I know, it's evil!) and `$ORIGIN` so that samtools binaries know where to find libhts.so relative to it, so a local install doesn't need LD_LIBRARY_PATH or ld.so configs.

Personally I'd also like to see us release binaries.  Ultimately most people compiling the package are doing so because there aren't up to date binaries available in the linux distributions (or they don't have root access to install).  Providing our own binaries will go a long way.  Those either need rpath shenanigans as above or semi-static linking.

**Comment by kyleabeauchamp** [comment]
So we at Bioconda are building and distributing binaries that we are happy to share control of.  If you want to make changes, you just need to merge a PR here: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/samtools
