### ISSUE TITLE
Format that cannot be usefully indexed

### ISSUE THREAD

**Issue by fhodel** [samtools/samtools#821]
While trying to index my file I get this error message: `index: "filename.vcf.gz" is in a format that cannot be usefully indexed`. However, my VCF file is bgzip compressed. 

If I do:
`htsfile filename.vcf.gz`

I get:
`filename.vcf.gz:	VCF version 4.3 gzip-compressed variant calling data`

Why do I get this error message then?

**Comment by jkbonfield** [comment]
I expect @fhodel realised the problem and closed it.

If you're having the same issue, it's because it is *gzip* and not *bgzip* compressed.  They both look the same and can be "zcat"ed, but bgzip resets the gzip stream on every block and thus permits random access, which is necessary for indexing.  Normal gzip doesn't do this.

**Comment by ysq1770368148** [comment]
Hi,I am using bcftools to build index,but I get this error:

index: "SRR8990698output.snp.vcf.gz" is in a format that cannot be usefully indexed

What can I do to solve this problem

**Comment by jkbonfield** [comment]
Please open new issues rather than simply replying to long-closed ones.

In answer to your question though, that error occurs when the program doesn't believe the input to be either BCF or VCF format.  Is it actually VCF?  If you `zless` it (or `zcat file.gz|more`, etc) then does it look like a VCF?  My guess is not.  Or if it does, possibly it's gzipped and not bgzipped and the software detected the difference.  I haven't explored what error it would report then.

The `htsfile` command should also give some hints as to what we believe the format to be.
