### ISSUE TITLE
creation of vcf takes for ever (never occurs?) with 100,000x coverage

### ISSUE THREAD

**Issue by Lcarey** [samtools/samtools#838]
Hi,
I have a .cram file with 150,000x sequencing coverage. 

samtools can create a .mpileup file
(`samtools mpileup -O -Q 20 -C 50 -q 30 -d 1000000 -f $(GENOME)  CRAM/$${S}.cram`) works fine

but the job to create a .vcf file still hasn't finished after 19hrs. Is there something known broken/difficult about creating a .vcf file with very high depth of coverage? 
`samtools mpileup --VCF -Q 20 -C 50 -q 30 -d 1000000 -f $(GENOME) --output-tags DP,AD,ADF,ADR,SP,INFO/AD,INFO/ADF,INFO/ADR --gap-frac=0.000000001 --max-idepth=1000000  CRAM/$${S}.cram  > MPILEUP_Q$${Q}/$${S}.vcf.gz`

-Lucas
`$ samtools --version
samtools 1.8
Using htslib 1.8`

**Comment by daviesrob** [comment]
It's very likely that the VCF caller doesn't scale linearly with depth, so this much coverage could well result in a very long run time.

You might want to try using `samtools view -s <fraction>` to reduce the depth of the input data.  If you run it more than once with different numbers in front of the decimal point then you will get different samplings of your data, which you could use to see if you get stable results from the caller.

You might also want to use `bcftools mpileup` to generate the VCF file instead of samtools.  The bcftools version is more advanced than the one in samtools and likely to work better with `bcftools call`.

**Comment by daviesrob** [comment]
Closing as it's unlikely that we can easily fix this (apart from generally speeding the algorithm up).
