### ISSUE TITLE
Cannot open input file "gs://bucket/path/to/sampleID.bam" for reading: Protocol not supported

### ISSUE THREAD

**Issue by smrgit** [samtools/samtools#862]
I have gone through at least 3 rounds of trying to make sure I have a completely clean and up-to-date build of htslib and samtools 1.8 on a Google VM but I'm still getting the "protocol not supported" error.
```
$samtools --version
samtools 1.8
Using htslib 1.8
Copyright (C) 2018 Genome Research Ltd.

$uname -sr
Linux 4.4.0-127-generic

$uname -m
x86_64

$gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
```

Here's what my latest build process looked like:
```
cd htslib-1.8
make clean
./configure --enable-plugins --enable-libcurl
make
sudo make install

cd ../samtools-1.8
make clean
./configure --enable-plugins --enable-libcurl --with-htslib=system
make
sudo make install
```
Previously I had not used some of these configuration options -- I tried them after looking at the notes I had kept form testing the very earliest versions of htslib which supported accessing bam files in Google Cloud Storage.

Any suggestions would be greatly appreciated!  tia

**Comment by jmarshall** [comment]
What extra logging does `htsfile -vv gs://bucket/path/to/sampleID.bam` produce? (It would be good if samtools itself also offered a way to crank up the `hts_verbose` level, but at present it doesn't.)

**Comment by smrgit** [comment]
Here's a test using an open-access bam (though the real ones I need to operate on are controlled-access):
```
$ htsfile -vv gs://isb-ccle-open/gdc/009d7f14-c6fd-42c5-9b9f-00dff58644a8/G30640.KG-1-C.1.bam
[D::init_add_plugin] Loaded "knetfile"
[D::init_add_plugin] Loaded "mem"
htsfile: can't open "gs://isb-ccle-open/gdc/009d7f14-c6fd-42c5-9b9f-00dff58644a8/G30640.KG-1-C.1.bam": Protocol not supported
```

**Comment by jmarshall** [comment]
Literally `gs://bucket/foo.bam` would do — it just needs the `gs:` to trigger the relevant code.

Since you didn't use any --prefix options, I assume there is a _hfile_gsc.so_ in _/usr/local/libexec/htslib_? Are there any other htslib or samtools installations already on the machine, perhaps in _/usr_? Does `which htsfile` show the one you just installed in _/usr/local/bin_, and what does `ldd /usr/local/bin/samtools` say?

**Comment by smrgit** [comment]
hmmmm ... I don't see (nor can I find) any file called ``hfile_gsc.so`` nor is there a ``libexec`` directory under ``/usr/local/`` ...

```
$ ls -alt /usr/local/bin/* | grep "Jun  5"
-rwxr-xr-x 1 root root   61777 Jun  5 19:39 /usr/local/bin/wgsim
-rwxr-xr-x 1 root root   19525 Jun  5 19:39 /usr/local/bin/md5sum-lite
-rwxr-xr-x 1 root root   26212 Jun  5 19:39 /usr/local/bin/md5fa
-rwxr-xr-x 1 root root   26318 Jun  5 19:39 /usr/local/bin/maq2sam-short
-rwxr-xr-x 1 root root   26318 Jun  5 19:39 /usr/local/bin/maq2sam-long
-rwxr-xr-x 1 root root   87407 Jun  5 19:39 /usr/local/bin/ace2sam
-rwxr-xr-x 1 root root 2194141 Jun  5 19:39 /usr/local/bin/samtools
-rwxr-xr-x 1 root root 2776877 Jun  5 19:38 /usr/local/bin/tabix
-rwxr-xr-x 1 root root 2710468 Jun  5 19:38 /usr/local/bin/htsfile
-rwxr-xr-x 1 root root 2276350 Jun  5 19:38 /usr/local/bin/bgzip

$ which samtools
/usr/local/bin/samtools
$ which htsfile
/usr/local/bin/htsfile

$ ldd /usr/local/bin/samtools
        linux-vdso.so.1 =>  (0x00007ffc8654e000)
        libhts.so.2 => /usr/local/lib/libhts.so.2 (0x00007efc8becf000)
        libncursesw.so.5 => /lib/x86_64-linux-gnu/libncursesw.so.5 (0x00007efc8bc9b000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007efc8ba72000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007efc8b76c000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007efc8b553000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007efc8b335000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efc8af6c000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007efc8ad4a000)
        libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007efc8ab3a000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007efc8a936000)
        /lib64/ld-linux-x86-64.so.2 (0x00007efc8c17c000)
```

**Comment by jkbonfield** [comment]
My guess is you don't have libcurl-devel (or whatever the equivalent is) package on your system iinstalled.  Did ./configure say anything any curl?

Really we should nuke knet from orbit and just make it a big red failure to configure if curl isn't present unless explicitly built with ./configure --without-libcurl.  I reckon most of our problems come from A) libcurl & configure scripts and B) lzma support. Gah!

**Comment by smrgit** [comment]
any suggestions on which ``libcurl-*-dev`` should I pick?
```
$ sudo apt-get install libcurl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libcurl-dev is a virtual package provided by:
  libcurl4-openssl-dev 7.35.0-1ubuntu2.16
  libcurl4-nss-dev 7.35.0-1ubuntu2.16
  libcurl4-gnutls-dev 7.35.0-1ubuntu2.16
You should explicitly select one to install.
E: Package 'libcurl-dev' has no installation candidate
```

**Comment by jmarshall** [comment]
Do `dpkg -l '*curl*'` and pick the dev package corresponding to the runtime that is installed (`ii`).

**Comment by jmarshall** [comment]
> make it a big red failure to configure if curl isn't present 

It **is** a big red failure for `./configure --enable-libcurl` if curl isn't present. But I suppose one advantage of the usual _Makefile.in_ approach is that after a failed `./configure`, `make` doesn't work because there is no _Makefile_. One hopes that people will read the error messages, but I guess `make` carrying on and using defaults after a failed `./configure` is less than ideal… and if your theory is correct, is the bug here.

**Comment by smrgit** [comment]
success!!!!  it seems that ``sudo apt-get install libcurl4-gnutls-dev`` followed by a clean rebuild (no options at all on ``./configure``) seems to have done the trick :-)

I notice that the output of ``ldd /usr/local/bin/samtools`` is 2-3 times as long as before:
```
$ ldd /usr/local/bin/samtools
        linux-vdso.so.1 =>  (0x00007ffffe96b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f15d63b9000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f15d61a0000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f15d5e9a000)
        libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f15d5c8a000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f15d5a68000)
        libcurl-gnutls.so.4 => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f15d5806000)
        libncursesw.so.5 => /lib/x86_64-linux-gnu/libncursesw.so.5 (0x00007f15d55d2000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f15d53a9000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f15d4fe0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f15d65d7000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f15d4ddc000)
        libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f15d4ba9000)
        librtmp.so.0 => /usr/lib/x86_64-linux-gnu/librtmp.so.0 (0x00007f15d498f000)
        libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 (0x00007f15d470f000)
        libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007f15d4450000)
        libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f15d4209000)
        liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f15d3ffa000)
        libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f15d3da9000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f15d3ba4000)
        libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f15d3990000)
        libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f15d374e000)
        libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f15d3483000)
        libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f15d3254000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f15d3050000)
        libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f15d2e45000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f15d2c2a000)
        libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f15d2a0f000)
        libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f15d27d1000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f15d25c9000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f15d23c5000)
        libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f15d21bc000)
        libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f15d1f34000)
        libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f15d1c93000)
        libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f15d1a60000)
        libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007f15d184b000)
        libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007f15d1622000)
        libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f15d1414000)
        libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f15d11cb000)
        libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f15d0f12000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f15d0cd9000)
```
and the size of the ``samtools`` binary has more than doubled ...

Thanks so much for your help -- I *thought* I looked at the outputs as I was going through the build process and didn't notice any errors ...

**Comment by jmarshall** [comment]
Huzzah :tada:

By omitting `--with-htslib=system` this time the `samtools` binary is statically linked to the _libhts.a_ in samtools's _htslib-1.8_ subdirectory, rather than using the shared _libhts.so_ that you had just built as previously. And by omitting `--enable-plugins` all the networking and cryptography related shared libraries are used directly by _libhts.a_ and are linked into `samtools`.

The former explains the binary size, and the latter explains the voluminous `ldd samtools` output.

**Comment by jkbonfield** [comment]
| It is a big red failure for ./configure --enable-libcurl if curl isn't present

However that's still not enough.  Right now it's too easy to do "./configure && make" and get things to compile, but without curl due to no dev packages (the norm for most systems).   If you don't have curl it ought to die rather than simply falling back to knet and offering a (IMO) broken library.  If you're happy with cut down functionality then fine, but you should explicitly have to request it via something like "./configure --disable-libcurl" rather than having a default fallback mechanism.

Right now it just causes us to get bug reports because, let's face it, hardly anyone reads all that configure script verbage!

Good point on failed configure still leaving a Makefile.  I wonder if there's something we can put in it to block that.

**Comment by jmarshall** [comment]
Doing `./configure && make` would of course fail after configure and never run make. However most people (and the instructions!) do them as separate commands, leaving the possibility of not noticing the eight line error message.

samtools/htslib@efbded02d4b5d9311ec09ee53fa4d5d4b16f1d3c changed the default for $enable_libcurl to `check`; it'd be a one-line change to further tighten the default to `yes`.

> Good point on failed configure still leaving a Makefile. I wonder if there's something we can put in it to block that.

PR samtools/htslib#711 fixes this in the existing build infrastructure, which enables a better error message than the usual _No targets specified and no makefile found_ due to no Makefile having been generated.
