### ISSUE TITLE
allow setting level of compression in --output-fmt-option

### ISSUE THREAD

**Issue by dkj** [samtools/samtools#872]
#### Is your feature request related to a problem? Please specify.
I'd like to pipe from `fixmate`, to `sort`, to `markdup`, to more downstream processing so I'd like to avoid unnecessary compression of BAM between these [sub]tools. I can use `-l 0` with `sort`, I'd like to have uncompressed BAM output from `fixmate` and `markdup` as well. This doesn't seem to be possible from reading the man page.

#### Describe the solution you would like.
- add a `level=` optional argument to the global `--output-fmt-options` 
- short cut of `-u` and/or `-l 0` would also be good

**Comment by jmarshall** [comment]
Incidentally the original plan with **-O** was for **-Obam0** etc to be a shorthand for setting compression level. See the **TODO** in `sam_open_mode()` (samtools/htslib@252d27d7ea0ea065acbe1c07200602b32b972733).

**Comment by jkbonfield** [comment]
I've been meaning to do this for a while.  It's tripped me up before too.  It shouldn't be hard.  It's half there already (see HTS_OPT_COMPRESSION_LEVEL in the hts_fmt_option enum), and compression_level in htsFormat struct (complete with comment about it being unused!): https://github.com/samtools/htslib/blob/develop/htslib/hts.h#L156

Regarding bam0, this is just a minor tweak to hts_parse_format: https://github.com/samtools/htslib/blob/develop/hts.c#L714

I'll take a look.  Sounds like a quick Friday afternoon job. :-)

While I'm there I may fix it so that setting verbosity actually does something.  That code is partially there already too, just ignored.
