### ISSUE TITLE
Why bases mapped (cigar) is longer than bases mapped?

### ISSUE THREAD

**Issue by haowenz** [samtools/samtools#882]
Could you tell me in which case bases mapped (cigar) is longer than bases mapped?

Thanks

**Comment by daviesrob** [comment]
This is most likely because "bases mapped (cigar)" includes secondary and supplementary alignments, while "bases mapped" does not.  Filtering out secondary and supplementary alignments using the option `-F 0x900` will make "bases mapped (cigar)" decrease if any were present.

It's not clear if this is intended behaviour or not.  @pd3 or @mp15 may want to comment on that.

**Comment by haowenz** [comment]
Thanks for the reply.
