### ISSUE TITLE
samtools fasta (samtools fastq) does not extract paired reads

### ISSUE THREAD

**Issue by bernt-matthias** [samtools/samtools#885]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

samtools 1.7
Using htslib 1.7

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

- Linux 4.4.0-128-generic
- x86_64
- gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

I'm using the bioconda package.

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

Using the test data provided in the samtools sources

```
samtools fasta samtools_fastx-in1.bam -0 /tmp/pairs
```

should write (according to the help) all paired reads to  /tmp/pairs. But it does not. Also name sorting the file seems not to help. 

See also https://github.com/samtools/samtools/issues/634

Possible solutions: 
- improve documentation and specify what `-0` actually does 
- fix the bug

**Comment by bernt-matthias** [comment]
Very helpful for me. I guess if you link to the sam reference and use the description of the flags it should be clear for most. 

I would suggest to add something like the following on the website to the introduction of the tool (before the parameters are listed) and after the command line options: 

If the -s option is not used:

- read that are marked as the first in a pair (FLAG & 0xc0 == 0x40) go to the file given in the -1 option (or stdout if -1 is not used).
- read that are marked as the second in a pair (FLAG & 0xc0 == 0x80) go to the file given in the -2 option (or stdout if -2 is not used).
- reads that are marked neither as first nor second in a pair or first and second in a pair (FLAG & 0xc0 == 0x00 || FLAG & 0xc0 == 0xc0) go to the file given in the -0 option (or stdout if -0 is not used).

For each QNAME, only one read will be output for each of these categories. It will prefer to output reads which have quality values over ones which don't, otherwise you will get the first one found in the input file.

If the -s option is used:

- reads will only be written to the -1 and -2 files if a pair is found. I.e. for the given QNAME one read with FLAG & 0xc0 == 0x40 and one read with FLAG & 0xc0 == 0x80 will be written to the corresponding files. If instead only one of them is present then it will be written to the singletons file given in the -s option. 
- Note, the input has to be name collated, either using samtools collate or samtools sort -n. 
```

Two more question

1. do you have an example for the case `FLAG & 0xc0 == 0x00 || FLAG & 0xc0 == 0xc0`? I just have no clear idea how this could happen. I this, e.g. when the reads overlap or are not properly paired? 
2. what happens to the data that would be written to the -0 file if -s is used?

**Comment by daviesrob** [comment]
#887 is an attempt to improve both the online help and the manual page.  Does it look more comprehensible to you?

As an extra, it also fixes a bug with flushing the output that I discovered when testing the examples.  Using the `-0` option would prevent stdout from being closed correctly, resulting in a truncated output file.

**Comment by bernt-matthias** [comment]
great .. thanks

**Comment by Xiaofei-git** [comment]
> `FLAG & 0xc0 == 0x00` is for where you've lost track and have no idea where the reads came from.
> 
> `FLAG & 0xc0 == 0xc0` is for reads that are known to come between the ones with FLAG 0x40 and 0x80. It's quite difficult to do that with standard short-read sequencing, but easy with good old-fashioned Sanger capillary sequencing (you make a forward read, a reverse one and one with a custom primer). There was also a PacBio "strobe" sequencing idea at one point where you would get many short-ish reads from a single long piece of DNA, but I think it was dropped due to improved chemistry removing the need for it.
> 
> In practice I expect you're unlikely to see either of these.
> 
> The `-s` flag doesn't affect the data written to the `-0` file.


@daviesrob It is really helpful from the discussion on this thread. But, I still have some questions based on my objective and like to double check with you.

I have lots of bams that I can't tell which ones are single or paired end reads. The bams contain all original reads including chimeric and unaligned reads beside the mapped reads. My goal is to retrieve all original reads from the bams.

1. `FLAG & 0xc0 == 0x00` is for where you've lost track and have no idea where the reads came from.
Does that mean unmapped reads? For unmapped reads, it should be 0x4, is't it? My understanding of "no idea where the reads came from" is unmapped reads, but I don't think I am right.

2. "FLAG & 0xc0 == 0x40" is the first in a pair. I don't think it can retrieve the unmapped read1, right? If it can't, what should I do? Do I need to follow the steps here (http://www.novocraft.com/documentation/novoalign-2/novoalign-ngs-quick-start-tutorial/1040-2/ and https://darencard.net/blog/2017-09-07-extract-fastq-bam/)? 

In a word, the second question is that does the unmapped Read1 go to the file of "-1 paired1.fq" and unmapped Read2 to "-2 paired2.fq"?

"If the -s option is not used:

- read that are marked as the first in a pair (FLAG & 0xc0 == 0x40) go to the file given in the -1 option (or stdout if -1 is not used)."

Another link for reference: http://broadinstitute.github.io/picard/explain-flags.html

3. Since I can't tell which ones are single- or paired- end, if I use same coding as below  for both single- paired- end reads, which file the reads should go to for single-end reads? I think it should be in single.fastq (I tested it while asking this).


``` 
samtools fastq -1 paired1.fastq -2 paired2.fastq -s singleton.fastq -0 single.fastq sorted.bam
```


Thanks a lot!

**Comment by Xiaofei-git** [comment]
> If you have a BAM file with mixed paired-end data and single-end data, then presumably it originated from multiple runs possibly on different technologies. You'd be best to first filter to a single read-group to isolate that individual run, and then apply fastq on that output.
> 
> `samtools view -r` _paired_rg_ `-u | samtools fastq ...`
> 
> Similarly for the read-group of the single ended run. So we get multiple sets of FASTQs out, each matching the original separated sequencing runs. This is the correct way to handle such things as aligners typically won't be happy with mixing multiple runs together either.
> 
> As for unmapped data, that is an orthogonal concept to the read1/read2 flagging. You can have READ1 unmapped or READ2 unmapped just fine. If you have neither flag set it basically means it was single-ended, or some processing has happened which has (incorrectly IMO) discarded read meta-data. It's a pretty unlikely case to occur so I wouldn't worry about it treating them any differently than single-ended data.

@jkbonfield I am sorry, I don't think I made my questions clearly.

I have a lot of BAMs, such as. S1.bam, S2.bam, ... I don't know they are SR or PE without checking anything when I got the data, which doesn't mean they are mixed with paired-end and single-end data in one BAM (e.g. S1.bam). For each BAM, they are either SR or PE, not mixed with both SR and PE in a BAM. To avoid checking it is a SR or PE BAM, I used same code to all BAMs as below (same code because of batch jobs). By testing, the code below worked well for SR BAMs even with "-1" and "-2" option, the reads went to "$Smp_single.fastq" as I expected (understanding for -0 option).
``` 
samtools fastq -1 $Smp_paired1.fastq -2 $Smp_paired2.fastq -s $Smp_singleton.fastq -0 $Smp_single.fastq $Smp_sorted.bam 
```

But you prompted me to think about if the BAMs are mixed with both SR and PE. I will check it (at this time, I believe the BAMs contain only either SR or PE for a single file). 

For unmapped reads, you confirmed me it is an orthogonal concept to the read1/read2 flagging. My goal is to retrieve all original reads from a BAM. So, to retrieve the unmapped paired reads (read1 and read2), I believe I have to add another step to get the bam containing the unmapped reads (https://darencard.net/blog/2017-09-07-extract-fastq-bam/). I will do a test.
