### ISSUE TITLE
bam2fq speedup?

### ISSUE THREAD

**Issue by map2085** [samtools/samtools#905]
what is the expected speedup of multi-threaded `bam2fq` command? a very rough guess is fine - should it be pretty good or near-optimal, or is it complicated?

**Comment by tseemann** [comment]
In my experience of using `samtools fastq` (formerly `bam2fq`) I do not get any speed-up with providing more threads via `-@`.   u thought maybe it would help with compression when using `-`-1` and `-2` with `.gz` output filenames, but it doesn't appear to do much in reality.

**Comment by mp15** [comment]
Your problem is that bam2fq is IO heavy and compute low. There is a certain amount of benefit to using parallel gzip decoding but that's about it (and that's already done).

Also FASTQ has a variable output size, even if you could break the BAM into chunks and process them independently, you would still have to synchronise and concatenate the output. Unless you had some sort of specialised file system which allowed you to concat without writing a new file, you'd probably lose all your speed up there.

> On 29 Jul 2018, at 09:52, Torsten Seemann <notifications@github.com> wrote:
> 
> In my experience of using samtools fastq (formerly bam2fq) I do not get any speed-up with providing more threads via -@. u thought maybe it would help with compression when using --1and-2with.gz` output filenames, but it doesn't appear to do much in reality.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by jkbonfield** [comment]
The only threading used is for decoding the input file, which isn't likely to be a major bottleneck for BAM decoding.  Thus I wouldn't expect much beyond double speed increase.  Giving it 8 threads I see 270% cpu usage when decoding a file that's not in disk-cache and outputting to /dev/null.  Writing to disk will slow this up as it becomes more I/O bound.

The algorithm could be parallelised much more, but at the time of the multi-threading revamp we just added it to bgzf decode/encode across all commands as the easy starting point.  I'd expect it not to help hugely due to the I/O load though.

(Closing as this is a question.)

**Comment by jkbonfield** [comment]
Note, the lack of using threading for the output files if gzipped/bgzfed I view as a bug.  I'm working on a PR to fix this, although it's not going to change the answer to this unless you use gzipped output.  (There isn't even a way to do that for stdout I note.)
