### ISSUE TITLE
Default compression level for samtools fastq ?

### ISSUE THREAD

**Issue by tseemann** [samtools/samtools#906]
```
  -c                   compression level [0..9] to use when creating gz or bgzf fastq files
```

The default is not mentioned.

**Comment by jkbonfield** [comment]
I didn't even know it could do compression! :-)

Now I see it does, by a rather twisty filename analysis method.  Blergh.  I guess there's no need when going to stdout?

The problem here with documenting the default compression level is about all we could document is by default samtools fastq uses the default htslib compression level, which in turn will just state it uses the default zlib compression level.  Furthermore, in the code this is -1, which doesn't help users at all.

I guess we could work out what the current zlib default is when given -1 and document that, but I'm not sure it's the same default level across all deflate implementations.

**Comment by jkbonfield** [comment]
Actually I take that back, the libdeflate code doesn't use -1 so we explicitly set it to 6:

>         level = level > 0 ? level : 6; // libdeflate doesn't honour -1 as default

I guess it's easy enough to add "[6]" after the help then. :-)  Will do.

**Comment by jkbonfield** [comment]
Argh, *now* I see it's actually hardcoded as level 1 by default in sam_view.c!

Right, this issue is indeed very pertinent as it's not the default level that every other command uses.

**Comment by tseemann** [comment]
Glad I could "help" :-)

**Comment by jmarshall** [comment]
> I guess there's no need when going to stdout?

There is a desire for compression when going to stdout. This is the `-o` side-request in #874.
