### ISSUE TITLE
samtools fastq ignoring -f/-F

### ISSUE THREAD

**Issue by finswimmer** [samtools/samtools#939]
Hello,

I'm running samtools v1.9.

```
$ samtools --version
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
```

According to the examples given on the [web manual page](http://www.htslib.org/doc/samtools.html) and the comment about bugs there, I understood that `samtools fastq` extract all alignments nevertheless which FLAG is set. So the number of reads in the final `fastq` file, should be the same number as in the `bam` file. If one would get rid of secondary aligned reads, the option `-F 0x100` have to be set.

My `bam` file was generated by `bwa` and sorted by name:

`$ bwa mem -R '@RG\tID:1\tPL:ILLUMINA\tSM:1' -t 3 -M genome.fa Sample1_L001_R1_001.fastq.gz Sample1_L001_R2_001.fastq.gz | samtools sort -n -o Sample1.bam -`

Number of reads in `Sample1_L001_R1_001.fastq.gz`:

```
$ zcat Sample1_L001_R1_001.fastq.gz|wc -l 
7946560
```

So the total number of reads should be:

`Total_Reads = 2x (7946560/4) = 3973280`

Checking total number of reads in `bam`:
```
$ samtools view -c Sample1.bam
3975850
```

Checking number of reads in `bam` without secondary alignments:
```
$ samtools view -c -F 0x100 Sample1.bam
3973280
```

Now I create `fastq` without any option:

`$ samtools fastq Sample1.bam|bgzip -c > all.fastq.gz`

Checking read numbers:
```
$ zcat all.fastq.gz|wc -l 
15893120
```

So the number of reads is `15893120/4 = 3973280`. So it seems the secondary alignment were removed.

So maybe the default was changed and the manual page wasn't update? To confirm this, I try to convert only secondary alignments to `fastq`:

```
$ samtools fastq -f 0x100 Sample1.bam|bgzip -c > secondary.fastq.gz
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 0 reads
```

No reads were extracted.

At this time it seems to me that `samtools fastq`

- extract unique reads by default
- ignoring the filter FLAGs

Is it a bug? Is the manual not correct? Or do I misunderstood something?

fin swimmer

**Comment by daviesrob** [comment]
It turns out that the manual page is not entirely correct.  While both it and the online help correctly state that the default values for `-f`, `-F` and `-G` are all zero, they don't mention that supplementary and secondary alignments are filtered out unconditionally by [this line of code](https://github.com/samtools/samtools/blob/2d34e15/sam_view.c#L1546).  I also failed to notice that when last updating the manual page.  So effectively the default for `-F` is `0x900` and you can't actually unset those bits.

I expect it was written that way because they are likely to break the read pairing.  We could change the default for `-F` to `0x900` and remove the forced filtering, but I think they would have to go to the `-0` file, or maybe somewhere else entirely.  Trying to mix them with the primary alignments is unlikely to work well.

**Comment by finswimmer** [comment]
Hello @daviesrob ,

thanks for having a look at this. 

At the moment I think it must be mentioned that `0x900` is effectively the default and one cannot unset this. I guess this is what most people instinctively expect when they are trying to convert `bam` to `fastq`. But it's vexing if the manual says one could filter by flag and in the end it isn't entirely possible.

fin swimmer

**Comment by valeriuo** [comment]
Fixed by https://github.com/samtools/samtools/pull/1042
