### ISSUE TITLE
/usr/bin/ld: bam_tview_curses.o: undefined reference to symbol 'cbreak'

### ISSUE THREAD

**Issue by davidvilanova** [samtools/samtools#940]
Hi,
While trying to compile latest samtool-1.9 i get the following error

```
gcc -L/home/david/miniconda3/lib -L./lz4 -L/home/david/miniconda3/lib -o samtools bam_index.o bam_plcmd.o sam_view.o bam_cat.o bam_md.o bam_reheader.o bam_sort.o bedidx.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_stat.o bam_color.o bamtk.o bam2bcf.o bam2bcf_indel.o sample.o cut_target.o phase.o bam2depth.o padding.o bedcov.o bamshuf.o faidx.o dict.o stats.o stats_isize.o bam_flags.o bam_split.o bam_tview.o bam_tview_curses.o bam_tview_html.o bam_lpileup.o bam_quickcheck.o bam_addrprg.o bam_markdup.o tmp_file.o ./lz4/lz4.o libbam.a libst.a htslib-1.9/libhts.a -lpthread -lz -lm -lbz2 -llzma -ldeflate -lncurses -lm -lz  -lpthread
/usr/bin/ld: bam_tview_curses.o: undefined reference to symbol 'cbreak'
//usr/lib/libtinfo.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:144: recipe for target 'samtools' failed
make: *** [samtools] Error 1
david@localhost ~/tools/samtools $ 
```

Seems related to ncurses. I have installed the latest ncurses-6.1 through conda .

Any idea ?

$ uname -a
Linux 4.10.0-38-generic 42 16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
 $ gcc --version
gcc (Ubuntu 7.3.0-21ubuntu1~16.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by davidvilanova** [comment]
Yes that´s what i first tried. It will work but for some reason the conda version will downgrade ncurses to 5.9 which will break the installation of other packages. Thought samtools was relying on ncurses 6.1 ?

```
## Package Plan ##

  environment location: /home/david/miniconda3

  added / updated specs: 
    - samtools


The following packages will be UPDATED:

    python:   3.6.4-hc3d631a_1        anaconda    --> 3.6.5-1        conda-forge
    samtools: 1.7-1                   bioconda    --> 1.9-h46bd0b3_0 bioconda   

The following packages will be DOWNGRADED:

    libedit:  3.1.20170329-h6b74fdf_2 anaconda    --> 3.1.20170329-0 conda-forge
    ncurses:  6.1-hfc679d8_1          conda-forge --> 5.9-10         conda-forge
    r-base:   3.4.1-h4fe35fd_8        conda-forge --> 3.4.1-4        conda-forge
    readline: 7.0-ha6073c6_4          anaconda    --> 7.0-0          conda-forge
```

**Comment by dpryan79** [comment]
It's a good idea to make a separate conda env for specific tool versions, then you don't have this issue. Bioconda pins recipes to specific versions of ncurses, if memory serves.

**Comment by davidvilanova** [comment]
Thanks, will do that !!!!

**Comment by daviesrob** [comment]
Mixing conda libraries with system ones can lead to problems, but you may be able to get away with it if you fiddle with `rpath`.  Try configuring like this:

```
make distclean
./configure CPPFLAGS=-I/home/david/miniconda3/include LDFLAGS='-L/home/david/miniconda3/lib -Wl,-rpath=/home/david/miniconda3/lib'
```

If that doesn't work you could also try adding `-Wl,-rpath-link=/home/david/miniconda3/lib` although that wasn't necessary when I tried it.  Setting `rpath` makes your conda libraries prefer their own dependencies instead of the ones that come with the system.

**Comment by jkbonfield** [comment]
This doesn't appear to be a problem of mixing system and conda together.  Both samtools and ncurses are listed as conda packages above, but for whatever reason samtools is triggering a requirement for a fixed (outdated) version of ncurses instead of version >= x.y.

This sounds like a conda package dependency problem and should be reported to conda and/or bioconda (ideally after looking through the package configs to find the culprit) and it isn't a samtools issue.

**Comment by jmarshall** [comment]
It might not be quite as simple as that.

`cbreak()` is defined in libtinfo. The linker is complaining that there is no definition of `cbreak` available and indeed `-ltinfo` is not listed on that command line. If `-lncurses` resolves to a shared _libncurses.so_, then that file is typically a linker script (e.g. `INPUT(libncurses.so.5 -ltinfo)`) that pulls in `-ltinfo` and all is well. But if `-lncurses` resolves to a static _libncurses.a_ then the command line would have to say `-ltinfo` itself.

Does the conda installation perchance provide only _libncurses.a_ with no accompanying _libncurses.so_?

If so, then the bug would be that samtools's _m4/ax_with_curses.m4_ does not have a code path that adds `-ltinfo` to CURSES_LIB and thus does not support linking against a static libncurses. This is what I was alluding to back in https://github.com/samtools/samtools/issues/577#issuecomment-220283910. After a quick glance at autoconf-archive's current `AX_WITH_CURSES`, I'm not convinced that the current upstream version supports such a configuration either. Sigh…

**Comment by dpryan79** [comment]
The conda installation provides libncurses.so as part of the `ncurses` dependency (libtinfo.so is there too), it's just not getting linked against.

**Comment by jmarshall** [comment]
Is the conda-provided _libcurses.so_ a real shared object (and if so what does `ldd libcurses.so` say?) or a text file?

**Comment by davidvilanova** [comment]
In the samtools package from bioconda i found the following :
https://anaconda.org/bioconda/samtools/1.9/download/linux-64/samtools-1.9-h46bd0b3_0.tar.bz2

In conda_build_config_yaml

```
requirements:
    build:
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.4.16 0
        - curl 7.59.0 1
        - krb5 1.14.6 0
        - libdeflate 1.0 h470a237_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - libssh2 1.8.0 h5b517e9_2
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - xz 5.2.3 0
        - zlib 1.2.11 h470a237_3
```

In meta.yaml

`ncurses: '5.9'
`
So seems the requirements point to 5.9 whereas it should point to version 6.1. Rebuilding the packages with latest should fix the problem ?

Also it should normally contain a folder with the 1.9 definition which is not there (see image)

<img width="676" alt="screen shot 2018-09-05 at 12 34 42" src="https://user-images.githubusercontent.com/11404840/45088078-44631900-b108-11e8-893c-7e334424417e.png">

I finally could install locally using the source package but the bioconda package will fail if the ncurses dependency remains to 5.9.

**Comment by daviesrob** [comment]
You should raise issues about bioconda dependencies on their [issue tracker](https://github.com/bioconda/bioconda-recipes/issues), as we can't fix them here.

Samtools should work with pretty much any version of ncurses, so they've probably just tied it down too tightly.

At the start of this, were you trying to build from one of [our releases](https://github.com/samtools/samtools/releases)?  And if so, have you tried setting `LDFLAGS` when configuring it [as I suggested above](https://github.com/samtools/samtools/issues/940#issuecomment-418441610)?

**Comment by davidvilanova** [comment]
Yes sure, my `LDFLAGS` and `CPPFLAGS` were set properly  to link to my conda libraries and defintions. So installing it with the source worked properly . Will report to conda....
Thanks

**Comment by dpryan79** [comment]
I've brought up the ncurses pinning in the bioconda gitter channel, I suggest follow ups be moved there.

**Comment by jmarshall** [comment]
I think you'll find this fails with either conda-forge version of ncurses (5.9-* or 6.1-*), so any pinning is a red herring.

This turns out to be this old chestnut: [DSO Linking / ToolchainTransition](https://wiki.ubuntu.com/NattyNarwhal/ToolchainTransition) — the part where `--no-add-needed`/`--no-copy-dt-needed-entries` is now the default setting.

To compile your own version of samtools (or anything else) against bioconda's ncurses, one of three things needs to happen:

1. Conda's ncurses needs to use the _libncurses.so_-is-a-linker-script trick that real Linux distributions use. Before this ToolchainTransition, conda's real shared library _libncurses.so_ worked okay because the linker would resolve samtools's `cbreak` needs by using the libtinfo hint given by _libncurses.so_. Part of the point of the transition was not to do that anymore.

    The linker script trick is the fix for that. See e.g. 5.7-4.20100116 in the [CentOS RPM's ChangeLog](https://git.centos.org/blob/rpms!ncurses.git/c7/SPECS!ncurses.spec).

2. You need to turn back time and link using `--add-needed`, e.g. by adding `-Wl,--add-needed` to $LDFLAGS. This is the dirty hack solution, and is what bioconda's samtools recipe does (see the very well-commented bioconda/bioconda-recipes@199fad44a85fb54a880c50defa5e2a154969d62d).

3. You need to add `-ltinfo` to the link command line. This is the clean solution in the absence of conda doing (1). As you know the platform you're using uses a separate tinfo library, you can just use `LIBS=-ltinfo` unconditionally.

    Or the heroic solution would be for samtools's _m4/ax_with_curses.m4_ to add `-ltinfo` to CURSES_LIB or LIBS or somewhere when appropriate and when it is necessary; i.e., to implement support for libtinfo-using libncurses when linking against a static _libncurses.a_ or a real non-script _libncurses.so_ shared object in a no-add-needed world.

**Comment by daviesrob** [comment]
Well, I guess a suitably designed `AC_SEARCH_LIBS` in _m4/ax_with_curses.m4_ should be able to resolve this.

**Comment by daviesrob** [comment]
My attempt at the heroic solution is #942.  It's been tested on a machine with conda installed and no libcurses-dev, and it does manage to configure and build a working samtools (with suitable `CPPFLAGS` and `LDFLAGS` settings).

It only adds -ltinfo when needed, so building on a system with a working libcurses-dev is unchanged from normal.

If you want to try it out, don't forget to do `autoconf && autoheader` to rebuild the configure script.

**Comment by jmarshall** [comment]
FWIW conda-forge implemented option (1) from https://github.com/samtools/samtools/issues/940#issuecomment-418754819 in December. So conda is now in line with other platforms and the existing configure script works with the vanilla conda libncurses. (Provided the conda user has selected conda-forge for their ncurses and has updated to December's 6.1-hfc*_2 or 6.1-*_1002.)
