### ISSUE TITLE
faidx -o OUTNAME FASTA is ignored, still writes to FASTA.fai

### ISSUE THREAD

**Issue by tseemann** [samtools/samtools#970]
#### Are you using the latest version of [samtools]

samtools 1.9 / Using htslib 1.9

 #### Please describe your environment.

Linux, x86_64 gcc version 5.5.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

```
$ cat in.fa
>seq1
AGTC
>seq2
CTGA

$ samtools faidx in.fa

$ cat in.fa.fai
seq1    4       6       4       5
seq2    4       17      4       5

$ rm -f in.fa.fai

$ samtools faidx -o foo in.fa

$ cat foo
cat: foo: No such file or directory

$ cat in.fa.fai
seq1    4       6       4       5
seq2    4       17      4       5

```
Also tried `-o /dev/stdout` and `-o -` with no luck.
`strace` shows no attempt to open `foo`.

**Comment by whitwham** [comment]
Well no, it wouldn't.  From the man page:

>       -o, --output FILE
>               Write FASTA to file rather than to stdout.

The option is for writing out FASTA files when you give faidx a region to output.  Without a region faidx just does the indexing; it doesn't write a FASTA file.

**Comment by tseemann** [comment]
Hmm. Good point. I must have read `FASTA` as `FASTA index`. My bad.

**Comment by whitwham** [comment]
I thought about adding something like that when I re-writing bits of faidx but I decided it was too much fuss for a feature no one (to the best of my knowledge) had asked for.

You could open an issue requesting `--output-idx` and its associated `--input-idx` if that would be useful to you.  It may be some time before I get around to writing more faidx code though.

**Comment by joshua-theisen** [comment]
IMO, the expected behavior of `faidx` is to output a `.fai` file, so when I saw documentation stating --output directs `faidx` to "write...to file" I, like @tseemann, assumed it was referring to the index. It might be more clear if the flag were call `--fasta-output" or something of that nature. Thanks.

**Comment by jmarshall** [comment]
`samtools faidx` has two modes of operation: indexing with one argument, or retrieval with more than one.

At present `-o`/`--output` (and most of the other options) are ignored in indexing mode. As this option in particular is tempting in indexing mode, it would be better for using it to cause an error.

Or a redirection option could be added to indexing mode too, but that (and what it should be called) is #983.

(`-o`/`--output` is used rather than e.g. `--fasta-ouptut` because it is a [well-known standard](https://www.gnu.org/prep/standards/html_node/Option-Table.html#Option-Table).)

**Comment by joshua-theisen** [comment]
Understood. I had only used `samtools faidx` for indexing but now realize that the retrieval usage is probably more common. Thanks
