### ISSUE TITLE
biobambam/scramble complain about samtools 1.9 cram file

### ISSUE THREAD

**Issue by EvanTheB** [samtools/samtools#980]
I do not know if this is an issue from samtools, scramble, or biobambam2, but hopefully someone can help me narrow it down. 

```
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.

-=- sCRAMble -=-     version 1.14.11

This is biobambam2 version 2.0.87.

```

 #### Please describe your environment.
Linux 2.6.32-642.3.1.el6.x86_64
x86_64
gcc (GCC) 7.3.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I have a simple fastq -> cram workflow. The data integrity is checked with biobambam2 bamseqchksum. 
I updated samtools from 1.8 to 1.9, and io_lib (used by biobambam2) from 1.14.9 to 1.14.11. 

After the upgrade I get an error from bamseqchksum while reading a samtools created cram:

```
$ bamseqchksum inputformat=cram < dst/test2.cram 
Invalid alignment: Length of null terminated query name is inconsistent with alignment header

blah/lib/libmaus2.so.2(libmaus2::util::StackTrace::StackTrace()+0x56)[0x7f1c479cbca6]
bamseqchksum(libmaus2::exception::LibMausException::LibMausException()+0x2b)[0x456a77]
bamseqchksum()[0x470da2]
bamseqchksum()[0x46afdf]
bamseqchksum()[0x455b0e]
bamseqchksum()[0x4563b5]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x3dc441ed1d]
bamseqchksum()[0x453b19]
```

```
$ samtools view dst/one2.sam -O cram | scramble 
@PG	ID:scramble	PN:scramble	VN:1.14.11	CL:/share/ScratchGeneral/evaben/mgrb_cram/batch_4/build/install/bin/scramble 
Failed in scram_close(in)
```

I can reproduce the error from a single read, I suspect the error occurs after the first cram 'block' because initially this triggered after 10k reads. I can suppress the error by deleting parts of the header, but I cannot make head or tail of which parts are critical - UB? 

Using a different version of samtools, OR a different version of io_lib fixes the issue.

```
samtools view one2.sam -O cram | bamseqchksum inputformat=cram
```

[one.sam.txt](https://github.com/samtools/samtools/files/2583744/one.sam.txt)

[one.cram.gz](https://github.com/samtools/samtools/files/2583751/one.cram.gz)

Thanks

**Comment by jkbonfield** [comment]
Thanks for the bug report with ready made test data.

I see this error comes from biobambam, in the code here:  https://github.com/gt1/libmaus2/blob/master/src/libmaus2/bambam/BamAlignmentDecoderBase.hpp#L5218-L5236

It looks like it's been there since 2015, but that doesn't explain why only new versions fail (unless it is due to new versions of io_lib).

I am wondering if it is related to our (both io_lib and htslib) use of multiple nul padding bytes in the read name to ensure the CIGAR field is word-aligned.  This is only done in-memory and not part of the BAM specification.   Given this is a CRAM file, it would be the in-memory representation which is likely giving the problem, however that doesn't explain how come changing samtools fixes it too as that indicates it is something in the file itself that is giving the problem.  Most bizarre.

We'll investigate, but pinging @gt1 in case he is aware of the cause already.

**Comment by jkbonfield** [comment]
Argh I've found the cause.  The short answer is biobambam it won't work with modern io_lib's until it is updated to use structure elements.

`::libmaus2::bambam::BamAlignmentDecoderBase::getReadName(D)` is just (uint8_t *)D+32.  Ie it takes an array (D) are returns 32 bytes into that structure (after some preamble such as array length).  D here is a bam in-memory structure, in the layout as defined in the BAM specification.

The problem is this D array holding the BAM structure is filled out incorrectly.  There is an implicit assumption that the io_lib bam_seq_t structure has an identical memory layout to the BAM on-disk format.  This is not true in the current io_lib implementation as some fields have been made 64-bit.

https://github.com/gt1/libmaus2/blob/master/src/libmaus2/bambam/Scram.c#L478-L514 is the code that casts a bam_seq_t struct to uint8_t.  It will need to be rewritten to shuffle bytes around to generate the BAM on-disk layout.

**Comment by gt1** [comment]
Thanks for letting me know James. I have put an updated version at

https://gitlab.com/german.tischler/libmaus2/blob/master/src/libmaus2/bambam/Scram.c#L478

which should work as long as an on disk type layout starts at the ref field of bam_seq_t of io_lib. I'd like to avoid unnecessary restructuring/conversion as long as the data layout allows it.

**Comment by EvanTheB** [comment]
Great! Thanks for the excellent response team, closing here as it is a iolib/libmaus issue.
